A({page:20, page2:7, orig:"Thyroid 2",
  stem:"A patient has a firm thyroid nodule. TSH is normal. Ultrasound shows a 1.8-cm hypoechoic solid nodule with irregular margins and increased vascularity. What is the most appropriate next step?",
  gray:"A patient came with neck mass, firm, U/S revealed a 1.8-cm well circumscribed hypoechoic lesion, irregular border, increased vascularity, what is the next management? — A. FNA",
  opts:["Fine-needle aspiration","Core needle biopsy","Radionuclide thyroid scan","Total thyroidectomy","Repeat ultrasound in 12 months"],
  ans:0, key:"A FNA"+KS,
  flag:"⚠ เล็กน้อย: เติม TSH ปกติ ใน stem (ตาม algorithm ต้องดู TSH ก่อน)",
  interp:"ก้อนไทรอยด์ขนาด <b>1.8 cm</b> ที่ ultrasound เป็น <b>solid hypoechoic + ขอบไม่เรียบ (irregular margin)</b> และ TSH ปกติ — ถามขั้นตอนถัดไปตาม algorithm ของ thyroid nodule ซึ่งตัดสินด้วย <b>TSH → US pattern → ขนาด</b>",
  why:"ตาม ATA 2015: ทุก thyroid nodule ตรวจ <b>TSH</b> ก่อน → TSH ปกติหรือสูง ให้ใช้ <b>US pattern + ขนาด</b> ตัดสินว่าต้อง FNA หรือไม่; solid hypoechoic ร่วมกับ irregular/infiltrative margin = <b>high suspicion pattern</b> (malignancy risk 70–90%) → ทำ <b>FNA เมื่อ ≥1 cm</b> ก้อนนี้ 1.8 cm จึงต้อง FNA เพื่อจัด cytology ตาม <b>Bethesda I–VI</b> ก่อนวางแผนผ่าตัด; vascularity ไม่ใช่เกณฑ์หลักใน ATA risk pattern",
  wrong:["Core needle biopsy ไม่ใช่การตรวจชิ้นเนื้อขั้นแรกของ thyroid nodule (FNA ปลอดภัย ถูก แม่นยำพอ) — จะเลือกเมื่อ FNA ได้ผล <b>nondiagnostic (Bethesda I) ซ้ำ</b> หรือสงสัย lymphoma/anaplastic carcinoma ที่ต้องการ histology",
    "Radionuclide scan (I-123 หรือ Tc-99m) ใช้เมื่อ <b>TSH ต่ำ (subnormal)</b> เพื่อหา hyperfunctioning (hot) nodule ซึ่งแทบไม่เป็นมะเร็งและไม่ต้อง FNA — ในข้อนี้ TSH ปกติ scan จึงไม่ช่วยตัดสิน; จะถูกถ้าโจทย์ให้ TSH suppressed (ดูข้อ 50)",
    "ยังไม่มี cytology จึงไม่ควรผ่าตัดทันที; total thyroidectomy เหมาะเมื่อ cytology เป็น Bethesda VI หรือ V ร่วมกับก้อน &gt;4 cm, ETE ชัดเจน, มี nodal/distant metastasis, ก้อนหลายข้าง หรือมีประวัติฉายรังสี; carcinoma 1–4 cm ที่ไม่มีลักษณะเสี่ยงอาจทำ lobectomy",
    "การนัด US ซ้ำโดยไม่ทำ FNA ใช้กับก้อนที่ <b>ไม่เข้าเกณฑ์ FNA</b> (high/intermediate &lt;1 cm, low suspicion &lt;1.5 cm, very low suspicion &lt;2 cm, pure cyst) หรือก้อนที่ FNA ได้ benign แล้ว — ก้อน high suspicion 1.8 cm ต้อง FNA ไม่ใช่เฝ้าดู"],
  trap:"เห็น \"increased vascularity\" แล้วไปสั่ง scan หรือผ่าตัดเลย — vascularity ไม่ใช่เกณฑ์หลัก สิ่งที่ตัดสินคือ TSH (ถ้าต่ำจึง scan) และ US pattern + ขนาด; และลักษณะ well circumscribed ที่ต้นฉบับเขียนจะขัดกับ irregular border (high suspicion ดูจากขอบไม่เรียบ)",
  summary:["Thyroid nodule ทุกก้อน: ตรวจ <b>TSH</b> ก่อน → TSH ต่ำ ทำ radionuclide scan (hot nodule ไม่ต้อง FNA); TSH ปกติหรือสูง → US แล้วตัดสิน FNA ตาม pattern + ขนาด",
    "ATA 2015 US pattern: <b>high</b> = solid hypoechoic + ≥1 อย่าง (irregular/infiltrative margin, microcalcification, taller-than-wide, rim calcification with extrusion, ETE) → FNA ≥1 cm; <b>intermediate</b> = solid hypoechoic ขอบเรียบ → FNA ≥1 cm",
    "<b>Low</b> = isoechoic/hyperechoic solid หรือ partially cystic มี solid eccentric → FNA ≥1.5 cm; <b>very low</b> = spongiform หรือ partially cystic ไม่มีลักษณะข้างต้น → FNA ≥2 cm หรือเฝ้าดู; pure cyst ไม่ต้อง FNA",
    "Bethesda: I nondiagnostic (ทำซ้ำ), II benign (ติดตาม), III AUS (ทำซ้ำ/molecular), IV follicular neoplasm (molecular หรือ lobectomy), V suspicious for malignancy, VI malignant (ผ่าตัด)",
    "Core needle biopsy สงวนไว้เมื่อ FNA nondiagnostic ซ้ำหรือสงสัย lymphoma/anaplastic",
    "Total thyroidectomy เมื่อ carcinoma &gt;4 cm, ETE, nodal/distant metastasis, bilateral หรือประวัติฉายรังสี; 1–4 cm ไม่มี risk ทำ lobectomy ได้",
    "ดูข้อ 50 (thyroid nodule + TSH ต่ำ → radionuclide scan)"],
  notes:"แถว <b>thyroid 2</b> ในไฟล์เฉลยเขียนแค่ <b>\"A\"</b> (ไม่มีคำอธิบาย)<br>ต้นฉบับโจทย์: \"A patient came with <b>neck mass</b>, firm, U/S revealed a 1.8-cm <b>well circumscribed</b> hypoechoic lesion, <b>irregular border</b>, increased vascularity\" — ต้นฉบับเขียนทั้ง well circumscribed และ irregular border ซึ่งขัดกันเอง เราใช้ irregular margins (ลักษณะเด่นที่ผู้จดน่าจะจำได้) และเปลี่ยน neck mass เป็น thyroid nodule<br>เราเติม <b>TSH is normal</b> ใน stem (ตาม algorithm ต้องดู TSH ก่อนตัดสิน FNA)<br>ต้นฉบับผู้จดจำช้อยได้ช้อยเดียว \"A. FNA\" — ช้อย B–E เราแต่งเพิ่ม",
  mnemonic:"<b>TSH ต่ำ → scan; TSH ปกติ → US + size → FNA</b> (high/intermediate 1, low 1.5, very low 2 cm)",
  guide:"ATA 2015",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง — เติม TSH ปกติเพื่อให้เข้า algorithm ที่ต้อง FNA; สอดคล้องกับข้อสอบชุด 76D (TSH ปกติ + solid hypoechoic nodule → FNA)",
  variants:["หญิงอายุ 40 ปี ก้อนไทรอยด์ 1.2 cm TSH ปกติ US พบ solid hypoechoic มี microcalcification และ taller-than-wide → FNA","ผู้ป่วยก้อนไทรอยด์ 2.5 cm TSH ต่ำ → radionuclide scan; ถ้าเป็น hot nodule ไม่ต้อง FNA","ก้อนไทรอยด์ 1.5 cm เป็น spongiform nodule TSH ปกติ → ยังไม่ต้อง FNA (very low suspicion ต้อง ≥2 cm) ติดตาม US"]}),
A({page:20, page2:7, orig:"MIS 1",
  stem:"Which of the following is a relative contraindication to laparoscopic surgery?",
  gray:"Which of the following is contraindication for laparoscopic surgery? — A. Mild obesity (BMI 32) B. History of DM C. Prior abdominal surgery D. … E. Hypertension and ASA",
  opts:["Obesity with BMI 32","Diabetes mellitus","Prior abdominal surgery","Age over 65 years","Controlled hypertension, ASA class II"],
  ans:2, key:"C? Prior abdominal surgery — คำอธิบายในคีย์: น่าตอบสุดแต่ก็ไม่ใช่ Absolute"+KS,
  flag:"⚠ คีย์ใส่ C? และบอกว่าไม่ใช่ absolute contraindication — เปลี่ยนคำถามเป็น relative contraindication; ช้อย D ผู้จดจำไม่ได้ (แต่งเอง), ช้อย E ต้นฉบับ \"Hypertension and ASA\" ไม่ครบ → เติม controlled, ASA class II",
  interp:"ถามข้อห้าม <b>แบบ relative</b> ของการผ่าตัดส่องกล้อง — ต้องแยกให้ออกว่าภาวะใดเพิ่มความยากหรือความเสี่ยงของการเข้าช่องท้อง/pneumoperitoneum จริง และภาวะใดไม่ใช่ข้อห้ามเลย",
  why:"<b>Prior abdominal surgery</b> ทำให้มี <b>adhesion</b> → เสี่ยงบาดเจ็บลำไส้/หลอดเลือดตอนใส่ Veress needle หรือ trocar แรก และทำให้ผ่าตัดยากขึ้นหรือต้อง convert จึงเป็น <b>relative contraindication</b> — แก้ไขได้ด้วยการเลือกจุดเข้าที่ห่างแผลเดิม (<b>Palmer's point</b> ที่ LUQ ใต้ชายโครงซ้ายแนว midclavicular) หรือใช้ <b>open (Hasson) technique</b>; ไม่ใช่ absolute เพราะยังส่องกล้องได้ (ตรงกับคำอธิบายในคีย์ \"น่าตอบสุดแต่ก็ไม่ใช่ Absolute\")",
  wrong:["BMI 32 เป็น obesity class I ไม่ใช่ข้อห้าม — ผู้ป่วยอ้วนกลับได้ประโยชน์จาก laparoscopy มากกว่า (แผลติดเชื้อ, incisional hernia, ปอดแทรกซ้อนน้อยกว่า); <b>morbid obesity</b> (BMI ≥40) จัดเป็น relative contraindication ในบางตำราเพราะเทคนิคยาก ต้องใช้ trocar ยาว",
    "เบาหวานเพิ่มความเสี่ยง SSI และ cardiovascular event ทั่วไป ต้องคุมน้ำตาล perioperative แต่ <b>ไม่ใช่ข้อห้าม</b>ของ laparoscopy (แผลเล็กยิ่งลดการติดเชื้อแผล)",
    "อายุมากอย่างเดียวไม่ใช่ข้อห้าม — ตัดสินจาก physiologic reserve และโรคร่วม (frailty, cardiopulmonary function) ผู้สูงอายุมักฟื้นตัวเร็วกว่าเมื่อผ่าตัดแบบส่องกล้อง",
    "Hypertension ที่ควบคุมได้ (ASA II = mild systemic disease) ทนต่อ pneumoperitoneum ได้ดี ไม่ใช่ข้อห้าม; ที่เป็นข้อห้ามคือ <b>severe cardiopulmonary disease</b> ที่ทนการเพิ่ม intra-abdominal pressure และ CO2 absorption ไม่ได้ (ASA IV, EF ต่ำมาก, severe COPD)"],
  trap:"มองหา absolute contraindication แล้วพบว่าไม่มีช้อยใดเป็น absolute เลยลังเล — ตามคีย์ ช้อยที่เหมาะที่สุดคือ prior abdominal surgery ซึ่งเป็น relative; อย่าเลือก obesity เพราะ BMI 32 ไม่ใช่ morbid obesity",
  summary:["<b>Absolute contraindication</b>: ทน general anesthesia/pneumoperitoneum ไม่ได้ (severe cardiopulmonary disease, EF ต่ำมาก), uncorrectable coagulopathy, hemodynamic instability ที่ต้องเปิดท้องทันที (บางตำรารวม generalized peritonitis ที่ unstable)",
    "<b>Relative contraindication</b>: previous abdominal surgery (adhesion), morbid obesity, pregnancy (ทำได้ทุกไตรมาสแต่ระวัง), portal hypertension/cirrhosis, large ventral hernia, bowel distension มาก, peritonitis",
    "Prior surgery: เลือกจุดเข้าห่างแผลเดิม <b>Palmer's point</b> (LUQ 3 cm ใต้ชายโครงซ้ายแนว midclavicular) หรือ <b>open Hasson technique</b>; ระวังกรณี splenomegaly, NG tube decompress กระเพาะก่อน",
    "ผลทาง physiology ของ CO2 pneumoperitoneum (12–15 mmHg): venous return ลด, SVR เพิ่ม, hypercarbia/acidosis, FRC ลด, renal blood flow ลด — จึงเป็นปัญหาในผู้ป่วย cardiopulmonary reserve ต่ำ",
    "ข้อดีของ laparoscopy: ปวดน้อย, แผลติดเชื้อและ incisional hernia น้อย, ฟื้นตัวเร็ว — ผู้ป่วยอ้วน ผู้สูงอายุ เบาหวาน ได้ประโยชน์",
    "ดูข้อ 1, 2 (perioperative assessment)"],
  notes:"แถว <b>mis 1</b> ในไฟล์เฉลย: คำตอบ <b>\"C?\"</b> + คำอธิบาย <b>\"น่าตอบสุดเเต่ก็ไม่ใช่ Absolute\"</b><br>ต้นฉบับถาม \"contraindication\" เฉย ๆ — เราเปลี่ยนเป็น <b>relative contraindication</b> ตามคำอธิบายในคีย์<br>ต้นฉบับช้อย A \"Mild obesity (BMI 32)\" → Obesity with BMI 32 (ตัดคำว่า mild เพราะ BMI 32 เป็น obesity class I และช้อยห้ามวงเล็บ); B \"History of DM\" → Diabetes mellitus; <b>ช้อย D ผู้จดเขียน \"…\" (จำไม่ได้)</b> — เราแต่งเป็น Age over 65 years; ช้อย E ต้นฉบับ \"Hypertension and ASA\" (ไม่ครบ) → เติมเป็น Controlled hypertension, ASA class II",
  mnemonic:"",
  guide:"Schwartz 11th ed.; SAGES diagnostic laparoscopy guideline 2010",
  opinion:"เห็นด้วยกับคีย์ว่า C ดีที่สุด (มั่นใจปานกลางถึงสูง) แต่เป็น relative contraindication ตามที่คีย์อธิบายเอง ต้นฉบับถาม contraindication โดยไม่ระบุ จึงปรับเป็น relative เพื่อให้มีคำตอบเดียว; ช้อย D แต่งเพิ่ม ช้อย E เติมให้ครบ — สอดคล้องกับข้อสอบชุด 76A และ 76D (absolute contraindication = EF ต่ำมาก หรือ Child C uncorrectable coagulopathy) และชุด 77C (poor candidate for GA)",
  variants:["ผู้ป่วยมีประวัติผ่าตัด midline laparotomy มาก่อน จะทำ laparoscopic cholecystectomy ควรเข้าช่องท้องอย่างไร → open Hasson technique หรือ Palmer's point","ผู้ป่วย severe COPD ร่วมกับ EF 20% มี symptomatic gallstone → laparoscopy มีข้อห้าม พิจารณา percutaneous cholecystostomy หรือ open surgery ตามความเสี่ยง","ผู้ป่วย BMI 45 มี acute cholecystitis → laparoscopic cholecystectomy ยังเป็นทางเลือกแรก แต่ต้องใช้ trocar ยาวและเตรียมพร้อม convert"]}),
A({page:20, page2:7, orig:"MIS 2",
  stem:"An elderly woman presents with abdominal distension, nausea, vomiting and obstipation. The plain abdominal radiograph is shown. What is the most likely diagnosis?",
  gray:"A patient presented with abdominal distension, N/V, obstipation, X-ray as shown, what is the diagnosis? — A. Gallstone ileus",
  img:QI(53), imgNote:"Plain abdominal radiograph with a white arrow",
  opts:["Impacted feces","Gallstone ileus","Sigmoid volvulus","Foreign body ingestion","Intussusception"],
  ans:1, key:"B Gallstone ileus"+KS,
  interp:"อาการลำไส้อุดตัน (distension, N/V, obstipation) ในหญิงสูงอายุ + ฟิล์มท้องมี <b>ลำไส้เล็กโป่งหลายห่วง</b> และลูกศรชี้ <b>ก้อน calcification รูปไข่มีขอบ</b> ที่ RLQ นอกตำแหน่งถุงน้ำดี — ต้องรู้ว่า radiopaque ectopic stone ร่วมกับ SBO คืออะไร",
  why:"<b>Gallstone ileus</b> = นิ่วถุงน้ำดีขนาดใหญ่ (&gt;2–2.5 cm) หลุดผ่าน <b>cholecystoenteric fistula</b> (ส่วนใหญ่ cholecystoduodenal) ไปอุดที่ตำแหน่งแคบที่สุดคือ <b>terminal ileum/ileocecal valve</b> → mechanical SBO; ฟิล์มท้องตาม <b>Rigler triad</b> = (1) SBO (ลำไส้เล็กโป่งหลายห่วง) (2) <b>pneumobilia</b> (ลมในทางเดินน้ำดี RUQ) (3) <b>ectopic calcified gallstone</b> (ลูกศรใน RLQ) — พบบ่อยในหญิงสูงอายุ CT ยืนยันได้แม่นกว่า",
  wrong:["Fecal impaction พบในผู้สูงอายุติดเตียง ท้องผูกเรื้อรัง ฟิล์มเห็น <b>เงาอุจจาระเป็นจุดลายฟองอากาศ (mottled)</b> เต็ม rectum/colon และ colon โป่ง ไม่ใช่ก้อน calcification ขอบชัดก้อนเดียวใน RLQ ร่วมกับลำไส้เล็กโป่ง; จะถูกถ้า PR พบอุจจาระแข็งอัดแน่น",
    "Sigmoid volvulus เห็น <b>sigmoid โป่งมากรูปตัว U กลับหัว (coffee bean)</b> ชี้ไปทาง RUQ, ไม่มีลมใน rectum เป็น large bowel obstruction ในผู้สูงอายุ/ติดเตียง/ท้องผูก — ฟิล์มนี้เป็นลำไส้เล็กโป่งและมีก้อนทึบ จึงไม่ใช่ (ดูข้อ 26)",
    "Foreign body ที่กลืนเข้าไปมักเป็นวัตถุโลหะ/กระดูกที่มีความทึบสูง รูปร่างตามวัตถุ และต้องมีประวัติ (เด็ก ผู้ป่วยจิตเวช ฟันปลอม) — ก้อนรูปไข่ขอบทึบชั้น ๆ ในผู้สูงอายุที่ไม่มีประวัติกลืนวัตถุ เข้ากับนิ่วมากกว่า",
    "Intussusception ในผู้ใหญ่มัก <b>มี lead point</b> (เนื้องอก) อาการปวดท้องเป็นพัก ๆ ฟิล์มอาจเห็นเพียง SBO; การวินิจฉัยใช้ CT (<b>target/sausage sign</b>) — ไม่ทำให้เห็น calcified mass ใน RLQ; จะถูกในเด็ก 6 เดือนถึง 3 ปีที่มี currant jelly stool"],
  trap:"มองแค่ว่าเป็น SBO แล้วตอบ adhesion หรือ intussusception — ต้องหา <b>ก้อนทึบนอกตำแหน่งถุงน้ำดี</b> และลมในทางเดินน้ำดี; นิ่วส่วนใหญ่ radiolucent จึงเห็นนิ่วในฟิล์มได้เพียง ~10–15% ของ gallstone ileus (pneumobilia ช่วยมาก)",
  summary:["Gallstone ileus: นิ่วใหญ่ &gt;2–2.5 cm ผ่าน <b>cholecystoduodenal fistula</b> (พบบ่อยสุด) → อุด <b>terminal ileum</b>; ~1–4% ของ mechanical SBO แต่สูงถึง ~25% ในผู้ป่วย &gt;65 ปี; หญิงมากกว่าชาย",
    "<b>Rigler triad</b>: SBO + pneumobilia + ectopic gallstone (เห็นครบในฟิล์มได้น้อย; CT sensitivity &gt;90%)",
    "อาการอาจเป็นพัก ๆ (tumbling obstruction) เพราะนิ่วกลิ้งไปเรื่อย ๆ ก่อนติด",
    "รักษา: resuscitation, NG decompression → <b>enterolithotomy</b> (ผ่าลำไส้ด้านเหนือก้อนตามยาว เอานิ่วออก ปิดตามขวาง) + คลำหานิ่วอื่นทั้งลำไส้",
    "Cholecystectomy + fistula repair พร้อมกัน (one-stage) เฉพาะผู้ป่วยแข็งแรง; ส่วนใหญ่ทำ enterolithotomy อย่างเดียวแล้วพิจารณา cholecystectomy ภายหลังหรือไม่ทำ (two-stage) เพราะผู้ป่วยสูงอายุและโรคร่วมมาก",
    "Bouveret syndrome = นิ่วอุดที่ duodenum/pylorus ทำให้ gastric outlet obstruction",
    "ดูข้อ 26, 35 (ภาพรังสีลำไส้อุดตัน) และ 28, 31 (gallbladder)"],
  notes:"แถว <b>mis 2</b> ในไฟล์เฉลยเขียนแค่ <b>\"A\"</b> (= Gallstone ileus ซึ่งเป็นช้อยเดียวที่ผู้จดจำได้; ลำดับของเราเป็น B)<br>ต้นฉบับผู้จดจำช้อยได้ช้อยเดียว \"A. Gallstone ileus\" — ช้อยอีก 4 ช้อยเราแต่งเพิ่ม และเราเติม <b>elderly woman</b> ใน stem<br>ภาพเดียวกับข้อสอบชุด 77D: ฟิล์มท้องท่านอนเห็นลำไส้เล็กโป่งหลายห่วง ลูกศรสีขาวชี้ก้อนทึบรูปไข่ที่ RLQ",
  mnemonic:"<b>Rigler triad = ลำไส้เล็กโป่ง + ลมในท่อน้ำดี + นิ่วผิดที่</b>",
  guide:"Schwartz 11th ed.; Sabiston 21st ed.",
  opinion:"เห็นด้วยกับคีย์ (Gallstone ileus) มั่นใจสูง — สอดคล้องกับข้อสอบชุด 76A และ 77D (gallstone ileus)",
  variants:["หญิงอายุ 80 ปี มีประวัตินิ่วถุงน้ำดี มาด้วยอาเจียน ท้องอืด CT พบลมใน biliary tree และก้อนนิ่วใน distal ileum → enterolithotomy","ผู้ป่วยสูงอายุอาเจียนมากหลังอาหาร CT พบนิ่วขนาด 4 cm อุดที่ duodenal bulb และมี cholecystoduodenal fistula → Bouveret syndrome","ผู้ป่วย gallstone ileus อายุ 85 ปี โรคหัวใจรุนแรง ควรผ่าตัดแบบใด → enterolithotomy อย่างเดียว ไม่ทำ cholecystectomy พร้อมกัน"]}),
A({page:21, page2:7, orig:"Colorectal 1",
  stem:"A 76-year-old man with sigmoid colon cancer has stable angina, diabetes and hypertension. His ECOG performance status is 3 and he does not wish to undergo major surgery. There is no bowel obstruction or distant metastasis. What is the most appropriate management?",
  gray:"ผู้ป่วยอายุ 76ปี เป็น sigmoid colon CA, U/D: stable angina,DM (ECOG3), hypertension ทำไร — A. Palliative B. Stent",
  opts:["Palliative and best supportive care","Colonic stent placement","Sigmoidectomy with primary anastomosis","Hartmann procedure","Neoadjuvant chemoradiation then surgery"],
  ans:0, key:NK+" — แถว colorectal 1 ในไฟล์เฉลยว่าง (ผู้จดให้ช้อย A Palliative, B Stent)",
  flag:"⚠ ไม่มีคีย์ และต้นฉบับขาดข้อมูล — เติมใน stem ว่าไม่มีลำไส้อุดตัน ไม่มี metastasis ECOG 3 จากโรคร่วม และผู้ป่วยไม่ต้องการผ่าตัดใหญ่ (ถ้ามีลำไส้อุดตันจะตอบ stent)",
  interp:"ผู้ป่วยสูงอายุมะเร็ง sigmoid ที่ <b>performance status แย่ (ECOG 3)</b> จากโรคร่วมหลายอย่าง ไม่มีลำไส้อุดตัน และไม่ต้องการผ่าตัดใหญ่ — ถามว่าการรักษาที่เหมาะสมคือ curative resection, การใส่ stent หรือ palliative care",
  why:"<b>ECOG 3</b> = ดูแลตัวเองได้จำกัด อยู่บนเตียงหรือเก้าอี้ &gt;50% ของเวลาตื่น → ทนการผ่าตัดใหญ่และ chemotherapy ได้ไม่ดี (มาตรฐานการให้ systemic therapy มักต้อง ECOG 0–2) ร่วมกับผู้ป่วยไม่ต้องการผ่าตัด และ <b>ไม่มีภาวะอุดตันที่ต้องแก้</b> → เหมาะกับ <b>symptom-directed palliative/best supportive care</b>: ให้เลือดหรือธาตุเหล็กเมื่อซีด, คุมอาการปวดและการขับถ่าย, ดูแลภาวะโภชนาการ, advance care planning; หากภายหลังเกิด obstruction จึงพิจารณา stent หรือ diverting stoma",
  wrong:["Colonic stent (SEMS) ใช้เมื่อมี <b>malignant large bowel obstruction</b> — เพื่อ palliation ในผู้ป่วยที่ผ่าตัดไม่ได้ หรือ bridge to surgery; ใส่ใน tumor ที่ไม่อุดตันไม่มีประโยชน์และเสี่ยง perforation/migration; <b>จะถูกถ้าโจทย์บอกว่ามีลำไส้อุดตัน</b> (ต้นฉบับไม่ได้ระบุ ผู้จดให้ช้อยนี้ไว้)",
    "Oncologic sigmoidectomy + ลิมฟ์ ≥12 ต่อม + primary anastomosis เป็นมาตรฐานของ non-metastatic colon cancer ใน <b>ผู้ป่วยที่ fit (ECOG 0–2)</b> และยินยอม — ผู้ป่วยรายนี้ ECOG 3 และไม่ต้องการผ่าตัดใหญ่",
    "Hartmann procedure (resection + end colostomy) ใช้ในภาวะฉุกเฉิน เช่น obstruction หรือ perforation ที่ต่อลำไส้ไม่ปลอดภัย — ยังเป็นการผ่าตัดใหญ่ ไม่เหมาะในผู้ป่วยรายนี้ที่ไม่มีภาวะฉุกเฉิน",
    "Neoadjuvant chemoradiation ใช้ใน <b>rectal cancer</b> (locally advanced) ไม่ใช่มาตรฐานใน sigmoid colon cancer และผู้ป่วย ECOG 3 ทนการรักษาร่วมหลายแบบไม่ได้"],
  trap:"เลือก stent เพราะคิดว่า \"palliative intervention\" — stent ใช้แก้ obstruction ไม่ได้ใช้รักษาตัวมะเร็ง; ถ้าไม่มี obstruction การดูแลแบบประคับประคองคือคำตอบ",
  summary:["ECOG: 0 ปกติ, 1 ทำงานเบาได้, 2 ดูแลตัวเองได้แต่ทำงานไม่ได้ ลุกจากเตียง &gt;50%, <b>3 ดูแลตัวเองได้จำกัด อยู่บนเตียง/เก้าอี้ &gt;50%</b>, 4 ติดเตียงทั้งหมด, 5 เสียชีวิต",
    "Non-metastatic colon cancer ใน fit patient: colectomy + en bloc mesentery + ลิมฟ์ ≥12 ต่อม; stage III ให้ adjuvant chemotherapy",
    "ผู้สูงอายุ: ใช้ geriatric assessment (frailty, cognition, function) ร่วมกับเป้าหมายของผู้ป่วยตัดสินใจ ไม่ใช่อายุอย่างเดียว",
    "ผู้ป่วย ECOG 3–4 หรือไม่ต้องการผ่าตัด: best supportive care — แก้ซีด, คุมอาการ, โภชนาการ, advance care planning",
    "Malignant LBO: palliative SEMS หรือ diverting stoma ในผู้ป่วยผ่าตัดไม่ได้; SEMS เป็น bridge to surgery ได้ใน fit patient",
    "Neoadjuvant CRT เป็นมาตรฐานของ locally advanced rectal cancer ไม่ใช่ colon cancer",
    "ดูข้อ 55, 56, 57, 58 (colorectal)"],
  notes:"<b>แถว colorectal 1 ในไฟล์เฉลยว่าง</b> (section colorectal ในคีย์ แถว 1–3 ว่างทั้งหมด)<br>ต้นฉบับโจทย์เป็นภาษาไทย: \"ผู้ป่วยอายุ 76ปี เป็น sigmoid colon CA, U/D: stable angina,DM (ECOG3), hypertension ทำไร\" — ผู้จดให้ช้อยไว้ 2 ช้อย A. Palliative B. Stent แต่ไม่ได้บอกว่าตอบข้อไหน; ช้อย C, D, E เราแต่งเพิ่ม<br>เราเติมใน stem: ผู้ป่วยไม่ต้องการผ่าตัดใหญ่, ไม่มีลำไส้อุดตัน, ไม่มี distant metastasis (เพื่อให้เหลือคำตอบเดียว)",
  mnemonic:"",
  guide:"NCCN Colon Cancer 2025; ESMO localised colon cancer 2020",
  opinion:"ไม่มีคีย์ — เราตอบ A ความมั่นใจปานกลาง เพราะต้นฉบับข้อมูลไม่ครบ: ถ้าข้อสอบจริงบอกว่ามี obstruction คำตอบจะเป็น stent (B) ซึ่งผู้จดให้ไว้เป็นช้อยด้วย; เราเติมว่าไม่มี obstruction และผู้ป่วยไม่ต้องการผ่าตัดเพื่อให้ palliative care เป็นคำตอบเดียว",
  variants:["ชายอายุ 80 ปี ECOG 3 มะเร็ง sigmoid มาด้วยท้องอืด ไม่ถ่าย CT พบ large bowel obstruction ที่ sigmoid ไม่มี perforation → palliative colonic stent","ชายอายุ 72 ปี ECOG 1 มะเร็ง sigmoid ไม่มี metastasis → laparoscopic sigmoidectomy + lymphadenectomy","ผู้ป่วยมะเร็ง sigmoid มี obstruction ร่วมกับ perforation และ fecal peritonitis → Hartmann procedure"]}),
A({page:21, page2:7, orig:"Colorectal 2",
  stem:"A patient has right-sided colon cancer with pericolonic lymph node involvement and no distant metastasis. He needs procedure (1), shown in the figure, followed by (2) to restore bowel continuity and postoperative treatment (3). What are (1), (2) and (3)?",
  gray:"A patient presented with right sided colon cancer with pericolonic lymph nodes involvement, no evidence of metastasis, needed to undergo procedure (1, as shown) which need (2) to preserve bowel continuity, and postoperative (3), what are (1), (2), (3) — A. (1) Left colectomy, (2) …, (3) … B. (1) Left colectomy, (2) … (3) … C. (1) Right colectomy, (2) … , (3) palliative chemoradiation D. (1) Right colectomy, (2) ileocolic anastomosis, (3) adjuvant chemoradiation E. (1) Extended right colectomy, (2) …, (3) palliative chemoradiation",
  img:QI(55), imgNote:"Diagram of the colon and its blood supply with a shaded, dotted-outline resection area",
  opts:["Left colectomy; colorectal anastomosis; adjuvant chemotherapy","Left colectomy; end colostomy; surveillance only","Right colectomy; end ileostomy; palliative chemoradiation","Right colectomy; ileocolic anastomosis; adjuvant chemotherapy","Extended right colectomy; ileocolic anastomosis; palliative chemoradiation"],
  ans:3, key:NK+" — แถว colorectal 2 ในไฟล์เฉลยว่าง",
  flag:"⚠ ไม่มีคีย์ — ปรับ (3) ของช้อย D จาก adjuvant chemoradiation เป็น adjuvant chemotherapy (มะเร็งลำไส้ใหญ่ไม่ใช้ radiation เป็นมาตรฐาน); ช้อยที่ผู้จดเขียน \"…\" แต่งเติมเอง",
  interp:"มะเร็งลำไส้ใหญ่ด้านขวา <b>มีต่อมน้ำเหลือง pericolic (N+) ไม่มี metastasis = stage III</b> — ต้องอ่านรูปว่าตัดส่วนใด (1), ต่อลำไส้แบบใด (2) และการรักษาเสริมหลังผ่าตัด (3)",
  why:"รูปแรเงา <b>cecum, ascending colon, hepatic flexure และ transverse colon ส่วนต้น</b> พร้อม mesentery ที่มี ileocolic, right colic และแขนงขวาของ middle colic = <b>right (hemi)colectomy</b>; ต่อ terminal ileum กับ transverse colon = <b>ileocolic (ileotransverse) anastomosis</b>; pN+ M0 = <b>stage III</b> → <b>adjuvant chemotherapy</b> (CAPOX หรือ FOLFOX: low-risk T1–3N1 ให้ CAPOX 3 เดือน, high-risk T4 หรือ N2 ให้ 6 เดือน ตาม IDEA) — radiation ไม่ใช่การรักษามาตรฐานของ colon cancer",
  wrong:["Left colectomy ตัด descending colon ถึง sigmoid (inferior mesenteric/left colic) ใช้กับมะเร็งด้านซ้าย — รูปแรเงาด้านขวาของลำไส้ใหญ่ และโจทย์บอก right-sided colon cancer",
    "Left colectomy ไม่ตรงกับรูป, end colostomy ไม่ได้ \"preserve bowel continuity\" ตามที่โจทย์ถาม และ stage III ต้องได้ adjuvant chemotherapy ไม่ใช่แค่ surveillance (surveillance อย่างเดียวใช้กับ stage I และ low-risk stage II)",
    "End ileostomy ไม่ได้ต่อลำไส้ ใช้เฉพาะภาวะที่ต่อไม่ปลอดภัย (ฉุกเฉิน, peritonitis, ผู้ป่วยไม่ stable); palliative chemoradiation ไม่เหมาะกับ stage III ที่ตัดได้หมดและตั้งใจหายขาด",
    "Extended right colectomy ตัดเลยไปถึง transverse colon ส่วนปลายหรือ splenic flexure (รวม middle colic ทั้งหมด) ใช้กับมะเร็ง hepatic flexure/transverse colon ส่วนต้น — รูปนี้ตัดแค่ transverse ส่วนต้น และ (3) palliative chemoradiation ผิดเช่นกัน"],
  trap:"เห็นช้อย D ต้นฉบับเขียน adjuvant chemoradiation แล้วคิดว่าถูกทั้งหมด — colon cancer ใช้ adjuvant <b>chemotherapy</b>; radiation เป็นส่วนหนึ่งของการรักษา <b>rectal</b> cancer",
  summary:["Right hemicolectomy: ตัด terminal ileum ~10 cm, cecum, ascending colon, hepatic flexure, transverse ส่วนต้น + ligate ileocolic, right colic, right branch of middle colic → ileotransverse anastomosis; ใช้กับมะเร็ง cecum/ascending",
    "Extended right hemicolectomy: เพิ่ม transverse colon จน splenic flexure + middle colic ทั้งหมด → ใช้กับมะเร็ง hepatic flexure/transverse",
    "Left hemicolectomy: descending colon (± splenic flexure) ligate left colic/IMA; sigmoidectomy สำหรับ sigmoid cancer",
    "หลัก oncologic: en bloc mesentery (complete mesocolic excision), high ligation, ลิมฟ์ ≥12 ต่อม, margin ≥5 cm",
    "Stage III (N+ M0): adjuvant FOLFOX หรือ CAPOX — low-risk (T1–3N1) CAPOX 3 เดือน, high-risk (T4 หรือ N2) 6 เดือน (IDEA); high-risk stage II พิจารณา chemotherapy",
    "Radiation: มาตรฐานใน rectal cancer (neoadjuvant) ไม่ใช่ colon cancer",
    "ดูข้อ 54, 56, 57, 58 (colorectal)"],
  notes:"<b>แถว colorectal 2 ในไฟล์เฉลยว่าง</b><br>ต้นฉบับช้อย D: \"(1) Right colectomy, (2) ileocolic anastomosis, (3) <b>adjuvant chemoradiation</b>\" — เราเปลี่ยน (3) เป็น adjuvant chemotherapy<br>ช้อยอื่นผู้จดจำบางส่วนไม่ได้ (\"…\"): A \"(1) Left colectomy, (2) …, (3) …\", B \"(1) Left colectomy, (2) … (3) …\", C \"(1) Right colectomy, (2) … , (3) palliative chemoradiation\", E \"(1) Extended right colectomy, (2) …, (3) palliative chemoradiation\" — ส่วนที่เป็น \"…\" เราแต่งเติมเอง (A: colorectal anastomosis, adjuvant chemotherapy; B: end colostomy, surveillance only; C: end ileostomy; E: ileocolic anastomosis)<br>รูป: ภาพวาดลำไส้ใหญ่และหลอดเลือด แรเงาสีฟ้าล้อมเส้นประบริเวณ cecum, ascending colon, hepatic flexure และ transverse ส่วนต้น",
  mnemonic:"",
  guide:"NCCN Colon Cancer 2025",
  opinion:"ไม่มีคีย์ — เราตอบ D ความมั่นใจสูงว่าเจตนาของข้อคือช้อยนี้ (ช้อยเดียวที่ผู้จดจำได้ครบทั้ง 3 ส่วน) แต่ปรับ (3) จาก adjuvant chemoradiation เป็น adjuvant chemotherapy เพราะ radiation ไม่ใช่มาตรฐานใน colon cancer",
  variants:["ผู้ป่วยมะเร็ง cecum T3N0M0 ตรวจลิมฟ์ได้ 15 ต่อม ไม่มี high-risk feature → right hemicolectomy แล้ว surveillance","ผู้ป่วยมะเร็ง hepatic flexure T3N1M0 → extended right hemicolectomy + adjuvant CAPOX","ผู้ป่วยมะเร็ง descending colon T4N2M0 หลัง left hemicolectomy → adjuvant FOLFOX หรือ CAPOX 6 เดือน"]}),
A({page:22, page2:7, orig:"Colorectal 3",
  stem:"A young patient has the oral and perioral findings shown and is scheduled for colonoscopy. Which lesions are most likely to be found?",
  gray:"A patient with oral lesion as shown, colonoscopy as shown (หารูปไม่เจออะ), what will be found in colonoscopy? — A. Hamartomatous polyps",
  img:QI(56), imgNote:"Photograph of the lips and perioral area (ข้อสอบจริงมีรูป colonoscopy ด้วยแต่ผู้จดหาไม่เจอ)",
  opts:["Hamartomatous polyps","Hundreds of adenomatous polyps","Hyperplastic polyps","Inflammatory pseudopolyps","Sessile serrated lesions"],
  ans:0, key:RC("A. Hamartomatous polyps"),
  interp:"รูปริมฝีปากมี <b>จุดสีน้ำตาลเข้มถึงดำหลายจุด</b> ที่ริมฝีปากและรอบปาก ในคนอายุน้อย — ต้องเชื่อม mucocutaneous pigmentation กับ polyposis syndrome และชนิดของ polyp ที่จะพบใน colonoscopy",
  why:"<b>Peutz-Jeghers syndrome</b> = mucocutaneous <b>melanin pigmentation</b> (ริมฝีปาก, buccal mucosa, รอบปาก, นิ้วมือนิ้วเท้า — เริ่มในวัยเด็กและจางลงตามอายุ ยกเว้น buccal) + <b>hamartomatous polyps</b> ทั่วทางเดินอาหาร (พบมากสุดที่ <b>ลำไส้เล็ก โดยเฉพาะ jejunum</b> รองลงมา colon และกระเพาะ) ซึ่งมีลักษณะ <b>arborizing smooth muscle</b> แตกกิ่งในชั้น lamina propria; autosomal dominant ยีน <b>STK11 (LKB1)</b>",
  wrong:["Adenomatous polyps นับร้อยถึงพันตัว = <b>FAP</b> (APC gene) — ไม่มี mucocutaneous pigmentation แต่มี extracolonic feature เช่น desmoid tumor, osteoma, CHRPE (Gardner syndrome); จะถูกถ้าโจทย์ให้ประวัติครอบครัวมะเร็งลำไส้อายุน้อยกับ polyp จำนวนมาก",
    "Hyperplastic polyp เป็น polyp เล็ก ๆ ที่พบบ่อยใน rectosigmoid โดยไม่สัมพันธ์กับ pigmentation; ถ้ามีจำนวนมาก/ใหญ่ต้องนึกถึง serrated polyposis syndrome ไม่ใช่ภาพนี้",
    "Inflammatory pseudopolyp เกิดจาก mucosa ที่งอกใหม่หลังการอักเสบ พบใน <b>IBD</b> (โดยเฉพาะ ulcerative colitis เรื้อรัง) ไม่ใช่ polyposis syndrome ทางพันธุกรรม",
    "Sessile serrated lesion เป็น precursor ของมะเร็งผ่าน serrated pathway (BRAF, CIMP) มักอยู่ proximal colon พบในผู้ใหญ่ทั่วไป ไม่สัมพันธ์กับ pigmentation ที่ริมฝีปาก"],
  trap:"เห็นคำว่า hamartoma แล้วสับสนกับ juvenile polyposis (ก็เป็น hamartoma แต่ <b>ไม่มี pigmentation</b> และพบใน colon มากสุด) หรือคิดว่า polyposis ทุกชนิดเป็น adenoma แบบ FAP",
  summary:["Peutz-Jeghers: AD, <b>STK11/LKB1</b>; mucocutaneous melanin pigmentation + hamartomatous polyps (jejunum &gt; ileum, colon, stomach) ที่มี arborizing smooth muscle",
    "ภาวะแทรกซ้อน: <b>intussusception</b> (ลำไส้เล็ก) ทำให้ปวดท้อง/SBO, เลือดออก, ซีด — มักเริ่มในวัยเด็กถึงวัยรุ่น",
    "เสี่ยงมะเร็งสูงทั้ง GI (colon, stomach, small bowel, pancreas) และนอก GI: breast, ovary (sex cord tumor with annular tubules), cervix (adenoma malignum), testis (Sertoli cell tumor)",
    "Surveillance: เริ่ม EGD + colonoscopy + capsule endoscopy หรือ MR enterography ราวอายุ 8 ปี ทำซ้ำทุก 2–3 ปี; ตัด polyp ลำไส้เล็กที่ใหญ่ ≥1–1.5 cm เพื่อป้องกัน intussusception",
    "แยกโรค: FAP (APC) adenoma นับร้อย; juvenile polyposis (SMAD4, BMPR1A) hamartoma ใน colon ไม่มี pigmentation; Cowden (PTEN) hamartoma + trichilemmoma + มะเร็งเต้านม/ไทรอยด์",
    "ดูข้อ 16 (hereditary colorectal cancer syndrome) และ 54, 55, 57, 58 (colorectal)"],
  notes:"<b>แถว colorectal 3 ในไฟล์เฉลยว่าง</b> — ไม่มีคีย์ ผู้จดจำช้อยได้ช้อยเดียว \"A. Hamartomatous polyps\" (น่าจะเป็นคำตอบที่ผู้จดเลือก) ช้อยอีก 4 ช้อยเราแต่งเพิ่ม<br>โน้ตผู้จดในโจทย์: <b>\"(หารูปไม่เจออะ)\"</b> — ข้อสอบจริงมีรูป colonoscopy ด้วย แต่ผู้จดหารูปไม่เจอ ในไฟล์จึงมีแต่รูปริมฝีปาก<br>รูป: ริมฝีปากล่างและบนมีจุดสีน้ำตาลเข้มถึงดำจำนวนมาก และมีจุดสีน้ำตาลกระจายรอบปากและจมูก",
  mnemonic:"<b>Peutz-Jeghers = ปากมีจุด + hamartoma ลำไส้เล็ก + intussusception</b>",
  guide:"NCCN Genetic/Familial High-Risk Assessment: Colorectal 2025; ACG hereditary GI cancer syndromes 2015",
  opinion:"ไม่มีคีย์ — เราตอบ A ตรงกับช้อยที่ผู้จดใส่ไว้ มั่นใจสูง (pigmentation ที่ริมฝีปากเป็นลักษณะของ Peutz-Jeghers); สอดคล้องกับข้อสอบชุด 76D (pigmented lips + SBO → hamartomatous polyp)",
  variants:["วัยรุ่นมาด้วยปวดท้องเป็นพัก ๆ อาเจียน มีจุดสีเข้มที่ริมฝีปาก CT พบ target sign ที่ jejunum → intussusception จาก hamartomatous polyp ใน Peutz-Jeghers","ผู้ป่วยอายุ 20 ปี colonoscopy พบ adenomatous polyp มากกว่า 100 ตัว บิดาเสียชีวิตจากมะเร็งลำไส้อายุ 40 ปี → FAP วางแผน proctocolectomy","เด็กอายุ 5 ปี ถ่ายเป็นเลือด colonoscopy พบ juvenile polyp จำนวนมากใน colon ไม่มี pigmentation → juvenile polyposis syndrome"]}),
A({page:22, page2:7, orig:"Colorectal 4",
  stem:"A young patient has had bloody diarrhea for 3 months. Colonoscopy reveals continuous mucosal lesions from the rectum to the ascending colon, as shown. What is the most likely diagnosis?",
  gray:"A patient came with …, colonoscopy revealed lesions along rectum to the ascending colon as shown, what is the diagnosis? — A. Crohn's disease B. Ulcerative colitis C. Irritable bowel syndrome",
  img:QI(57), imgNote:"Colonoscopic image",
  opts:["Crohn's disease","Ulcerative colitis","Irritable bowel syndrome","Ischemic colitis","Colonic tuberculosis"],
  ans:1, key:NK+" — ไม่มีแถวข้อนี้ในไฟล์เฉลย",
  flag:"⚠ ไม่มีคีย์ — อาการนำผู้จดจำไม่ได้ (\"…\") จึงเติม chronic bloody diarrhea",
  interp:"ถ่ายเป็นเลือดเรื้อรังในคนอายุน้อย + colonoscopy เห็นรอยโรค <b>ต่อเนื่องตั้งแต่ rectum ขึ้นไป</b> ถึง ascending colon และภาพ mucosa — ต้องแยก IBD สองชนิดจากการกระจายตัวและลักษณะ mucosa",
  why:"<b>Ulcerative colitis</b> เป็นการอักเสบของ <b>mucosa</b> ที่ <b>เริ่มที่ rectum เสมอ</b> แล้วลามขึ้นไป proximal <b>ต่อเนื่องไม่มีช่วงเว้น</b> — รอยโรคถึง ascending colon (เลย splenic flexure) = extensive colitis; ภาพ colonoscopy: mucosa แดงทั่ว ๆ <b>granular</b>, เปราะเลือดออกง่าย (friability, spontaneous bleeding), หลอดเลือดใต้ mucosa หายไป, แผลตื้น — ตรงกับภาพ; อาการเด่น bloody diarrhea, tenesmus, urgency",
  wrong:["Crohn's disease มีรอยโรค <b>เป็นหย่อม (skip lesion)</b>, มัก <b>rectal sparing</b>, พบ terminal ileum บ่อย, แผล aphthous หรือ deep linear ulcer, cobblestone, อักเสบทุกชั้น (transmural) จึงเกิด fistula/stricture/perianal disease และ granuloma ในชิ้นเนื้อ — จะถูกถ้ารอยโรคเว้นช่วงและ rectum ปกติ",
    "IBS เป็น functional disorder ปวดท้องสัมพันธ์กับการถ่าย <b>ไม่มีรอยโรคใน mucosa</b> ไม่มีเลือดออก — การถ่ายเป็นเลือดและ colonoscopy ผิดปกติเป็น alarm feature ที่ตัด IBS ออก",
    "Ischemic colitis พบในผู้สูงอายุที่มีโรคหลอดเลือด อาการเฉียบพลัน ปวดท้องแล้วถ่ายเป็นเลือด มักเป็นที่ <b>watershed area (splenic flexure, rectosigmoid junction)</b> เป็นช่วง ๆ และ rectum มักไม่เป็นเพราะเลือดมาเลี้ยงสองทาง — ไม่ใช่อาการเรื้อรัง 3 เดือนตั้งแต่ rectum",
    "Colonic TB มักเป็นที่ <b>ileocecal region</b> มีแผลแนวขวาง (transverse ulcer), ileocecal valve เปิดอ้า, ก้อน, stricture ร่วมกับไข้ น้ำหนักลด — ไม่ใช่รอยโรคต่อเนื่องจาก rectum"],
  trap:"สับสนว่ารอยโรคไปถึง ascending colon แล้วนึกว่าเป็น Crohn (เพราะอยู่ด้านขวา) — ตัวตัดสินคือ <b>เริ่มที่ rectum และต่อเนื่อง</b> = UC; Crohn ต้องเป็นหย่อมและมัก rectal sparing",
  summary:["UC: mucosal inflammation เริ่ม rectum ลามต่อเนื่อง; Montreal: E1 proctitis, E2 left-sided (ถึง splenic flexure), E3 extensive (เลย splenic flexure)",
    "ภาพส่องกล้อง UC: erythema, granularity, friability, หลอดเลือดหาย, ulcer ตื้น, pseudopolyp ในรายเรื้อรัง; ชิ้นเนื้อ crypt abscess, crypt distortion",
    "Crohn: skip lesion, rectal sparing, terminal ileum, aphthous/linear ulcer, cobblestone, transmural, fistula/stricture, perianal disease, noncaseating granuloma",
    "ประเมินความรุนแรงด้วย Truelove-Witts; acute severe UC ให้ IV corticosteroid และ rescue therapy (infliximab หรือ cyclosporine) หรือ colectomy",
    "ข้อบ่งชี้ผ่าตัด UC: toxic megacolon, perforation, massive bleeding, refractory disease, dysplasia/cancer → total proctocolectomy + IPAA (ทำให้หายขาด)",
    "แยกโรค: infectious colitis (เพาะเชื้อ, C. difficile), ischemic colitis (ผู้สูงอายุ watershed), TB (ileocecal), IBS (ไม่มีรอยโรค)",
    "ดูข้อ 54, 55, 56, 58 (colorectal)"],
  notes:"<b>ไม่มีแถวข้อนี้ในไฟล์เฉลย</b> (section colorectal ในคีย์มีแค่แถว 1–3 และว่างทั้งหมด)<br>ต้นฉบับ: \"A patient came with <b>…</b>, colonoscopy revealed lesions along rectum to the ascending colon as shown\" — ผู้จดจำอาการนำไม่ได้ เราเติม <b>young patient + bloody diarrhea for 3 months</b> และเติมคำว่า continuous mucosal lesions ตามที่ต้นฉบับบอกว่ารอยโรคยาวตั้งแต่ rectum ถึง ascending colon<br>ผู้จดให้ช้อย A Crohn's disease, B Ulcerative colitis, C Irritable bowel syndrome แต่ไม่ได้บอกคำตอบ; ช้อย D, E เราแต่งเพิ่ม<br>รูป: colonoscopy เห็น mucosa แดงทั่ว ๆ granular มีจุดเลือดออก หลอดเลือดใต้ mucosa มองไม่เห็น",
  mnemonic:"<b>UC = Up from the rectum, Continuous</b>",
  guide:"ACG ulcerative colitis 2019; ECCO UC 2022",
  opinion:"ไม่มีคีย์ — เราตอบ B มั่นใจสูง จากการกระจายตัวที่เริ่ม rectum ต่อเนื่องและภาพ mucosa; อาการนำเราเติมเองเพราะผู้จดจำไม่ได้",
  variants:["หญิงอายุ 25 ปี ถ่ายเป็นเลือดมีมูก 10 ครั้งต่อวัน ไข้ ชีพจร 110 Hb 9 → acute severe UC ให้ IV corticosteroid","ชายอายุ 22 ปี ปวดท้อง RLQ ท้องเสียเรื้อรัง มี perianal fistula colonoscopy พบ skip lesion ที่ terminal ileum → Crohn's disease","ผู้ป่วย UC 10 ปี colonoscopy surveillance พบ high-grade dysplasia ใน flat mucosa → total proctocolectomy"]}),
A({page:23, page2:7, orig:"Colorectal 5",
  stem:"An elderly patient with chronic constipation presents with massive painless bright red blood per rectum. Vital signs are stable. What is the most likely diagnosis?",
  gray:"An old patient came with massive rectal bleeding with a history of chronic constipation, no anal pain, V/S stable, what is the diagnosis? — A. Internal hemorrhoids B. Diverticulosis",
  opts:["Internal hemorrhoids","Colonic diverticulosis","Anal fissure","Ischemic colitis","Rectal cancer"],
  ans:1, key:NK+" — ไม่มีแถวข้อนี้ในไฟล์เฉลย (ผู้จดให้ช้อย A Internal hemorrhoids, B Diverticulosis)",
  interp:"ผู้สูงอายุมี <b>massive painless hematochezia</b> + ประวัติท้องผูกเรื้อรัง ไม่ปวดทวาร สัญญาณชีพคงที่ — ถามสาเหตุที่พบบ่อยที่สุดของ lower GI bleeding ปริมาณมากในผู้สูงอายุ",
  why:"<b>Diverticular bleeding</b> เป็นสาเหตุที่พบบ่อยที่สุดของ LGIB ในผู้สูงอายุ: เลือดแดงสดหรือแดงคล้ำ <b>ปริมาณมาก ไม่เจ็บ ไม่ปวดท้อง</b> เกิดจาก vasa recta ที่ยืดบางบริเวณคอ diverticulum แตก; <b>หยุดเองได้ราว 75–80%</b> แต่เป็นซ้ำได้; ท้องผูกเรื้อรังและอาหารใยต่ำเป็นปัจจัยเสี่ยงของ diverticulosis (NSAIDs/antiplatelet เพิ่มความเสี่ยงเลือดออก); ในคนเอเชีย diverticula ด้านขวาพบบ่อยและเลือดออกรุนแรงกว่า",
  wrong:["Internal hemorrhoid เลือดแดงสดหยดหรือติดกระดาษ <b>หลังถ่าย</b> ไม่เจ็บ ปริมาณน้อยถึงปานกลาง ไม่ค่อยทำให้ massive bleeding — จะถูกถ้าโจทย์บอกเลือดหยดหลังถ่ายปริมาณน้อยร่วมกับก้อนยื่น (ดูข้อ 47, 48)",
    "Anal fissure <b>ปวดมากขณะถ่ายและหลังถ่าย</b> เลือดออกน้อยติดกระดาษ — โจทย์บอกไม่ปวดทวารและเลือดออกมาก จึงไม่ใช่ (ดูข้อ 46)",
    "Ischemic colitis พบในผู้สูงอายุเช่นกัน แต่มัก <b>ปวดท้องเฉียบพลันก่อน</b> (มักด้านซ้าย) แล้วถ่ายเป็นเลือดปนอุจจาระ/bloody diarrhea ปริมาณไม่มาก — ไม่ใช่ painless massive bleeding",
    "Rectal cancer มักเลือดออกปริมาณน้อยปนอุจจาระเป็นช่วง ๆ ร่วมกับ <b>เปลี่ยนนิสัยการขับถ่าย, tenesmus, น้ำหนักลด, ซีด</b> — ไม่ค่อยทำให้เลือดออกมากฉับพลัน แต่ยังต้องส่องกล้องตัดออกในผู้สูงอายุทุกราย"],
  trap:"เห็น painless bright red bleeding แล้วตอบ hemorrhoid — คำว่า <b>massive</b> ในผู้สูงอายุชี้ไปที่ diverticular bleeding (หรือ angiodysplasia); hemorrhoid เลือดออกไม่มาก",
  summary:["สาเหตุ LGIB ในผู้สูงอายุ: diverticulosis (พบบ่อยสุด), angiodysplasia, ischemic colitis, neoplasia, post-polypectomy, hemorrhoid; ต้องคิดถึง brisk UGIB ถ้า hemodynamics ไม่คงที่",
    "Diverticular bleeding: massive, painless, หยุดเองได้ ~75–80%, เป็นซ้ำ ~25%; diverticulitis กลับไม่ค่อยเลือดออก",
    "ขั้นตอน: resuscitation + ประเมินความเสี่ยง (Oakland score) → stable: <b>colonoscopy</b> หลัง bowel prep (ภายใน 24 ชม. ในรายเสี่ยงสูง) ให้การรักษาทางกล้องได้ (clip, epinephrine, band)",
    "Unstable หรือเลือดออกต่อเนื่อง: <b>CT angiography</b> หา active extravasation → angioembolization; ถ้าล้มเหลว → segmental colectomy (รู้ตำแหน่ง) หรือ subtotal colectomy (ไม่รู้ตำแหน่ง)",
    "Hemorrhoid เลือดหยดหลังถ่าย, fissure ปวดมาก, ischemic colitis ปวดท้องก่อนเลือดออก, rectal cancer เปลี่ยนนิสัยการขับถ่าย",
    "ดูข้อ 46, 47, 48, 49 (anorectal) และ 54, 55, 57 (colorectal)"],
  notes:"<b>ไม่มีแถวข้อนี้ในไฟล์เฉลย</b> (section colorectal ในคีย์มีแค่แถว 1–3 และว่าง)<br>ผู้จดให้ช้อย A. Internal hemorrhoids B. Diverticulosis แต่ไม่ได้บอกคำตอบ; ช้อย C, D, E เราแต่งเพิ่ม (จงใจไม่ใส่ angiodysplasia เพราะจะแข่งกับคำตอบ)<br>ช้อย B ต้นฉบับ \"Diverticulosis\" → Colonic diverticulosis",
  mnemonic:"",
  guide:"ACG lower GI bleeding 2023",
  opinion:"ไม่มีคีย์ — เราตอบ B มั่นใจสูง: massive painless hematochezia ในผู้สูงอายุที่ท้องผูกเรื้อรังคือ diverticular bleeding เป็นอันดับแรก",
  variants:["ชายอายุ 75 ปี กิน aspirin ถ่ายเลือดแดงคล้ำจำนวนมาก BP 80/50 หลัง resuscitation ยังไม่ stable → CT angiography แล้ว angioembolization","หญิงอายุ 80 ปี มี aortic stenosis ถ่ายเลือดเป็นพัก ๆ ซีดเรื้อรัง colonoscopy พบ vascular ectasia ที่ cecum → angiodysplasia (Heyde syndrome)","ชายอายุ 70 ปี ปวดท้องซ้ายเฉียบพลันหลังผ่าตัด AAA แล้วถ่ายเป็นเลือด → ischemic colitis"]}),
A({page:23, page2:7, orig:"Vascular 1",
  stem:"A patient has had rest pain in the right foot for 1 month. Pulses: right femoral 2+, right popliteal 1+, right posterior tibial and dorsalis pedis absent; left leg pulses normal. ABI is 0.4 on the right and 0.8 on the left. What is the most appropriate next step?",
  gray:"A patient came with leg pain, PE: Rt femoral 2+, Rt popliteal 1+, Rt PTA 0, Rt DPA, 0, Lt normal, Rt ABI 0.4, Lt ABI 0.8, what is the next management? — A. CTA and revascularization assessment",
  opts:["CTA and assessment for revascularization","Supervised exercise therapy alone","Primary above-knee amputation","Venous duplex ultrasound","Cilostazol and reassess in 1 year"],
  ans:0, key:"A CTA and revascularization assessment"+KS,
  flag:"⚠ เล็กน้อย: เติม rest pain ใน stem (ต้นฉบับบอกแค่ leg pain — ถ้าเป็นแค่ claudication ที่ไม่กระทบชีวิต ขั้นแรกคือ exercise + best medical therapy)",
  interp:"ขาขวามี <b>rest pain</b> ชีพจรลดลงตั้งแต่ popliteal และคลำไม่ได้ที่เท้า + <b>ABI ขวา 0.4</b> — ต้องจัดระดับความรุนแรง (claudication หรือ chronic limb-threatening ischemia) แล้วเลือกขั้นตอนถัดไป",
  why:"Rest pain นาน &gt;2 สัปดาห์ร่วมกับ ABI 0.4 (severe; เกณฑ์ CLTI ABI &lt;0.4, ankle pressure &lt;50 หรือ toe pressure &lt;30 mmHg) = <b>chronic limb-threatening ischemia (CLTI)</b> เสี่ยงเสียขา → ต้องทำ <b>anatomical imaging</b> (duplex, <b>CTA</b>, MRA หรือ DSA) เพื่อวางแผน <b>revascularization</b> (endovascular หรือ bypass ตาม WIfI และ GLASS) ร่วมกับ best medical therapy (statin, antiplatelet, หยุดบุหรี่, คุมเบาหวาน); ชีพจร femoral ปกติแต่ popliteal ลดและเท้าไม่มี → โรคอยู่ที่ <b>femoropopliteal ลงไป infrapopliteal</b>",
  wrong:["Supervised exercise therapy เป็นการรักษาแรกของ <b>intermittent claudication</b> (ร่วมกับ BMT) — ใน CLTI ที่มี rest pain การออกกำลังไม่พอและทำไม่ได้ ต้อง revascularize; <b>จะถูกถ้าโจทย์บอกแค่ claudication</b> ที่ไม่กระทบชีวิตประจำวัน",
    "Primary amputation สงวนไว้เมื่อ revascularization ทำไม่ได้หรือไม่เกิดประโยชน์ (ไม่มี target vessel, เนื้อตายลุกลาม/ติดเชื้อรุนแรง, ผู้ป่วยติดเตียงไม่เดินอยู่แล้ว, ขาหดเกร็ง) — ผู้ป่วยรายนี้ยังไม่มีเนื้อตายและยังไม่ได้ประเมินหลอดเลือด",
    "Venous duplex ใช้หา DVT หรือ venous insufficiency — อาการนี้เป็น arterial insufficiency (pulse หาย, ABI ต่ำ) จึงต้องดู arterial anatomy",
    "Cilostazol ช่วยเพิ่มระยะเดินใน claudication (ห้ามใน heart failure) ไม่ช่วย CLTI และการรอ 1 ปีในผู้ป่วย rest pain เสี่ยงเกิดแผลและเสียขา"],
  trap:"เห็น leg pain แล้วตอบ exercise therapy — ต้องดูว่าเป็น rest pain หรือ claudication และ ABI 0.4 = severe; ส่วนขาซ้าย ABI 0.8 ก็ผิดปกติ (mild) แต่ยังไม่ต้อง revascularize",
  summary:["ABI: &gt;1.4 noncompressible (เบาหวาน, CKD → ใช้ toe-brachial index), 1.0–1.4 ปกติ, 0.91–0.99 borderline, <b>≤0.90 PAD</b>; 0.7–0.9 mild, 0.4–0.69 moderate, &lt;0.4 severe",
    "Fontaine: I asymptomatic, II claudication, III rest pain, IV ulcer/gangrene; Rutherford 0–6 (4 rest pain, 5 minor tissue loss, 6 major tissue loss)",
    "<b>CLTI</b> = rest pain &gt;2 สัปดาห์ หรือ tissue loss ร่วมกับหลักฐานทาง hemodynamic → imaging + revascularization เร่งด่วน; ประเมินขาด้วย WIfI และวางแผนด้วย GLASS",
    "Claudication: BMT (statin high intensity, antiplatelet, หยุดบุหรี่, คุม BP/DM) + supervised exercise ± cilostazol; revascularize เมื่ออาการจำกัดชีวิตแม้รักษาเต็มที่",
    "ตำแหน่งโรคจากชีพจร: femoral หาย → aortoiliac; femoral ปกติ popliteal ลด → femoropopliteal; popliteal ปกติ เท้าหาย → infrapopliteal",
    "Amputation เมื่อ revascularization ทำไม่ได้หรือไม่เกิดประโยชน์",
    "ดูข้อ 60, 61 (vascular) และ 27 (mesenteric ischemia)"],
  notes:"แถว <b>vas 1</b> ในไฟล์เฉลยเขียนแค่ <b>\"A\"</b><br>ต้นฉบับ: \"A patient came with <b>leg pain</b>, PE: Rt femoral 2+, Rt popliteal 1+, Rt PTA 0, <b>Rt DPA, 0</b>, Lt normal, Rt ABI 0.4, Lt ABI 0.8\" — เราเปลี่ยน leg pain เป็น <b>rest pain in the right foot for 1 month</b> (ต้นฉบับไม่บอกลักษณะอาการปวด) และเขียน PTA/DPA 0 เป็น absent<br>ผู้จดจำช้อยได้ช้อยเดียว \"A. CTA and revascularization assessment\" — ช้อย B–E เราแต่งเพิ่ม",
  mnemonic:"",
  guide:"Global Vascular Guidelines on CLTI 2019; 2024 ACC/AHA PAD guideline",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูงเมื่อเป็น rest pain — ต้นฉบับบอกแค่ leg pain ถ้าข้อสอบจริงเป็น claudication ขั้นแรกควรเป็น exercise + BMT แต่ ABI 0.4 ทำให้น่าจะเป็น CLTI ตามเจตนาของข้อ; สอดคล้องกับข้อสอบชุด 76A (CTA)",
  variants:["ชายอายุ 65 ปี สูบบุหรี่ ปวดน่องขวาเมื่อเดิน 200 เมตร หยุดพักแล้วหาย ABI 0.7 → supervised exercise + statin + antiplatelet + หยุดบุหรี่","ผู้ป่วยเบาหวานมีแผลที่นิ้วโป้งเท้าไม่หาย 6 สัปดาห์ ABI 1.5 → noncompressible วัด toe pressure แล้วทำ imaging เพื่อ revascularization","ผู้ป่วยปวดก้นและต้นขาทั้งสองข้างเวลาเดิน ร่วมกับ erectile dysfunction femoral pulse คลำไม่ได้ทั้งสองข้าง → aortoiliac occlusive disease (Leriche syndrome)"]}),
A({page:23, page2:7, orig:"Vascular 2",
  stem:"After a long-haul flight, a patient develops unilateral calf pain and swelling. What is the most appropriate investigation?",
  gray:"A patient presented with calf pain with a history of long flight, what is the most appropriate investigation? — A. Duplex U/S lower extremities B. Venography",
  opts:["Compression duplex ultrasound","Contrast venography","CT pulmonary angiography","MR venography","CT angiography of the lower extremity"],
  ans:0, key:"A Duplex U/S lower extremities"+KS,
  interp:"ปวดและบวมน่องข้างเดียวหลัง <b>นั่งเครื่องบินนาน</b> (immobility = risk factor ของ venous stasis) → สงสัย DVT — ถามการตรวจที่เหมาะสมที่สุด",
  why:"<b>Compression duplex ultrasound</b> = investigation of choice ของ DVT: ไม่ invasive ไม่มีรังสี ทำข้างเตียงได้ sensitivity/specificity &gt;95% สำหรับ proximal DVT — หลอดเลือดดำที่ <b>กดแล้วไม่แฟบ</b> (non-compressible) = มี thrombus; ลำดับตามหลัก: ประเมิน pretest probability (Wells) → unlikely ใช้ high-sensitivity D-dimer ก่อน (ลบ = ตัดออก), likely หรือ D-dimer บวก → duplex",
  wrong:["Contrast venography เคยเป็น gold standard แต่ <b>invasive</b> ใช้ contrast และรังสี เจ็บ อาจทำให้เกิด phlebitis จึงสงวนไว้เมื่อ ultrasound สรุปไม่ได้หรือวางแผน intervention (catheter-directed thrombolysis, stent)",
    "CTPA ใช้วินิจฉัย <b>pulmonary embolism</b> — จะถูกถ้าโจทย์มีเหนื่อยหอบ เจ็บหน้าอก hypoxia tachycardia; อาการเฉพาะที่น่องให้ตรวจขา",
    "MR venography ใช้ประเมิน thrombosis ของ <b>pelvic vein, IVC</b> หรือ May-Thurner ที่ ultrasound มองไม่ถึง ไม่ใช่การตรวจแรกของ calf DVT",
    "CT angiography ของขาดูหลอดเลือด <b>แดง</b> (PAD, acute limb ischemia, trauma) ไม่ใช่การตรวจหา DVT"],
  trap:"เลือก venography เพราะจำว่าเป็น gold standard — ข้อสอบถาม most appropriate ซึ่งคือ duplex US; อย่าลืมว่าผู้ป่วยกลุ่ม low probability ให้เริ่มที่ D-dimer",
  summary:["Virchow triad: stasis (นั่งนาน, ติดเตียง, เดินทางไกล &gt;4 ชม.), endothelial injury (ผ่าตัด, trauma), hypercoagulability (มะเร็ง, ฮอร์โมน, ตั้งครรภ์, thrombophilia)",
    "Wells score: unlikely → high-sensitivity D-dimer (ลบ = ตัดออก); likely หรือ D-dimer บวก → <b>compression duplex US</b> (proximal หรือ whole-leg)",
    "Duplex: non-compressibility เป็นเกณฑ์หลัก; proximal ultrasound ลบแต่ยังสงสัย → ทำซ้ำใน 1 สัปดาห์",
    "Venography gold standard แต่ invasive; MRV/CTV สำหรับ pelvic/IVC; CTPA สำหรับ PE",
    "รักษา: DOAC (rivaroxaban, apixaban) เป็นแรก; provoked DVT ให้ 3 เดือน, unprovoked พิจารณาให้ยาวต่อ; มะเร็งใช้ DOAC หรือ LMWH",
    "Isolated distal DVT ที่ไม่มีอาการรุนแรงหรือ risk ต่ำ อาจ serial US 2 สัปดาห์แทนการให้ยา",
    "ดูข้อ 59, 61 (vascular)"],
  notes:"แถว <b>vas 2</b> ในไฟล์เฉลยเขียนแค่ <b>\"A\"</b><br>ต้นฉบับบอกแค่ \"calf pain with a history of long flight\" — เราเติม <b>unilateral</b> และ <b>swelling</b> ตามแนวที่คลังใช้<br>ผู้จดให้ช้อย A. Duplex U/S lower extremities B. Venography; ช้อย C, D, E เราแต่งเพิ่ม (ชุดเดียวกับข้อสอบชุด 76A)",
  mnemonic:"",
  guide:"ASH VTE diagnosis 2018",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง — สอดคล้องกับข้อสอบชุด 76A และ 76C (duplex ultrasound)",
  variants:["หญิงอายุ 30 ปี กินยาคุม ปวดน่องเล็กน้อย Wells score unlikely → high-sensitivity D-dimer ก่อน ถ้าลบตัด DVT ได้","ผู้ป่วยหลังผ่าตัดสะโพก 5 วัน ขาบวมทั้งขา ร่วมกับเหนื่อยหอบ SpO2 88% HR 120 → CTPA","ผู้ป่วยหญิงขาซ้ายบวมทั้งขา duplex ไม่เห็นถึง iliac vein → CT หรือ MR venography หา iliac vein compression"]}),
A({page:23, page2:7, orig:"Vascular 3",
  stem:"A patient has sudden-onset right leg pain. The pulse is irregular, and there is weakness of the intrinsic muscles of the right foot. What is the most appropriate management?",
  gray:"A patient came with sudden onset of leg pain, PE: irregular pulse, intrinsic muscle weakness of right foot, what is the most appropriate management? — A. IV heparin and urgent embolectomy",
  opts:["IV heparin and urgent embolectomy","CT angiography then elective bypass","Catheter-directed thrombolysis over 48 hours","Primary amputation","Oral warfarin and outpatient follow-up"],
  ans:0, key:"A IV heparin and urgent embolectomy"+KS,
  interp:"ปวดขาเฉียบพลัน + <b>ชีพจรไม่สม่ำเสมอ</b> (นึกถึง AF เป็นแหล่ง embolus) + <b>กล้ามเนื้อเท้าอ่อนแรง</b> — ต้องจัดระดับความรุนแรงของการขาดเลือด (Rutherford) เพราะ motor deficit เปลี่ยนการรักษาจาก imaging เป็นผ่าตัดเร่งด่วน",
  why:"Sudden onset + irregular pulse = <b>embolus จาก AF</b> อุดหลอดเลือดแดงขา; <b>motor weakness</b> (ยังไม่ paralysis) = <b>Rutherford IIb (immediately threatened)</b> → ให้ <b>IV unfractionated heparin ทันที</b> (กันลิ่มเลือดลาม) แล้ว <b>emergency revascularization</b> — สำหรับ embolus ใช้ <b>Fogarty balloon embolectomy</b> (ผ่า femoral artery) ได้เร็วและได้ผลดี; ไม่ควรเสียเวลารอ imaging นานหรือ thrombolysis ที่ใช้เวลาหลายชั่วโมง",
  wrong:["CTA แล้วนัด bypass แบบ elective เหมาะกับ <b>Rutherford I (viable) หรือ IIa</b> ที่ไม่มี motor deficit และมีเวลาทำ imaging — ผู้ป่วยมีกล้ามเนื้ออ่อนแรงแล้วจึงต้องผ่าตัดเร่งด่วน การรอ elective ทำให้เสียขา",
    "Catheter-directed thrombolysis ใช้เวลาหลายชั่วโมงถึงวันกว่าจะเปิดหลอดเลือด เหมาะกับ <b>Rutherford I–IIa</b> โดยเฉพาะ thrombosis บน atherosclerotic lesion หรือ graft occlusion — ใน IIb ที่ขาดเลือดรุนแรงอาจช้าเกินไป (ยกเว้นทำ pharmacomechanical ได้รวดเร็ว)",
    "Primary amputation สำหรับ <b>Rutherford III (irreversible)</b>: paralysis, sensory loss ทั้งหมด, กล้ามเนื้อแข็ง (rigor), ไม่ได้ยินทั้ง arterial และ venous Doppler — ผู้ป่วยรายนี้แค่อ่อนแรง ขายังช่วยได้",
    "Warfarin กินและนัดติดตามเป็นการป้องกันระยะยาวหลังรักษา (ป้องกัน embolus ซ้ำจาก AF) แต่ไม่ได้เปิดหลอดเลือดที่อุดอยู่ — ขาจะขาดเลือดจนตาย"],
  trap:"สั่ง CTA ก่อนทุกราย — เมื่อมี <b>motor หรือ sensory deficit ที่เกินนิ้วเท้า</b> (IIb) ต้องไปผ่าตัดทันที; ส่วน IIa (ชาเฉพาะนิ้ว ไม่อ่อนแรง) จึงมีเวลาทำ imaging",
  summary:["6P: pain, pallor, pulselessness, poikilothermia, paresthesia, paralysis — paresthesia/paralysis บ่งความรุนแรงมาก",
    "Rutherford ALI: <b>I viable</b> (ไม่มี sensory/motor loss, Doppler ได้ยิน) → imaging; <b>IIa marginally threatened</b> (ชาเฉพาะนิ้ว ไม่มี motor loss) → revascularize เร่งด่วน",
    "<b>IIb immediately threatened</b> (sensory loss เกินนิ้ว + rest pain, motor loss เล็กน้อยถึงปานกลาง) → heparin + emergency revascularization",
    "<b>III irreversible</b> (anesthesia, paralysis, rigor, ไม่มีทั้ง arterial และ venous Doppler) → amputation",
    "Embolus (AF, MI, valvular) → Fogarty embolectomy; thrombosis บน atherosclerosis/graft → thrombolysis หรือ bypass",
    "หลัง revascularize: เฝ้าระวัง reperfusion injury, compartment syndrome (ทำ fasciotomy), hyperkalemia, myoglobinuria; หาแหล่ง embolus (ECG, echo) แล้วให้ anticoagulant ระยะยาว",
    "ดูข้อ 27 (mesenteric embolism จาก AF) และ 59, 60 (vascular)"],
  notes:"แถว <b>vas 3</b> ในไฟล์เฉลยเขียนแค่ <b>\"A\"</b><br>ผู้จดจำช้อยได้ช้อยเดียว \"A. IV heparin and urgent embolectomy\" — ช้อย B–E เราแต่งเพิ่ม; stem แปลจากต้นฉบับโดยไม่บอกชื่อภาวะ",
  mnemonic:"<b>IIa ชานิ้ว → มีเวลา; IIb อ่อนแรง → ผ่าเลย; III อัมพาต แข็ง → ตัดขา</b>",
  guide:"ESVS acute limb ischaemia 2020",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง — สอดคล้องกับข้อสอบชุด 76D (sensation และ motor ปกติ → CTA; มี motor loss → embolectomy ทันที)",
  variants:["ผู้ป่วย AF ปวดขาซ้ายเฉียบพลัน 3 ชั่วโมง ขาเย็นซีด sensation และ motor ปกติ ได้ยิน Doppler ที่ข้อเท้า → Rutherford I ให้ heparin แล้วทำ CTA","ผู้ป่วยปวดขา 24 ชั่วโมง ขาเป็นจ้ำม่วงคงที่ กล้ามเนื้อน่องแข็ง ขยับไม่ได้ ไม่ได้ยิน Doppler ทั้ง artery และ vein → primary amputation","หลัง embolectomy 6 ชั่วโมง น่องตึงมาก ปวดเมื่อเหยียดนิ้วเท้า → compartment syndrome ทำ fasciotomy"]}),
A({page:24, page2:7, orig:"Esophagus 1",
  stem:"A patient has progressive dysphagia and can now take only milk and liquids but not solid food. What is the most appropriate investigation to establish the diagnosis?",
  gray:"A patient presented with progressive dysphagia, able to eat only milk and liquid food, cannot eat solid food, what is the appropriate investigation for diagnosis? — A. Esophagoscopy with biopsy",
  opts:["Barium swallow","Esophagoscopy with biopsy","CT scan of the chest","Esophageal manometry","Chest radiograph"],
  ans:1, key:"B Esophagoscopy with biopsy"+KS,
  interp:"กลืนลำบาก <b>ค่อย ๆ แย่ลงจากของแข็งไปของเหลว</b> = mechanical obstruction ที่ตีบมากขึ้นเรื่อย ๆ — ถามการตรวจที่ใช้ <b>วินิจฉัย</b> (ยืนยันโรค)",
  why:"Progressive dysphagia ที่เริ่มจาก <b>solid แล้วลามมา liquid</b> บ่งการตีบแคบทางกายภาพที่ลุกลาม (มะเร็งหลอดอาหารเป็นอันดับแรก โดยเฉพาะผู้สูงอายุ น้ำหนักลด; peptic stricture รองลงมา) → <b>esophagoscopy (EGD) with biopsy</b> เห็นรอยโรคโดยตรงและได้ <b>ชิ้นเนื้อยืนยัน</b>ชนิดของมะเร็ง (SCC หรือ adenocarcinoma) จึงเป็นการตรวจที่ใช้วินิจฉัย",
  wrong:["Barium swallow เห็นกายวิภาค (apple-core lesion, stricture, ring, web, Zenker diverticulum) และอาจทำก่อนใน proximal lesion หรือสงสัย Zenker แต่ <b>ไม่ได้ชิ้นเนื้อ</b> จึงยืนยันการวินิจฉัยไม่ได้",
    "CT chest/abdomen ใช้ <b>staging</b> (T4 ลุกลามอวัยวะข้างเคียง, ต่อมน้ำเหลือง, metastasis) หลังวินิจฉัยด้วยชิ้นเนื้อแล้ว ไม่ใช่การตรวจวินิจฉัย",
    "Manometry ใช้กับ <b>motility disorder</b> (achalasia, spasm) ที่กลืนลำบากทั้ง solid และ liquid ตั้งแต่แรก — ทำหลัง EGD ตัด mechanical cause แล้ว (ดูข้อ 63)",
    "Chest radiograph อาจเห็น air-fluid level หรือ mediastinal widening แต่ไม่ไวและไม่เจาะจง ไม่ใช่การตรวจวินิจฉัย"],
  trap:"ตอบ barium swallow เพราะเป็นการตรวจแรกในตำราเก่า — คำถามคือ \"for diagnosis\" ต้องได้ชิ้นเนื้อ จึงเป็น EGD with biopsy",
  summary:["Dysphagia solid → liquid แบบ progressive = mechanical (มะเร็ง, peptic stricture); ทั้ง solid และ liquid ตั้งแต่แรก = motility (achalasia)",
    "Alarm features: อายุมาก, น้ำหนักลด, progressive, GI bleeding, ซีด → EGD เร็ว",
    "<b>EGD + biopsy</b> = การวินิจฉัย; barium swallow ช่วยดูกายวิภาค ใช้ก่อนใน proximal lesion หรือสงสัย Zenker",
    "Staging มะเร็งหลอดอาหาร: CT chest/abdomen, PET-CT (distant metastasis), EUS (T และ N), bronchoscopy ใน upper/mid tumor ที่อยู่ใกล้ trachea",
    "SCC: middle third, สูบบุหรี่ ดื่มสุรา, achalasia, caustic; adenocarcinoma: distal third/GEJ, GERD, Barrett, obesity",
    "Manometry หลัง EGD ปกติเพื่อหา motility disorder",
    "ดูข้อ 63, 64 (esophagus)"],
  notes:"แถว <b>eso 1</b> ในไฟล์เฉลยเขียนแค่ <b>\"A\"</b> (= Esophagoscopy with biopsy ซึ่งเป็นช้อยเดียวที่ผู้จดจำได้; ลำดับของเราเป็น B)<br>ผู้จดจำช้อยได้ช้อยเดียว \"A. Esophagoscopy with biopsy\" — ช้อยอีก 4 ช้อยเราแต่งเพิ่ม (ชุดเดียวกับข้อสอบชุด 77B)",
  mnemonic:"",
  guide:"ASGE role of endoscopy in esophageal dysphagia 2014; NCCN Esophageal 2025",
  opinion:"เห็นด้วยกับคีย์ (Esophagoscopy with biopsy) มั่นใจสูง — สอดคล้องกับข้อสอบชุด 77B (EGD first) และ 77D (progressive dysphagia → มะเร็งหลอดอาหาร)",
  variants:["ชายอายุ 65 ปี สูบบุหรี่ ดื่มสุรา กลืนลำบากของแข็ง 2 เดือน น้ำหนักลด 8 kg EGD พบก้อนที่ mid esophagus biopsy เป็น SCC → staging ด้วย CT, PET-CT และ EUS","ผู้ป่วย GERD เรื้อรัง กลืนลำบากของแข็งค่อย ๆ เป็นมากขึ้น ไม่มีน้ำหนักลด → EGD พบ peptic stricture ทำ dilation + PPI","ผู้สูงอายุสำลักอาหารที่ไม่ย่อยออกมา มีกลิ่นปาก มีเสียงกลั้วคอ → barium swallow หา Zenker diverticulum ก่อน EGD"]}),
A({page:24, page2:7, orig:"Esophagus 2",
  stem:"A patient has intermittent dysphagia to both solids and liquids. A barium swallow is unremarkable, and upper endoscopy is normal. What is the most appropriate next investigation?",
  gray:"A patient presented with intermittent dysphagia of both solid and liquid food, barium swallowing result is insignificant, what is the next management? — A. Esophageal manometry",
  opts:["Esophageal manometry","24-hour pH monitoring","CT scan of the chest","Repeat barium swallow in 6 months","Endoscopic ultrasound"],
  ans:0, key:"A Esophageal manometry"+KS,
  flag:"⚠ เล็กน้อย: เติม \"EGD is normal\" ใน stem (ต้องตัด mechanical cause/pseudoachalasia ด้วย EGD ก่อน manometry)",
  interp:"กลืนลำบาก <b>ทั้งของแข็งและของเหลว</b> เป็น ๆ หาย ๆ โดยภาพรังสีและการส่องกล้องไม่พบรอยโรค — ถามการตรวจถัดไปเพื่อหาสาเหตุ",
  why:"Dysphagia ต่อทั้ง solid และ liquid ตั้งแต่แรกบ่ง <b>esophageal motility disorder</b>; เมื่อ EGD ตัด mechanical cause และมะเร็ง (pseudoachalasia) ออกแล้ว การตรวจถัดไปคือ <b>high-resolution esophageal manometry</b> = gold standard ในการวินิจฉัย motility disorder ตาม <b>Chicago Classification v4.0</b> (เช่น IRP สูงร่วมกับ peristalsis ล้มเหลว, spastic contraction, absent contractility)",
  wrong:["24-hour pH monitoring ใช้ยืนยัน <b>GERD</b> (อาการ heartburn/regurgitation ที่ไม่ตอบสนองต่อ PPI หรือก่อนผ่าตัด antireflux) ไม่ใช่การหาสาเหตุ dysphagia ทั้ง solid และ liquid",
    "CT chest ใช้หา mediastinal mass หรือ external compression และ staging มะเร็ง — เมื่อ EGD ปกติและอาการเข้ากับ motility disorder ยังไม่ใช่การตรวจถัดไป",
    "การรอแล้วทำ barium ซ้ำไม่ได้ให้การวินิจฉัย ปล่อยให้อาการแย่ลง ผู้ป่วย motility disorder จะได้ประโยชน์จากการรักษาเมื่อวินิจฉัยได้",
    "EUS ใช้ประเมิน submucosal lesion, staging มะเร็ง หรือสงสัย <b>pseudoachalasia</b> (มะเร็ง GEJ ที่ซ่อนอยู่ในผู้สูงอายุ น้ำหนักลดเร็ว) — ใช้เสริมเมื่อ manometry เข้ากับ achalasia แต่ยังสงสัยมะเร็ง"],
  trap:"ข้ามขั้น EGD แล้วไปทำ manometry เลย — ต้องตัด mechanical และมะเร็งก่อนเสมอ; อีกกับดักคือคิดว่า barium ปกติแล้วไม่มีโรค",
  summary:["Solid + liquid dysphagia ตั้งแต่แรก = motility; solid → liquid แบบ progressive = mechanical",
    "ลำดับการตรวจ: <b>EGD</b> (ตัด mechanical, malignancy, eosinophilic esophagitis โดย biopsy) → <b>high-resolution manometry</b> (gold standard) → timed barium esophagram หรือ FLIP เสริม",
    "Achalasia (Chicago v4.0): IRP สูง + 100% failed peristalsis; type I ไม่มี pressurization, type II panesophageal pressurization (ตอบสนองต่อการรักษาดีสุด), type III premature/spastic contraction",
    "Motility อื่น: EGJ outflow obstruction, distal esophageal spasm, hypercontractile (jackhammer) esophagus, absent contractility (scleroderma)",
    "Barium ใน achalasia: bird's beak, หลอดอาหารขยาย; รักษา: pneumatic dilation, Heller myotomy + partial fundoplication, POEM (ดีสุดใน type III); botulinum toxin ในผู้ป่วยเสี่ยงสูง",
    "pH monitoring สำหรับ GERD; EUS สำหรับ submucosal lesion หรือ pseudoachalasia",
    "ดูข้อ 62, 64 (esophagus)"],
  notes:"แถว <b>eso 2</b> ในไฟล์เฉลยเขียนแค่ <b>\"A\"</b><br>ต้นฉบับ: \"barium swallowing result is <b>insignificant</b>, what is the next management?\" — เราแปลเป็น unremarkable และเติม <b>upper endoscopy is normal</b> ใน stem (ตาม algorithm ต้อง EGD ก่อน manometry)<br>ผู้จดจำช้อยได้ช้อยเดียว \"A. Esophageal manometry\" — ช้อย B–E เราแต่งเพิ่ม",
  mnemonic:"",
  guide:"ACG achalasia 2020; Chicago Classification v4.0 2021",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง — เติม EGD ปกติเพื่อให้ manometry เป็นขั้นตอนถัดไปตามหลัก; สอดคล้องกับข้อสอบชุด 76A, 77A และ 77C (manometry ยืนยัน) และชุด 76C (EGD ก่อน)",
  variants:["หญิงอายุ 35 ปี กลืนลำบากทั้งของแข็งและของเหลว 1 ปี สำรอกอาหารไม่ย่อย barium พบ bird's beak → EGD ตัดมะเร็ง แล้ว manometry ยืนยัน achalasia","ชายอายุ 70 ปี กลืนลำบาก 3 เดือน น้ำหนักลด 10 kg manometry เข้าได้กับ achalasia → สงสัย pseudoachalasia ทำ EUS หรือ CT","ผู้ป่วยเจ็บหน้าอกและกลืนลำบากเป็นพัก ๆ barium เห็น corkscrew esophagus → manometry หา distal esophageal spasm"]}),
A({page:24, page2:7, orig:"Esophagus 3",
  stem:"A medically fit patient has a mid-thoracic esophageal carcinoma. Staging shows the tumor invading the adventitia with multiple regional lymph node metastases and no distant metastasis. What is the most appropriate management?",
  gray:"A patient presented with esophageal cancer, imaging revealed the extent of tumor to serosa with multiple lymph nodes involved, what is the management? — A. Esophagectomy B. Neoadjuvant chemoradiation + esophagectomy C. Definitive chemoradiation",
  opts:["Esophagectomy alone","Neoadjuvant chemoradiation then esophagectomy","Definitive chemoradiation without surgery","Endoscopic submucosal dissection","Palliative esophageal stent alone"],
  ans:1, key:"B Neoadjuvant chemoradiation + esophagectomy"+KS,
  flag:"⚠ เล็กน้อย: เติม medically fit, mid-thoracic, no distant metastasis ใน stem; หลอดอาหารไม่มี serosa (ชั้นนอกสุด = adventitia)",
  interp:"มะเร็งหลอดอาหาร <b>ลุกลามถึงชั้นนอกสุด (T3)</b> + <b>ต่อมน้ำเหลืองหลายต่อม (N+)</b> ไม่มี distant metastasis ในผู้ป่วยที่ผ่าตัดได้ = <b>locally advanced resectable</b> — ถามแนวทางรักษาหลัก",
  why:"T3 หรือ N+ (M0) ที่ resectable ในผู้ป่วย fit → <b>neoadjuvant chemoradiation แล้ว esophagectomy</b> (<b>CROSS trial</b>: carboplatin + paclitaxel ร่วมกับ 41.4 Gy) ลด tumor ทำให้ R0 resection สูงขึ้นและ <b>overall survival ดีกว่าผ่าตัดอย่างเดียว</b> (ได้ประโยชน์ชัดเจนใน SCC) และถ้ามี residual disease หลังผ่าตัดให้ adjuvant nivolumab (CheckMate 577); ใน adenocarcinoma ทางเลือก perioperative FLOT (ESOPEC)",
  wrong:["Esophagectomy อย่างเดียวเหมาะกับ <b>T1b–T2N0</b> (low risk) — ใน T3N+ การผ่าตัดอย่างเดียวมี R0 rate และ survival ต่ำกว่าการให้ neoadjuvant",
    "Definitive chemoradiation (50–50.4 Gy) เป็นทางเลือกใน <b>SCC</b> โดยเฉพาะ <b>cervical esophagus</b> หรือผู้ป่วยที่ไม่ fit หรือไม่ต้องการผ่าตัด (และใช้เมื่อมี unresectable T4b) — ผู้ป่วยรายนี้ fit และผ่าตัดได้ จึงเลือก trimodality",
    "ESD/EMR ใช้กับมะเร็งระยะแรกมาก <b>T1a</b> (จำกัดใน mucosa) ไม่มีต่อมน้ำเหลือง — ไม่ใช่ T3N+",
    "Stent อย่างเดียวเป็น palliation ของ dysphagia ใน <b>metastatic หรือ unresectable</b> disease หรือ tracheoesophageal fistula — ผู้ป่วยรายนี้ยังรักษาเพื่อหายขาดได้"],
  trap:"ต้นฉบับเขียนว่า tumor ลุกลามถึง serosa — หลอดอาหาร <b>ไม่มี serosa</b> ชั้นนอกสุดคือ adventitia (T3) ซึ่งเป็นเหตุผลที่มะเร็งหลอดอาหารลุกลามออกนอกได้ง่าย; อย่าสับสนกับ definitive CRT ที่ใช้ในผู้ป่วยไม่ fit หรือ cervical esophagus",
  summary:["T staging: Tis HGD, T1a lamina propria/muscularis mucosae, T1b submucosa, T2 muscularis propria, T3 adventitia, T4a pleura/pericardium/diaphragm (resectable), T4b aorta/vertebra/trachea (unresectable)",
    "Tis–T1a: endoscopic resection (EMR/ESD) ± ablation",
    "T1b–T2N0: esophagectomy (บางรายพิจารณา neoadjuvant ถ้า high risk)",
    "<b>T3 หรือ N+ M0 resectable</b>: neoadjuvant CRT (CROSS) → esophagectomy → adjuvant nivolumab ถ้ามี residual; adenocarcinoma ใช้ perioperative FLOT ได้",
    "Definitive CRT: SCC ที่ cervical esophagus, ผู้ป่วยไม่ fit หรือไม่ต้องการผ่าตัด, T4b; M1 → systemic therapy ± palliation (stent, RT)",
    "หลอดอาหารไม่มี serosa และมี lymphatic ใน submucosa → ลุกลามและกระจายทางต่อมน้ำเหลืองเร็ว",
    "ดูข้อ 62 (การวินิจฉัยมะเร็งหลอดอาหาร) และ 63"],
  notes:"แถว <b>eso 3</b> ในไฟล์เฉลยเขียนแค่ <b>\"B\"</b><br>ต้นฉบับ: \"imaging revealed the extent of tumor to <b>serosa</b> with multiple lymph nodes involved\" — หลอดอาหารไม่มี serosa เราจึงเขียนเป็น invading the adventitia และเติม <b>medically fit, mid-thoracic, no distant metastasis</b> ใน stem<br>ผู้จดให้ช้อย A. Esophagectomy B. Neoadjuvant chemoradiation + esophagectomy C. Definitive chemoradiation; ช้อย D, E เราแต่งเพิ่ม",
  mnemonic:"",
  guide:"NCCN Esophageal and Esophagogastric Junction Cancers 2025",
  opinion:"เห็นด้วยกับคีย์ B มั่นใจสูง — สอดคล้องกับข้อสอบชุด 76D (มี supraclavicular node → definitive CRT) และชุด 76A, 77A, 77B, 77C (T1–2N0 → esophagectomy)",
  variants:["ผู้ป่วยมะเร็ง SCC ที่ cervical esophagus ห่าง cricopharyngeus 3 cm → definitive chemoradiation","ผู้ป่วย EGD พบ SCC จำกัดใน mucosa ขนาด 1.5 cm EUS ไม่พบต่อมน้ำเหลือง → endoscopic submucosal dissection","ผู้ป่วยมะเร็งหลอดอาหารมี liver metastasis กลืนน้ำลายไม่ได้ → palliative esophageal stent ร่วมกับ systemic therapy"]}),
A({page:25, page2:8, orig:"Transplant 1",
  stem:"A patient with end-stage kidney disease has an identical twin who is willing to donate a kidney. Which of the following is NOT an advantage of using the identical twin as the donor?",
  gray:"Which of the following is not an advantage of using identical twins as donors? — A. Less organ rejection B. Less need for immunosuppression C. Increased risk of chronic GVHD D. Better overall outcome",
  opts:["Less organ rejection","Less need for immunosuppression","Increased risk of chronic GVHD","Better overall graft outcome","Lower risk of opportunistic infection"],
  ans:2, key:"C Increased risk of chronic GVHD"+KS,
  interp:"ถามข้อที่ <b>ไม่ใช่ข้อดี</b> ของการใช้แฝดเหมือน (identical twin) เป็นผู้ให้อวัยวะ — ต้องเข้าใจว่า isograft มี HLA เหมือนกันทุกตำแหน่งส่งผลอย่างไรต่อ rejection, immunosuppression และ GVHD",
  why:"แฝดเหมือนมีพันธุกรรม <b>เหมือนกันทุกประการ</b> (syngeneic, isograft) → HLA ตรงกันทุก locus จึงแทบไม่มี rejection; ส่วน <b>GVHD</b> เกิดเมื่อ <b>T cell ที่มีภูมิคุ้มกันของผู้ให้</b> มองเนื้อเยื่อผู้รับที่ HLA ต่างกันเป็นสิ่งแปลกปลอม (พบใน HSCT, liver/small bowel transplant ที่มี lymphoid tissue มาก, transfusion ในผู้ภูมิคุ้มกันต่ำ) — เมื่อ HLA เหมือนกัน GVHD จะ <b>ลดลง ไม่ใช่เพิ่มขึ้น</b> ช้อย C จึงไม่ใช่ข้อดีและยังเป็นข้อความที่ไม่จริง",
  wrong:["ข้อดีจริง: HLA เหมือนกันทุก locus จึงแทบไม่มี acute หรือ chronic rejection",
    "ข้อดีจริง: ต้องการ immunosuppression น้อยมากหรือไม่ต้องใช้ (บางศูนย์ให้ระยะสั้น) ลดผลข้างเคียงจากยา เช่น nephrotoxicity ของ calcineurin inhibitor",
    "ข้อดีจริง: isograft มี graft survival ดีที่สุดในบรรดาผู้ให้ทุกประเภท (ดีกว่า living related ที่ HLA ตรงกันบางส่วน และ deceased donor)",
    "ข้อดีจริง: เมื่อใช้ immunosuppression น้อย ความเสี่ยง opportunistic infection (CMV, PJP) และมะเร็งที่สัมพันธ์กับยากดภูมิ (PTLD, skin cancer) ก็ลดลง"],
  trap:"คิดว่าเมื่อเนื้อเยื่อเหมือนกันแล้ว donor T cell จะทำร้ายผู้รับมากขึ้น — GVHD ต้องอาศัย HLA disparity; ข้อเสียจริงของแฝดเหมือนใน HSCT คือ <b>ไม่มี graft-versus-tumor effect</b> (relapse สูงขึ้น) และอาจมีโรคพันธุกรรมหรือ autoimmune เดียวกัน",
  summary:["ประเภท graft: autograft (ตัวเอง), <b>isograft/syngeneic</b> (แฝดเหมือน), allograft (คนละคนในสปีชีส์เดียวกัน), xenograft (ต่างสปีชีส์)",
    "Isograft: HLA เหมือนกันทุก locus → แทบไม่มี rejection, immunosuppression น้อยหรือไม่ต้อง, infection/มะเร็งจากยาน้อย, graft survival ดีที่สุด",
    "GVHD ต้องมี 3 ข้อ (Billingham): graft มี immunocompetent cell, ผู้รับมี antigen ที่ผู้ให้ไม่มี (HLA disparity), ผู้รับกำจัด graft cell ไม่ได้ → syngeneic จึงเสี่ยงน้อย",
    "ข้อเสียของแฝดเหมือน: HSCT ไม่มี graft-versus-leukemia effect; อาจมีโรคพันธุกรรมเดียวกัน หรือ recurrent autoimmune disease (type 1 DM ใน pancreas transplant)",
    "Rejection: hyperacute (นาที–ชั่วโมง, preformed antibody), acute (สัปดาห์–เดือน, T cell หรือ antibody), chronic (เดือน–ปี, fibrosis/vasculopathy)",
    "ดูข้อ 66 (mixed lymphocyte reaction และ HLA matching)"],
  notes:"แถว <b>transplant 1</b> ในไฟล์เฉลยเขียนแค่ <b>\"C\"</b><br>ต้นฉบับถามสั้น ๆ \"Which of the following is not an advantage of using identical twins as donors?\" — เราทำเป็นเคสผู้ป่วยไตวายระยะสุดท้ายที่มีแฝดเหมือนเป็นผู้ให้ (ไม่เปลี่ยนสิ่งที่ถาม)<br>ผู้จดให้ช้อย A–D ครบ; ช้อย D \"Better overall outcome\" → Better overall graft outcome; ช้อย E เราแต่งเพิ่ม",
  mnemonic:"",
  guide:"Schwartz 11th ed. (Transplantation)",
  opinion:"เห็นด้วยกับคีย์ C มั่นใจสูง — สอดคล้องกับข้อสอบชุด 77C (แฝดเหมือนไม่มี HLA barrier)",
  variants:["ผู้ป่วย AML ได้ HSCT จากแฝดเหมือน ข้อเสียหลักเมื่อเทียบกับ HLA-matched sibling คืออะไร → relapse สูงขึ้นเพราะไม่มี graft-versus-leukemia effect","ผู้ป่วยได้ liver transplant 3 สัปดาห์ มีผื่น ท้องเสีย และ pancytopenia ตรวจพบ donor lymphocyte ในเลือด → graft-versus-host disease","ผู้ป่วยไตวายได้ไตจากแฝดเหมือน ต้องใช้ยากดภูมิแบบใด → น้อยมากหรือไม่ต้อง เพราะ HLA เหมือนกันทุกตำแหน่ง"]}),
A({page:25, page2:8, orig:"Transplant 2",
  stem:"Before transplantation, a mixed lymphocyte reaction between donor and recipient is positive. What does this result indicate?",
  gray:"What is the meaning of positive mixed lymphocyte reaction? — A. Increased risk of hyperacute rejection B. ช้อยอื่นคุ้น ๆ ว่าเป็นแบบทำให้ transplant สำเร็จมากขึ้น",
  opts:["Increased risk of hyperacute rejection","T-cell reactivity to donor HLA class II","Better expected graft survival","Lower immunosuppression requirement","Donor and recipient are HLA identical"],
  ans:1, key:"A Increased risk of hyperacute rejection"+KS,
  flag:"⚠ คำตอบต่างจากคีย์ — คีย์ตอบ A hyperacute rejection แต่ MLR วัด T-cell response ต่อ HLA class II ของผู้ให้ (บ่งความเสี่ยง cellular rejection); hyperacute rejection ตรวจด้วย crossmatch หา preformed antibody",
  interp:"ถามความหมายของ <b>mixed lymphocyte reaction (MLR) ที่ให้ผลบวก</b> — ต้องแยกการตรวจที่ดู <b>cell-mediated (T cell)</b> กับการตรวจที่ดู <b>preformed antibody</b> (crossmatch) ซึ่งทำนาย rejection คนละชนิด",
  why:"<b>MLR/MLC</b> = เลี้ยง lymphocyte ผู้รับ (responder) ร่วมกับ lymphocyte ผู้ให้ที่ถูก irradiate (stimulator ไม่แบ่งตัว) แล้ววัดการแบ่งตัวของ T cell ผู้รับ (³H-thymidine uptake) → <b>positive = T cell ผู้รับถูกกระตุ้นโดย HLA class II (โดยเฉพาะ HLA-DR) ของผู้ให้ที่ไม่ตรงกัน</b> = มี HLA class II disparity บ่งความเสี่ยง <b>acute cellular rejection</b> (และใน HSCT เสี่ยง GVHD); ปัจจุบันถูกแทนด้วย molecular HLA typing เพราะใช้เวลา 5–7 วัน ไม่ทันใช้กับ deceased donor",
  wrong:["<b>คีย์ตอบช้อยนี้</b> แต่ hyperacute rejection เกิดจาก <b>preformed antibody</b> ของผู้รับ (anti-ABO หรือ anti-HLA class I จาก transfusion, pregnancy, prior transplant) จับ endothelium ของ graft ทันที → complement, thrombosis ใน graft ภายในนาทีถึงชั่วโมง ตรวจด้วย <b>CDC หรือ flow cytometry crossmatch</b> + PRA/DSA ไม่ใช่ MLR — จะถูกถ้าโจทย์ถาม positive crossmatch",
    "ผลบวกบ่งว่า HLA class II ไม่ตรงกัน จึงคาดว่า graft survival <b>แย่ลง</b> ไม่ใช่ดีขึ้น; ผล MLR ที่ <b>ลบ</b> (ไม่มีการกระตุ้น) จึงจะสัมพันธ์กับผลดี",
    "ผลบวกบ่งความเสี่ยง cellular rejection จึงต้องการ immunosuppression <b>มากขึ้นหรือเท่าเดิม</b> ไม่ใช่น้อยลง",
    "ถ้า HLA ตรงกันทุก locus (เช่น แฝดเหมือน) MLR จะเป็น <b>ลบ</b> เพราะ T cell ผู้รับไม่เห็น antigen แปลกปลอม — ผลบวกแปลตรงข้าม (ดูข้อ 65)"],
  trap:"รวมการตรวจก่อนปลูกถ่ายทุกชนิดว่าเป็นการทำนาย hyperacute rejection — hyperacute = <b>antibody</b> ตรวจด้วย <b>crossmatch</b>; MLR = <b>T cell</b> ต่อ <b>HLA class II</b> ทำนาย cellular rejection",
  summary:["การตรวจก่อนปลูกถ่าย: ABO compatibility, HLA typing (class I: A, B, C; class II: DR, DQ, DP — DR สำคัญที่สุดต่อ graft survival), PRA/DSA, crossmatch",
    "<b>Crossmatch</b> (CDC หรือ flow): serum ผู้รับ + lymphocyte ผู้ให้ → positive = มี preformed anti-donor antibody → เสี่ยง <b>hyperacute rejection</b> เป็นข้อห้ามปลูกถ่ายไต (ถ้าไม่ desensitize)",
    "<b>MLR</b>: lymphocyte ผู้รับ + lymphocyte ผู้ให้ที่ irradiate → วัด T cell proliferation → positive = HLA class II disparity → เสี่ยง acute cellular rejection (HSCT: GVHD); ใช้เวลา 5–7 วัน ปัจจุบันใช้ molecular typing แทน",
    "PRA สูง = ผู้รับ sensitized (เคยได้เลือด ตั้งครรภ์ ปลูกถ่าย) หาผู้ให้ที่ crossmatch ลบยาก",
    "Hyperacute: นาที–ชั่วโมง, preformed antibody, graft thrombosis → เอา graft ออก; acute cellular: สัปดาห์–เดือน, T cell → steroid pulse/ATG; antibody-mediated: DSA, C4d → plasmapheresis, IVIG",
    "ดูข้อ 65 (identical twin donor)"],
  notes:"แถว <b>transplant 2</b> ในไฟล์เฉลยเขียนแค่ <b>\"A\"</b> (ไม่มีคำอธิบาย)<br>ผู้จดจำช้อยได้ช้อยเดียว \"A. Increased risk of hyperacute rejection\" และโน้ตผู้จดในตำแหน่งช้อย B: <b>\"ช้อยอื่นคุ้น ๆ ว่าเป็นแบบทำให้ transplant สำเร็จมากขึ้น\"</b><br>ช้อย C, D, E เราแต่งตามโน้ตผู้จด (ช้อยที่ฟังดูเหมือนทำให้ปลูกถ่ายสำเร็จมากขึ้น) และเพิ่มช้อย B (T-cell reactivity to donor HLA class II) ซึ่งเป็นความหมายที่ถูกตามหลักฐาน; stem เติมว่าเป็นการตรวจก่อนปลูกถ่ายระหว่าง donor กับ recipient",
  mnemonic:"<b>Crossmatch = antibody = hyperacute; MLR = T cell = class II = cellular rejection</b>",
  guide:"Schwartz 11th ed. (Transplantation); Abbas Cellular and Molecular Immunology 10th ed.",
  opinion:"<b>ไม่เห็นด้วยกับคีย์ (มั่นใจสูง)</b> — คีย์ตอบ A hyperacute rejection แต่ MLR วัดการตอบสนองของ T cell ผู้รับต่อ HLA class II ของผู้ให้ ผลบวกบ่ง HLA class II disparity และความเสี่ยง acute cellular rejection ส่วน hyperacute rejection เกิดจาก preformed antibody และตรวจด้วย CDC หรือ flow crossmatch + PRA/DSA; ถ้าข้อสอบจริงไม่มีช้อยแบบ B (ช้อยอื่นตามที่ผู้จดจำเป็นแบบ \"ทำให้ transplant สำเร็จมากขึ้น\" ซึ่งผิดชัดเจน) ช้อย A อาจเป็นช้อยที่ใกล้ที่สุดในสายตาผู้ออกข้อสอบ แต่ตามหลักฐานไม่ถูกต้อง เราจึงเพิ่มช้อย B เพื่อให้มีคำตอบที่ถูก — สอดคล้องกับข้อสอบชุด 77D (crossmatch ตรวจ preformed antibody → hyperacute) และชุด 77C (HLA เป็น barrier หลัก)",
  variants:["ผู้ป่วยหญิงเคยตั้งครรภ์ 3 ครั้ง ได้รับเลือดหลายครั้ง ก่อนปลูกถ่ายไตตรวจ CDC crossmatch เป็นบวก → มี preformed anti-HLA antibody เสี่ยง hyperacute rejection ไม่ควรใช้ผู้ให้รายนี้","หลังปลูกถ่ายไต 10 นาที ไตเปลี่ยนเป็นสีม่วงคล้ำ นุ่มเหลว ไม่มีปัสสาวะ → hyperacute rejection จาก preformed antibody ต้องเอาไตออก","ผู้ป่วยหลังปลูกถ่ายไต 6 สัปดาห์ creatinine สูงขึ้น biopsy พบ lymphocyte แทรกใน tubule (tubulitis) → acute cellular rejection ให้ steroid pulse"]}),
