A({page:8, page2:4, orig:"Professionalism 2",
  stem:"Which of the following best describes the \"time out\" in the WHO Surgical Safety Checklist?",
  gray:"Which of the following is “time out”? — A. When surgical team pauses, identify the patient, incision site, with responses from all members",
  opts:["Nurse and anesthetist confirm identity and consent before induction","Team confirms instrument, sponge and needle counts before closure","Whole team pauses before incision to confirm patient, site and procedure","Surgeon marks the operative site on the ward before transfer","Anesthetist checks the machine and medications before the case"],
  ans:2, key:RC("A. When surgical team pauses, identify the patient, incision site, with responses from all members"),
  interp:"ถามนิยามของ <b>time out</b> ซึ่งเป็น 1 ใน 3 ช่วงของ WHO Surgical Safety Checklist — ต้องแยกให้ได้ว่าแต่ละกิจกรรมเกิด<b>ช่วงเวลาไหน</b> (ก่อน induction / ก่อนลงมีด / ก่อนออกจากห้องผ่าตัด) และใครเป็นคนทำ",
  why:"<b>Time out</b> = ช่วงหลัง induction และ<b>ก่อนลงมีด (before skin incision)</b> ที่<b>ทีมทั้งหมดหยุดพร้อมกัน</b> — ทุกคนแนะนำชื่อและบทบาท, ศัลยแพทย์ วิสัญญี และพยาบาล<b>ยืนยันด้วยวาจา</b>ว่าเป็นผู้ป่วยคนนี้ ผ่าตัดตำแหน่งนี้ (รวมข้าง) และหัตถการนี้, ทบทวน anticipated critical events (ศัลยแพทย์: ขั้นตอนวิกฤต ระยะเวลา เลือดที่คาดว่าจะเสีย; วิสัญญี: ข้อกังวลเฉพาะผู้ป่วย; พยาบาล: sterility และเครื่องมือ), ยืนยันว่าให้ antibiotic prophylaxis <b>ภายใน 60 นาที</b>ก่อนลงมีด และภาพ imaging ที่จำเป็นถูกแสดงไว้ — ตรงกับช้อยเดียวที่ผู้จดจำได้ \"surgical team pauses … with responses from all members\"",
  wrong:["การยืนยันตัวผู้ป่วย ตำแหน่ง หัตถการ และใบยินยอม<b>ก่อน induction</b> โดยพยาบาลกับวิสัญญีแพทย์ (อย่างน้อย) = <b>Sign in</b> ไม่ใช่ time out; จะถูกถ้าโจทย์ถามว่า Sign in คืออะไร",
    "การนับเครื่องมือ ผ้าซับเลือด และเข็มให้ครบ, ทวนชื่อหัตถการ, ติดป้ายชิ้นเนื้อ และปัญหาอุปกรณ์ <b>ก่อนผู้ป่วยออกจากห้องผ่าตัด</b> = <b>Sign out</b>; จะถูกถ้าโจทย์ถามว่า Sign out คืออะไร",
    "การทำเครื่องหมายตำแหน่งผ่าตัด (site marking) ทำโดยผู้ผ่าตัด<b>ก่อนเข้าห้องผ่าตัด</b> เป็นส่วนหนึ่งของ pre-procedure verification ตาม Universal Protocol และถูกเช็กใน Sign in ว่า \"site marked\" — ไม่ใช่การหยุดยืนยันพร้อมกันของทั้งทีมก่อนลงมีด; จะถูกถ้าโจทย์ถามขั้นตอนป้องกัน wrong-site surgery ก่อนนำผู้ป่วยเข้าห้อง",
    "การตรวจเครื่องดมยาและยา (anesthesia safety check) และเช็ก pulse oximeter เป็นรายการใน <b>Sign in</b> ที่วิสัญญีทำก่อน induction; จะถูกถ้าโจทย์ถามรายการที่ต้องเช็กก่อน induction"],
  trap:"สับสน 3 ช่วงของ checklist — ทุกช่วงมีการยืนยันตัวผู้ป่วย แต่ time out คือ<b>ช่วงเดียวที่ทั้งทีมหยุดพร้อมกันก่อนลงมีด</b>และตอบด้วยวาจาทุกคน; ช้อยที่พูดถึงการยืนยันตัวตนกับ consent ก่อน induction เป็น Sign in",
  summary:["WHO Surgical Safety Checklist (2009) แบ่ง 3 ช่วง: <b>Sign in</b> (ก่อน induction) → <b>Time out</b> (ก่อนลงมีด) → <b>Sign out</b> (ก่อนผู้ป่วยออกจากห้องผ่าตัด)",
    "Sign in: ผู้ป่วยยืนยันตัวตน ตำแหน่ง หัตถการ และ consent; site marked; anesthesia machine และยาเช็กแล้ว; pulse oximeter ใช้งานได้; ประวัติแพ้ยา; difficult airway หรือ aspiration risk; เสี่ยงเสียเลือด &gt;500 mL (เด็ก &gt;7 mL/kg) เตรียม IV access และเลือด",
    "Time out: ทุกคนแนะนำชื่อและบทบาท; ยืนยันด้วยวาจา patient, site, procedure; anticipated critical events ของศัลยแพทย์ วิสัญญี และพยาบาล; antibiotic prophylaxis ภายใน 60 นาที; แสดง imaging ที่จำเป็น",
    "Sign out: พยาบาลทวนชื่อหัตถการที่บันทึก, นับเครื่องมือ ผ้า เข็มครบ, ติดป้ายชิ้นเนื้อ (ชื่อผู้ป่วย), ปัญหาอุปกรณ์; ทีมทบทวนประเด็นสำคัญสำหรับการดูแลหลังผ่าตัด",
    "หลักฐาน: การศึกษา 8 โรงพยาบาลทั่วโลก (Haynes, NEJM 2009) พบว่าการใช้ checklist ลด mortality และ major complication ลงอย่างมีนัยสำคัญ",
    "เป้าหมายคือป้องกัน wrong patient, wrong site, wrong procedure, retained foreign body และเพิ่ม teamwork/communication — ทุกคนในทีมมีสิทธิ์หยุดการผ่าตัดถ้าข้อมูลไม่ตรง",
    "ดูข้อ 17, 19 (professionalism, safety และ consent)"],
  notes:"<b>แถว Professionalism and Surgical safety 2 ในไฟล์เฉลยว่าง</b> (section นี้ในไฟล์เฉลยมีแค่แถว 1 = \"A\"; แถว 2–5 ว่าง)<br>ไฟล์โจทย์: ผู้จดใส่ช้อยไว้ช้อยเดียว \"A. When surgical team pauses, identify the patient, incision site, with responses from all members\" (น่าจะเป็นคำตอบที่ผู้จดเลือก)<br>ช้อยอื่น 4 ช้อย (Sign in, Sign out, site marking, machine check) เราแต่งเพิ่ม; ช้อยที่ถูกเราเกลาถ้อยคำจากช้อยของผู้จดให้สั้นลงโดยความหมายเดิม",
  mnemonic:"<b>IN–OUT ล้อมรอบมีด</b>: Sign <b>in</b> ก่อนหลับ · <b>Time out</b> ก่อนกรีด · Sign <b>out</b> ก่อนออกห้อง",
  guide:"WHO Surgical Safety Checklist 2009",
  opinion:"ไม่มีคีย์ — ตอบตามช้อยที่ผู้จดใส่ไว้ มั่นใจสูงตามนิยามของ WHO; สอดคล้องกับข้อสอบชุด 77A และ 77B ที่ถามเรื่อง time out เช่นกัน",
  variants:["ก่อนลงมีดผ่าตัด inguinal hernia ข้างขวา ทีมหยุดและพบว่าเครื่องหมายอยู่ข้างซ้าย ใบยินยอมเขียนข้างขวา ควรทำอย่างไร → หยุดการผ่าตัด ตรวจเวชระเบียน ภาพ และสอบถามจนข้อมูลตรงกันก่อนดำเนินการต่อ",
    "เมื่อผ่าตัดเสร็จ พยาบาลนับผ้าซับเลือดขาด 1 ผืน ขั้นตอนนี้อยู่ในช่วงใดของ checklist และควรทำอย่างไร → Sign out; ค้นหาในแผลและห้อง ถ้าไม่พบ ทำ intraoperative radiograph ก่อนปิดแผล"]}),
A({page:8, page2:4, orig:"Professionalism 3",
  stem:"A patient who needs laparoscopic cholecystectomy refuses the operation. The doctor still schedules the surgery without the patient's consent. Which ethical or legal obligation has the doctor violated?",
  gray:"A patient needed for laparoscopic cholecystectomy but the patient denied, then the doctor still arranged the surgery without consent. How does the doctor violate the ethics law? — A. The doctor failed to achieve informed consent",
  opts:["Breach of patient confidentiality","Failure to obtain informed consent","Unfair allocation of medical resources","Conflict of interest","Abandonment of the patient"],
  ans:1, key:RC("A. The doctor failed to achieve informed consent"),
  interp:"ผู้ป่วยปฏิเสธการผ่าตัดแล้ว แต่แพทย์ยังนัดผ่าตัดต่อ — ถามว่าแพทย์ละเมิดหลักอะไร คำสำคัญคือ <b>ผู้ป่วยปฏิเสธ</b> + <b>ไม่ได้รับความยินยอม</b> → เรื่อง autonomy และ informed consent",
  why:"ผู้ใหญ่ที่มี <b>decision-making capacity</b> มีสิทธิ์ตัดสินใจรับหรือ<b>ปฏิเสธ</b>การรักษา (หลัก <b>respect for autonomy</b>) แม้การตัดสินใจนั้นแพทย์เห็นว่าไม่ดีต่อสุขภาพ — การผ่าตัดโดยไม่มีความยินยอมจึง<b>ผิดทั้งจริยธรรมและกฎหมาย</b> (อาจเข้าข่ายการทำร้ายร่างกายหรือละเมิด) แม้ผลการผ่าตัดจะดี; informed consent ที่สมบูรณ์ต้องมี (1) capacity (2) disclosure: การวินิจฉัย ทางเลือก ประโยชน์ ความเสี่ยง และผลของการไม่รักษา (3) understanding (4) voluntariness ปราศจากการบังคับ (5) การตัดสินใจและลงนาม — ในประเทศไทย สิทธิ์นี้รับรองใน พรบ.สุขภาพแห่งชาติ 2550 และคำประกาศสิทธิและข้อพึงปฏิบัติของผู้ป่วย",
  wrong:["Confidentiality คือการรักษาความลับข้อมูลสุขภาพของผู้ป่วย — โจทย์ไม่มีการเปิดเผยข้อมูลให้บุคคลอื่น; จะถูกถ้าแพทย์แจ้งผลการวินิจฉัยแก่นายจ้างหรือญาติโดยผู้ป่วยไม่ยินยอม",
    "Unfair allocation เป็นเรื่องหลัก <b>justice</b> (การจัดสรรทรัพยากรที่จำกัด เช่น เตียง ICU อวัยวะ) — ไม่เกี่ยวกับโจทย์; จะถูกถ้าแพทย์จัดคิวผ่าตัดให้คนรู้จักก่อนผู้ป่วยที่เร่งด่วนกว่า",
    "Conflict of interest คือผลประโยชน์ส่วนตัว (เงิน ค่าตอบแทนจากบริษัทยา) มีอิทธิพลต่อการตัดสินใจทางคลินิก — โจทย์ไม่ได้บอกผลประโยชน์ใด; จะถูกถ้าแพทย์แนะนำผ่าตัดเพราะได้ส่วนแบ่งจากอุปกรณ์ที่ใช้",
    "Abandonment คือการยุติความสัมพันธ์การรักษาโดยไม่แจ้งล่วงหน้าหรือไม่ส่งต่อ ทั้งที่ผู้ป่วยยังต้องการการดูแล — โจทย์ตรงกันข้าม แพทย์ยังจะรักษาต่อแต่ละเมิดการปฏิเสธ; จะถูกถ้าแพทย์เลิกดูแลผู้ป่วยทันทีหลังผู้ป่วยปฏิเสธผ่าตัดโดยไม่ให้การรักษาทางเลือกหรือส่งต่อ"],
  trap:"คิดว่าแพทย์ทำเพื่อประโยชน์ของผู้ป่วย (beneficence) จึงทำได้ — แต่ในผู้ป่วยที่มี capacity และไม่ใช่ภาวะฉุกเฉิน <b>autonomy อยู่เหนือ beneficence</b>; การ \"ยินยอม\" ต้องเป็นการยินยอมต่อหัตถการนั้นจริง ๆ ไม่ใช่การเซ็นใบรับเข้าโรงพยาบาล",
  summary:["หลักจริยธรรม 4 ข้อ (Beauchamp &amp; Childress): respect for autonomy, beneficence, non-maleficence, justice",
    "Informed consent: capacity + disclosure (diagnosis, ลักษณะหัตถการ, ประโยชน์, ความเสี่ยง, ทางเลือก, ผลของการไม่รักษา) + understanding + voluntariness + authorization; ผู้ที่ทำหัตถการเป็นผู้ขอ consent",
    "Capacity ประเมินเฉพาะเรื่อง: เข้าใจข้อมูล, รับรู้ว่าเกี่ยวกับตนเอง, ใช้เหตุผลชั่งทางเลือก, สื่อสารการตัดสินใจได้คงที่",
    "ผู้ป่วยมี capacity ปฏิเสธการรักษา → สำรวจเหตุผล ให้ข้อมูลซ้ำ เสนอทางเลือก ให้เวลาคิด บันทึกการปฏิเสธในเวชระเบียน (refusal form) และยังดูแลต่อด้วยการรักษาอื่น",
    "ข้อยกเว้นที่ทำได้โดยไม่ต้องรอ consent: ภาวะฉุกเฉินคุกคามชีวิตที่ผู้ป่วยไม่รู้สติและไม่มีผู้แทน (ทำเท่าที่จำเป็น); ผู้ป่วยไม่มี capacity หรือเป็นผู้เยาว์ → ผู้แทนโดยชอบธรรมตัดสินใจแทนเพื่อประโยชน์สูงสุดของผู้ป่วย",
    "ผ่าตัดโดยไม่มี consent หรือขัดต่อการปฏิเสธ = ผิดจริยธรรมและอาจผิดกฎหมาย แม้ผลการรักษาจะดี",
    "ดูข้อ 17, 18 (professionalism และ surgical safety)"],
  notes:"<b>แถว Professionalism and Surgical safety 3 ในไฟล์เฉลยว่าง</b><br>ไฟล์โจทย์: ผู้จดใส่ช้อยไว้ช้อยเดียว \"A. The doctor failed to achieve informed consent\"<br>ช้อยอื่น 4 ช้อย (confidentiality, justice, conflict of interest, abandonment) เราแต่งเพิ่ม; ช้อยที่ถูกเกลาเป็น \"Failure to obtain informed consent\" ความหมายเดิม",
  mnemonic:"",
  guide:"พรบ.สุขภาพแห่งชาติ 2550 และคำประกาศสิทธิผู้ป่วย; Beauchamp &amp; Childress, Principles of Biomedical Ethics",
  opinion:"ไม่มีคีย์ — ตอบตามช้อยที่ผู้จดใส่ไว้ มั่นใจสูง",
  variants:["ผู้ป่วยหญิงอายุ 45 ปี รู้สติดี เป็นพยานพระยะโฮวา ปฏิเสธการรับเลือดก่อนผ่าตัดที่อาจเสียเลือดมาก แพทย์ควรทำอย่างไร → เคารพการปฏิเสธ บันทึกไว้ วางแผน blood conservation (preop anemia correction, cell salvage ถ้าผู้ป่วยยอมรับ, hemostasis อย่างพิถีพิถัน)",
    "ผู้ป่วยชายถูกรถชน หมดสติ ความดันต่ำ มี hemoperitoneum ไม่มีญาติ แพทย์ควรทำอย่างไร → ผ่าตัดฉุกเฉินได้เพื่อรักษาชีวิต (emergency exception) และบันทึกเหตุผลไว้"]}),
A({page:9, page2:4, orig:"Metabolic 1",
  stem:"A patient sustains a major injury. Which group consists of proinflammatory cytokines?",
  gray:"In a situation of someone with injury, which of the following are inflammatory cytokines? — A. IL-1, TNF-alpha, IFN-gamme B. ช้อยอื่นมี IL-4, IL-10, IL-13 ทุกช้อย",
  opts:["IL-1, TNF-alpha and IFN-gamma","IL-4, IL-10 and IL-13","IL-4, IL-10 and TGF-beta","IL-10, IL-13 and IL-1 receptor antagonist","IL-4, IL-13 and soluble TNF receptor"],
  ans:0, key:"A IL-1, TNF-alpha, IFN-gamme"+KS,
  interp:"ถามกลุ่ม <b>proinflammatory cytokine</b> ในการตอบสนองต่อการบาดเจ็บ — ต้องจำแยกได้ว่า cytokine ตัวไหนกระตุ้นการอักเสบ (SIRS) และตัวไหนต้านการอักเสบ (CARS)",
  why:"หลังบาดเจ็บ macrophage/monocyte และ endothelium ที่ถูกกระตุ้นจาก DAMPs (และ PAMPs ถ้าติดเชื้อ) หลั่ง <b>proinflammatory cytokines</b>: <b>TNF-α</b> (หลั่งเร็วที่สุด ภายในราว 30–90 นาที กระตุ้น fever, catabolism ของกล้ามเนื้อ, procoagulant), <b>IL-1</b> (ออกฤทธิ์คล้าย TNF-α, กระตุ้นไข้ผ่าน PGE2 ที่ hypothalamus), <b>IL-6</b> (ระดับสัมพันธ์กับความรุนแรงของการบาดเจ็บ กระตุ้น acute phase proteins เช่น CRP), IL-8 (chemotaxis ของ neutrophil), IL-12 และ <b>IFN-γ</b> (จาก Th1 และ NK cell กระตุ้น macrophage) — ช้อย A จึงเป็นกลุ่ม proinflammatory ทั้งหมด",
  wrong:["IL-4, IL-10, IL-13 เป็น <b>anti-inflammatory cytokines</b> (IL-4, IL-13 จาก Th2; IL-10 ยับยั้งการสร้าง TNF-α, IL-1, IL-6 จาก macrophage) — เป็นส่วนของ CARS; จะถูกถ้าโจทย์ถามกลุ่ม anti-inflammatory",
    "IL-4, IL-10 และ <b>TGF-β</b> ล้วนต้านการอักเสบ (TGF-β ยังกระตุ้น fibroblast และ collagen ในช่วง wound healing) — ไม่มีตัวใดเป็น proinflammatory; จะถูกถ้าถาม anti-inflammatory หรือ immunosuppressive cytokine",
    "IL-10, IL-13 และ <b>IL-1 receptor antagonist</b> (แย่งจับ IL-1 receptor ยับยั้งฤทธิ์ IL-1) เป็นตัวกลางฝั่ง CARS ทั้งหมด; จะถูกถ้าถามสารที่ร่างกายใช้ถ่วงดุลการอักเสบ",
    "IL-4, IL-13 และ <b>soluble TNF receptor</b> (จับ TNF-α ในกระแสเลือดทำให้หมดฤทธิ์) เป็นตัวต้านการอักเสบ; จะถูกถ้าถามตัวกลางที่ลดฤทธิ์ของ TNF-α"],
  trap:"เห็น IL ตัวเลขน้อย ๆ แล้วเดา — ต้องจำเป็นกลุ่ม: <b>TNF-α, IL-1, IL-6, IL-8, IL-12, IFN-γ = กระตุ้นการอักเสบ</b> ส่วน <b>IL-4, IL-10, IL-13, TGF-β, IL-1ra, sTNFR = ต้านการอักเสบ</b>; IL-6 มีฤทธิ์ทั้งสองด้านแต่ในบริบทบาดเจ็บจัดเป็น proinflammatory",
  summary:["การบาดเจ็บ → DAMPs (HMGB1, mitochondrial DNA, heat shock proteins) กระตุ้น pattern recognition receptors (TLRs) บน immune cells → หลั่ง cytokines",
    "Proinflammatory: <b>TNF-α</b> (เร็วที่สุด, catabolism, fever), <b>IL-1</b> (fever, คล้าย TNF), <b>IL-6</b> (สัมพันธ์ความรุนแรง, acute phase proteins, พยากรณ์โรค), IL-8 (neutrophil chemotaxis), IL-12, <b>IFN-γ</b> (กระตุ้น macrophage)",
    "Anti-inflammatory: <b>IL-4, IL-10, IL-13, TGF-β</b>, IL-1 receptor antagonist, soluble TNF receptors",
    "SIRS ↔ <b>CARS</b> (compensatory anti-inflammatory response syndrome) เกิดคู่กัน; ถ้า CARS เด่นนาน → immunoparalysis เสี่ยงติดเชื้อแทรกซ้อน; ถ้า SIRS เด่น → MODS",
    "Neuroendocrine response ทำงานร่วม: catecholamines, cortisol, glucagon, ADH, aldosterone → hypermetabolism, catabolism, hyperglycemia, เก็บน้ำและเกลือ",
    "Ebb phase (24–48 ชม.แรก: hypometabolism, ลด cardiac output) → flow phase (hypermetabolism, catabolism แล้วเข้าสู่ anabolism)",
    "ดูข้อ 21, 7 (metabolic response, stress hyperglycemia และ lactic acidosis)"],
  notes:"แถว Metabolic response 1 ในไฟล์เฉลยมีแต่ <b>\"A\"</b> ไม่มีคำอธิบาย<br>ไฟล์โจทย์: ช้อย A พิมพ์ว่า \"IL-1, TNF-alpha, IFN-gamme\" (สะกด gamme ตามต้นฉบับ = IFN-gamma); ช้อย B ผู้จดเขียนโน้ตแทนช้อยว่า <b>\"ช้อยอื่นมี IL-4, IL-10, IL-13 ทุกช้อย\"</b><br>ช้อย B–E เราแต่งตามโน้ตนี้ (ทุกช้อยมี IL-4, IL-10 หรือ IL-13 ร่วมกับ anti-inflammatory mediator อื่น)",
  mnemonic:"<b>\"1-6-8-12 + TNF + IFN-γ = ไฟลุก\"</b> · <b>\"4-10-13 + TGF-β = ดับไฟ\"</b>",
  guide:"Schwartz 11th ed. (Systemic response to injury)",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง; สอดคล้องกับข้อสอบชุด 76C ที่ถาม TNF-alpha ในการตอบสนองต่อการบาดเจ็บ",
  variants:["ผู้ป่วย burn 40% TBSA วันที่ 1 มีไข้และหัวใจเต้นเร็ว cytokine ใดหลั่งเร็วที่สุดหลังบาดเจ็บ → TNF-α",
    "cytokine ใดมีระดับสัมพันธ์กับความรุนแรงของการบาดเจ็บและใช้พยากรณ์ภาวะแทรกซ้อนได้ดีที่สุด → IL-6",
    "ผู้ป่วย ICU หลังผ่าตัดใหญ่ 10 วัน ติดเชื้อซ้ำหลายครั้ง สัมพันธ์กับ cytokine กลุ่มใดเด่น → anti-inflammatory (IL-10, TGF-β) ภาวะ CARS/immunoparalysis"]}),
A({page:9, page2:4, orig:"Metabolic 2",
  stem:"After a major injury, a patient without a history of diabetes develops hyperglycemia. What is the main mechanism?",
  gray:"In a situation of someone with injury, a patient has hyperglycemia without prior history of DM, what is the mechanism? — A. Catecholamines and glucocorticoids (ประมาณนี้มั้ง จำไม่ค่อยได้เหมือนกัน)",
  opts:["Catecholamines and glucocorticoids","Excess insulin secretion","Suppressed glucagon release","Increased peripheral glucose uptake","Reduced hepatic gluconeogenesis"],
  ans:0, key:"A Catecholamines and glucocorticoids"+KS,
  interp:"<b>Stress hyperglycemia</b> ในผู้ป่วยที่ไม่เคยเป็นเบาหวาน — ถามกลไกหลัก ต้องนึกถึง counter-regulatory hormones และ insulin resistance ใน neuroendocrine response ต่อการบาดเจ็บ",
  why:"หลังบาดเจ็บ sympathetic–adrenal axis และ HPA axis ถูกกระตุ้น: <b>catecholamines</b> (epinephrine) → glycogenolysis และ gluconeogenesis ที่ตับ + ยับยั้งการหลั่ง insulin จาก β-cell (α-adrenergic) + ลดการใช้ glucose ที่กล้ามเนื้อ; <b>cortisol (glucocorticoid)</b> → กระตุ้น gluconeogenesis จาก amino acid (สลายกล้ามเนื้อ) และ lactate/glycerol + เพิ่ม <b>insulin resistance</b> ที่ peripheral; ร่วมกับ <b>glucagon ↑</b>, GH และ cytokine (TNF-α, IL-6) ที่ลดการทำงานของ GLUT4 → hepatic glucose output ↑ แต่ peripheral uptake ↓ → hyperglycemia",
  wrong:["ช่วงแรกหลังบาดเจ็บ (ebb phase) insulin <b>ถูกกด</b> โดย catecholamine; ช่วง flow phase ระดับ insulin อาจปกติหรือสูงได้แต่มี <b>insulin resistance</b> — insulin เกินทำให้น้ำตาล<b>ต่ำ</b> ไม่ใช่สูง; จะถูกถ้าโจทย์ถามกลไกของ late dumping (hyperinsulinemic hypoglycemia)",
    "หลังบาดเจ็บ glucagon <b>เพิ่มขึ้น</b> (ร่วมกับ catecholamine และ cortisol) กระตุ้น glycogenolysis และ gluconeogenesis; การกด glucagon จะทำให้น้ำตาลลดลง; จะถูกถ้าถามผลของ somatostatin หรือ octreotide",
    "Peripheral insulin-mediated glucose uptake (กล้ามเนื้อ ไขมัน) <b>ลดลง</b>จาก insulin resistance; แม้แผลและเซลล์อักเสบจะใช้ glucose มากขึ้นแบบไม่พึ่ง insulin แต่ผลรวมคือน้ำตาลสูง; จะถูกถ้าถามกลไกที่ insulin ใช้ลดน้ำตาลในภาวะปกติ",
    "Hepatic gluconeogenesis <b>เพิ่มขึ้น</b> (จาก glucagon, cortisol, catecholamine โดยใช้ alanine, lactate, glycerol เป็นสารตั้งต้น) และไม่ถูกกดด้วยการให้ glucose ตามปกติ; จะถูกถ้าถามผลของ insulin ต่อตับ"],
  trap:"คิดว่าน้ำตาลสูงเพราะขาด insulin อย่างเดียวเหมือนเบาหวาน — ใน stress hyperglycemia กลไกหลักคือ <b>counter-regulatory hormones + insulin resistance</b> และตับยังผลิต glucose ต่อแม้ให้ glucose หรือ insulin",
  summary:["Counter-regulatory hormones หลังบาดเจ็บ: <b>catecholamines, cortisol, glucagon, GH</b> → glycogenolysis + gluconeogenesis ↑, insulin secretion ช่วงแรก ↓",
    "Insulin resistance ที่กล้ามเนื้อและไขมัน (GLUT4 translocation ↓) จาก cortisol, catecholamines และ cytokines (TNF-α, IL-6)",
    "Catabolism: สลาย protein กล้ามเนื้อ (alanine, glutamine) ไปทำ gluconeogenesis → negative nitrogen balance; lipolysis → free fatty acids, glycerol",
    "Ebb phase (ชั่วโมงแรกถึง 24–48 ชม.: hypometabolism, ลด O2 consumption) → flow phase (hypermetabolism, catabolism แล้วเข้าสู่ anabolism)",
    "Stress hyperglycemia สัมพันธ์กับ infection และ mortality ที่เพิ่มขึ้น → คุมน้ำตาลใน ICU <b>140–180 mg/dL</b> ด้วย insulin infusion; <b>NICE-SUGAR 2009</b>: tight control 81–108 mg/dL เพิ่ม mortality และ hypoglycemia",
    "Steroid ที่ให้จากภายนอก, TPN ที่ให้ glucose มากเกิน และ sepsis ทำให้น้ำตาลสูงขึ้นได้อีก — ตรวจ HbA1c ช่วยแยกเบาหวานที่ไม่เคยวินิจฉัย",
    "ดูข้อ 20, 7 (cytokines ในการตอบสนองต่อการบาดเจ็บและ lactic acidosis)"],
  notes:"แถว Metabolic response 2 ในไฟล์เฉลยมีแต่ <b>\"A\"</b> ไม่มีคำอธิบาย<br>ไฟล์โจทย์: ผู้จดใส่ช้อยไว้ช้อยเดียว \"A. Catecholamines and glucocorticoids\" ตามด้วยโน้ตผู้จด <b>\"(ประมาณนี้มั้ง จำไม่ค่อยได้เหมือนกัน)\"</b> — ผู้จดไม่แน่ใจถ้อยคำของช้อย<br>ช้อย B–E เราแต่งเพิ่ม",
  mnemonic:"",
  guide:"Schwartz 11th ed.; NICE-SUGAR 2009",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง (แม้ผู้จดไม่แน่ใจถ้อยคำ แต่กลไก catecholamine + glucocorticoid ถูกต้องตามตำรา); สอดคล้องกับข้อสอบชุด 76C, 77B และ 77C ที่ถาม metabolic response ต่อการบาดเจ็บ",
  variants:["ผู้ป่วย polytrauma ใน ICU วันที่ 2 น้ำตาล 260 mg/dL HbA1c 5.4% เป้าหมายการคุมน้ำตาลที่เหมาะสมคือ → 140–180 mg/dL ด้วย insulin infusion",
    "หลังผ่าตัดใหญ่ ผู้ป่วยมี negative nitrogen balance กล้ามเนื้อลีบลง ฮอร์โมนใดเป็นตัวหลักที่กระตุ้นการสลายโปรตีนกล้ามเนื้อไปทำ gluconeogenesis → cortisol"]}),
A({page:9, page2:4, orig:"Nutrition 1",
  stem:"After gastrectomy, a patient develops tachycardia, sweating and abdominal discomfort 30 minutes after meals. What is the most likely diagnosis?",
  gray:"A patient undergoes gastrectomy and develops tachycardia, sweating, abdominal discomfort 30 mins after meal (อาการประมาณนี้มั้ง), what is the diagnosis? — A. Early dumping syndrome",
  opts:["Late dumping syndrome","Early dumping syndrome","Afferent loop syndrome","Efferent loop syndrome","Bile reflux gastritis"],
  ans:1, key:"B Early dumping syndrome"+KS,
  interp:"อาการหลัง gastrectomy ที่เกิด <b>หลังอาหาร 30 นาที</b> มีทั้งอาการ<b>ระบบหัวใจหลอดเลือด/vasomotor</b> (ใจสั่น เหงื่อออก) และ<b>ทางเดินอาหาร</b> (ไม่สบายท้อง) — เวลาที่เกิดอาการหลังอาหารคือตัวแยกโรคหลัก",
  why:"<b>Early dumping</b> เกิดภายใน <b>15–30 นาที (ไม่เกิน 1 ชม.)</b> หลังอาหาร — เมื่อเสีย pylorus หรือ reservoir ของกระเพาะ อาหาร hyperosmolar เทเข้าลำไส้เล็กเร็ว → <b>fluid shift</b> จาก intravascular เข้าลำไส้ (ลำไส้ขยาย, intravascular volume ลด) + หลั่ง vasoactive peptides (serotonin, VIP, neurotensin, bradykinin, GLP-1) → อาการ GI (ปวดท้อง อืด คลื่นไส้ ท้องเสีย) และ vasomotor (<b>ใจสั่น tachycardia เหงื่อออก</b> หน้าแดง หน้ามืด อยากนอน) ตรงกับโจทย์",
  wrong:["Late dumping เกิด <b>1–3 ชม.</b>หลังอาหาร — glucose ดูดซึมเร็ว → hyperglycemia → insulin หลั่งมากเกิน (GLP-1) → <b>hypoglycemia</b> (เหงื่อ สั่น ใจสั่น สับสน) มีอาการ GI น้อย; จะถูกถ้าอาการเกิด 2 ชม.หลังอาหารและวัดน้ำตาลได้ต่ำ",
    "Afferent loop syndrome เกิดหลัง <b>Billroth II</b> จาก afferent limb อุดตัน — แบบเฉียบพลัน = closed-loop obstruction ปวดท้องรุนแรง amylase อาจสูง เสี่ยง perforation; แบบเรื้อรัง = ปวดแน่นท้องด้านขวาบนหลังอาหารแล้ว<b>อาเจียนน้ำดีพุ่ง (ไม่มีเศษอาหาร) แล้วอาการดีขึ้น</b>; จะถูกถ้าโจทย์ให้อาการแบบนี้",
    "Efferent loop obstruction — อาการลำไส้อุดตันสูง: ปวดท้อง ท้องอืด <b>อาเจียนมีทั้งน้ำดีและเศษอาหาร</b> (จาก adhesion, internal hernia, intussusception ที่ efferent limb); จะถูกถ้าโจทย์ให้อาเจียนเศษอาหารปนน้ำดีและภาพรังสีเห็น obstruction",
    "Bile reflux (alkaline reflux) gastritis — ปวดแสบลิ้นปี่<b>ตลอดเวลา</b> อาเจียนน้ำดีแล้ว<b>ไม่ดีขึ้น</b> ส่องกล้องเห็นกระเพาะอักเสบมีน้ำดี, HIDA เห็น reflux; รักษาโดยเปลี่ยนเป็น Roux-en-Y (Roux limb 45–60 cm); จะถูกถ้าโจทย์ให้อาการแบบนี้"],
  trap:"สลับ early กับ late dumping เพราะทั้งคู่มีใจสั่นเหงื่อออก — ให้ดู<b>เวลา</b>: ≤30–60 นาที = early (fluid shift + GI เด่น), 1–3 ชม. = late (hypoglycemia, GI น้อย)",
  summary:["Dumping พบหลัง gastrectomy, pyloroplasty, gastrojejunostomy, Roux-en-Y gastric bypass และ esophagectomy — เกิดจากเสียการควบคุมการเทอาหารของ pylorus",
    "<b>Early dumping</b> 15–30 นาที (≤1 ชม.): hyperosmolar load → fluid shift + vasoactive peptides → GI (ปวดท้อง อืด ท้องเสีย) + vasomotor (tachycardia เหงื่อ หน้าแดง หน้ามืด) — พบบ่อยกว่า late",
    "<b>Late dumping</b> 1–3 ชม.: carbohydrate ดูดซึมเร็ว → hyperinsulinemia (GLP-1) → reactive hypoglycemia",
    "วินิจฉัยจากอาการ (Sigstad score ≥7 ชี้ว่าน่าจะเป็น), modified oral glucose tolerance test (HR เพิ่ม &gt;10 ครั้ง/นาทีในชั่วโมงแรก = early; น้ำตาลต่ำในชั่วโมงที่ 2–3 = late)",
    "รักษาขั้นแรกด้วยอาหาร: มื้อเล็กบ่อย 5–6 มื้อ, ลด simple sugar, เพิ่ม protein/fiber, <b>แยกน้ำออกจากมื้ออาหาร</b> (ดื่มหลังอาหาร ≥30 นาที), นอนราบหลังกิน; ส่วนใหญ่ดีขึ้นเองตามเวลา",
    "ยา: acarbose (late dumping), somatostatin analog <b>octreotide</b> (ทั้ง early และ late เมื่อปรับอาหารไม่ได้ผล); ผ่าตัดแก้ไข (เช่น เปลี่ยนเป็น Roux-en-Y) เป็นทางสุดท้าย",
    "Post-gastrectomy syndromes อื่น: afferent loop (อาเจียนน้ำดีพุ่งแล้วดีขึ้น), efferent loop (อาเจียนเศษอาหาร + น้ำดี), bile reflux gastritis (ปวดตลอด อาเจียนน้ำดีไม่ดีขึ้น), postvagotomy diarrhea, anemia (B12, iron)",
    "ดูข้อ 40, 38, 41 (nutrition และ stomach/duodenum)"],
  notes:"แถว Surgical Nutrition 1 ในไฟล์เฉลยมีแต่ <b>\"A\"</b> ไม่มีคำอธิบาย (= Early dumping syndrome ช้อยเดียวในต้นฉบับ → ช้อย B ของเรา)<br>ไฟล์โจทย์: ผู้จดใส่ช้อยเดียว \"A. Early dumping syndrome\" และโน้ตผู้จดในโจทย์ <b>\"(อาการประมาณนี้มั้ง)\"</b> — ผู้จดไม่แน่ใจรายละเอียดอาการ<br>ช้อยอื่น 4 ช้อย (late dumping, afferent loop, efferent loop, bile reflux gastritis) เราแต่งเพิ่ม",
  mnemonic:"<b>\"ครึ่งชั่วโมงน้ำไหล–สองชั่วโมงน้ำตาลตก\"</b>: early = fluid shift ใน 30 นาที · late = hypoglycemia 1–3 ชม.",
  guide:"Schwartz 11th ed.; Sabiston 21st ed.",
  opinion:"เห็นด้วยกับคีย์ (Early dumping) มั่นใจสูง — เวลา 30 นาทีหลังอาหารและอาการ vasomotor ร่วม GI เข้ากับ early dumping; สอดคล้องกับข้อสอบชุด 76D, 77A และ 77D ที่ถาม dumping โดยแยกตามเวลา",
  variants:["หลัง distal gastrectomy with Billroth II 3 เดือน ผู้ป่วยเหงื่อออก มือสั่น สับสน 2 ชั่วโมงหลังอาหาร น้ำตาล 50 mg/dL → late dumping; ลด simple carbohydrate, มื้อเล็กบ่อย, acarbose",
    "หลัง Billroth II ผู้ป่วยปวดแน่นท้องหลังอาหาร 20 นาที แล้วอาเจียนน้ำดีพุ่งไม่มีเศษอาหาร หลังอาเจียนอาการหายทันที → chronic afferent loop syndrome",
    "ผู้ป่วยมี early dumping หลัง gastrectomy การแนะนำเรื่องน้ำดื่มที่ถูกต้องคือ → ดื่มน้ำแยกจากมื้ออาหาร อย่างน้อย 30 นาทีหลังอาหาร"]}),
A({page:10, page2:4, orig:"Hernia 1",
  stem:"A patient has a reducible groin mass above the inguinal ligament. When the deep inguinal ring is occluded with a finger and the patient coughs, the mass does not reappear. What is the diagnosis?",
  gray:"A patient with groin mass, superior to inguinal ligament, occlusion test positive, what is the diagnosis? — A. Femoral hernia B. Direct inguinal hernia C. Indirect inguinal hernia",
  opts:["Femoral hernia","Direct inguinal hernia","Indirect inguinal hernia","Spigelian hernia","Obturator hernia"],
  ans:2, key:"C Indirect inguinal hernia"+KS,
  flag:"⚠ เล็กน้อย: \"occlusion test positive\" มีการใช้คำต่างกัน — เขียน stem ตามความหมายมาตรฐาน (กด deep ring แล้วก้อนไม่โผล่)",
  interp:"ก้อนที่ขาหนีบ<b>อยู่เหนือ inguinal ligament</b> (= inguinal ไม่ใช่ femoral) และเมื่อกด deep ring แล้วให้ไอ <b>ก้อนไม่โผล่</b> = deep ring คุมก้อนได้ → ก้อนออกทาง deep ring",
  why:"<b>Deep ring occlusion test</b>: ให้ผู้ป่วยดันก้อนกลับ (reduce) แล้วใช้นิ้วกดที่ <b>deep inguinal ring</b> (เหนือจุดกึ่งกลาง inguinal ligament ราว 1.5 cm) แล้วให้ไอ — ถ้า<b>ก้อนไม่โผล่</b>ขณะกด (และโผล่เมื่อปล่อยนิ้ว) แปลว่าก้อนต้องผ่าน deep ring = <b>indirect inguinal hernia</b> (ออกทาง deep ring ซึ่งอยู่ lateral ต่อ inferior epigastric vessels ผ่าน patent processus vaginalis ไปตาม inguinal canal และลงถุงอัณฑะได้); ถ้าก้อนโผล่ทางด้าน medial ต่อนิ้ว = direct",
  wrong:["Femoral hernia ออกทาง femoral canal <b>ใต้ inguinal ligament</b> อยู่ inferolateral ต่อ pubic tubercle พบบ่อยในหญิงสูงอายุ และเสี่ยง strangulation สูง — โจทย์บอกว่าก้อนอยู่เหนือ inguinal ligament; จะถูกถ้าก้อนอยู่ใต้ ligament ด้านข้างต่อ pubic tubercle",
    "Direct inguinal hernia ดันผ่าน transversalis fascia ที่อ่อนแอใน <b>Hesselbach triangle</b> (medial ต่อ inferior epigastric vessels) — การกด deep ring <b>คุมไม่ได้</b> ก้อนจะโผล่ทางด้าน medial ต่อนิ้ว; จะถูกถ้าโจทย์บอกว่ากด deep ring แล้วก้อนยังโผล่ medial ต่อนิ้ว (ดูข้อ 24)",
    "Spigelian hernia ออกทาง Spigelian fascia ตาม <b>linea semilunaris</b> (ขอบ lateral ของ rectus) มักระดับ arcuate line — ก้อนอยู่ที่ผนังหน้าท้องส่วนล่างด้านข้าง อาจอยู่ใต้ external oblique aponeurosis จนคลำยาก (ต้องใช้ US/CT) ไม่ใช่ก้อนที่ขาหนีบ; จะถูกถ้าโจทย์ให้ก้อนหรือจุดกดเจ็บที่ขอบ lateral ของ rectus ใต้สะดือ",
    "Obturator hernia ออกทาง obturator canal พบใน<b>หญิงสูงอายุผอม</b> มักมาด้วยลำไส้อุดตันและ <b>Howship-Romberg sign</b> (ปวดร้าวต้นขาด้านใน) มักคลำก้อนไม่ได้; จะถูกถ้าโจทย์ให้หญิงชราผอมมีลำไส้อุดตันและปวดต้นขาด้านใน"],
  trap:"คำว่า \"occlusion test <b>positive</b>\" — บางแหล่งใช้หมายถึง \"ก้อนถูกคุมไว้ได้\" (= indirect) แต่บางคนเข้าใจว่า \"ก้อนโผล่\" ต้องอ่านว่าผลจริงคืออะไร: <b>กด deep ring แล้วก้อนไม่โผล่ = indirect</b>, โผล่ medial ต่อนิ้ว = direct",
  summary:["Inguinal canal: deep ring (กลาง inguinal ligament เหนือขึ้นไปราว 1.5 cm, lateral ต่อ inferior epigastric vessels) → superficial ring (เหนือและ lateral ต่อ pubic tubercle)",
    "<b>Indirect</b> (พบบ่อยที่สุดทั้งชายและหญิง, ทุกวัย): ผ่าน deep ring lateral ต่อ inferior epigastric vessels, ในถุง processus vaginalis, ลงถุงอัณฑะได้",
    "<b>Direct</b>: ผ่าน Hesselbach triangle (inferior epigastric vessels, ขอบ lateral ของ rectus, inguinal ligament) จาก transversalis fascia อ่อนแอ, ผู้สูงอายุ, ก้อนกลมโผล่ตรงไปข้างหน้า, strangulate น้อย",
    "<b>Femoral</b>: ใต้ inguinal ligament, inferolateral ต่อ pubic tubercle, หญิงสูงอายุ, strangulation สูง → ผ่าตัดเร็ว",
    "PE: <b>deep ring occlusion test</b> (กดแล้วไม่โผล่ = indirect), invagination test (นิ้วในคลองรู้สึกแรงกระแทกที่ปลายนิ้ว = indirect, ที่ด้านข้างนิ้ว = direct) — ความแม่นยำในการแยก direct/indirect ไม่สูง และไม่เปลี่ยนการรักษา",
    "ไม่แน่ใจว่าเป็น hernia หรือไม่ → US ขาหนีบ (dynamic); รักษาด้วยการผ่าตัดซ่อม: Lichtenstein (open mesh) หรือ TEP/TAPP; ผู้ชายที่ไม่มีอาการหรืออาการน้อยอาจ watchful waiting ได้",
    "ดูข้อ 24, 25 (deep ring occlusion test และการเลือกวิธีผ่าตัด hernia)"],
  notes:"แถว +=Hernia 1 ในไฟล์เฉลยมีแต่ <b>\"C\"</b> ไม่มีคำอธิบาย (หัว section ในไฟล์เฉลยพิมพ์ว่า \"+=Hernia\")<br>ไฟล์โจทย์เขียนว่า <b>\"occlusion test positive\"</b> เฉย ๆ — เราเขียน stem ตามความหมายมาตรฐานของการทดสอบ (กด deep ring แล้วให้ไอ ก้อนไม่โผล่) และเติม \"reducible\"<br>ต้นฉบับมีช้อย A–C; ช้อย D (Spigelian) และ E (Obturator) เราแต่งเพิ่ม",
  mnemonic:"<b>MDs don't LIe</b>: Medial to inferior epigastric = Direct · Lateral = Indirect",
  guide:"HerniaSurge 2018; Schwartz 11th ed.",
  opinion:"เห็นด้วยกับคีย์ C มั่นใจสูง โดยตีความ \"occlusion test positive\" ว่ากด deep ring แล้วคุมก้อนได้ (ไม่โผล่) — ถ้าผู้ออกข้อสอบตั้งใจให้ \"positive\" หมายถึงก้อนยังโผล่ จะเป็น direct แต่การใช้คำในตำราส่วนใหญ่และคีย์ C สนับสนุนการตีความนี้; สอดคล้องกับข้อสอบชุด 77A ที่ถาม occlusion test (no protrusion = indirect)",
  variants:["ชายอายุ 25 ปี ก้อนที่ขาหนีบขวาลงถุงอัณฑะเวลายืน ดันกลับได้ กด deep ring แล้วให้ไอ ก้อนไม่โผล่ → indirect inguinal hernia",
    "หญิงอายุ 70 ปี ก้อนแข็งกดเจ็บใต้ inguinal ligament ด้านข้างต่อ pubic tubercle ดันกลับไม่ได้ อาเจียน → incarcerated femoral hernia ต้องผ่าตัดฉุกเฉิน"]}),
A({page:10, page2:4, orig:"Hernia 2",
  stem:"A patient has a reducible groin mass. Firm pressure is applied over the deep inguinal ring, just above the midpoint of the inguinal ligament, and the patient is asked to cough. The mass protrudes medial to the pressure point. Through which area does the hernia protrude?",
  gray:"A patient with groin mass, when applying pressure at mid inguinal canal and asked a patient to cough, the mass protruded medially to the pressure point, which space does the mass protrude from? — A. Hesselbach's triangle",
  opts:["Deep inguinal ring","Hesselbach's triangle","Femoral canal","Linea semilunaris","Obturator canal"],
  ans:1, key:"B Hesselbach's triangle"+KS,
  interp:"กดที่ deep ring แล้วให้ไอ ก้อน<b>ยังโผล่ทางด้าน medial ต่อนิ้ว</b> → deep ring คุมไม่ได้ ก้อนออกจากผนังด้านหลังของ inguinal canal medial ต่อ inferior epigastric vessels = direct hernia — ถามชื่อบริเวณนั้น",
  why:"บริเวณที่ direct inguinal hernia ดันผ่านคือ <b>Hesselbach's (inguinal) triangle</b> — ขอบ: <b>inferior epigastric vessels</b> (superolateral), <b>ขอบ lateral ของ rectus abdominis/rectus sheath</b> (medial), <b>inguinal ligament</b> (inferior); พื้นเป็น transversalis fascia ที่อ่อนแอลงตามอายุ → ก้อนดันออกตรงไปข้างหน้า medial ต่อตำแหน่ง deep ring ที่ถูกกด เพราะไม่ได้ผ่าน deep ring",
  wrong:["Deep inguinal ring เป็นทางออกของ <b>indirect</b> hernia — ถ้าก้อนออกทางนี้ การกด deep ring จะ<b>คุมก้อนไม่ให้โผล่</b>; จะถูกถ้าโจทย์บอกว่ากดแล้วก้อนไม่โผล่ (ดูข้อ 23)",
    "Femoral canal อยู่<b>ใต้ inguinal ligament</b> medial ต่อ femoral vein — ก้อนจะอยู่ inferolateral ต่อ pubic tubercle; จะถูกถ้าก้อนอยู่ใต้ ligament ที่ต้นขาด้านใน",
    "Linea semilunaris (ขอบ lateral ของ rectus sheath) เป็นตำแหน่งของ <b>Spigelian hernia</b> อยู่สูงกว่าขาหนีบ ระดับ arcuate line; จะถูกถ้าก้อนอยู่ที่ผนังหน้าท้องส่วนล่างด้านข้าง lateral ต่อ rectus",
    "Obturator canal เป็นทางออกของ <b>obturator hernia</b> อยู่ลึกในอุ้งเชิงกราน มักคลำก้อนไม่ได้ มาด้วยลำไส้อุดตัน + Howship-Romberg sign; จะถูกถ้าโจทย์ให้หญิงสูงอายุผอมมี SBO และปวดต้นขาด้านใน"],
  trap:"สับสนว่าก้อนที่โผล่ medial ต่อนิ้วคือ indirect ที่หลุดจากการกด — ถ้าก้อนผ่าน deep ring การกดต้องคุมได้; โผล่ medial = ไม่ได้ผ่าน deep ring = direct ผ่าน Hesselbach triangle",
  summary:["Hesselbach triangle: inferior epigastric vessels (superolateral) + ขอบ lateral ของ rectus (medial) + inguinal ligament (inferior) → ทางออกของ <b>direct</b> inguinal hernia",
    "Direct: acquired, transversalis fascia อ่อนแอ (อายุ, สูบบุหรี่, collagen ผิดปกติ, ไอเรื้อรัง, เบ่งถ่าย), ผู้ชายสูงอายุ, ก้อนกลมคอกว้าง, strangulate น้อย, ไม่ค่อยลงถุงอัณฑะ",
    "Indirect: ผ่าน deep ring lateral ต่อ inferior epigastric vessels, patent processus vaginalis, ลงถุงอัณฑะได้, คอแคบกว่าเสี่ยง incarceration มากกว่า direct",
    "Pantaloon hernia = มีทั้ง direct และ indirect คร่อม inferior epigastric vessels",
    "ตำแหน่ง deep ring: เหนือจุดกึ่งกลางของ inguinal ligament (ASIS ถึง pubic tubercle) ราว 1.5 cm; mid-inguinal point (กึ่งกลาง ASIS ถึง pubic symphysis) เป็นตำแหน่ง femoral artery",
    "Hernia อื่น: femoral (ใต้ ligament), Spigelian (linea semilunaris), obturator (obturator canal), umbilical/epigastric (linea alba)",
    "ดูข้อ 23, 25 (occlusion test และการผ่าตัด hernia)"],
  notes:"แถว +=Hernia 2 ในไฟล์เฉลยมีแต่ <b>\"A\"</b> ไม่มีคำอธิบาย (= Hesselbach's triangle ช้อยเดียวในต้นฉบับ → ช้อย B ของเรา)<br>ไฟล์โจทย์: ผู้จดใส่ช้อยเดียว \"A. Hesselbach's triangle\"; ช้อยอื่น 4 ช้อยเราแต่งเพิ่ม<br>ต้นฉบับเขียนว่ากดที่ <b>\"mid inguinal canal\"</b> — เราเขียน stem เป็นการกดที่ deep inguinal ring เหนือจุดกึ่งกลาง inguinal ligament ซึ่งเป็นตำแหน่งจริงของการทำ deep ring occlusion test และเติม \"reducible\"",
  mnemonic:"<b>RIP</b> (Hesselbach): <b>R</b>ectus (medial) · <b>I</b>nferior epigastric (lateral) · <b>P</b>oupart's = inguinal ligament (inferior)",
  guide:"Schwartz 11th ed.",
  opinion:"เห็นด้วยกับคีย์ (Hesselbach's triangle) มั่นใจสูง; ต้นฉบับเขียน \"mid inguinal canal\" ซึ่งไม่ใช่ตำแหน่งมาตรฐาน แต่เจตนาของโจทย์ชัดว่าเป็น deep ring occlusion test ที่ก้อนโผล่ medial ต่อจุดกด; สอดคล้องกับข้อสอบชุด 77C ที่ถาม Hesselbach triangle และ pantaloon hernia และเชื่อมกับข้อ 23",
  variants:["ชายอายุ 72 ปี ไอเรื้อรังจาก COPD มีก้อนกลมที่ขาหนีบขวาโผล่ตรงไปข้างหน้าเวลายืน ไม่ลงถุงอัณฑะ กด deep ring แล้วยังโผล่ → direct inguinal hernia ผ่าน Hesselbach triangle",
    "ระหว่างผ่าตัด TEP พบถุง hernia ทั้งด้าน medial และ lateral ต่อ inferior epigastric vessels → pantaloon hernia"]}),
A({page:10, page2:5, orig:"Hernia 3",
  stem:"A patient has bilateral reducible indirect inguinal hernias and is concerned about postoperative pain. Which operation is most appropriate?",
  gray:"A patient with bilateral indirect inguinal hernia with concern of postoperative pain, which operation is the most appropriate? — A. Open … B. Open … C. Open … D. TEP E. IPOM",
  opts:["Open Lichtenstein repair","Open Shouldice repair","Open Bassini repair","Laparoscopic TEP repair","Laparoscopic IPOM repair"],
  ans:3, key:"D TEP"+KS,
  interp:"Inguinal hernia <b>ทั้งสองข้าง</b> + ผู้ป่วย<b>กังวลเรื่องปวดหลังผ่าตัด</b> — ถามวิธีผ่าตัดที่เหมาะที่สุด ต้องรู้ข้อบ่งชี้ของ laparo-endoscopic repair ตาม HerniaSurge",
  why:"HerniaSurge 2018 แนะนำ <b>laparo-endoscopic repair (TEP หรือ TAPP)</b> สำหรับ <b>bilateral</b> inguinal hernia (รวมถึง recurrent หลัง open repair และ hernia ในผู้หญิง) เมื่อมีศัลยแพทย์ที่ชำนาญ — ซ่อมทั้งสองข้างผ่าน port ชุดเดียวกัน วาง mesh ใน preperitoneal space ครอบคลุม myopectineal orifice ทั้งหมด (direct, indirect, femoral), <b>ปวดหลังผ่าตัดน้อยกว่า, chronic postoperative inguinal pain น้อยกว่า</b> และกลับไปทำกิจวัตรได้เร็วกว่า open; TEP ไม่เข้าช่องท้อง (totally extraperitoneal) ข้อเสียคือต้องดมยาสลบ (GA) และมี learning curve",
  wrong:["Lichtenstein (open tension-free mesh) เป็น<b>มาตรฐานของ open repair</b> สำหรับ primary unilateral hernia ทำภายใต้ local anesthesia ได้ — สำหรับ bilateral ต้องเปิดแผลสองข้าง ปวดและ chronic pain มากกว่า laparo-endoscopic; จะถูกถ้าเป็น unilateral primary hernia ในผู้ป่วยที่ไม่เหมาะกับ GA หรือไม่มีความชำนาญ laparoscopy",
    "Shouldice เป็น <b>tissue repair (ไม่ใช้ mesh)</b> ที่ดีที่สุด เย็บ transversalis fascia ซ้อน 4 ชั้น recurrence ต่ำในมือผู้ชำนาญ — แต่ HerniaSurge แนะนำ mesh repair เป็นหลัก และเป็น open สองแผล; จะถูกถ้าผู้ป่วยไม่ต้องการ mesh หรือไม่มี mesh ใช้",
    "Bassini เป็น tissue repair แบบดั้งเดิม (เย็บ conjoint tendon กับ inguinal ligament) มี tension และ <b>recurrence สูง</b> ปัจจุบันแทบไม่ใช้; จะถูกถ้าโจทย์ถามประวัติศาสตร์ของ tissue repair หรือสถานการณ์ที่ไม่มี mesh และไม่ชำนาญ Shouldice",
    "IPOM (intraperitoneal onlay mesh) วาง mesh ในช่องท้องสัมผัสลำไส้ ใช้สำหรับ <b>ventral/incisional hernia</b> — HerniaSurge <b>ไม่แนะนำ</b>สำหรับ inguinal hernia (เสี่ยง adhesion, fistula และยึด mesh ใกล้ triangle of pain/doom ไม่ได้); จะถูกถ้าโจทย์เป็น ventral หรือ incisional hernia"],
  trap:"เลือก Lichtenstein เพราะเป็น \"gold standard\" — มาตรฐานนี้สำหรับ open repair ของ unilateral primary hernia; สำหรับ <b>bilateral</b>, recurrent หลัง open และเน้นลดปวด → TEP/TAPP",
  summary:["HerniaSurge 2018: ผู้ใหญ่ที่มีอาการ → mesh repair; ชายที่ไม่มีอาการหรืออาการน้อย → watchful waiting ได้ (แต่ส่วนใหญ่จะมีอาการและต้องผ่าตัดในที่สุด)",
    "<b>Laparo-endoscopic (TEP/TAPP)</b> เลือกเมื่อ: bilateral, recurrent หลัง open repair, ผู้หญิง (ตรวจหา femoral hernia ได้พร้อมกัน), ต้องการปวดน้อยและกลับไปทำงานเร็ว — ต้องการ GA และความชำนาญ",
    "<b>Lichtenstein</b>: มาตรฐานของ open mesh repair, ทำ local anesthesia ได้ (เหมาะผู้ป่วยเสี่ยงสูงต่อ GA), recurrent หลัง laparo-endoscopic repair → ทำ open",
    "Tissue repair: Shouldice ดีที่สุดเมื่อไม่ใช้ mesh; Bassini, McVay (Cooper ligament repair ใช้ซ่อม femoral hernia ได้) recurrence สูงกว่า",
    "TEP vs TAPP: ผลลัพธ์ใกล้เคียงกัน; TAPP เข้าช่องท้องเห็น anatomy ทั้งสองข้างชัด, TEP ไม่เข้าช่องท้อง; ระวัง triangle of doom (external iliac vessels) และ triangle of pain (lateral femoral cutaneous, genitofemoral nerves)",
    "IPOM ไม่ใช้กับ inguinal hernia; ภาวะแทรกซ้อนสำคัญหลังผ่าตัด hernia: chronic postoperative inguinal pain (~10%), recurrence, seroma, mesh infection",
    "ดูข้อ 23, 24 (การแยก indirect และ direct hernia)"],
  notes:"แถว +=Hernia 3 ในไฟล์เฉลยอยู่บนสุดของหน้า 5 = <b>\"3 D\"</b> ไม่มีคำอธิบาย (แถว 1–2 ของ section อยู่ท้ายหน้า 4; แถว 4–5 ว่าง)<br>ไฟล์โจทย์: ช้อย A–C ผู้จดจำได้แค่ <b>\"Open …\"</b> (จำชนิด open repair ไม่ได้) — เราเติมเป็น Lichtenstein, Shouldice และ Bassini; ช้อย D \"TEP\" และ E \"IPOM\" ตามต้นฉบับ (เติมคำว่า Laparoscopic และ repair)",
  mnemonic:"<b>\"สองข้าง–ซ้ำหลังเปิด–ผู้หญิง → ส่องกล้อง\"</b>",
  guide:"HerniaSurge 2018 (International guidelines for groin hernia management)",
  opinion:"เห็นด้วยกับคีย์ D มั่นใจสูง (TAPP ก็ถูกเท่ากันแต่ไม่อยู่ในช้อย); ช้อย open ทั้ง 3 เราเติมชนิดเองเพราะผู้จดจำไม่ได้ ไม่กระทบคำตอบ; สอดคล้องกับข้อสอบชุด 76C (TAPP/TEP สำหรับ bilateral) และ 77C (laparoscopic repair ครอบคลุม myopectineal orifice)",
  variants:["ชายอายุ 50 ปี เคยผ่าตัด Lichtenstein ข้างขวาเมื่อ 3 ปีก่อน ตอนนี้ก้อนกลับเป็นซ้ำข้างเดิม วิธีผ่าตัดที่เหมาะคือ → laparo-endoscopic (TEP/TAPP) ผ่านชั้นที่ยังไม่เคยผ่าตัด",
    "ชายอายุ 85 ปี มี severe COPD และ heart failure มี unilateral inguinal hernia ที่มีอาการ → open Lichtenstein ภายใต้ local anesthesia"]}),
A({page:11, page2:5, orig:"Small bowel 1",
  img:QI(26), imgNote:"Supine plain abdominal radiograph",
  stem:"A patient presents with abdominal pain, marked distension and obstipation. The plain abdominal radiograph is shown. What is the most likely diagnosis?",
  gray:"A plain X-ray was given, what is the diagnosis? [รูป plain abdomen] — A. Sigmoid volvulus",
  opts:["Sigmoid volvulus","Cecal volvulus","Small bowel obstruction","Paralytic ileus","Toxic megacolon"],
  ans:0, key:"A Sigmoid volvulus"+KS,
  flag:"⚠ เล็กน้อย: ต้นฉบับมีแค่รูป ไม่มีประวัติ — เติมอาการลำไส้อุดตันใน stem โดยไม่บอกชื่อ sign",
  interp:"อ่าน plain abdomen ในผู้ป่วยที่มีอาการลำไส้ใหญ่อุดตัน (ปวดท้อง ท้องอืดมาก ไม่ถ่ายไม่ผายลม) — ต้องดูว่าลำไส้ที่โป่งเป็นลำไส้เล็กหรือใหญ่ รูปร่าง และตำแหน่งต้นกำเนิดของห่วงที่โป่ง",
  why:"รูปเป็น<b>ห่วงลำไส้ใหญ่ที่โป่งขยายมาก</b> รูปตัว U กลับหัว ผนังเรียบไม่มี haustra <b>ขึ้นมาจากอุ้งเชิงกราน</b>ไปทางช่องท้องส่วนบน (ลักษณะ coffee bean หรือ bent inner tube — ผนังด้านในของสองขาห่วงชิดกันเป็นเส้นกลางชี้ลงไปทาง pelvis) ร่วมกับลำไส้ใหญ่ส่วนต้นโป่งตาม = <b>sigmoid volvulus</b> — sigmoid ที่ยาวและ mesentery แคบ (redundant sigmoid) บิดรอบ mesentery ทำให้เกิด closed-loop obstruction; พบในผู้สูงอายุ ท้องผูกเรื้อรัง ผู้ป่วยติดเตียง โรคทางระบบประสาทหรือจิตเวช",
  wrong:["Cecal volvulus: ห่วงลำไส้ที่โป่ง (cecum) <b>เริ่มจาก RLQ แล้วย้ายไปอยู่ช่องท้องกลางหรือ LUQ</b> รูปไตหรือ comma มี air-fluid level เดียว ลำไส้เล็กโป่งร่วม และลำไส้ใหญ่ส่วนปลายแฟบ — รักษาด้วยการผ่าตัด (right hemicolectomy) ไม่ทำ endoscopic detorsion; จะถูกถ้าห่วงที่โป่งเริ่มจากด้านขวาล่าง",
    "Small bowel obstruction: ลำไส้เล็กโป่งอยู่<b>กลางช่องท้อง</b> หลายห่วง เห็น valvulae conniventes พาดเต็มความกว้าง เส้นผ่านศูนย์กลาง &gt;3 cm air-fluid levels แบบขั้นบันได และลำไส้ใหญ่แฟบ; จะถูกถ้าเห็นลำไส้เล็กโป่งหลายห่วงโดยไม่มีลำไส้ใหญ่ขยาย",
    "Paralytic ileus: ลำไส้เล็กและใหญ่<b>โป่งทั่ว ๆ ไปอย่างสม่ำเสมอ</b> มีลมถึง rectum ไม่มี transition point มักพบหลังผ่าตัด electrolyte ผิดปกติ หรือยา opioid; จะถูกถ้าทั้งลำไส้เล็กและใหญ่ขยายเท่า ๆ กันและมีลมใน rectum",
    "Toxic megacolon: transverse colon โป่ง <b>&gt;6 cm</b> ร่วมกับ colitis (UC, C. difficile) และ systemic toxicity (ไข้ หัวใจเต้นเร็ว WBC สูง) ผนังลำไส้บวม เห็น thumbprinting; จะถูกถ้าโจทย์ให้ bloody diarrhea และอาการ toxic"],
  trap:"เห็นห่วงลำไส้ใหญ่โป่งแล้วตอบ cecal volvulus หรือ pseudo-obstruction — ให้ดูว่าห่วงโป่ง<b>เริ่มจาก pelvis</b> (sigmoid) หรือจาก RLQ (cecum); sigmoid volvulus ห่วงขึ้นไปสูงจน apex อยู่ใต้ diaphragm ซ้ายเหนือ transverse colon ได้",
  summary:["Sigmoid volvulus พบบ่อยที่สุดของ colonic volvulus — ผู้สูงอายุ, ท้องผูกเรื้อรัง, โรคระบบประสาท (Parkinson, dementia), ผู้ป่วยในสถานพักฟื้น, Chagas disease; อาการ: ปวดท้อง ท้องอืดมาก obstipation",
    "Plain film: ห่วงลำไส้ใหญ่โป่งรูป U กลับหัวไม่มี haustra เริ่มจาก pelvis (<b>coffee bean / bent inner tube</b>), apex ใต้ diaphragm ซ้ายเหนือ transverse colon (northern exposure sign); CT: <b>whirl sign</b> ของ mesentery, bird's beak; contrast enema: bird's beak",
    "ไม่มี peritonitis หรือ ischemia → <b>endoscopic detorsion</b> (flexible sigmoidoscopy ประเมิน mucosa ได้) + ใส่ rectal tube → ตามด้วย <b>elective sigmoidectomy ใน admission เดียวกัน</b> เพราะ recurrence หลัง detorsion อย่างเดียวสูงมาก (ราวครึ่งหนึ่งขึ้นไป)",
    "มี peritonitis, perforation, หรือ mucosa ขาดเลือด/gangrene จากการส่องกล้อง → ผ่าตัดฉุกเฉิน sigmoidectomy (มักเป็น <b>Hartmann procedure</b>); ไม่ detorse ลำไส้ที่ตายแล้วก่อนตัดเพื่อลดการปล่อย toxin",
    "Cecal volvulus: ห่วงโป่งจาก RLQ ไป LUQ, ผู้ป่วยอายุน้อยกว่า; รักษาด้วย <b>right hemicolectomy</b> (ไม่แนะนำ endoscopic detorsion; cecopexy recurrence สูง)",
    "แยกจาก Ogilvie (acute colonic pseudo-obstruction): ลำไส้ใหญ่ขยายโดยไม่มีจุดอุดตันจริง cecum &gt;12 cm เสี่ยงแตก → แก้ electrolyte, neostigmine, colonoscopic decompression",
    "ดูข้อ 53, 35, 54 (bowel obstruction และ plain abdomen)"],
  notes:"แถว Small bowel and Small bowel obstruction 1 ในไฟล์เฉลยมีแต่ <b>\"A\"</b> ไม่มีคำอธิบาย<br>ไฟล์โจทย์: ต้นฉบับมีแค่ \"A plain X-ray was given, what is the diagnosis?\" + รูป plain abdomen และผู้จดใส่ช้อยเดียว \"A. Sigmoid volvulus\" — ไม่มีประวัติผู้ป่วย; เราเติมอาการลำไส้อุดตัน (ปวดท้อง ท้องอืดมาก obstipation) ใน stem โดยไม่บอกชื่อ sign<br>ช้อย B–E เราแต่งเพิ่ม<br>รูปที่ใช้ครอปจากรูปที่ฝังในไฟล์โจทย์ (ไม่มีลูกศรหรือข้อความกำกับ)",
  mnemonic:"<b>Sigmoid ขึ้นจาก pelvis → ส่องกล้องคลายบิดแล้วตัด · Cecum ขึ้นจาก RLQ → ผ่าตัดเลย</b>",
  guide:"ASCRS Clinical Practice Guidelines for Colon Volvulus and Acute Colonic Pseudo-Obstruction 2021; WSES sigmoid volvulus guidelines 2023",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง — ภาพเป็นห่วง sigmoid โป่งขึ้นจาก pelvis แบบ bent inner tube; ต้นฉบับไม่มีประวัติจึงเติมอาการลำไส้อุดตันกว้าง ๆ ซึ่งไม่ใบ้คำตอบเพราะทุกช้อยมีอาการท้องอืดได้",
  variants:["ชายอายุ 80 ปี ติดเตียงจาก Parkinson ท้องอืดมาก 2 วัน ไม่มี peritonitis plain film เป็นรูป coffee bean ขึ้นจาก pelvis การรักษาขั้นแรกคือ → flexible sigmoidoscopic detorsion + rectal tube แล้วนัด sigmoidectomy ใน admission เดียวกัน",
    "ผู้ป่วย sigmoid volvulus ส่องกล้องพบ mucosa สีดำ มีไข้และ guarding การรักษาคือ → emergency laparotomy, sigmoidectomy แบบ Hartmann procedure",
    "หญิงอายุ 35 ปี ปวดท้องอืดเฉียบพลัน plain film เห็นห่วงลำไส้ใหญ่โป่งรูปไตอยู่ LUQ ลำไส้เล็กโป่งร่วม → cecal volvulus รักษาด้วย right hemicolectomy"]}),
A({page:11, page2:5, orig:"Small bowel 2",
  stem:"A patient with valvular heart disease presents with acute abdominal pain. The pulse is irregular, and rectal examination reveals blood. What is the most likely diagnosis?",
  gray:"A patient with underlying valvular heart disease, presented with abdominal pain, PE: irregular pulse, PR: blood, what is the diagnosis? — A. Acute mesenteric thrombosis B. Acute mesenteric embolism",
  opts:["Acute mesenteric arterial thrombosis","Acute mesenteric embolism","Mesenteric venous thrombosis","Nonocclusive mesenteric ischemia","Ischemic colitis"],
  ans:1, key:"B Acute mesenteric embolism"+KS,
  interp:"ปวดท้องเฉียบพลันในผู้ป่วยโรคลิ้นหัวใจ + <b>ชีพจรไม่สม่ำเสมอ</b> (atrial fibrillation) + PR มีเลือด (ลำไส้ขาดเลือดจน mucosa หลุด) → ต้องคิดถึง acute mesenteric ischemia และแยกกลไกจากแหล่งที่มาของลิ่มเลือด",
  why:"<b>Acute mesenteric embolism</b> เป็นสาเหตุที่พบบ่อยที่สุดของ AMI (~40–50%) — ลิ่มเลือดจาก<b>หัวใจ</b> (AF, valvular heart disease, mural thrombus หลัง MI, endocarditis) หลุดไปอุด <b>SMA</b> ซึ่งออกจาก aorta เป็นมุมแหลม มักติดที่ 3–10 cm จาก origin ใต้ต่อแขนง middle colic → proximal jejunum และ transverse colon ส่วนต้นมักรอด; อาการเกิด<b>เฉียบพลันทันที</b> ปวดรุนแรงไม่สัมพันธ์กับการตรวจร่างกาย (pain out of proportion) อาจมีอาเจียนและถ่ายทันที ระยะหลังมี bloody stool, peritonitis — ผู้ป่วยรายนี้มีทั้งแหล่งลิ่มเลือด (valvular disease + AF) และอาการ",
  wrong:["Acute mesenteric arterial thrombosis (~25%) เกิดบน<b>คราบ atherosclerosis</b> ที่ origin ของ SMA — มักมีประวัติ <b>intestinal angina</b> (ปวดท้องหลังอาหาร กลัวการกิน น้ำหนักลด) และ atherosclerosis ที่อื่น ลำไส้ขาดเลือดกว้างกว่า (ตั้งแต่ proximal jejunum); จะถูกถ้าโจทย์ให้ชายสูงอายุสูบบุหรี่ มีปวดท้องหลังอาหารและน้ำหนักลดมาหลายเดือน",
    "Mesenteric venous thrombosis (~5–10%) — ผู้ป่วยมีภาวะ <b>hypercoagulable</b> (OCP, protein C/S deficiency, malignancy, polycythemia), portal hypertension, pancreatitis อาการค่อยเป็นค่อยไปหลายวัน; รักษาด้วย anticoagulation; จะถูกถ้าโจทย์ให้หญิงกินยาคุมมีปวดท้องหลายวัน CT เห็น SMV thrombus",
    "NOMI (~20%) เกิดจาก <b>low-flow state</b> + vasospasm โดยไม่มีสิ่งอุดตัน — shock, heart failure, vasopressor, digoxin, หลังผ่าตัดหัวใจ, dialysis; angiography เห็น SMA แขนงตีบเป็นช่วง ๆ (string of sausages) รักษาด้วยแก้สาเหตุ + intra-arterial papaverine; จะถูกถ้าโจทย์เป็นผู้ป่วย ICU ใช้ vasopressor ขนาดสูง",
    "Ischemic colitis — ขาดเลือดของลำไส้ใหญ่ (watershed: splenic flexure, rectosigmoid) มัก<b>ไม่รุนแรง</b> ปวดท้องด้านซ้ายแบบบีบ + bloody diarrhea ใน 24 ชม. ส่วนใหญ่หายด้วย supportive care; จะถูกถ้าโจทย์ให้ผู้สูงอายุปวดท้องซ้ายเล็กน้อยแล้วถ่ายเป็นเลือดหลังภาวะความดันต่ำ"],
  trap:"เห็น PR มีเลือดแล้วตอบ ischemic colitis — แต่ประวัติ<b>โรคลิ้นหัวใจ + ชีพจรไม่สม่ำเสมอ</b> คือแหล่งลิ่มเลือดจากหัวใจ ชี้ไปที่ embolism ของ SMA; bloody stool ใน AMI เป็นอาการระยะท้ายที่บ่งว่า mucosa ตายแล้ว",
  summary:["AMI แบ่งเป็น: <b>arterial embolism</b> (~40–50%), arterial thrombosis (~25%), NOMI (~20%), mesenteric venous thrombosis (~5–10%)",
    "Embolism: แหล่งจากหัวใจ (AF, valvular, post-MI, endocarditis) → SMA ห่างจาก origin ใต้ middle colic, เริ่มเฉียบพลัน, pain out of proportion; thrombosis: ที่ origin, มี chronic mesenteric ischemia นำมาก่อน",
    "Lab: leukocytosis, lactate สูง, metabolic acidosis (ไม่ไวพอที่จะใช้ตัดโรค); <b>CTA</b> เป็น investigation แรกที่ควรทำทันทีเมื่อสงสัย",
    "รักษา: resuscitation, <b>heparin ทันที</b>, broad-spectrum antibiotics → revascularization (open embolectomy ผ่าน transverse arteriotomy ของ SMA หรือ endovascular aspiration/thrombolysis/stent ในรายเลือกได้) → ประเมิน viability ตัดลำไส้ที่ตาย, damage control + <b>second-look</b> ใน 24–48 ชม.",
    "Peritonitis หรือสงสัยลำไส้ตาย → ผ่าตัด (laparotomy) เสมอ; หลังรักษาให้ anticoagulation ระยะยาวในผู้ป่วย AF",
    "MVT: anticoagulation เป็นหลัก ผ่าตัดเมื่อมีลำไส้ตาย; NOMI: แก้ low flow, หยุด vasoconstrictor, papaverine ทาง SMA",
    "ดูข้อ 61, 59 (vascular: embolism จาก AF)"],
  notes:"แถว Small bowel and Small bowel obstruction 2 ในไฟล์เฉลยมีแต่ <b>\"B\"</b> ไม่มีคำอธิบาย<br>ไฟล์โจทย์: มีช้อย A \"Acute mesenteric thrombosis\" และ B \"Acute mesenteric embolism\"; ช้อย C–E เราแต่งเพิ่ม; ช้อย A เติมคำว่า arterial เพื่อแยกจาก venous thrombosis",
  mnemonic:"<b>AF + ปวดท้องรุนแรงแต่ท้องนุ่ม = SMA embolus จนกว่าจะพิสูจน์ได้ว่าไม่ใช่</b>",
  guide:"ESVS Clinical Practice Guidelines on the Management of Diseases of Mesenteric Arteries and Veins 2017; WSES guidelines for acute mesenteric ischemia 2022",
  opinion:"เห็นด้วยกับคีย์ B มั่นใจสูง; สอดคล้องกับข้อสอบชุด 76C (AMI กับชีพจรไม่สม่ำเสมอ) และ 77D (embolus ใน SMA)",
  variants:["หญิงอายุ 75 ปี มี AF ไม่ได้กินยาต้านการแข็งตัวของเลือด ปวดท้องรุนแรงเฉียบพลัน 3 ชั่วโมง ท้องนุ่ม lactate 4 mmol/L investigation ที่ควรทำคือ → CT angiography และเริ่ม heparin",
    "ชายอายุ 68 ปี สูบบุหรี่ ปวดท้องหลังอาหาร 30 นาทีมา 6 เดือน กลัวการกิน น้ำหนักลด 8 kg วันนี้ปวดท้องรุนแรงต่อเนื่อง → acute-on-chronic mesenteric arterial thrombosis ที่ origin ของ SMA"]}),
A({page:12, page2:5, orig:"Liver 1",
  stem:"A previously healthy patient has fever and right upper quadrant pain. He is hemodynamically stable. Ultrasound shows a thickened gallbladder wall with gas within the gallbladder wall. What is the most appropriate management?",
  gray:"A patient with fever + RUQ pain, abdominal U/S shows thickened gallbladder wall and gas in gallbladder wall, what is the management? — A. IV antibiotics + elective cholecystectomy in 1-2 weeks B. IV antibiotics + urgent cholecystectomy",
  opts:["IV antibiotics and elective cholecystectomy in 1–2 weeks","IV antibiotics and urgent cholecystectomy","Oral antibiotics and outpatient follow-up","ERCP with sphincterotomy","Observation without antibiotics"],
  ans:1, key:"\"?\" — คำอธิบายในคีย์: Class 2 TG18 &gt;&gt; Early LC (ตรงกับช้อย B IV antibiotics + urgent cholecystectomy)"+KS,
  flag:"⚠ คีย์ใส่ \"?\" แทนตัวอักษร แต่คำอธิบาย (TG18 grade II → early LC) ตรงกับ B; เติม previously healthy, stable ใน stem",
  interp:"Acute cholecystitis (ไข้ + ปวด RUQ + ผนังถุงน้ำดีหนา) ที่มี<b>ลมในผนังถุงน้ำดี</b> — ต้องประเมินความรุนแรงตาม TG18 แล้วเลือก timing ของ cholecystectomy; stem ระบุว่าผู้ป่วยแข็งแรงดีและ stable (ไม่มี organ dysfunction และผ่าตัดได้)",
  why:"ลมในผนังถุงน้ำดีจากเชื้อสร้างก๊าซ (Clostridium, E. coli, Klebsiella) = <b>marked local inflammation</b> ซึ่งจัดเป็น <b>TG18 grade II (moderate)</b> — เกณฑ์ grade II ข้อใดข้อหนึ่ง: WBC &gt;18,000/mm³, คลำได้ก้อนกดเจ็บที่ RUQ, อาการ &gt;72 ชม., หรือ marked local inflammation (gangrenous, <b>emphysematous</b> cholecystitis, pericholecystic abscess, hepatic abscess, biliary peritonitis); TG18 แนะนำ <b>early laparoscopic cholecystectomy</b> ใน grade II เมื่อผู้ป่วยพร้อม (CCI ≤5 และ ASA-PS ≤2) และศัลยแพทย์ชำนาญ ร่วมกับ <b>IV antibiotics</b> ครอบคลุม gram-negative และ anaerobe — เพราะถุงน้ำดีชนิดนี้เสี่ยง gangrene และ perforation สูงกว่า cholecystitis ทั่วไปหลายเท่า (ตรงกับคำอธิบายในคีย์ \"Class 2 TG18 &gt;&gt; Early LC\")",
  wrong:["การรอผ่าตัดแบบ elective หลังให้ยาฆ่าเชื้อ (delayed cholecystectomy มักรอ 6–12 สัปดาห์ ไม่ใช่ 1–2 สัปดาห์ซึ่งเป็นช่วงที่การอักเสบหนาแน่นผ่าตัดยากที่สุด) <b>ไม่เหมาะกับ emphysematous cholecystitis</b> ที่เสี่ยง gangrene/perforation ระหว่างรอ; จะถูกถ้าผู้ป่วยมาช้าหรือเสี่ยงสูง ผ่าตัดเร็วไม่ได้ และตอบสนองต่อยาฆ่าเชื้อดี (แต่ grade II ที่ไม่ fit มักต้องทำ gallbladder drainage ร่วม)",
    "ยาฆ่าเชื้อชนิดกินและนัดติดตามแบบผู้ป่วยนอก <b>ไม่เพียงพอ</b>สำหรับ acute cholecystitis ที่มีไข้และ marked local inflammation ต้องรับไว้ในโรงพยาบาล; จะ \"ใกล้เคียง\" เฉพาะการให้ยาต่อหลังผ่าตัดในบางราย หรือ biliary colic ที่ไม่มีการอักเสบ (ไม่ต้องให้ยาฆ่าเชื้อ)",
    "ERCP with sphincterotomy ใช้ระบายท่อน้ำดีใน <b>choledocholithiasis หรือ acute cholangitis</b> — โจทย์ไม่มี jaundice หรือท่อน้ำดีขยาย และ ERCP ไม่ได้รักษาการติดเชื้อในผนังถุงน้ำดี; จะถูกถ้าโจทย์ให้ไข้ jaundice ปวด RUQ และ CBD ขยาย/เห็นนิ่วใน CBD",
    "การสังเกตอาการโดยไม่ให้ยาฆ่าเชื้อไม่เหมาะ — ผู้ป่วยมีไข้และติดเชื้อชนิดสร้างก๊าซ เสี่ยง sepsis และ perforation; การไม่ให้ยาฆ่าเชื้อ (หรือให้สั้น) ใช้ได้กับ <b>biliary colic</b> หรือหลังผ่าตัด cholecystitis grade I–II ที่เอาแหล่งติดเชื้อออกแล้ว"],
  trap:"เห็นคำว่า \"IV antibiotics + elective\" แล้วคิดว่าปลอดภัยกว่า — ใน TG18 ทั้ง grade I และ II ที่ผู้ป่วยพร้อมผ่าตัด แนะนำ <b>early LC</b> (ภายใน 72 ชม.หลังรับไว้หรือเร็วที่สุด) โดยเฉพาะ emphysematous ที่เสี่ยง perforation สูง",
  summary:["TG18 diagnosis acute cholecystitis: A local inflammation (Murphy sign, RUQ mass/pain/tenderness) + B systemic inflammation (ไข้, CRP สูง, WBC สูง) + C imaging (US: ผนังหนา &gt;4–5 mm, pericholecystic fluid, sonographic Murphy, นิ่วติดคอถุงน้ำดี)",
    "TG18 grading: <b>grade III</b> = organ dysfunction (cardiovascular, neurological, respiratory, renal, hepatic, hematologic); <b>grade II</b> = WBC &gt;18,000, คลำได้ก้อน, อาการ &gt;72 ชม., หรือ marked local inflammation (gangrenous, emphysematous, abscess, biliary peritonitis); <b>grade I</b> = ไม่เข้าเกณฑ์ข้างต้น",
    "การรักษา: grade I → early LC; grade II → <b>early LC</b> ถ้า CCI ≤5 และ ASA-PS ≤2 และศัลยแพทย์ชำนาญ ไม่เช่นนั้น antibiotics ± gallbladder drainage แล้วผ่าตัดภายหลัง; grade III → แก้ organ dysfunction, early LC ในศูนย์ที่พร้อมและผู้ป่วยเข้าเกณฑ์ ไม่เช่นนั้น urgent/early gallbladder drainage",
    "<b>Emphysematous cholecystitis</b>: ผู้ชาย สูงอายุ <b>เบาหวาน</b> (ราวครึ่งหนึ่ง), acalculous ได้บ่อยกว่าปกติ, เชื้อ Clostridium perfringens, E. coli, Klebsiella; US: echogenic line ในผนังมี dirty shadowing, CT ไวที่สุดในการเห็นลม; เสี่ยง gangrene และ perforation สูง",
    "Antibiotics: ครอบคลุม Enterobacteriaceae + anaerobe (เช่น ceftriaxone + metronidazole, piperacillin-tazobactam); หลังเอาถุงน้ำดีออกใน grade I–II ให้ยาต่อไม่เกิน 24 ชม. (ยกเว้นมี perforation หรือ abscess)",
    "ผู้ป่วยไม่ fit ต่อการผ่าตัด → percutaneous transhepatic gallbladder drainage (PTGBD) หรือ endoscopic transpapillary/EUS-guided drainage",
    "ดูข้อ 29, 31, 34 (gallbladder และ biliary)"],
  notes:"แถว Liver + Jaundice 1 ในไฟล์เฉลย: คำตอบพิมพ์ว่า <b>\"?\"</b> และคำอธิบาย <b>\"Class 2 TG18 &gt;&gt; Early LC\"</b> (ผู้เฉลยไม่ใส่ตัวอักษร แต่คำอธิบายชี้ไปที่ early laparoscopic cholecystectomy = ช้อย B)<br>ไฟล์โจทย์: มีช้อย A \"IV antibiotics + elective cholecystectomy in 1-2 weeks\" และ B \"IV antibiotics + urgent cholecystectomy\"; ช้อย C–E เราแต่งเพิ่ม<br>เราเติมใน stem ว่า <b>previously healthy</b> และ <b>hemodynamically stable</b> (ต้นฉบับไม่ได้บอก) เพื่อให้ผู้ป่วยเข้าเกณฑ์ผ่าตัดเร็วได้ตาม TG18",
  mnemonic:"",
  guide:"Tokyo Guidelines 2018 (TG18)",
  opinion:"เห็นด้วยกับเจตนาของคีย์ (TG18 grade II → early LC = ช้อย B) มั่นใจสูง — คีย์ใส่ \"?\" แทนตัวอักษรแต่คำอธิบายชัดเจน; ต้นฉบับไม่ได้บอกโรคประจำตัวหรือสภาพผู้ป่วย ถ้าผู้ป่วยมี comorbidity มาก (CCI ≥6 หรือ ASA-PS ≥3) TG18 จะแนะนำ antibiotics ± gallbladder drainage แล้วผ่าตัดภายหลังแทน ซึ่งไม่ตรงกับช้อย A ที่รอ 1–2 สัปดาห์โดยไม่ระบายอยู่ดี — จึงเติม previously healthy, stable ใน stem; สอดคล้องกับข้อสอบชุด 76A (ลมในผนังถุงน้ำดี → emergency cholecystectomy)",
  variants:["ชายอายุ 65 ปี เบาหวาน ไข้ ปวด RUQ 2 วัน CT เห็นลมในผนังและในถุงน้ำดี ความดันปกติ creatinine ปกติ ASA-PS 2 การรักษาคือ → IV antibiotics ครอบคลุม anaerobe + early laparoscopic cholecystectomy",
    "หญิงอายุ 88 ปี heart failure รุนแรง (ASA-PS 4) มี acute cholecystitis grade II ไม่ดีขึ้นหลังให้ยาฆ่าเชื้อ 24 ชม. → percutaneous transhepatic gallbladder drainage แล้วพิจารณาผ่าตัดภายหลัง"]}),
A({page:12, page2:5, orig:"Liver 2",
  img:QI(29), imgNote:"Ultrasound of the right upper quadrant; a yellow arrow points to a structure (ผู้จดบอกว่าในข้อสอบจริงมี label GB, CBD)",
  stem:"A patient has fever, jaundice and right upper quadrant pain. The abdominal ultrasound is shown. What is the most appropriate management?",
  gray:"A patient with fever + jaundice + RUQ pain, abdominal U/S as shown (ในรูป label GB, CBD ให้), what is the management? [รูป US มีลูกศรเหลือง] — A. ERCP",
  opts:["ERCP with stone extraction","Emergency open common bile duct exploration","Laparoscopic cholecystectomy alone","Percutaneous cholecystostomy","IV antibiotics and oral ursodeoxycholic acid"],
  ans:0, key:"A ERCP"+KS,
  interp:"ไข้ + jaundice + ปวด RUQ = <b>Charcot triad</b> และ US เห็นสิ่งผิดปกติในท่อน้ำดี (ลูกศรชี้) — ต้องวินิจฉัยสาเหตุจากภาพแล้วเลือกวิธี<b>ระบายท่อน้ำดี</b>ที่เหมาะสม",
  why:"ภาพ US: ท่อน้ำดี (CBD) ขยาย และลูกศรชี้ <b>echogenic focus ภายใน CBD</b> มีเงาด้านหลัง = นิ่วในท่อน้ำดี → <b>acute cholangitis จาก choledocholithiasis</b>; การรักษาคือ resuscitation + IV antibiotics + <b>biliary drainage</b> โดย <b>ERCP</b> (endoscopic sphincterotomy + stone extraction หรือใส่ stent/nasobiliary drain ถ้าผู้ป่วยหนักหรือ coagulopathy) เป็นวิธีแรกตาม TG18 เพราะ morbidity/mortality ต่ำกว่าการผ่าตัดและ PTBD; timing: grade III ระบายเร่งด่วนหลัง stabilize, grade II ระบายเร็ว (early), grade I ระบายถ้าไม่ตอบสนองต่อยาใน 24 ชม. — จากนั้นทำ cholecystectomy ใน admission เดียวกันหรือเร็วที่สุดเพื่อป้องกันการกลับเป็นซ้ำ",
  wrong:["Open CBD exploration ฉุกเฉินในผู้ป่วยที่มี sepsis จาก cholangitis มี <b>mortality สูงกว่า</b> endoscopic drainage อย่างชัดเจน; จะถูกถ้า ERCP ล้มเหลวหรือทำไม่ได้ (เช่น หลัง Roux-en-Y, นิ่วใหญ่มาก) และ PTBD ทำไม่ได้ หรือทำร่วมกับ cholecystectomy แบบ elective ในผู้ป่วยไม่ติดเชื้อ",
    "LC อย่างเดียวเอาถุงน้ำดีออกแต่<b>ไม่ได้เอานิ่วใน CBD ออก</b>และไม่ได้ระบายท่อน้ำดีที่ติดเชื้อ; จะถูกถ้าเป็น acute cholecystitis ที่ไม่มีนิ่วใน CBD หรือทำ LC ร่วมกับ laparoscopic CBD exploration ในผู้ป่วยไม่ septic ที่ศูนย์ชำนาญ",
    "Percutaneous cholecystostomy ระบาย<b>ถุงน้ำดี</b> ใช้ใน acute cholecystitis ที่ผู้ป่วยไม่ fit ต่อการผ่าตัด — ไม่ระบาย CBD ได้เชื่อถือ (cystic duct มักอุดตัน); วิธีระบายทางผิวหนังที่ใช้ใน cholangitis เมื่อ ERCP ไม่ได้คือ <b>PTBD</b>; จะถูกถ้าโจทย์เป็น acute cholecystitis ในผู้ป่วยเสี่ยงสูง",
    "IV antibiotics จำเป็นแต่<b>ไม่พอ</b>ถ้าไม่ระบายท่อน้ำดี; ursodeoxycholic acid ใช้ละลายนิ่ว cholesterol ขนาดเล็กในถุงน้ำดีที่ทำงานดีหรือป้องกันนิ่วหลัง bariatric surgery ไม่มีบทบาทใน cholangitis จากนิ่วอุด CBD; จะถูกถ้าเป็นนิ่วถุงน้ำดีขนาดเล็กไม่มีอาการรุนแรงในผู้ที่ผ่าตัดไม่ได้"],
  trap:"เลือก cholecystostomy เพราะเห็นว่าเป็นการระบายแบบ minimal — ต้องแยก<b>ระบายถุงน้ำดี</b> (cholecystitis) กับ<b>ระบายท่อน้ำดี</b> (cholangitis: ERCP หรือ PTBD); และอย่าลืมว่า cholangitis ต้องระบายท่อ ไม่ใช่แค่ให้ยาฆ่าเชื้อ",
  summary:["Acute cholangitis: Charcot triad (ไข้ jaundice ปวด RUQ) — sensitivity ต่ำ; Reynolds pentad เพิ่ม shock + สับสน; สาเหตุบ่อย: นิ่วใน CBD, malignant stricture, stent อุดตัน",
    "TG18 diagnosis: A systemic inflammation (ไข้ &gt;38 °C หรือหนาวสั่น, lab อักเสบ) + B cholestasis (bilirubin ≥2 mg/dL, LFT &gt;1.5 เท่าของค่าปกติ) + C imaging (ท่อน้ำดีขยาย หรือเห็นสาเหตุ: นิ่ว stricture stent)",
    "TG18 grading: <b>III</b> organ dysfunction; <b>II</b> มี ≥2 ข้อ: WBC &gt;12,000 หรือ &lt;4,000, ไข้ ≥39 °C, อายุ ≥75, bilirubin ≥5 mg/dL, albumin ต่ำ (&lt;0.7 เท่าของค่าปกติต่ำสุด); <b>I</b> ไม่เข้าเกณฑ์",
    "รักษา: fluid, IV antibiotics (gram-negative + anaerobe ตามความรุนแรง), blood culture; drainage — grade III urgent หลัง stabilize, grade II early, grade I ถ้าไม่ตอบสนองใน 24 ชม.",
    "วิธีระบาย: <b>ERCP</b> (sphincterotomy + stone extraction, หรือ stent/ENBD ในรายหนัก) เป็นอันดับแรก → EUS-guided drainage หรือ <b>PTBD</b> เมื่อ ERCP ไม่สำเร็จ → open surgery เป็นทางสุดท้าย",
    "หลังหายจาก cholangitis จากนิ่ว → cholecystectomy (ใน admission เดียวกันในรายไม่รุนแรง) เพื่อลดการกลับเป็นซ้ำ",
    "ดูข้อ 28, 31, 34 (biliary และ jaundice work-up)"],
  notes:"แถว Liver + Jaundice 2 ในไฟล์เฉลยมีแต่ <b>\"A\"</b> ไม่มีคำอธิบาย<br>ไฟล์โจทย์: ผู้จดใส่ช้อยเดียว \"A. ERCP\" และโน้ตผู้จดในโจทย์ <b>\"(ในรูป label GB, CBD ให้)\"</b> — รูปที่ผู้จดแปะในไฟล์มีแค่ลูกศรสีเหลือง ไม่มี label GB หรือ CBD<br>ช้อย A เติมคำว่า \"with stone extraction\"; ช้อย B–E เราแต่งเพิ่ม",
  mnemonic:"<b>Cholecystitis → เอาถุงออก/ระบายถุง · Cholangitis → ระบายท่อ (ERCP)</b>",
  guide:"Tokyo Guidelines 2018 (TG18); ASGE guideline on the management of choledocholithiasis 2019",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง; สอดคล้องกับข้อสอบชุด 76A และ 77A ที่ถาม cholangitis และ ERCP",
  variants:["หญิงอายุ 70 ปี ไข้ หนาวสั่น ตัวเหลือง สับสน ความดัน 80/50 mmHg หลังให้สารน้ำแล้ว ใช้ norepinephrine อยู่ US เห็น CBD 12 mm มีนิ่ว การรักษาคือ → resuscitation + IV antibiotics + urgent ERCP drainage (grade III)",
    "ผู้ป่วยเคยผ่าตัด Roux-en-Y gastric bypass มี cholangitis จากนิ่วใน CBD ทำ ERCP ทั่วไปไม่ได้ วิธีระบายที่เหมาะคือ → PTBD (หรือ enteroscopy-assisted/laparoscopy-assisted ERCP ในศูนย์ชำนาญ)"]}),
A({page:12, page2:5, orig:"Liver 3",
  img:QI(30), imgNote:"Liver ultrasound with two arrows pointing to a lesion",
  stem:"An asymptomatic patient is positive for HBsAg and anti-HCV. The liver ultrasound is shown. Which of the following should NOT be done?",
  gray:"A patient with HBsAg+, anti-HCV+, abdominal U/S as shown, which of the following should not be done? [รูป US ตับ อยู่ต้นหน้า 13] — A. Discuss anti-viral therapy B. Unroof the cyst",
  opts:["Discuss antiviral therapy","Unroof the cyst","Check HBV DNA and HCV RNA","HCC surveillance with ultrasound every 6 months","Assess the degree of liver fibrosis"],
  ans:1, key:"B Unroof the cyst"+KS,
  interp:"ผู้ป่วยไม่มีอาการ ติดเชื้อ <b>HBV ร่วมกับ HCV</b> และ US ตับพบรอยโรค — ถามสิ่งที่<b>ไม่ควรทำ</b>: ต้องอ่านภาพว่ารอยโรคคืออะไรต้องรักษาหรือไม่ และรู้ว่าการดูแล HBV/HCV coinfection ประกอบด้วยอะไรบ้าง",
  why:"ภาพ US: ก้อน<b>ไม่มีเสียงสะท้อน (anechoic)</b> ขอบเรียบ ผนังบางจนมองไม่เห็น ไม่มี septum หรือ nodule และมี <b>posterior acoustic enhancement</b> (ลูกศรล่างชี้บริเวณที่สว่างขึ้นหลังก้อน) = <b>simple hepatic cyst</b> — พบบ่อย ไม่กลายเป็นมะเร็ง ถ้า<b>ไม่มีอาการไม่ต้องรักษาและไม่ต้องติดตาม</b>; การ unroof/fenestration ทำเฉพาะ cyst ขนาดใหญ่ที่<b>มีอาการ</b> (ปวด แน่นท้อง อิ่มเร็ว กดเบียด) หรือมีภาวะแทรกซ้อน — การผ่าตัดในผู้ป่วยรายนี้จึงไม่ควรทำ ส่วนช้อยอื่นเป็นการดูแล HBV/HCV coinfection ที่ควรทำทั้งหมด",
  wrong:["<b>ควรทำ</b>: HBV/HCV coinfection ควรได้รับการพิจารณารักษา — HCV รักษาด้วย DAA (sustained virologic response &gt;95%) และต้องเฝ้าระวัง <b>HBV reactivation</b> ระหว่าง/หลัง DAA (ให้ nucleos(t)ide analog เป็น prophylaxis หรือรักษาตามเกณฑ์ HBV); จะเป็นคำตอบถ้าโจทย์ถามสิ่งที่ควรหลีกเลี่ยงในผู้ป่วยที่มี decompensated cirrhosis บางราย (เช่น protease inhibitor)",
    "<b>ควรทำ</b>: ตรวจ HBV DNA, HBeAg, ALT และ HCV RNA เพื่อดูว่าไวรัสตัวไหน active (มักมีตัวหนึ่งเด่น) — anti-HCV บวกบอกแค่เคยสัมผัสเชื้อ ต้องยืนยันการติดเชื้อปัจจุบันด้วย HCV RNA",
    "<b>ควรทำ</b>: ผู้ป่วยกลุ่มเสี่ยง (cirrhosis, HBV carrier ชายอายุ &gt;40 ปี/หญิง &gt;50 ปีในเอเชีย, ประวัติครอบครัว HCC) ควรตรวจ <b>US ± AFP ทุก 6 เดือน</b> — coinfection เพิ่มความเสี่ยง HCC มากกว่าติดเชื้อตัวเดียว",
    "<b>ควรทำ</b>: ประเมิน fibrosis ด้วย transient elastography (FibroScan), APRI หรือ FIB-4 เพื่อกำหนดการรักษา ระยะเวลา และความจำเป็นของ HCC/varices surveillance"],
  trap:"คิดว่าก้อนในตับของผู้ป่วยไวรัสตับอักเสบต้องจัดการทุกครั้ง — ต้อง<b>อ่านภาพก่อน</b>: anechoic + posterior enhancement + ผนังบาง = simple cyst ไม่ต้องทำอะไร; ก้อน solid ในตับแข็งต่างหากที่ต้องคิดถึง HCC และทำ multiphase CT/MRI",
  summary:["Simple hepatic cyst: พบได้ราว 2.5–18% ของประชากร, หญิงมากกว่าชาย; US: anechoic, ผนังบางมองไม่เห็น, ขอบเรียบ, <b>posterior acoustic enhancement</b>, ไม่มี septum/nodule/flow",
    "ไม่มีอาการ → <b>ไม่ต้องรักษาและไม่ต้องติดตาม</b>; มีอาการ (มักขนาด &gt;5–10 cm) → <b>laparoscopic deroofing (fenestration)</b> หรือ aspiration sclerotherapy; aspiration อย่างเดียว recurrence สูงเกือบทั้งหมด",
    "แยกจาก mucinous cystic neoplasm (biliary cystadenoma: septum หนา, nodule, มักในหญิงวัยกลางคน → ผ่าตัดเอาออกทั้งหมด), hydatid cyst (daughter cysts, ผนังมี calcification), abscess (ไข้, ผนังหนา, debris), polycystic liver disease",
    "HBV/HCV coinfection: ตรวจ HBV DNA, HBeAg, ALT, HCV RNA; ประเมิน fibrosis (FibroScan, APRI, FIB-4)",
    "รักษา HCV ด้วย <b>DAA</b> (pangenotypic เช่น sofosbuvir/velpatasvir) — ผู้ที่ HBsAg บวกเสี่ยง <b>HBV reactivation</b> ระหว่าง DAA → ให้ nucleos(t)ide analog (entecavir, tenofovir) ตามเกณฑ์ HBV หรือเป็น prophylaxis และติดตาม HBV DNA",
    "HCC surveillance: US ± AFP ทุก 6 เดือนใน cirrhosis ทุกราย และ HBV carrier กลุ่มเสี่ยงแม้ไม่มี cirrhosis",
    "ดูข้อ 32, 33 (liver)"],
  notes:"แถว Liver + Jaundice 3 ในไฟล์เฉลยมีแต่ <b>\"B\"</b> ไม่มีคำอธิบาย<br>ไฟล์โจทย์: มีช้อย A \"Discuss anti-viral therapy\" และ B \"Unroof the cyst\"; ช้อย C–E (สิ่งที่ควรทำ) เราแต่งเพิ่ม; รูป US ตับอยู่ต้นหน้า 13 ของไฟล์โจทย์ (โจทย์เริ่มท้ายหน้า 12)<br>ต้นฉบับใช้คำว่า \"cyst\" ในช้อยเอง เราจึงคงไว้ในช้อย แต่ไม่ได้เขียนใน stem<br>เราเติม \"asymptomatic\" ใน stem",
  mnemonic:"<b>ดำสนิท–ขอบบาง–หลังสว่าง = simple cyst → ปล่อยไว้</b>",
  guide:"EASL Clinical Practice Guidelines on the management of benign liver tumours 2016; EASL cystic liver diseases 2022; AASLD HBV guidance 2018; EASL recommendations on treatment of hepatitis C 2020",
  opinion:"เห็นด้วยกับคีย์ B มั่นใจสูง; สอดคล้องกับข้อสอบชุด 77A (asymptomatic liver cyst — unroofing ไม่จำเป็น)",
  variants:["หญิงอายุ 50 ปี ตรวจสุขภาพพบ cyst ในตับขนาด 3 cm ลักษณะ simple cyst ไม่มีอาการ ควรทำอย่างไร → ไม่ต้องรักษาและไม่ต้องติดตาม",
    "หญิงอายุ 45 ปี แน่นท้องขวาบน อิ่มเร็ว US พบ simple cyst ขนาด 14 cm ในตับกลีบขวา การรักษาที่เหมาะคือ → laparoscopic deroofing (fenestration)",
    "ผู้ป่วย HBsAg บวก HBV DNA ต่ำ กำลังจะเริ่ม DAA รักษา HCV ควรทำอะไรเพิ่ม → ให้ nucleos(t)ide analog prophylaxis หรือติดตาม HBV DNA ระหว่างและหลังการรักษา"]}),
A({page:13, page2:5, orig:"Liver 4",
  stem:"A patient has progressive painless jaundice with pruritus, pale stools and dark urine. Which investigation provides the definitive diagnosis?",
  gray:"A patient with progressive painless jaundice, itching, pale stool, dark urine, which of the following should be done for definitive diagnosis? — A. ERCP with biopsy",
  opts:["Abdominal ultrasound","Serum CA 19-9","ERCP with brushing and biopsy","Plain abdominal radiograph","HIDA scan"],
  ans:2, key:"C ERCP with biopsy"+KS,
  flag:"⚠ เล็กน้อย: ในทางปฏิบัติทำ CT/MRCP ก่อน และถ้าเป็นก้อนที่หัวตับอ่อน EUS-FNA เป็นวิธีเก็บชิ้นเนื้อที่ดีกว่า (ไม่ได้ใส่ในช้อยเพื่อไม่ให้แข่งกับคีย์)",
  interp:"<b>Obstructive jaundice</b> แบบค่อยเป็นค่อยไปและไม่ปวด (คัน อุจจาระซีด ปัสสาวะสีเข้ม) → สงสัย<b>มะเร็งบริเวณ periampullary หรือท่อน้ำดี</b> — ถามการตรวจที่ให้ <b>definitive diagnosis</b> คือการได้ชิ้นเนื้อหรือเซลล์ยืนยันพยาธิวิทยา",
  why:"การวินิจฉัยที่แน่นอนของมะเร็งต้องได้ <b>tissue (cytology/histology)</b> — <b>ERCP</b> เห็นตำแหน่งตีบของท่อน้ำดีโดยตรง และเก็บ <b>brush cytology + intraductal biopsy</b> (± cholangioscopy-guided biopsy) ได้ในหัตถการเดียว พร้อมใส่ stent ระบายน้ำดีถ้าจำเป็น (เช่น cholangitis หรือต้องรอ neoadjuvant therapy) — ในช้อยที่ให้มา ERCP with biopsy เป็นวิธีเดียวที่ได้ชิ้นเนื้อ; ช้อยอื่นเป็นการตรวจเบื้องต้นหรือ tumor marker ที่ยืนยันมะเร็งไม่ได้",
  wrong:["Abdominal US เป็น<b>การตรวจแรก</b>ใน jaundice — แยก obstructive จาก hepatocellular ได้ด้วยการเห็นท่อน้ำดีขยาย และบอกระดับการอุดตันได้คร่าว ๆ แต่ไม่ได้ชิ้นเนื้อ และเห็นตับอ่อน/distal CBD ได้ไม่ดี; จะถูกถ้าโจทย์ถาม initial investigation",
    "CA 19-9 เป็น tumor marker ของมะเร็งตับอ่อนและท่อน้ำดี <b>ไม่ใช้วินิจฉัย</b> — สูงได้ใน cholestasis/cholangitis ที่ไม่ใช่มะเร็ง และผู้ที่ Lewis antigen negative (~5–10%) ไม่สร้าง CA 19-9 เลย; ใช้ประเมินพยากรณ์โรค resectability และติดตามหลังรักษา; จะถูกถ้าโจทย์ถาม marker ที่ใช้ติดตามการกลับเป็นซ้ำ",
    "Plain abdominal radiograph <b>ไม่มีบทบาท</b>ใน obstructive jaundice (อาจเห็น calcification ของ chronic pancreatitis หรือลมในท่อน้ำดีบ้าง); จะถูกถ้าโจทย์ถามการตรวจเบื้องต้นในผู้ป่วยสงสัย bowel obstruction หรือ perforation",
    "HIDA (cholescintigraphy) ใช้วินิจฉัย <b>acute cholecystitis</b> (ไม่เห็นถุงน้ำดีเพราะ cystic duct อุด), bile leak และ biliary dyskinesia — ใน bilirubin สูงมากภาพไม่ชัดและไม่ได้ชิ้นเนื้อ; จะถูกถ้าโจทย์สงสัย acute cholecystitis ที่ US ไม่ชัดเจน หรือ bile leak หลังผ่าตัด"],
  trap:"เลือก US เพราะเป็นการตรวจแรก หรือ CA 19-9 เพราะคิดว่าเป็น marker ของมะเร็ง — คำว่า <b>definitive diagnosis</b> หมายถึง<b>ได้ชิ้นเนื้อ</b>; ในทางปฏิบัติจริงลำดับคือ US → pancreatic protocol CT/MRCP → tissue (ERCP brushing สำหรับ biliary stricture หรือ EUS-FNA/FNB สำหรับก้อนที่ตับอ่อน)",
  summary:["Painless progressive obstructive jaundice + น้ำหนักลด → มะเร็ง periampullary: หัวตับอ่อน (พบบ่อยสุด), distal cholangiocarcinoma, ampulla of Vater, duodenum; <b>Courvoisier sign</b> (คลำถุงน้ำดีได้ไม่เจ็บ + jaundice) ชี้ว่าไม่น่าใช่นิ่ว",
    "ขั้นตอน: <b>US</b> (ท่อน้ำดีขยาย ระดับการอุดตัน) → <b>pancreatic protocol CT</b> (staging, resectability ดูการลุก SMA, SMV, celiac) และ/หรือ <b>MRCP</b> (กายวิภาคท่อน้ำดี) → tissue",
    "Tissue: ก้อนที่ตับอ่อน → <b>EUS-FNA/FNB</b> (แม่นยำสูง เสี่ยง seeding น้อยกว่า percutaneous); biliary stricture → <b>ERCP brush cytology + biopsy</b> ± cholangioscopy (brush cytology ความไวค่อนข้างต่ำ อาจต้องทำซ้ำ)",
    "มะเร็งตับอ่อนที่ resectable ชัดเจนและจะผ่าตัดเลย อาจไม่ต้องได้ชิ้นเนื้อก่อน แต่ต้องมีชิ้นเนื้อเสมอก่อนให้ neoadjuvant therapy หรือเมื่อ unresectable",
    "Preoperative biliary drainage <b>ไม่ทำ routine</b> — ทำเมื่อมี cholangitis, คันรุนแรง, ต้องรอผ่าตัดนาน หรือจะให้ neoadjuvant chemotherapy (นิยม metal stent)",
    "CA 19-9: ใช้พยากรณ์และติดตาม ไม่ใช้วินิจฉัย (false positive ใน cholestasis; Lewis negative ไม่สร้าง)",
    "ดูข้อ 29, 34, 45 (jaundice work-up และตับอ่อน)"],
  notes:"แถว Liver + Jaundice 4 ในไฟล์เฉลยมีแต่ <b>\"A\"</b> ไม่มีคำอธิบาย (= ERCP with biopsy ช้อยเดียวในต้นฉบับ → ช้อย C ของเรา)<br>ไฟล์โจทย์: ผู้จดใส่ช้อยเดียว \"A. ERCP with biopsy\" (เราเติมคำว่า brushing); ช้อยอื่น 4 ช้อยเราแต่งเพิ่ม โดย<b>ตั้งใจไม่ใส่</b> EUS-FNA, CT หรือ MRCP เพื่อไม่ให้แข่งกับคำตอบของคีย์",
  mnemonic:"",
  guide:"NCCN Guidelines: Pancreatic Adenocarcinoma 2025; NCCN Guidelines: Biliary Tract Cancers 2025",
  opinion:"เห็นด้วยกับคีย์ในบริบทของช้อยที่ให้ (ERCP with biopsy เป็นวิธีเดียวที่ได้ชิ้นเนื้อ) — มั่นใจปานกลางถึงสูง; ข้อสังเกต: ในทางปฏิบัติทำ CT/MRCP ก่อนเสมอ และถ้าสาเหตุเป็นก้อนที่หัวตับอ่อน EUS-FNA/FNB แม่นยำกว่าและเป็นวิธีมาตรฐานในการเก็บชิ้นเนื้อ ส่วน ERCP brushing เหมาะกับ biliary stricture; ถ้าข้อสอบจริงมีช้อย EUS-FNA และโจทย์บอกว่ามีก้อนที่ตับอ่อน จะตอบ EUS-FNA; สอดคล้องกับข้อสอบชุด 77B (US → CT → EUS) และ 76C",
  variants:["ชายอายุ 65 ปี ตัวเหลืองไม่ปวด คลำถุงน้ำดีได้ CT พบก้อนขนาด 2.5 cm ที่หัวตับอ่อน วางแผนให้ neoadjuvant chemotherapy การตรวจเพื่อยืนยันชิ้นเนื้อที่เหมาะที่สุดคือ → EUS-guided FNA/FNB",
    "หญิงอายุ 60 ปี ตัวเหลืองไม่ปวด MRCP พบ distal CBD stricture ไม่เห็นก้อนที่ตับอ่อน การตรวจเพื่อวินิจฉัยและระบายน้ำดีพร้อมกันคือ → ERCP with brush cytology, biopsy และใส่ stent"]}),
A({page:13, page2:5, orig:"Liver 5",
  stem:"A patient with liver metastases needs a major hepatectomy, but CT volumetry shows the future liver remnant is insufficient. What should be done before resection?",
  gray:"A patient needed to undergo liver resection but the liver remnant is not enough, what is the management? — A. Portal vein embolization",
  opts:["Transarterial chemoembolization","Portal vein embolization","Hepatic vein embolization alone","Radiofrequency ablation","Systemic chemotherapy alone"],
  ans:1, key:"B Portal vein embolization"+KS,
  interp:"ต้องตัดตับขนาดใหญ่แต่ <b>future liver remnant (FLR)</b> ไม่พอ (เสี่ยง post-hepatectomy liver failure) — ถามวิธีเตรียมก่อนผ่าตัดเพื่อ<b>เพิ่มขนาดตับส่วนที่จะเหลือ</b>",
  why:"<b>Portal vein embolization (PVE)</b>: อุดหลอดเลือด portal vein ของกลีบตับ<b>ฝั่งที่จะตัด</b> (ผ่านทางผิวหนัง) → เลือด portal และ hepatotrophic factors ไหลไปตับฝั่งที่จะเหลือ → ตับส่วนนั้น <b>hypertrophy</b> ภายในราว 3–6 สัปดาห์ แล้วจึงวัด volume ซ้ำก่อนผ่าตัด; ยังเป็นการทดสอบความสามารถในการงอกใหม่ของตับ (degree of hypertrophy &gt;5% และ kinetic growth rate &gt;2% ต่อสัปดาห์ สัมพันธ์กับความเสี่ยง liver failure ที่ต่ำ) — ข้อสำคัญคือ PVE <b>ไม่ได้ทำให้ก้อนมะเร็งเล็กลง</b> แต่ทำให้ผ่าตัดได้อย่างปลอดภัย",
  wrong:["TACE ให้ยาเคมีบำบัดร่วมกับอุดแขนง hepatic artery ที่เลี้ยงก้อน — เป็นการรักษา <b>HCC</b> ระยะ intermediate (BCLC B) ไม่ได้เพิ่ม FLR; จะถูกถ้าโจทย์เป็น HCC หลายก้อนที่ผ่าตัดไม่ได้และตับยังทำงานดี (ใน HCC บนตับแข็งอาจทำ TACE ก่อน PVE แบบ sequential เพื่อคุมก้อนและเพิ่ม hypertrophy)",
    "Hepatic vein embolization <b>อย่างเดียว</b>ไม่ใช่วิธีมาตรฐาน — ใช้<b>ร่วมกับ</b> PVE พร้อมกันหรือตามกัน (liver venous deprivation) เพื่อเพิ่ม hypertrophy ให้มากและเร็วกว่า PVE อย่างเดียว; จะถูกถ้าโจทย์ถามเทคนิคที่เพิ่ม FLR ได้มากกว่า PVE (ทำร่วมกับ PVE)",
    "RFA ทำลายก้อนขนาดเล็ก (มัก ≤3 cm) ด้วยความร้อน ใช้แทนหรือร่วมกับการผ่าตัดเพื่อ<b>ประหยัดเนื้อตับ</b> แต่ไม่ได้เพิ่มขนาด FLR และไม่เหมาะกับก้อนใหญ่หรือหลายก้อนที่ต้องทำ major hepatectomy; จะถูกถ้าโจทย์เป็นก้อนเล็กเดี่ยวที่อยู่ลึกหรือผู้ป่วยผ่าตัดไม่ได้",
    "Systemic chemotherapy (conversion chemotherapy) ทำให้ก้อนเล็กลงจนผ่าตัดได้ในบางราย แต่<b>ไม่เพิ่ม FLR</b> และ chemotherapy เองทำให้ตับเสีย (steatohepatitis จาก irinotecan, sinusoidal obstruction จาก oxaliplatin) จน FLR ที่ต้องการสูงขึ้น; จะถูกถ้าโจทย์เป็น CRLM ที่ unresectable เพราะก้อนติดโครงสร้างสำคัญ"],
  trap:"เลือก TACE เพราะเป็น \"embolization\" เหมือนกัน — TACE อุด<b>แขนง hepatic artery ที่เลี้ยงก้อน</b>เพื่อรักษามะเร็ง ส่วน PVE อุด<b>portal vein ฝั่งที่จะตัด</b>เพื่อให้ตับอีกฝั่งโต",
  summary:["FLR ที่ต้องการ (เทียบกับ total liver volume): ตับปกติ <b>≥20–25%</b>, ตับได้ chemotherapy นานหรือ steatosis <b>≥30%</b>, ตับแข็ง (Child-Pugh A) <b>≥40%</b>",
    "ประเมินด้วย CT/MRI volumetry + ประเมินการทำงานของตับ (Child-Pugh, MELD, ICG retention, portal hypertension)",
    "<b>PVE</b>: อุด portal vein ฝั่งที่จะตัด → FLR โต 3–6 สัปดาห์ → วัด volume ซ้ำแล้วผ่าตัด; ข้อเสีย: ก้อนอาจโตระหว่างรอ, ราว 10–20% ไม่โตพอหรือโรคลุกลามจนผ่าตัดไม่ได้",
    "ทางเลือกเพิ่ม FLR: <b>liver venous deprivation</b> (PVE + hepatic vein embolization), <b>ALPPS</b> (ผ่าตัด 2 ขั้น ผูก portal vein + แยกเนื้อตับ → hypertrophy เร็วมากใน 1–2 สัปดาห์ แต่ morbidity สูง), <b>two-stage hepatectomy</b> (ก้อน CRLM ทั้งสองกลีบ)",
    "Post-hepatectomy liver failure (ISGLS): INR สูงขึ้นและ bilirubin สูงขึ้นตั้งแต่วันที่ 5 หลังผ่าตัด — สาเหตุการตายหลักหลัง major hepatectomy",
    "CRLM resectability = ตัดก้อนออกได้หมด (R0) โดยเหลือตับอย่างน้อย 2 segments ที่ติดกัน มี inflow, outflow และ biliary drainage ครบ และ FLR พอ",
    "ดูข้อ 30, 33 (liver)"],
  notes:"แถว Liver + Jaundice 5 ในไฟล์เฉลยมีแต่ <b>\"A\"</b> ไม่มีคำอธิบาย (= Portal vein embolization ช้อยเดียวในต้นฉบับ → ช้อย B ของเรา)<br>ไฟล์โจทย์: ผู้จดใส่ช้อยเดียว \"A. Portal vein embolization\"; ช้อยอื่น 4 ช้อยเราแต่งเพิ่ม<br>เราเติมใน stem ว่าเป็น liver metastases และวัดด้วย CT volumetry (ต้นฉบับเขียนแค่ \"liver remnant is not enough\")",
  mnemonic:"<b>\"อุดฝั่งที่ตัด ให้ฝั่งที่เหลือโต\"</b> · FLR <b>20–30–40</b> = ปกติ–หลังเคมี–ตับแข็ง",
  guide:"AHPBA/SSAT/SSO consensus on resection of colorectal liver metastases 2006; ESMO metastatic colorectal cancer guideline 2023",
  opinion:"เห็นด้วยกับคีย์ (Portal vein embolization) มั่นใจสูง; สอดคล้องกับข้อสอบชุด 76A, 77A และ 77D ที่ถาม PVE เมื่อ FLR ไม่พอ",
  variants:["ชายอายุ 58 ปี มะเร็งลำไส้ใหญ่กระจายไปตับกลีบขวาหลายก้อน ได้ FOLFOX 6 รอบ ต้องทำ right hepatectomy CT volumetry พบ FLR 22% ควรทำอย่างไร → PVE ฝั่งขวาก่อน (ต้องการ FLR ≥30% เพราะได้ chemotherapy) แล้ววัด volume ซ้ำ",
    "ผู้ป่วย HCC ขนาด 8 cm ในตับกลีบขวาบนตับแข็ง Child-Pugh A FLR 30% → sequential TACE แล้วตามด้วย PVE เพื่อให้ FLR ≥40% ก่อน right hepatectomy"]}),
A({page:13, page2:5, orig:"Jaundice 1",
  img:QI(33), imgNote:"Contrast-enhanced CT of the liver; the arrow points to a lesion (ผู้จดบอกว่ารูปคล้ายรูปในข้อสอบจริง)",
  stem:"A patient has subacute fever and right upper quadrant pain after travelling to India. The CT scan is shown. What is the most likely diagnosis?",
  gray:"A patient presented with subacute fever, RUQ pain, history of traveling to India, CT scan as shown (รูปค่อนข้างคล้ายแบบนี้เลย มีลูกศรชี้), what is the diagnosis? [รูป CT ต้นหน้า 14] — A. Pyogenic liver abscess B. Amoebic liver abscess C. Hydatid cyst",
  opts:["Pyogenic liver abscess","Amoebic liver abscess","Hydatid cyst","Simple liver cyst","Hepatocellular carcinoma"],
  ans:1, key:"B Amoebic liver abscess"+KS,
  interp:"ไข้แบบ subacute + ปวด RUQ + <b>ประวัติเดินทางไปอินเดีย</b> (endemic area ของ Entamoeba histolytica) + CT เห็นรอยโรคในตับ — ต้องแยกฝีในตับชนิดต่าง ๆ จากลักษณะทางระบาดวิทยาและภาพ",
  why:"ภาพ CT: ก้อน <b>hypodense เดี่ยว</b> ขอบชัด กลมรี อยู่ใน<b>ตับกลีบขวา ใกล้ capsule</b> มี<b>ขอบ enhance และวงบวมน้ำรอบ ๆ</b> (double target appearance) = ลักษณะของ liver abscess; เมื่อรวมกับประวัติเดินทางไปพื้นที่ระบาด อาการกึ่งเฉียบพลัน และก้อนเดี่ยวในกลีบขวา → <b>amoebic liver abscess</b> — Entamoeba histolytica ติดต่อทาง fecal-oral รุกผ่านผนัง colon เข้า portal vein ไปตับ (ส่วนใหญ่กลีบขวาเพราะรับเลือดจาก SMV มากกว่า) พบมากในชายวัยหนุ่ม ดื่มสุรา; หนองลักษณะ \"anchovy paste\" ไม่มีกลิ่น; วินิจฉัยด้วย <b>serology</b> (anti-Entamoeba antibody ความไว &gt;90%) และรักษาด้วย <b>metronidazole</b> ส่วนใหญ่ไม่ต้องเจาะระบาย",
  wrong:["Pyogenic liver abscess พบใน<b>ผู้สูงอายุ เบาหวาน</b> มีโรคทางเดินน้ำดีเป็นแหล่งติดเชื้อบ่อยที่สุด (นิ่ว มะเร็ง หลัง ERCP) หรือ portal pyemia จาก appendicitis/diverticulitis; มักหลายก้อนหรือรวมกลุ่ม (cluster sign) เชื้อ <b>Klebsiella pneumoniae</b> เด่นในเอเชีย (ระวัง endophthalmitis); รักษาด้วย IV antibiotics + percutaneous drainage; จะถูกถ้าโจทย์ให้ผู้สูงอายุเบาหวาน มีนิ่วในท่อน้ำดี และไม่มีประวัติเดินทาง",
    "Hydatid cyst (Echinococcus granulosus) — สัมผัส<b>สุนัขหรือแกะ</b> (พื้นที่เลี้ยงสัตว์) โตช้า มักไม่มีไข้ เว้นแต่ติดเชื้อซ้ำ; ภาพเป็น cyst มี <b>daughter cysts</b>, ผนังมี calcification, water lily sign; ห้ามเจาะสุ่มสี่สุ่มห้า (anaphylaxis, แพร่กระจาย) รักษาด้วย albendazole + PAIR หรือผ่าตัด; จะถูกถ้าโจทย์ให้คนเลี้ยงแกะ ภาพเป็น cyst มีผนังซ้อนหรือ cyst ลูกข้างใน",
    "Simple liver cyst — <b>ไม่มีไข้</b> ไม่มีขอบ enhance ไม่มีวงบวมรอบ ๆ ผนังบางมองไม่เห็น ความหนาแน่นเท่าน้ำ; จะถูกถ้าเป็นผู้ป่วยไม่มีอาการ พบก้อนน้ำผนังบางโดยบังเอิญ",
    "HCC เกิดบนตับแข็งหรือ HBV/HCV — ภาพ multiphase CT: <b>arterial phase hyperenhancement + washout</b> ใน portal venous/delayed phase (LI-RADS 5) ไม่ได้มาด้วยไข้กึ่งเฉียบพลันหลังเดินทาง; จะถูกถ้าโจทย์ให้ผู้ป่วยตับแข็ง AFP สูง และก้อน enhance แบบ washout"],
  trap:"เห็นก้อนในตับมีไข้แล้วตอบ pyogenic ทันที — <b>ประวัติเดินทางไปพื้นที่ระบาด + ชายวัยหนุ่ม + ก้อนเดี่ยวกลีบขวา</b> ชี้ amoebic ซึ่งรักษาด้วยยาเป็นหลัก ไม่ใช่ drainage ทุกราย",
  summary:["Amoebic liver abscess: Entamoeba histolytica, fecal-oral, ชายอายุ 20–50 ปี, ดื่มสุรา, ผู้อยู่หรือเดินทางไปพื้นที่ระบาด (อินเดีย เม็กซิโก แอฟริกา ไทย); มัก<b>เดี่ยว กลีบขวา ใกล้ capsule</b>; ส่วนใหญ่ไม่มีท้องเสียขณะมาด้วยฝี",
    "วินิจฉัย: US/CT (ก้อน hypodense ขอบชัด ขอบ enhance + edema รอบ) + <b>serology anti-E. histolytica</b> (อาจลบใน 7–10 วันแรก); หนอง anchovy paste ไม่มีกลิ่น ส่วนใหญ่ไม่พบเชื้อในหนอง",
    "รักษา: <b>metronidazole</b> 750 mg วันละ 3 ครั้ง 7–10 วัน (ตอบสนองใน 72–96 ชม.) ตามด้วย <b>luminal agent</b> (paromomycin หรือ diloxanide furoate) เพื่อกำจัด cyst ในลำไส้",
    "Aspiration/drainage เฉพาะ: ไม่ตอบสนองต่อยาใน 3–5 วัน, ก้อนใหญ่ (&gt;5–10 cm) เสี่ยงแตก, <b>กลีบซ้าย</b> (เสี่ยงแตกเข้า pericardium), แยกจาก pyogenic ไม่ได้; ภาวะแทรกซ้อน: แตกเข้าช่องเยื่อหุ้มปอด ปอด pericardium peritoneum",
    "Pyogenic: สูงอายุ เบาหวาน biliary source, หลายก้อน, Klebsiella pneumoniae (เอเชีย), E. coli, anaerobe → IV antibiotics 4–6 สัปดาห์ + percutaneous drainage (ก้อน &gt;5 cm), รักษาแหล่งต้นเหตุ, ตรวจตา (endophthalmitis) และ colonoscopy ในบางกลุ่ม",
    "Hydatid: Echinococcus, สุนัข/แกะ, cyst มี daughter cysts, ผนัง calcified, water lily sign → albendazole + PAIR หรือผ่าตัด ระวัง spillage (anaphylaxis)",
    "ดูข้อ 30, 32 (liver)"],
  notes:"แถว jaundice 1 ในไฟล์เฉลยมีแต่ <b>\"B\"</b> ไม่มีคำอธิบาย (หัว section ในไฟล์เฉลยพิมพ์ว่า \"jaundice\" = section \"Jaundice + liver\" ในไฟล์โจทย์; section นี้ในไฟล์เฉลยมีแถว 1, 2, 3, 5)<br>ไฟล์โจทย์: มีช้อย A–C; โน้ตผู้จด <b>\"(รูปค่อนข้างคล้ายแบบนี้เลย มีลูกศรชี้)\"</b> — รูป CT ที่ผู้จดแปะ (อยู่ต้นหน้า 14 ของไฟล์โจทย์) เป็นรูปที่<b>คล้าย</b>รูปในข้อสอบจริง ไม่ใช่รูปเดียวกัน<br>ช้อย D (Simple liver cyst) และ E (Hepatocellular carcinoma) เราแต่งเพิ่ม",
  mnemonic:"<b>Amoebic = \"หนุ่ม–เดี่ยว–ขวา–เดินทาง → metronidazole\"</b> · Pyogenic = \"แก่–เบาหวาน–ท่อน้ำดี–หลายก้อน → ระบาย\"",
  guide:"Sabiston 21st ed.; Schwartz 11th ed.",
  opinion:"เห็นด้วยกับคีย์ B มั่นใจสูง (ภาพเป็นฝีเดี่ยวกลีบขวาใกล้ capsule ร่วมประวัติเดินทาง แม้ภาพ CT แยก amoebic กับ pyogenic ไม่ได้ร้อยเปอร์เซ็นต์); สอดคล้องกับข้อสอบชุด 77A (amoebic liver abscess)",
  variants:["ชายอายุ 32 ปี ดื่มสุราทุกวัน ไข้ 10 วัน ปวด RUQ ร้าวไหล่ขวา US พบ hypoechoic lesion เดี่ยว 6 cm ในตับกลีบขวา anti-E. histolytica บวก การรักษาคือ → metronidazole 7–10 วัน แล้วตามด้วย luminal agent",
    "หญิงอายุ 68 ปี เบาหวาน ไข้สูงหนาวสั่น CT พบ multiloculated abscess 7 cm ในตับ เพาะเชื้อได้ Klebsiella pneumoniae ต่อมามีตามัวข้างขวา → pyogenic liver abscess แทรกซ้อน endophthalmitis; IV antibiotics + percutaneous drainage + ปรึกษาจักษุแพทย์"]}),
A({page:14, page2:5, orig:"Jaundice 2",
  stem:"A patient with ulcerative colitis who undergoes annual surveillance colonoscopy presents with fever, jaundice, right upper quadrant pain and pruritus. What is the most likely diagnosis?",
  gray:"A patient presented with fever + jaundice + RUQ pain, itching, the patient got an annual colonoscopy for surveillance due to underlying ulcerative colitis, what is the diagnosis? — A. Distal bile duct cholangiocarcinoma B. Common bile duct stone impaction C. Mirizzi’s syndrome D. Sclerosing cholangitis E. Acute cholecystitis",
  opts:["Distal bile duct cholangiocarcinoma","Common bile duct stone impaction","Mirizzi syndrome","Primary sclerosing cholangitis","Acute cholecystitis"],
  ans:3, key:"D Sclerosing cholangitis"+KS,
  interp:"อาการท่อน้ำดีอุดตันและอักเสบ (ไข้ jaundice ปวด RUQ คัน) ในผู้ป่วย<b>ulcerative colitis</b> — โรคประจำตัวคือกุญแจ: ต้องนึกถึง extraintestinal manifestation ของ IBD ที่ท่อน้ำดี",
  why:"<b>Primary sclerosing cholangitis (PSC)</b> = การอักเสบเรื้อรังและ fibrosis ของท่อน้ำดีทั้งในและนอกตับ ทำให้เกิด stricture หลายตำแหน่งสลับท่อขยาย — <b>ราว 70–80% ของผู้ป่วย PSC มี IBD</b> (ส่วนใหญ่เป็น UC) พบมากในชายอายุ 30–40 ปี; อาการ: คัน อ่อนเพลีย jaundice และ<b>มี bacterial cholangitis เป็นพัก ๆ</b> (ไข้ ปวด RUQ) จาก stricture ที่ทำให้น้ำดีคั่ง; LFT เป็น cholestatic pattern (ALP สูงเด่น), p-ANCA พบได้บ่อยแต่ไม่จำเพาะ; วินิจฉัยด้วย <b>MRCP: beading</b> (stricture สลับ dilatation หลายจุด) — ผู้ป่วย UC ที่มาด้วยอาการท่อน้ำดีจึงต้องคิดถึง PSC ก่อน",
  wrong:["Distal cholangiocarcinoma มักมาด้วย <b>painless progressive jaundice</b> น้ำหนักลด ไม่ค่อยมีไข้ (ยกเว้นมี cholangitis แทรก) — เป็น<b>ภาวะแทรกซ้อนของ PSC</b> (lifetime risk 10–20%) ไม่ใช่การวินิจฉัยแรกเมื่อมีแค่ประวัติ UC; จะถูกถ้าผู้ป่วย PSC มี jaundice แย่ลงเรื่อย ๆ น้ำหนักลด CA 19-9 สูงขึ้น และพบ dominant stricture ใหม่",
    "CBD stone impaction ให้ Charcot triad ได้เหมือนกัน แต่<b>ไม่สัมพันธ์กับ UC</b> — มักมีประวัตินิ่วในถุงน้ำดี US เห็นนิ่วใน CBD; จะถูกถ้าโจทย์ให้ผู้ป่วยหญิงอ้วนมีนิ่วถุงน้ำดีและไม่มี IBD",
    "Mirizzi syndrome = นิ่วติดที่<b>คอถุงน้ำดีหรือ cystic duct กดเบียด common hepatic duct</b> → jaundice + อาการ cholecystitis; ภาพเห็นท่อเหนือจุดกดขยาย CBD ส่วนล่างปกติ (Csendes classification บอกระดับ fistula); จะถูกถ้าโจทย์ให้นิ่วใหญ่ติดคอถุงน้ำดีร่วมกับ CHD ขยาย",
    "Acute cholecystitis — ปวด RUQ ไข้ Murphy sign; jaundice <b>ไม่เด่น</b> (ถ้าเหลืองมากต้องคิดถึงนิ่วใน CBD หรือ Mirizzi) และไม่มีความสัมพันธ์กับ UC; จะถูกถ้าโจทย์ให้ Murphy sign บวก US เห็นผนังถุงน้ำดีหนาและ pericholecystic fluid โดยไม่มี jaundice"],
  trap:"เห็น Charcot triad แล้วตอบนิ่วใน CBD ทันที — ประวัติ <b>UC</b> คือ clue สำคัญที่ผู้ออกข้อสอบใส่ไว้ชี้ไปที่ PSC; ส่วน cholangiocarcinoma เป็นภาวะแทรกซ้อนระยะยาวของ PSC ไม่ใช่คำตอบแรก",
  summary:["PSC: chronic cholestatic disease ท่อน้ำดีในและนอกตับ — <b>70–80% มี IBD (ส่วนใหญ่ UC)</b>, ขณะที่ผู้ป่วย UC เป็น PSC ราว 2–8%; ชาย:หญิง ราว 2:1 อายุ 30–40 ปี",
    "อาการ: ไม่มีอาการ (ALP สูงโดยบังเอิญ), คัน, อ่อนเพลีย, jaundice, bacterial cholangitis เป็นพัก ๆ; ระยะท้าย cirrhosis และ portal hypertension",
    "วินิจฉัย: cholestatic LFT (ALP สูง) + <b>MRCP</b> เห็น multifocal stricture สลับ dilatation (<b>beading</b>); ERCP ใช้เมื่อต้องทำ intervention; liver biopsy เมื่อสงสัย small-duct PSC (onion-skin fibrosis); แยก IgG4-related sclerosing cholangitis (ตอบสนองต่อ steroid)",
    "ภาวะแทรกซ้อน: dominant stricture, cholangitis, <b>cholangiocarcinoma</b> (lifetime 10–20%), gallbladder cancer (polyp ≥8 mm → cholecystectomy), <b>colorectal cancer</b> (UC + PSC เสี่ยงสูงกว่า UC อย่างเดียว)",
    "Surveillance: colonoscopy + biopsy <b>ทุกปีตั้งแต่วินิจฉัย PSC</b> (ถ้ามี IBD); MRI/MRCP ± CA 19-9 ทุก 6–12 เดือนเพื่อหา cholangiocarcinoma; US ถุงน้ำดีทุกปี",
    "รักษา: ไม่มียาที่เปลี่ยนการดำเนินโรค (UDCA ขนาดสูงเพิ่มผลเสีย); cholangitis → antibiotics; dominant stricture → ERCP balloon dilation + brush cytology; คัน → cholestyramine; ระยะท้าย → <b>liver transplantation</b> (PSC กลับเป็นซ้ำใน graft ได้)",
    "ดูข้อ 29, 31, 28 (biliary และ jaundice work-up)"],
  notes:"แถว jaundice 2 ในไฟล์เฉลยมีแต่ <b>\"D\"</b> ไม่มีคำอธิบาย (หัว section ในไฟล์เฉลยพิมพ์ว่า \"jaundice\")<br>ไฟล์โจทย์: มีครบ 5 ช้อย (A. Distal bile duct cholangiocarcinoma B. Common bile duct stone impaction C. Mirizzi's syndrome D. Sclerosing cholangitis E. Acute cholecystitis) — เราเติมคำว่า \"Primary\" ในช้อย D และเขียน Mirizzi syndrome ไม่มี 's",
  mnemonic:"<b>UC + ท่อน้ำดี = PSC · PSC + jaundice แย่ลง/น้ำหนักลด = ระวัง cholangiocarcinoma</b>",
  guide:"AASLD Practice Guidance on primary sclerosing cholangitis and cholangiocarcinoma 2022; ACG Clinical Guideline: Primary Sclerosing Cholangitis 2015",
  opinion:"เห็นด้วยกับคีย์ D มั่นใจสูง — ประวัติ UC เป็นคำใบ้หลัก; ถ้าโจทย์เพิ่มน้ำหนักลด jaundice แบบค่อยเป็นค่อยไปและ CA 19-9 สูงในผู้ป่วยที่รู้ว่าเป็น PSC อยู่แล้ว จะตอบ cholangiocarcinoma",
  variants:["ชายอายุ 35 ปี เป็น UC มา 8 ปี ตรวจสุขภาพพบ ALP 480 U/L bilirubin ปกติ ไม่มีอาการ การตรวจที่เหมาะที่สุดคือ → MRCP (หา beading ของท่อน้ำดี)",
    "ผู้ป่วย PSC มา 10 ปี ตัวเหลืองมากขึ้นใน 2 เดือน น้ำหนักลด 6 kg CA 19-9 สูง MRCP พบ dominant stricture ที่ hilum ใหม่ → สงสัย cholangiocarcinoma; ERCP brush cytology และ biopsy ± cholangioscopy"]}),
