A({page:2, page2:3, orig:"Pre-Op/Post-Op 1",
  stem:"In which patient is a preoperative 12-lead ECG most appropriate before elective surgery?",
  gray:"Pre-Op EKG ทำในใครดีที่สุด — A. คนแก่ U/D HT B. อายุน้อย Healthy",
  opts:["Elderly patient with underlying hypertension","Young healthy patient","Healthy 25-year-old before excision of a skin lipoma","Healthy 30-year-old before inguinal hernia repair","Healthy 20-year-old before cataract surgery"],
  ans:0, key:"A คนแก่ U/D HT"+KS,
  interp:"ถามว่า <b>ECG ก่อนผ่าตัด</b> มีประโยชน์ในผู้ป่วยกลุ่มใด — หลักคือการส่งตรวจก่อนผ่าตัดทำตาม <b>ข้อบ่งชี้</b> (อายุ โรคประจำตัว ชนิดและขนาดของการผ่าตัด) ไม่ได้ทำ routine ทุกคน",
  why:"ผู้สูงอายุที่มี <b>hypertension</b> มีโอกาสมีโรคหัวใจแฝง (LVH, ischemia, arrhythmia) และเป็นกลุ่มที่ ECG ช่วยเป็น baseline สำหรับเทียบหลังผ่าตัด — <b>NICE NG45</b>: พิจารณา ECG ใน ASA ≥2 ที่มีโรคหัวใจหลอดเลือด ไต หรือเบาหวาน ก่อนผ่าตัด intermediate ขึ้นไป และในอายุ &gt;65 ปีก่อนผ่าตัดใหญ่; <b>ESC/ESAIC 2022</b>: แนะนำ ECG ก่อนผ่าตัด intermediate หรือ high risk ในผู้ที่มี cardiovascular risk factor หรืออายุ ≥65 ปี; ส่วนผู้ป่วยอายุน้อยสุขภาพดีที่ผ่าตัดเล็ก ECG ไม่เปลี่ยนการดูแล",
  wrong:[
    "คนอายุน้อยสุขภาพดีไม่มีอาการและไม่มี risk factor → ECG แทบไม่พบความผิดปกติที่เปลี่ยนการดูแล และอาจเจอ false positive ทำให้เลื่อนผ่าตัดโดยไม่จำเป็น; จะถูกถ้ามีอาการทางหัวใจ (เจ็บหน้าอก ใจสั่น หมดสติ) หรือตรวจพบ murmur",
    "Excision ของ lipoma ที่ผิวหนังเป็น <b>low-risk surgery</b> ภายใต้ local anesthesia ในคนอายุ 25 ปีที่แข็งแรง → ไม่ต้องตรวจเพิ่มเติมใด ๆ; จะถูกถ้าผู้ป่วยมีโรคหัวใจหรือประวัติชวนสงสัย",
    "Inguinal hernia repair ในคนอายุ 30 ปีที่แข็งแรง (ASA 1) → NICE ไม่แนะนำ ECG ก่อนผ่าตัดระดับ intermediate ใน ASA 1 ที่อายุน้อย; จะถูกถ้าเป็นผู้สูงอายุที่มีโรคหัวใจ ไต หรือเบาหวาน",
    "Cataract surgery เป็น <b>very low-risk</b> procedure — การศึกษาพบว่า routine preoperative testing ไม่ลด complication; คนอายุ 20 ปีที่แข็งแรงไม่ต้องตรวจ ECG; จะถูกถ้ามีอาการหรือโรคหัวใจที่ยังไม่ได้ประเมิน"],
  trap:"คิดว่า \"ก่อนผ่าตัดทุกคนต้องทำ CBC, CXR, ECG\" — แนวทางปัจจุบันไม่ทำ routine; ส่งตรวจตามประวัติ ตรวจร่างกาย อายุ โรคร่วม และ surgical risk เท่านั้น",
  summary:[
    "การส่งตรวจก่อนผ่าตัดยึด <b>history + physical examination</b> เป็นหลัก ไม่ทำ routine test ทุกคน (ไม่ลด complication เพิ่มค่าใช้จ่ายและการเลื่อนผ่าตัด)",
    "ECG: พิจารณาเมื่อมีโรคหัวใจหลอดเลือด ไต เบาหวาน หรือ cardiovascular risk factor ร่วมกับการผ่าตัด intermediate ถึง high risk, หรืออายุ ≥65 ปี (ESC/ESAIC 2022), อายุ &gt;65 ปีก่อนผ่าตัดใหญ่ (NICE NG45)",
    "ไม่ต้องทำ ECG ในผู้ป่วยไม่มีอาการ ไม่มี risk factor ที่ผ่าตัด low risk (ผ่าตัดผิวหนัง ตา เต้านมเล็กน้อย endoscopy)",
    "ประเมิน cardiac risk ด้วย <b>RCRI</b>: high-risk surgery, ischemic heart disease, heart failure, cerebrovascular disease, insulin-treated DM, creatinine &gt;2 mg/dL",
    "Functional capacity ≥4 METs (ขึ้นบันได 2 ชั้นได้) ไปผ่าตัดได้โดยไม่ต้อง stress test",
    "CXR ไม่ทำ routine — ทำเมื่อมีอาการหรือโรคปอดหัวใจที่ไม่คงที่; CBC ทำเมื่อผ่าตัดใหญ่ที่คาดว่าเสียเลือดหรือสงสัย anemia",
    "ดูข้อ 2, 3, 4 (perioperative care)"],
  notes:"ไฟล์เฉลย บท Pre-Op/ Post-Op แถว 1: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดช้อยไว้แค่ 2 ตัว (A. คนแก่ U/D HT, B. อายุน้อย Healthy) — ช้อย C–E แต่งเพิ่ม; ต้นฉบับเขียน \"EKG\" (= ECG)",
  mnemonic:"",
  guide:"NICE NG45 Routine preoperative tests 2016; ESC/ESAIC Guidelines on cardiovascular assessment for non-cardiac surgery 2022",
  variants:["ชายอายุ 70 ปี เป็น DM และ CKD นัดผ่าตัด open colectomy — ควรส่ง ECG ก่อนผ่าตัดหรือไม่ → ควรส่ง (อายุมาก มีโรคร่วม ผ่าตัด high risk)","หญิงอายุ 22 ปี แข็งแรง จะตัด sebaceous cyst ที่หลังภายใต้ local anesthesia — ต้องตรวจอะไรก่อนผ่าตัด → ไม่ต้องส่งตรวจเพิ่ม ซักประวัติตรวจร่างกายพอ","ชายอายุ 45 ปี มีอาการเจ็บหน้าอกเวลาออกแรง 2 เดือน นัดผ่าตัด laparoscopic cholecystectomy — ต้องทำอะไรก่อน → ประเมินโรคหัวใจตามอาการ (ECG และส่งพบอายุรแพทย์) ก่อนผ่าตัด elective"]}),
A({page:2, page2:3, orig:"Pre-Op/Post-Op 2",
  flag:"⚠ เล็กน้อย: แผลยังไม่แดงไม่มีหนอง — คีย์ตอบตามที่อาจารย์ชัยสิทธิ์สอน (day 5 = wound infection)",
  stem:"On postoperative day 5 after appendectomy, a patient whose Foley catheter was removed on day 2 is walking normally but has severe wound pain. The wound shows no pus and no redness. What is the most likely diagnosis?",
  gray:"Post-Op day 5 ของการผ่าไส้ติ่ง คนไข้ถอด foley day 2 เดินได้ปกติ แต่เจ็บแผลมาก แต่แผลไม่มีหนอง ไม่มีแดง ถามว่าเป็นไร — A. Pneumonia B. Thrombophlebitis C. Wound infection D. UTI",
  opts:["Pneumonia","Thrombophlebitis","Wound infection","Urinary tract infection","Atelectasis"],
  ans:2, key:"C Wound infection"+KS,
  interp:"โจทย์ให้ <b>เวลา (POD 5)</b> + ตัดสาเหตุอื่นทิ้งด้วยข้อมูล (ถอด Foley ตั้งแต่ day 2, เดินได้ปกติ, ไม่มีอาการทางเดินหายใจ) แล้วเหลืออาการเด่นคือ <b>ปวดแผลมาก</b> — ต้องใช้ timeline ภาวะแทรกซ้อนหลังผ่าตัด (5W) ตอบ",
  why:"Surgical site infection มักเกิด <b>POD 5–7</b> และอาการแรกที่พบบ่อยคือ <b>ปวดแผลมากผิดสัดส่วน</b> (ปวดมากขึ้นแทนที่จะดีขึ้น) ก่อนเห็นแดงหรือหนอง โดยเฉพาะ infection ระดับลึก (deep incisional) ที่อยู่ใต้ผิวหนังยังไม่โผล่ให้เห็น → ต้องตรวจแผล กดหา fluctuation และเปิดแผลบางส่วนเพื่อระบาย; appendectomy (โดยเฉพาะ complicated) เป็นแผล contaminated ถึง dirty ที่ SSI สูง; ไฟล์เฉลยเขียนว่าคำตอบนี้ <b>ตาม อ.ชัยสิทธิ์</b> (สอน day 5 = wound)",
  wrong:[
    "Pneumonia หลังผ่าตัดเกิดได้ช่วง POD 3–5 แต่ต้องมีไข้ ไอ เสมหะ หายใจเร็ว และไม่ทำให้ <b>ปวดแผล</b>; โจทย์ไม่มีอาการทางเดินหายใจ; จะถูกถ้ามีไข้ ไอมีเสมหะ crepitation และ infiltrate ใน CXR",
    "Thrombophlebitis (ทั้ง superficial ที่ตำแหน่ง IV line หรือ DVT) มักพบ POD 7 ขึ้นไป ปวด บวม แดงที่แขนหรือขา ไม่ใช่ที่แผล และผู้ป่วยเดินได้ปกติ (ความเสี่ยงต่ำ); จะถูกถ้ามีเส้นเลือดดำแข็งแดงเป็นลำตามแนว IV line หรือขาบวมข้างเดียว",
    "UTI เกิดช่วง POD 3–5 แต่สัมพันธ์กับ Foley catheter — รายนี้ <b>ถอดสายตั้งแต่ day 2</b> และอาการคือปวดแผลไม่ใช่ปัสสาวะแสบขัดหรือปวดท้องน้อย; จะถูกถ้ายังคาสายอยู่หรือมี dysuria, frequency, pyuria",
    "Atelectasis เป็นสาเหตุไข้ช่วง POD 1–2 (wind) ไม่ทำให้ปวดแผล และผู้ป่วยเดินได้ปกติ (ambulation ช่วยป้องกัน); จะถูกถ้าไข้ต่ำ ๆ ในวันแรกหลังผ่าตัด หายใจตื้น เสียงหายใจลดที่ฐานปอด"],
  trap:"คิดว่า wound infection ต้องเห็นแดงหรือหนองก่อน — ระยะแรกหรือ infection ที่ลึกอาจมีแค่ปวดแผลมาก (บางรายมี induration หรือ crepitus); และ <b>ปวดแผลรุนแรงผิดปกติเร็ว ๆ (ภายใน 24–48 ชม.)</b> ต้องคิดถึง necrotizing infection จาก Streptococcus group A หรือ Clostridium",
  summary:[
    "ภาวะแทรกซ้อนหลังผ่าตัดตามเวลา (<b>5W</b>): Wind (atelectasis, pneumonia) POD 1–3, Water (UTI) POD 3–5, Wound (SSI) POD 5–7, Walking (DVT, thrombophlebitis) POD 7 ขึ้นไป, Wonder drugs (drug fever) เมื่อไรก็ได้",
    "ไข้ภายใน 48 ชม. แรกส่วนใหญ่เป็น inflammatory response จากการผ่าตัด; ยกเว้นต้องคิดถึง necrotizing soft tissue infection, anastomotic leak ระยะแรก และ aspiration",
    "SSI แบ่งตาม CDC NHSN: superficial incisional (ผิวหนังและ subcutaneous), deep incisional (fascia และกล้ามเนื้อ), organ/space (intra-abdominal abscess) — เกิดภายใน 30 วัน (90 วันถ้าใส่ implant ในบาง procedure)",
    "อาการ SSI: ปวดแผลมากขึ้น บวม แดง ร้อน มีหนองหรือ discharge ขุ่น ไข้; ปวดผิดสัดส่วนอาจนำหน้าอาการเฉพาะที่",
    "การรักษา superficial SSI หลัก = <b>เปิดแผลระบาย</b> + ทำแผล; ให้ antibiotic เมื่อมี cellulitis รอบแผลกว้าง หรือมี systemic sign",
    "UTI หลังผ่าตัดสัมพันธ์กับระยะเวลาคาสาย — ถอด Foley เร็วที่สุด (ภายใน 24–48 ชม. ในผ่าตัดส่วนใหญ่)",
    "ดูข้อ 1, 16, 17, 18 (perioperative care และ SSI)"],
  notes:"ไฟล์เฉลย บท Pre-Op/ Post-Op แถว 2: <b>C</b> คำอธิบายเขียนว่า <b>\"ตามอจ ชัยสิทธิ์\"</b><br>ต้นฉบับจดช้อย 4 ตัว (A–D) — ช้อย E (Atelectasis) แต่งเพิ่ม; ช้อย D ต้นฉบับเขียน \"UTI\" เราเขียนเต็มว่า Urinary tract infection; โจทย์ต้นฉบับลงท้าย \"ถามว่าเป็นไร\"",
  mnemonic:"<b>5W</b> ตามวันหลังผ่าตัด: Wind 1–2 → Water 3–5 → <b>Wound 5–7</b> → Walking 7+ → Wonder drugs ทุกเมื่อ",
  guide:"Sabiston Textbook of Surgery 21st ed.; CDC NHSN Surgical Site Infection Event definitions 2024",
  opinion:"เห็นด้วยกับคีย์ C ความมั่นใจปานกลางถึงสูง — ตาม timeline และการตัดตัวเลือกอื่นด้วยข้อมูลในโจทย์ wound infection เหมาะสุด แม้แผลยังไม่แดงไม่มีหนอง (ต้องตีความว่าเป็นระยะแรกหรือ deep incisional SSI); ไฟล์เฉลยเองระบุว่าตอบตามที่ อ.ชัยสิทธิ์สอน",
  variants:["หลังผ่าตัด laparotomy POD 1 ผู้ป่วยมีไข้ 38.0°C หายใจตื้น ฟังเสียงหายใจลดที่ฐานปอดขวา — สาเหตุน่าจะเป็นอะไร → atelectasis (ให้ incentive spirometry และ early ambulation)","หลังผ่าตัด POD 4 ผู้ป่วยยังคาสาย Foley มีไข้ ปัสสาวะขุ่น — น่าจะเป็นอะไร → catheter-associated UTI (ถอดหรือเปลี่ยนสาย ส่ง urine culture)","หลังผ่าตัด POD 6 แผลบวมแดงกดเจ็บ มีหนองซึม — ควรทำอะไรก่อน → เปิดแผลระบายหนองและทำแผล ส่ง culture"]}),
A({page:2, page2:3, orig:"Pre-Op/Post-Op 3",
  flag:"⚠ ไม่มีคำตอบในไฟล์เฉลย และต้นฉบับจดแค่หัวข้อ — เติมเคสใน stem (ผู้ป่วยเคยเป็น DVT + ผ่าตัดมะเร็งช่องท้อง + bleeding risk ต่ำ) ตามแนวคำอธิบายในไฟล์เฉลย",
  stem:"A 65-year-old man with a history of deep vein thrombosis 3 years ago is scheduled for elective open colectomy for colon cancer. His bleeding risk is low. What is the most appropriate DVT prophylaxis?",
  gray:"DVT prophylaxis — 1. Pneumatic intermittent compression 2. Aggressive ambulation 3. LMWH",
  opts:["Intermittent pneumatic compression alone","Early aggressive ambulation alone","Low-molecular-weight heparin","Aspirin alone","Prophylactic IVC filter"],
  ans:2, key:NK+" — ช่องคำตอบว่าง คำอธิบายเขียนว่าโจทย์ไม่ครบ ดู Caprini ตอบ A หรือ B แล้วแต่สถานการณ์ ถ้าเคยเป็น DVT ตอบ LMWH",
  interp:"ต้นฉบับจดแค่ \"DVT prophylaxis\" — การเลือกวิธีป้องกันขึ้นกับ <b>VTE risk (Caprini score)</b> และ <b>bleeding risk</b>; เราเติมเคสที่ VTE risk สูง (เคยเป็น DVT + มะเร็ง + ผ่าตัดใหญ่ + อายุ) และ bleeding risk ต่ำ ตามที่ไฟล์เฉลยบอกว่า \"ถ้าเคยเป็น DVT ตอบ LMWH\"",
  why:"Caprini ของผู้ป่วยรายนี้: อายุ 61–74 ปี (2) + major open surgery &gt;45 นาที (2) + malignancy (2) + history of VTE (3) = <b>9 → high risk</b> (≥5) → ACCP 2012 แนะนำ <b>pharmacologic prophylaxis (LMWH หรือ low-dose UFH) ร่วมกับ mechanical</b> (IPC หรือ elastic stocking) เมื่อ bleeding risk ไม่สูง; ผ่าตัดมะเร็งช่องท้องหรืออุ้งเชิงกรานให้ <b>extended-duration LMWH 4 สัปดาห์</b> หลังผ่าตัด; enoxaparin 40 mg SC วันละครั้ง เริ่ม 12 ชม. ก่อนหรือ 6–12 ชม. หลังผ่าตัด",
  wrong:[
    "IPC alone เป็น mechanical prophylaxis ที่ใช้เมื่อ <b>bleeding risk สูง</b> หรือมีข้อห้ามยา anticoagulant, หรือใน Caprini 3–4 (moderate risk) ทดแทนยาได้; ในผู้ป่วย high risk ที่เลือดออกไม่ง่าย IPC อย่างเดียวไม่พอ ใช้เสริมยา; จะถูกถ้าโจทย์บอกว่ามีเลือดออกหรือเสี่ยงเลือดออกสูง (ไฟล์เฉลยเขียนว่าผู้ป่วยผ่าตัดทั่วไปตอบ A หรือ B แล้วแต่สถานการณ์)",
    "Early ambulation อย่างเดียวพอสำหรับ <b>very low risk</b> (Caprini 0) เช่นคนอายุน้อยผ่าตัดเล็กแบบ day surgery; ในผู้ป่วย high risk ต้องให้ยา; จะถูกถ้าเป็นผู้ป่วยอายุน้อยไม่มี risk factor ผ่าตัดเล็ก",
    "Aspirin มีที่ใช้ในการป้องกัน VTE หลังผ่าตัด orthopedic บางกรณี (hip, knee arthroplasty) แต่ไม่ใช่ยามาตรฐานใน general/abdominal surgery ที่ high risk; จะถูกถ้าเป็นหลังผ่าตัดเปลี่ยนข้อเข่าตามแนวทาง orthopedic",
    "IVC filter <b>ไม่ใช้เป็น primary prophylaxis</b> (ACCP แนะนำไม่ใช้) — ใช้เมื่อมี acute proximal DVT หรือ PE ที่ให้ anticoagulant ไม่ได้ หรือเกิดซ้ำแม้ให้ยาเต็มที่; จะถูกถ้าผู้ป่วยมี DVT ขณะนี้และห้ามให้ anticoagulant"],
  trap:"เลือก IPC เพราะคิดว่าปลอดภัยกว่า — mechanical อย่างเดียวเหมาะกับ bleeding risk สูง; ประวัติ VTE ได้ 3 คะแนนทันที และมะเร็งช่องท้องต้องให้ LMWH ต่อหลังกลับบ้านนาน 4 สัปดาห์",
  summary:[
    "ประเมิน VTE risk ด้วย <b>Caprini</b>: 1 คะแนน (อายุ 41–60, minor surgery, BMI &gt;25, varicose vein), 2 คะแนน (อายุ 61–74, major surgery &gt;45 นาที, laparoscopy &gt;45 นาที, malignancy, bed rest &gt;72 ชม.), 3 คะแนน (อายุ ≥75, history of VTE, family history, thrombophilia), 5 คะแนน (stroke, arthroplasty, hip/pelvis/leg fracture, spinal cord injury ภายใน 1 เดือน)",
    "Very low (0) → early ambulation; Low (1–2) → mechanical (IPC); Moderate (3–4) → LMWH หรือ LDUH หรือ IPC; High (≥5) → LMWH หรือ LDUH + mechanical",
    "Bleeding risk สูง → mechanical (IPC) ก่อน แล้วเริ่มยาเมื่อเลือดหยุดและความเสี่ยงลดลง",
    "ผ่าตัดมะเร็งช่องท้องหรืออุ้งเชิงกราน high risk → <b>extended LMWH 4 สัปดาห์</b>",
    "ยา: enoxaparin 40 mg SC วันละครั้ง, UFH 5,000 units SC ทุก 8–12 ชม. (เลือกใน CrCl &lt;30); ติดตาม platelet เฝ้าระวัง HIT",
    "IVC filter ไม่ใช้ป้องกันแบบ primary; ใช้เมื่อมี VTE แล้วให้ anticoagulant ไม่ได้",
    "ดูข้อ 1, 2, 4, 7 (perioperative care และ heparin)"],
  notes:"ไฟล์เฉลย บท Pre-Op/ Post-Op แถว 3: <b>ช่องคำตอบว่าง</b> คำอธิบายเขียนว่า <b>\"โจทย์ไม่ครบ ถ้า DVT ในคนไข้ผ่าตัดต้องดูตาม caprini criteria ตอบ A/B แล้วแต่สถานการณ์, ถ้าเป็น DVT ในคนที่เคยเป็นตอบ LMWH\"</b><br>ต้นฉบับจดโจทย์แค่ \"DVT prophylaxis\" และช้อยเป็นเลข 1–3 (1. Pneumatic intermittent compression 2. Aggressive ambulation 3. LMWH) — เราเรียงเป็น A–C ตามลำดับเดิม แต่งเพิ่ม D (Aspirin alone) และ E (Prophylactic IVC filter) และเติมเคสใน stem ทั้งหมด (อายุ 65, ประวัติ DVT 3 ปีก่อน, open colectomy จากมะเร็งลำไส้ใหญ่, bleeding risk ต่ำ)",
  mnemonic:"<b>Caprini 3 คะแนน = 3 อย่างที่เป็นเรื่องเลือดแข็งตัวในตัวคนไข้เอง</b>: เคยเป็น VTE, ญาติเป็น VTE, thrombophilia (+ อายุ ≥75)",
  guide:"ACCP Antithrombotic Therapy and Prevention of Thrombosis 9th ed. 2012 (non-orthopedic surgical patients); ASCO VTE prophylaxis and treatment in cancer 2023",
  opinion:"ไม่มีคีย์ — เราตอบ C (LMWH) ความมั่นใจสูงสำหรับ stem ที่เติม (Caprini 9, bleeding risk ต่ำ, ผ่าตัดมะเร็ง) และตรงกับคำอธิบายในไฟล์เฉลยที่ว่าผู้ที่เคยเป็น DVT ตอบ LMWH; ถ้าโจทย์จริงเป็นผู้ป่วยผ่าตัดทั่วไป VTE risk ต่ำถึงปานกลาง คำตอบจะเป็น IPC (A) หรือ ambulation (B) ตามที่ไฟล์เฉลยเขียน — จึงต้องเติมเคสให้เหลือคำตอบเดียว; สอดคล้องกับข้อสอบชุด 77A (high risk → LMWH) และชุด 76A, 76C (mechanical เมื่อเลือดออกง่ายหรือระหว่างผ่าตัด)",
  variants:["หญิงอายุ 35 ปี แข็งแรง ผ่าตัด laparoscopic cholecystectomy 40 นาที — DVT prophylaxis ที่เหมาะสม → early ambulation (Caprini ต่ำ)","ชายอายุ 70 ปี ผ่าตัด Whipple จากมะเร็งตับอ่อน ระหว่างผ่าตัดเสียเลือดมาก ยังมีเลือดซึมทาง drain — DVT prophylaxis ช่วงแรก → IPC ก่อน แล้วเริ่ม LMWH เมื่อเลือดหยุด","หญิงอายุ 60 ปี ผ่าตัด total abdominal hysterectomy จากมะเร็งรังไข่ ไม่มีเลือดออกผิดปกติ — ควรให้ LMWH นานเท่าไร → extended prophylaxis 4 สัปดาห์หลังผ่าตัด"]}),
A({page:2, page2:3, orig:"Pre-Op/Post-Op 4",
  stem:"A patient involved in a car accident received fluid resuscitation. A nasogastric tube and a Foley catheter were placed in the emergency department, and he has now been admitted to the ICU. His urine output over the last 3 hours was 50 mL, 0 mL and 0 mL. His BP has been 120/80 mmHg and HR 80/min throughout. What is the first, most appropriate management?",
  gray:"Patient has car accident. Was fluid resuscitated. Was put Ng and Foley from ER, now was admitted to ICU. Now Urine output @3,2,1 hr = 50ml 0ml 0 ml, BP 120/80 HR 80 bpm for 3 hours. what is the first most appropriate initial management — A. check foley catheter if it was blocked B. Observe for more 1 hour C. Increase fluid resus STAT",
  opts:["Check whether the Foley catheter is blocked","Observe for 1 more hour","Increase fluid resuscitation immediately","Give intravenous furosemide","Start low-dose dopamine infusion"],
  ans:0, key:"A check foley catheter if it was blocked"+KS,
  interp:"ปัสสาวะลดจาก 50 mL เป็น <b>0 mL ทันที</b> สองชั่วโมงติด ขณะที่ BP และ HR ปกติคงที่ — ถามสิ่งที่ต้องทำ <b>อันดับแรก</b> ก่อนจะสรุปว่าเป็น oliguria จาก hypovolemia หรือไต",
  why:"Anuria ที่เกิดขึ้น <b>ทันที</b> (ไม่ได้ค่อย ๆ ลด) ในผู้ป่วยที่ hemodynamics ปกติ ให้คิดถึง <b>สาเหตุทางกล</b> ก่อนเสมอ — สายพับ สายหลุดตำแหน่ง ลิ่มเลือดหรือตะกอนอุด ถุงแขวนสูงกว่ากระเพาะปัสสาวะ → ตรวจแนวสาย <b>flush สาย</b> หรือเปลี่ยนสาย และทำ <b>bladder scan</b> หรือคลำ/เคาะ bladder; การแก้ทำได้เร็ว ไม่เสี่ยง และถ้าไม่ทำอาจให้ fluid เกินหรือให้ยาโดยไม่จำเป็น; ในผู้ป่วย trauma ถ้าสายไม่อุดต้องคิดต่อถึง urethral หรือ bladder injury, rhabdomyolysis และ abdominal compartment syndrome",
  wrong:[
    "การรอดูอีก 1 ชั่วโมงเสียเวลาโดยไม่ได้หาสาเหตุ — 0 mL สองชั่วโมงติดต่อกันเป็นความผิดปกติที่ต้องประเมินทันที; จะถูกถ้าปัสสาวะลดลงเล็กน้อยแต่ยังออกอยู่ใกล้เป้าหมาย 0.5 mL/kg/hr และ hemodynamics ดี",
    "Fluid bolus เหมาะเมื่อมีหลักฐาน <b>hypovolemia</b> (HR เร็ว BP ต่ำ capillary refill ช้า lactate สูง ปัสสาวะค่อย ๆ ลด) — รายนี้ BP 120/80 HR 80 คงที่ ให้ fluid เพิ่มโดยไม่ตรวจสายก่อนเสี่ยง fluid overload; จะถูกถ้าสายไม่อุด bladder ว่าง และมี sign ของ hypoperfusion",
    "Furosemide ไม่รักษาหรือป้องกัน AKI และอาจทำให้ volume depletion แย่ลง; การบังคับให้ปัสสาวะออกไม่ได้แก้สาเหตุ; จะถูกถ้ามี fluid overload (pulmonary edema) ในผู้ป่วยที่ volume เกินชัดเจน",
    "Low-dose (\"renal-dose\") dopamine ไม่ป้องกันหรือรักษา AKI (KDIGO แนะนำไม่ใช้) และเพิ่ม arrhythmia; ไม่มีบริบทที่ถูก — vasopressor ใช้เมื่อ shock ที่ไม่ตอบสนองต่อ fluid"],
  trap:"เห็น urine output 0 แล้วรีบให้ fluid หรือ furosemide ทันที — ปัสสาวะที่หายไปทันทีในขณะที่สัญญาณชีพปกติ ให้ <b>ตรวจสายก่อน</b> เสมอ (สิ่งที่ง่ายที่สุดและพบบ่อยที่สุด)",
  summary:[
    "เป้าหมาย urine output ผู้ใหญ่ <b>0.5–1 mL/kg/hr</b> (เด็ก 1 mL/kg/hr, ทารก 2 mL/kg/hr)",
    "Oliguria หลังผ่าตัดหรือ trauma: ขั้นแรกตรวจ <b>catheter</b> (พับ อุด หลุด) + bladder scan → แล้วประเมิน volume status (HR, BP, CRT, lactate, ดู fluid balance) → ถ้า hypovolemia ให้ fluid challenge 250–500 mL แล้วประเมินซ้ำ",
    "แบ่งสาเหตุ: pre-renal (hypovolemia, ช็อก, abdominal compartment), renal (ATN, contrast, rhabdomyolysis, nephrotoxic drug), post-renal (สายอุด, urethral injury, ureteric injury)",
    "KDIGO AKI: creatinine เพิ่ม ≥0.3 mg/dL ใน 48 ชม. หรือ ≥1.5 เท่าใน 7 วัน หรือ urine &lt;0.5 mL/kg/hr นาน ≥6 ชม.",
    "Trauma: เลือดที่ meatus, scrotal hematoma, high-riding prostate → สงสัย urethral injury ห้ามใส่ Foley ก่อนทำ retrograde urethrogram; ปัสสาวะสีโคล่า → rhabdomyolysis เป้าหมาย urine 1–2 mL/kg/hr",
    "Furosemide และ low-dose dopamine ไม่ป้องกันหรือรักษา AKI",
    "ดูข้อ 10 (urine output เป้าหมาย), ข้อ 8 (fluid resuscitation ใน trauma)"],
  notes:"ไฟล์เฉลย บท Pre-Op/ Post-Op แถว 4: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับเป็นภาษาอังกฤษ จดช้อย 3 ตัว (A–C) — ช้อย D, E แต่งเพิ่ม; ต้นฉบับเขียน urine output \"@3,2,1 hr = 50ml 0ml 0 ml\" (ชั่วโมงที่ 3, 2, 1 ก่อนหน้า) และ \"Ng\" (= NG tube); ในไฟล์โจทย์บทนี้มีแถวข้อ 5 ว่าง (ไม่ใช่ข้อ)",
  mnemonic:"<b>Urine หายทันที = ดูสายก่อน</b>; urine ค่อย ๆ ลด = ดู volume",
  guide:"ATLS Advanced Trauma Life Support 10th ed. 2018; KDIGO Clinical Practice Guideline for Acute Kidney Injury 2012",
  opinion:"",
  variants:["ผู้ป่วยหลังผ่าตัด laparotomy 6 ชม. ปัสสาวะค่อย ๆ ลดจาก 40 เป็น 15 mL/hr HR 115 BP 95/60 สายไม่อุด — ทำอะไรต่อ → fluid challenge แล้วประเมินซ้ำ","ผู้ป่วยรถชนมีเลือดออกที่รูเปิดท่อปัสสาวะและ scrotal hematoma — ก่อนใส่ Foley ต้องทำอะไร → retrograde urethrogram","ผู้ป่วยถูกตึกถล่มทับขานาน 6 ชม. ปัสสาวะสีโคล่า CK สูงมาก — เป้าหมาย urine output → 1–2 mL/kg/hr (ประมาณ 200–300 mL/hr) ด้วย crystalloid ปริมาณมาก"]}),
A({page:2, page2:3, orig:"Hemostasis 1",
  flag:"⚠ ตอบต่างจากคีย์ตามตัวอักษร: ช้อยเดียวที่ผู้จดพิมพ์ (และคีย์ตอบ A) เรียง inflammation ก่อน hemostasis ซึ่งผิดลำดับ — น่าจะพิมพ์สลับ; เราตอบลำดับที่ถูก hemostasis → inflammation → proliferation → remodeling และใช้ข้อความต้นฉบับเป็นช้อย B",
  stem:"Which sequence correctly describes the phases of the wound healing response after injury?",
  gray:"ให้เรียง response ต่อแผล — A. Inflammation -&gt; Hemostasis -&gt; Proliferation -&gt; Modeling",
  opts:["Hemostasis, inflammation, proliferation, remodeling","Inflammation, hemostasis, proliferation, remodeling","Hemostasis, proliferation, inflammation, remodeling","Inflammation, proliferation, hemostasis, remodeling","Proliferation, hemostasis, inflammation, remodeling"],
  ans:0, key:"B Inflammation -&gt; Hemostasis -&gt; Proliferation -&gt; Modeling"+KS,
  interp:"ถามลำดับ <b>phase ของ wound healing</b> — ต้องรู้ว่าอะไรเกิดก่อน (หยุดเลือดก่อนเสมอ) และแต่ละ phase กินเวลาเท่าไร มีเซลล์อะไรเด่น",
  why:"<b>1) Hemostasis</b> (นาทีแรก): vasoconstriction, platelet adhesion และ aggregation, coagulation cascade → fibrin clot ซึ่งเป็นโครงให้เซลล์เข้ามา และ platelet ปล่อย PDGF, TGF-β เรียกเซลล์ → <b>2) Inflammation</b> (วัน 1–4): neutrophil เด่นใน 24–48 ชม. ตามด้วย <b>macrophage 48–96 ชม.</b> (เซลล์สำคัญที่สุด ขาดไม่ได้ ควบคุม phase ต่อไป) → <b>3) Proliferation</b> (วัน 4–21): fibroblast สร้าง collagen type III, angiogenesis, granulation tissue, epithelialization, wound contraction โดย myofibroblast → <b>4) Remodeling/maturation</b> (วัน 21 ถึง 1 ปี): collagen type III ถูกแทนด้วย type I, cross-linking, tensile strength สูงสุดราว <b>80%</b> ของผิวหนังเดิม",
  wrong:[
    "เรียง inflammation ก่อน hemostasis — ผิดเพราะการบาดเจ็บทำให้เลือดออก ร่างกายต้องหยุดเลือดก่อน และ platelet ใน clot เป็นตัวปล่อย cytokine ที่เรียก inflammatory cell เข้ามา; นี่คือช้อยที่ผู้จดพิมพ์และคีย์ตอบ (น่าจะพิมพ์สลับ); ไม่มีบริบทที่ลำดับนี้ถูก",
    "เอา proliferation มาก่อน inflammation — ผิดเพราะ fibroblast และ angiogenesis ต้องอาศัย growth factor จาก macrophage ใน inflammatory phase; ไม่มีบริบทที่ลำดับนี้ถูก",
    "เริ่มที่ inflammation และเอา hemostasis ไว้หลัง proliferation — ผิดทั้งสองจุด; ไม่มีบริบทที่ลำดับนี้ถูก",
    "เริ่มที่ proliferation — ผิดเพราะต้องมี fibrin matrix จาก hemostasis และ cytokine จาก inflammation ก่อนเซลล์จะ proliferate; ไม่มีบริบทที่ลำดับนี้ถูก"],
  trap:"ช้อยที่ผู้จดพิมพ์ขึ้นต้นด้วย inflammation — ระวังจำผิดตาม; บางตำราแบ่ง 3 phase (inflammatory ที่รวม hemostasis, proliferative, maturation) แต่ถ้าแยก hemostasis ออกมา ต้องมาก่อน inflammation เสมอ",
  summary:[
    "4 phase: <b>Hemostasis → Inflammation → Proliferation → Remodeling</b> (overlap กันได้)",
    "Hemostasis: vasoconstriction, platelet plug, fibrin clot; platelet ปล่อย PDGF, TGF-β",
    "Inflammation วัน 1–4: neutrophil 24–48 ชม. (ฆ่าเชื้อ เก็บกวาด), <b>macrophage 48–96 ชม. = เซลล์ที่ขาดไม่ได้</b>; lymphocyte ตามมา",
    "Proliferation วัน 4–21: fibroblast + collagen type III, angiogenesis (VEGF), granulation tissue, epithelialization, contraction โดย myofibroblast",
    "Remodeling วัน 21 ถึง 1 ปี: collagen III → I, cross-linking; tensile strength ราว 20% ที่ 3 สัปดาห์ และสูงสุดราว 80% ไม่กลับเท่าเดิม",
    "ปัจจัยที่ทำให้แผลหายช้า: infection, ischemia, เบาหวาน, steroid (ขัด inflammation แก้ด้วย vitamin A), malnutrition (protein, vitamin C, zinc), สูบบุหรี่, radiation",
    "ดูข้อ 14, 15 (การเลือกไหมเย็บ)"],
  notes:"ไฟล์เฉลย บท Hemostasis แถว 1: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดช้อยไว้ <b>ตัวเดียว</b> \"A. Inflammation -&gt; Hemostasis -&gt; Proliferation -&gt; Modeling\" (ผู้จดพิมพ์ inflammation ก่อน hemostasis และเขียน \"Modeling\" = remodeling) — ช้อยนี้คือช้อย B ของเรา; ช้อย A (ลำดับที่ถูก) และ C–E แต่งเพิ่ม",
  mnemonic:"<b>\"Hi Pro Rem\" ก่อนต้อง \"Hemo\"</b>: Hemostasis → Inflammation → Proliferation → Remodeling (เลือดหยุด → อักเสบ → สร้าง → ปรับ)",
  guide:"Sabiston Textbook of Surgery 21st ed.; Schwartz's Principles of Surgery 11th ed.",
  opinion:"คีย์ตอบ A ซึ่งเป็นช้อยเดียวที่ผู้จดพิมพ์ไว้ (inflammation → hemostasis → proliferation → modeling) ลำดับนี้ผิดตามตำรา — น่าจะเป็นการพิมพ์สลับตอนจด recall; เราเชื่อว่าข้อสอบจริงตอบลำดับ hemostasis → inflammation → proliferation → remodeling ความมั่นใจสูงมาก จึงใส่ลำดับที่ถูกเป็นช้อย A และใช้ข้อความต้นฉบับเป็นช้อย B (คีย์ตามตัวอักษรของเรา = B)",
  variants:["เซลล์ใดสำคัญที่สุดและขาดไม่ได้ในกระบวนการหายของแผล → macrophage","แผลผ่าตัดหน้าท้องหลังเย็บ 3 สัปดาห์ มี tensile strength ราวกี่เปอร์เซ็นต์ของเดิม → ประมาณ 20% (สูงสุดราว 80% หลังหลายเดือน)","ผู้ป่วยกิน prednisolone ระยะยาว แผลหายช้า — วิตามินใดช่วยแก้ฤทธิ์ steroid ต่อการหายของแผล → vitamin A"]}),
A({page:3, page2:3, orig:"Hemostasis 2",
  stem:"Warfarin reduces the activity of which coagulation factor?",
  gray:"ให้ Warfarin โดน Factor อะไร — A. Factor 1 B. Factor 5 C. Factor 9 D. Factor 11",
  opts:["Factor I","Factor V","Factor IX","Factor XI","Factor VIII"],
  ans:2, key:"C Factor 9"+KS,
  interp:"ถามกลไกของ <b>warfarin</b> — ยาออกฤทธิ์ต่อ factor ที่ต้องอาศัย vitamin K (II, VII, IX, X) ให้หาตัวที่อยู่ในกลุ่มนี้",
  why:"Warfarin เป็น <b>vitamin K antagonist</b> ยับยั้ง vitamin K epoxide reductase (<b>VKORC1</b>) → ไม่มี reduced vitamin K สำหรับ γ-carboxylation ของ glutamate บน <b>factor II, VII, IX, X</b> และ protein C, S → factor ที่สร้างออกมาจับ Ca²⁺ และ phospholipid ไม่ได้ ทำงานไม่ได้; ในช้อยมีแค่ <b>factor IX</b> ที่อยู่ในกลุ่มนี้; factor VII half-life สั้นสุด (~6 ชม.) จึงทำให้ PT/INR ยืดก่อน แต่ฤทธิ์ต้านการแข็งตัวเต็มที่ต้องรอ prothrombin (half-life ~60 ชม.) ลด ใช้เวลา 5 วัน",
  wrong:[
    "Factor I (fibrinogen) สร้างที่ตับแต่ <b>ไม่ต้องอาศัย vitamin K</b>; ลดลงใน DIC, massive transfusion, ตับวายรุนแรง หรือยา fibrinolytic; จะถูกถ้าถามเรื่อง cryoprecipitate หรือ fibrinogen concentrate",
    "Factor V ไม่ต้องอาศัย vitamin K (เป็น labile factor ลดในเลือดที่เก็บนาน); factor V Leiden คือการกลายพันธุ์ที่ต้าน activated protein C ทำให้เลือดแข็งง่าย; จะถูกถ้าถามสาเหตุ inherited thrombophilia ที่พบบ่อยในคนผิวขาว",
    "Factor XI อยู่ใน intrinsic pathway ไม่ต้องอาศัย vitamin K; ขาดแล้วเป็น hemophilia C (aPTT ยืด); จะถูกถ้าถามโรคเลือดออกง่ายที่ aPTT ยืดและพบบ่อยใน Ashkenazi Jew",
    "Factor VIII สร้างจาก endothelium (sinusoidal) ไม่ต้องอาศัย vitamin K; ขาดแล้วเป็น hemophilia A; จะถูกถ้าถามสาเหตุ aPTT ยืดในเด็กชายที่มี hemarthrosis"],
  trap:"จำว่า warfarin ทำให้ PT ยืดแล้วไปเลือก factor ของ extrinsic pathway อย่างเดียว — vitamin K-dependent factor ได้แก่ <b>2, 7, 9, 10</b> (มี IX ของ intrinsic ด้วย) + protein C, S; ช่วงแรกที่เริ่มยา protein C ลดก่อน → hypercoagulable จึงต้อง bridge ด้วย heparin",
  summary:[
    "Vitamin K-dependent: <b>factor II, VII, IX, X + protein C, S</b>; warfarin ยับยั้ง VKORC1",
    "ติดตามด้วย <b>PT/INR</b> (เป้า 2–3 สำหรับ AF, VTE; 2.5–3.5 สำหรับ mechanical mitral valve บางชนิด)",
    "เริ่มยา: protein C half-life สั้น ลดก่อน → hypercoagulable ช่วงแรก (warfarin skin necrosis ใน protein C deficiency) → bridge ด้วย heparin อย่างน้อย 5 วันจน INR อยู่ในเป้า 24 ชม.",
    "ก่อนผ่าตัด elective: หยุด warfarin 5 วัน ตรวจ INR ก่อนผ่าตัด; bridging เฉพาะ thrombotic risk สูง",
    "Reversal เลือดออกรุนแรงหรือผ่าตัดฉุกเฉิน: <b>vitamin K 5–10 mg IV + 4-factor PCC</b> (FFP ถ้าไม่มี PCC); INR สูงไม่มีเลือดออก → หยุดยา ± vitamin K กิน",
    "ยาเสริมฤทธิ์ warfarin: metronidazole, fluconazole, amiodarone, cotrimoxazole; ยาลดฤทธิ์: rifampicin, carbamazepine",
    "ดูข้อ 7, 9 (การแปลผล coagulation test)"],
  notes:"ไฟล์เฉลย บท Hemostasis แถว 2: <b>C</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดช้อย 4 ตัวเป็นเลขอารบิก (Factor 1, 5, 9, 11) — เราเขียนเป็นเลขโรมัน; ช้อย E (Factor VIII) แต่งเพิ่ม",
  mnemonic:"<b>1972</b> (เลข 10, 9, 7, 2) = factor ที่ต้องใช้ vitamin K; PT ยืดจาก warfarin = <b>\"WEPT\"</b> (Warfarin, Extrinsic, PT)",
  guide:"ACCP Antithrombotic Therapy 9th ed. 2012; ACC Expert Consensus Decision Pathway on Management of Bleeding in Patients on Oral Anticoagulants 2020",
  opinion:"",
  variants:["ผู้ป่วย AF กิน warfarin INR 8 มี GI bleeding และช็อก — การแก้ฤทธิ์ยาที่เร็วที่สุด → vitamin K IV + 4-factor PCC","ผู้ป่วยเริ่ม warfarin โดยไม่ได้ bridge วันที่ 3 มีผิวหนังเป็น purpura และเนื้อตายที่เต้านมและต้นขา — กลไกคืออะไร → protein C ลดก่อน factor อื่นทำให้ hypercoagulable (warfarin skin necrosis)","ผู้ป่วยกิน warfarin นัดผ่าตัด hernia elective — ควรหยุดยาก่อนกี่วัน → 5 วัน ตรวจ INR ก่อนผ่าตัด"]}),
A({page:3, page2:3, orig:"Hemostasis 3",
  stem:"A patient is started on a continuous intravenous unfractionated heparin infusion. Which test is used to monitor its effect?",
  gray:"Heparin monitor — A. aPTT B. PT",
  opts:["aPTT","PT","Bleeding time","Platelet count","D-dimer"],
  ans:0, key:"A aPTT"+KS,
  interp:"ถามการติดตามฤทธิ์ <b>unfractionated heparin</b> แบบหยดต่อเนื่อง — ต้องรู้ว่า heparin กระทบ pathway ไหนและการทดสอบไหนวัด pathway นั้น",
  why:"UFH จับ <b>antithrombin</b> เร่งฤทธิ์ยับยั้ง <b>thrombin (IIa)</b> และ <b>factor Xa</b> (รวมถึง IXa, XIa, XIIa) ซึ่งอยู่ใน intrinsic และ common pathway → วัดด้วย <b>aPTT</b> เป้าหมาย <b>1.5–2.5 เท่า</b> ของค่าควบคุม (หรือ anti-Xa 0.3–0.7 IU/mL); ตรวจ aPTT ทุก 6 ชม. หลังเริ่มหรือปรับขนาดยาจนคงที่; UFH half-life สั้น (60–90 นาที) แก้ด้วย <b>protamine sulfate</b> 1 mg ต่อ heparin 100 units",
  wrong:[
    "PT/INR ใช้ติดตาม <b>warfarin</b> (extrinsic pathway, factor VII); heparin ขนาดรักษาอาจยืด PT เล็กน้อยแต่ไม่ใช้ติดตาม; จะถูกถ้าโจทย์ถามการติดตาม warfarin",
    "Bleeding time วัด <b>platelet function</b> และผนังหลอดเลือด ไม่ไวต่อ heparin; จะถูกถ้าถามการประเมิน uremic platelet dysfunction หรือ von Willebrand disease (ปัจจุบันใช้ PFA-100 แทน)",
    "Platelet count ใช้เฝ้าระวัง <b>heparin-induced thrombocytopenia</b> (platelet ลด &gt;50% วันที่ 5–10) ไม่ได้วัดฤทธิ์ต้านการแข็งตัว; จะถูกถ้าถามสิ่งที่ต้องตรวจเป็นระยะเพื่อดู adverse effect ของ heparin",
    "D-dimer เป็น fibrin degradation product ใช้ <b>rule out VTE</b> เมื่อ pretest probability ต่ำ หรือประกอบการวินิจฉัย DIC ไม่ใช้ปรับขนาดยา; จะถูกถ้าถามการตรวจคัดกรอง DVT ใน Wells score ต่ำ"],
  trap:"สับสน <b>heparin = aPTT</b> กับ <b>warfarin = PT</b>; และ LMWH ไม่ต้องติดตาม routine (ถ้าจำเป็นใช้ anti-Xa ไม่ใช่ aPTT) ในไตวาย อ้วนมาก ตั้งครรภ์ เด็ก",
  summary:[
    "UFH: antithrombin-mediated ยับยั้ง IIa = Xa → ติดตาม <b>aPTT 1.5–2.5 เท่า</b> หรือ anti-Xa 0.3–0.7 IU/mL",
    "UFH ขนาดรักษา: bolus 80 units/kg แล้ว 18 units/kg/hr ปรับตาม nomogram; ข้อดีคือ half-life สั้น แก้ฤทธิ์ได้หมดด้วย protamine เหมาะกับไตวายและผู้ป่วยที่อาจต้องผ่าตัด",
    "LMWH (enoxaparin): ยับยั้ง Xa มากกว่า IIa ไม่ต้องติดตาม routine; anti-Xa ในไตวาย อ้วน ตั้งครรภ์; protamine แก้ได้บางส่วน",
    "Warfarin → PT/INR; Dabigatran → แก้ด้วย idarucizumab; rivaroxaban, apixaban → andexanet alfa หรือ 4F-PCC",
    "HIT: platelet ลด &gt;50% วัน 5–10 พร้อม thrombosis → หยุด heparin ทุกชนิด ให้ non-heparin anticoagulant (argatroban, fondaparinux) ห้ามให้ platelet transfusion",
    "ดูข้อ 6, 9 (coagulation test), ข้อ 3 (DVT prophylaxis)"],
  notes:"ไฟล์เฉลย บท Hemostasis แถว 3: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดโจทย์แค่ \"Heparin monitor\" และช้อย 2 ตัว (A. aPTT B. PT) — ช้อย C–E แต่งเพิ่ม, stem ขยายเป็นประโยคเต็มโดยไม่เปลี่ยนสิ่งที่ถาม; ในไฟล์โจทย์เลขข้อเขียนว่า \"3\" (ไม่มีจุด)",
  mnemonic:"<b>\"HIP\" vs \"WEPT\"</b>: Heparin = Intrinsic = PTT; Warfarin = Extrinsic = PT",
  guide:"ACCP Antithrombotic Therapy 9th ed. 2012",
  opinion:"",
  variants:["ผู้ป่วย PE ได้ UFH infusion aPTT 4 เท่าของค่าควบคุม มีเลือดออกจากแผล — ยาแก้ฤทธิ์คืออะไร → protamine sulfate","ผู้ป่วยได้ UFH วันที่ 7 platelet ลดจาก 250,000 เป็น 90,000 และเกิด DVT ใหม่ — ทำอะไร → หยุด heparin ทั้งหมด ให้ argatroban หรือ fondaparinux ส่ง anti-PF4 antibody","หญิงตั้งครรภ์ได้ enoxaparin ขนาดรักษา ต้องการติดตามระดับยา — ตรวจอะไร → anti-Xa level"]}),
A({page:3, page2:3, orig:"Hemostasis 4",
  flag:"⚠ เล็กน้อย: เติม \"while blood products are being prepared\" ใน stem — ถ้าโจทย์บอก class III–IV hemorrhage หรือไม่ตอบสนองต่อ crystalloid ต้องให้เลือด (ช้อย C)",
  stem:"After a car accident, a patient arrives hypotensive. While blood products are being prepared, which fluid should be given first for resuscitation?",
  gray:"car accident, hypotension resuscitation fluid ? — A. ringer acetate B. Dextrose C. Prc + nss",
  opts:["Ringer's acetate","5% dextrose in water","Packed red cells with normal saline","Hydroxyethyl starch","0.45% NaCl"],
  ans:0, key:"A ringer acetate"+KS,
  interp:"ผู้ป่วย trauma ที่ hypotension ถามสารน้ำที่ให้ <b>ก่อน</b> ในช่วงที่ยังไม่มีเลือด — ต้องเลือก <b>isotonic crystalloid</b> ที่อยู่ใน intravascular space ได้ดี (ข้อมูล \"ระหว่างรอเลือด\" เราเติมให้เหลือคำตอบเดียว)",
  why:"ATLS 10th ed.: initial fluid ใน hemorrhagic shock = <b>warmed isotonic crystalloid 1 L</b> ในผู้ใหญ่ (เด็ก 20 mL/kg) ผ่าน large-bore IV 2 เส้น แล้วประเมิน response (rapid, transient, non-responder); balanced crystalloid อย่าง <b>Ringer's acetate หรือ lactated Ringer's</b> มี Cl ใกล้ plasma ลด hyperchloremic metabolic acidosis เมื่อเทียบ NSS ปริมาณมาก; ถ้าเป็น transient หรือ non-responder หรือ class III–IV → ให้เลือดเร็ว (O-negative ระหว่างรอ crossmatch) ตาม massive transfusion protocol และ <b>หลีกเลี่ยง crystalloid ปริมาณมาก</b>",
  wrong:[
    "D5W เป็น <b>free water</b> เมื่อ glucose ถูก metabolize แล้ว กระจายทั่ว total body water เหลือใน intravascular แค่ราว 1/12 ไม่ช่วยเพิ่ม volume และทำให้ hyperglycemia, hyponatremia, สมองบวมในผู้ป่วย head injury; จะถูกถ้าโจทย์ถามสารน้ำสำหรับแก้ hypernatremia หรือ maintenance ร่วมกับ electrolyte",
    "PRC + NSS คือการให้เลือด — ถูกต้องเมื่อมี <b>class III–IV hemorrhage</b> หรือไม่ตอบสนองต่อ crystalloid 1 L และต้องให้ร่วมกับ plasma และ platelet (1:1:1) ไม่ใช่ PRC อย่างเดียว; เราเติม stem ว่าเลือดยังเตรียมไม่เสร็จจึงไม่ใช่คำตอบ; จะถูกถ้าโจทย์บอกว่าให้ crystalloid แล้วยังช็อกหรือเลือดพร้อมแล้ว",
    "Hydroxyethyl starch เพิ่ม <b>AKI, ความต้องการ renal replacement และ coagulopathy</b> ไม่ลดการเสียชีวิต — ไม่แนะนำใน trauma และ sepsis; ไม่มีบริบทที่ถูกในปัจจุบัน",
    "0.45% NaCl เป็น <b>hypotonic</b> อยู่ใน intravascular น้อย เพิ่มสมองบวม; ใช้เป็น maintenance fluid ร่วมกับ dextrose; จะถูกถ้าถามสารน้ำ maintenance หรือแก้ hypernatremia บางกรณี"],
  trap:"คิดว่าให้ crystalloid ไปเรื่อย ๆ จน BP ปกติ — ใน hemorrhagic shock ให้ crystalloid แค่ 1 L แล้วประเมิน ถ้าไม่ตอบสนองต้องให้เลือดและหยุดเลือด (crystalloid มากเกิน → dilutional coagulopathy, hypothermia, acidosis = lethal triad)",
  summary:[
    "Hemorrhagic shock class: I &lt;15% (HR ปกติ), II 15–30% (HR เร็ว pulse pressure แคบ), III 31–40% (BP ลด สับสน urine ลด), IV &gt;40% (BP ต่ำมาก ซึม ไม่มีปัสสาวะ)",
    "เริ่ม: 2 large-bore IV + warmed isotonic crystalloid <b>1 L</b> (เด็ก 20 mL/kg) แล้วดู response",
    "Rapid responder → ติดตาม; transient responder → ให้เลือด หาแหล่งเลือดออก; non-responder → เลือด + หยุดเลือดทันที (OR, angioembolization)",
    "Massive transfusion: PRC : FFP : platelet = <b>1:1:1</b>, ให้ <b>tranexamic acid ภายใน 3 ชม.</b> (1 g ใน 10 นาที แล้ว 1 g ใน 8 ชม.), แก้ hypothermia, calcium",
    "Permissive hypotension (SBP ~80–90 mmHg) จนกว่าจะหยุดเลือดได้ ยกเว้น traumatic brain injury (ต้องการ SBP ≥100–110)",
    "หลีกเลี่ยง D5W, hypotonic fluid และ starch ใน trauma resuscitation",
    "ดูข้อ 93 (เลือดฉุกเฉินเมื่อไม่ทราบหมู่เลือด), ข้อ 4 (urine output หลัง resuscitation)"],
  notes:"ไฟล์เฉลย บท Hemostasis แถว 4: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดโจทย์สั้น ๆ ลงท้ายด้วย \"?\" (\"car accident, hypotension resuscitation fluid ?\") และช้อย 3 ตัว (A. ringer acetate B. Dextrose C. Prc + nss) — เราเติมใน stem ว่า \"ระหว่างรอเตรียมเลือด\" และแต่งช้อย D, E; ช้อย B ต้นฉบับเขียนแค่ \"Dextrose\" เราเขียนเป็น 5% dextrose in water",
  mnemonic:"<b>1 L แล้วดูผล</b> — ไม่ดีขึ้นให้ <b>1:1:1 + TXA</b> ภายใน 3 ชม.",
  guide:"ATLS Advanced Trauma Life Support 10th ed. 2018",
  opinion:"เห็นด้วยกับคีย์ A ความมั่นใจปานกลางถึงสูง — ต้นฉบับไม่ได้บอกความรุนแรงของการเสียเลือด; ถ้าข้อสอบจริงให้ข้อมูลว่าเป็น class III–IV หรือให้ crystalloid ไปแล้วไม่ตอบสนอง คำตอบควรเป็นการให้เลือด (ช้อย C) จึงเติมใน stem ว่าเลือดยังเตรียมไม่เสร็จ; สอดคล้องกับข้อสอบชุด 77C (LRS ระหว่างรอเลือด) และชุด 76D (RL 3 L แล้วยังช็อก → PRC + FFP)",
  variants:["ผู้ป่วยรถชน BP 80/50 HR 130 ได้ LRS 1 L แล้ว BP ขึ้นเป็น 100/60 สักพักลดลงเป็น 80/50 อีก — ทำอะไรต่อ → transient responder ให้เลือด (MTP 1:1:1) และหาแหล่งเลือดออกเพื่อหยุดเลือด","ผู้ป่วย trauma ที่ต้องได้เลือดปริมาณมาก ยาใดที่ควรให้ภายใน 3 ชั่วโมงหลังบาดเจ็บ → tranexamic acid","ผู้ป่วย trauma มี head injury รุนแรงร่วมกับเลือดออกในช่องท้อง — เป้าหมาย BP ระหว่าง resuscitation → ไม่ทำ permissive hypotension รักษา SBP ≥100–110 mmHg"]}),
A({page:3, page2:3, orig:"Hemostasis 5",
  stem:"A patient with end-stage renal disease has normal aPTT and PT, a prolonged bleeding time and a normal platelet count. What is the most likely cause?",
  gray:"คนไข้ esrd normal aptt pt, prolonged bleeding time, platelet normal ถามว่าเป็นรัย — A. Uremic platelet function B. Thrombocytopenia",
  opts:["Uremic platelet dysfunction","Thrombocytopenia","Hemophilia A","Vitamin K deficiency","Disseminated intravascular coagulation"],
  ans:0, key:"A Uremic platelet function"+KS,
  interp:"แปลผล coagulation profile: <b>PT, aPTT ปกติ</b> (coagulation factor ปกติ), <b>platelet count ปกติ</b>, แต่ <b>bleeding time ยืด</b> → ปัญหาอยู่ที่ <b>การทำงานของ platelet</b> ในผู้ป่วย ESRD",
  why:"Uremia: uremic toxin (guanidinosuccinic acid, phenolic acid) และ nitric oxide ที่เพิ่มขึ้น ทำให้ <b>platelet adhesion และ aggregation บกพร่อง</b> (การทำงานของ GP IIb/IIIa และการจับ vWF ลด) ร่วมกับ anemia (RBC น้อยทำให้ platelet ไม่ถูกดันไปชิดผนังหลอดเลือด) → bleeding time ยืดแม้จำนวน platelet ปกติ; รักษาเมื่อมีเลือดออกหรือก่อนหัตถการ: <b>dialysis</b>, <b>desmopressin (DDAVP) 0.3 µg/kg IV</b> (ออกฤทธิ์ภายใน ~1 ชม. นาน 4–8 ชม. เพิ่ม vWF, factor VIII จาก endothelium; ให้ซ้ำแล้ว tachyphylaxis), cryoprecipitate, conjugated estrogen (ออกฤทธิ์ช้าแต่นาน), แก้ anemia ให้ Hct ราว 30% (EPO หรือ PRC)",
  wrong:[
    "Thrombocytopenia ทำให้ bleeding time ยืดได้แต่ต้องมี <b>platelet count ต่ำ</b> — โจทย์บอก platelet ปกติ; จะถูกถ้า platelet &lt;100,000 และมักมีเลือดออกเมื่อ &lt;50,000",
    "Hemophilia A (factor VIII deficiency) ทำให้ <b>aPTT ยืด</b> PT และ bleeding time ปกติ อาการเลือดออกในข้อและกล้ามเนื้อ; จะถูกถ้าเด็กชายมี hemarthrosis และ aPTT ยืดแก้ได้ด้วย mixing study",
    "Vitamin K deficiency ทำให้ <b>PT ยืดก่อน</b> (factor VII half-life สั้น) และ aPTT ยืดเมื่อรุนแรง bleeding time ปกติ; จะถูกถ้าผู้ป่วยกินไม่ได้นาน ได้ antibiotic, obstructive jaundice หรือ malabsorption",
    "DIC ทำให้ <b>ทุกค่าผิดปกติ</b>: PT, aPTT ยืด, platelet ต่ำ, fibrinogen ต่ำ, D-dimer สูง; จะถูกถ้ามี sepsis หรือ trauma รุนแรงร่วมกับเลือดออกหลายตำแหน่ง"],
  trap:"เห็น ESRD แล้วนึกถึง heparin ที่ได้ระหว่าง hemodialysis (aPTT จะยืด) — โจทย์บอก aPTT ปกติ; ESRD ที่มี bleeding time ยืดแต่ platelet ปกติ = <b>qualitative platelet defect</b>",
  summary:[
    "แปลผล: PT ยืดอย่างเดียว → extrinsic (factor VII, warfarin, vitamin K deficiency, ตับ); aPTT ยืดอย่างเดียว → intrinsic (VIII, IX, XI, XII, heparin, lupus anticoagulant); ทั้งคู่ยืด → common pathway, DIC, ตับวายรุนแรง",
    "Bleeding time ยืด + platelet ปกติ + PT/aPTT ปกติ → <b>platelet dysfunction</b>: uremia, aspirin, clopidogrel, von Willebrand disease (aPTT อาจยืด), Glanzmann, Bernard-Soulier",
    "Uremic bleeding รักษา: dialysis, <b>DDAVP 0.3 µg/kg</b>, cryoprecipitate, conjugated estrogen, แก้ anemia (Hct ~30%)",
    "ก่อนผ่าตัดในผู้ป่วย ESRD: dialysis ภายใน 24 ชม. ก่อนผ่าตัด (แก้ K, volume, uremia) และระวังการให้ heparin ระหว่าง dialysis",
    "Aspirin ยับยั้ง COX-1 แบบถาวร ฤทธิ์อยู่ตลอดอายุ platelet 7–10 วัน; หยุด 7 วันก่อนผ่าตัดที่เสี่ยงเลือดออกสูง",
    "ดูข้อ 6, 7 (coagulation test และยา anticoagulant)"],
  notes:"ไฟล์เฉลย บท Hemostasis แถว 5: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับลงท้ายโจทย์ว่า \"ถามว่าเป็นรัย\" (ภาษาพูด) และจดช้อย 2 ตัว (A. Uremic platelet function B. Thrombocytopenia) — เราเขียนช้อย A เป็น Uremic platelet dysfunction และแต่งช้อย C–E",
  mnemonic:"<b>\"DDAVP + Dialysis + Cryo + Estrogen + EPO\"</b> = 5 ทางรักษา uremic bleeding",
  guide:"Schwartz's Principles of Surgery 11th ed.",
  opinion:"",
  variants:["ผู้ป่วย ESRD จะทำ tunneled catheter แต่ bleeding time ยืด platelet ปกติ — ยาที่ออกฤทธิ์เร็วที่สุดเพื่อลดเลือดออก → desmopressin 0.3 µg/kg IV","ผู้ป่วยมี obstructive jaundice นาน 1 เดือน PT ยืด aPTT ปกติ — สาเหตุและการแก้ → vitamin K deficiency ให้ vitamin K parenteral","ชายอายุ 20 ปี เลือดออกนานหลังถอนฟัน aPTT ยืด PT ปกติ bleeding time ยืด platelet ปกติ — นึกถึงโรคใด → von Willebrand disease"]}),
A({page:3, page2:3, orig:"Fluid and Electrolyte 1",
  stem:"What is the target urine output for a 60-kg adult patient?",
  gray:"คนไข้หนัก 60 kg, urine output เท่าไหร่ดี — A. 30-60 cc/hr B. 5-10 cc/kg/hr C. 5-10 cc/hr",
  opts:["30–60 mL/hr","5–10 mL/kg/hr","5–10 mL/hr","100–150 mL/hr","200–300 mL/hr"],
  ans:0, key:"A 30-60 cc/hr"+KS,
  interp:"ถามเป้าหมาย <b>urine output ของผู้ใหญ่</b> คิดจากน้ำหนัก — สูตร 0.5–1 mL/kg/hr",
  why:"ผู้ใหญ่เป้าหมาย <b>0.5–1 mL/kg/hr</b> → 60 kg × 0.5–1 = <b>30–60 mL/hr</b> ซึ่งสะท้อนว่า renal perfusion และ end-organ perfusion เพียงพอ ใช้เป็นตัวชี้วัด resuscitation ที่สำคัญร่วมกับ HR, BP, mental status, capillary refill และ lactate; ต่ำกว่า 0.5 mL/kg/hr นาน ≥6 ชม. เข้าเกณฑ์ <b>KDIGO AKI stage 1</b>",
  wrong:[
    "5–10 mL/kg/hr = 300–600 mL/hr ใน 60 kg สูงเกินจริงมาก (เป็น polyuria) — พบใน diabetes insipidus, osmotic diuresis หรือระยะ diuretic ของ ATN; ไม่มีบริบทที่เป็นเป้าหมาย",
    "5–10 mL/hr ต่ำกว่าเกณฑ์มาก = <b>oliguria</b> (&lt;0.5 mL/kg/hr) ต้องประเมินหาสาเหตุทันที; จะถูกถ้าถามค่าที่เข้าเกณฑ์ oliguria หรือ AKI",
    "100–150 mL/hr ราว 1.7–2.5 mL/kg/hr สูงกว่าเป้าหมายมาตรฐาน — เป็นเป้าหมายใน <b>rhabdomyolysis</b> หรือ electrical burn ที่มี myoglobinuria (ผู้ใหญ่ราว 75–100 mL/hr ขึ้นไป); จะถูกถ้าโจทย์เป็นผู้ป่วยถูกไฟฟ้าแรงสูงหรือ crush injury",
    "200–300 mL/hr = 3–5 mL/kg/hr สูงเกิน แสดงถึงการให้สารน้ำมากเกินหรือ polyuria; เป้าหมายใน crush syndrome บางแนวทาง (ปัสสาวะ ~200–300 mL/hr ระยะแรก) แต่ไม่ใช่เป้าหมายผู้ป่วยทั่วไป; จะถูกถ้าโจทย์เป็น crush syndrome ที่ต้องการ forced diuresis"],
  trap:"จำหน่วยสลับ (mL/kg/hr กับ mL/hr) — <b>ผู้ใหญ่ 0.5 mL/kg/hr</b>, เด็ก 1 mL/kg/hr, ทารก 1–2 mL/kg/hr; ต้องคูณน้ำหนักก่อนเทียบช้อย",
  summary:[
    "Urine output เป้าหมาย: ผู้ใหญ่ <b>0.5–1 mL/kg/hr</b> (ประมาณ 30–50 mL/hr ในคน 60–70 kg), เด็ก 1 mL/kg/hr, ทารก &lt;1 ปี 1–2 mL/kg/hr",
    "Burn ผู้ใหญ่: 0.5 mL/kg/hr (30–50 mL/hr); เด็ก ≤30 kg 1 mL/kg/hr; electrical burn หรือ myoglobinuria: 1 mL/kg/hr (75–100 mL/hr) จนปัสสาวะใส",
    "KDIGO AKI ตาม urine: stage 1 &lt;0.5 mL/kg/hr 6–12 ชม., stage 2 &lt;0.5 ≥12 ชม., stage 3 &lt;0.3 ≥24 ชม. หรือ anuria ≥12 ชม.",
    "Maintenance fluid ผู้ใหญ่ราว 25–30 mL/kg/วัน หรือสูตร 4-2-1 (100 mL/hr ใน 60 kg)",
    "Urine output ลดทันที → ตรวจสาย Foley ก่อน; ลดค่อยเป็นค่อยไป → ประเมิน volume",
    "ดูข้อ 4 (oliguria ใน ICU), ข้อ 11, 12, 13 (fluid และ electrolyte)"],
  notes:"ไฟล์เฉลย บท Fluid and Electrolyte แถว 1: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับใช้หน่วย cc (= mL) และจดช้อย 3 ตัว (A. 30-60 cc/hr B. 5-10 cc/kg/hr C. 5-10 cc/hr) — ช้อย D, E แต่งเพิ่ม",
  mnemonic:"<b>\"ผู้ใหญ่ครึ่ง เด็กหนึ่ง ทารกสอง\"</b> (mL/kg/hr)",
  guide:"KDIGO Clinical Practice Guideline for Acute Kidney Injury 2012; ATLS Advanced Trauma Life Support 10th ed. 2018",
  opinion:"เห็นด้วยกับคีย์ A ความมั่นใจสูง — สอดคล้องกับข้อสอบชุด 77C เรื่องเดียวกัน (60 kg → 30–60 mL/hr) และชุด 76A (50 kg → 30–50 mL/hr)",
  variants:["ผู้ป่วยหนัก 80 kg ถูกไฟไหม้ 40% TBSA — เป้าหมาย urine output ระหว่าง resuscitation → 0.5 mL/kg/hr คือ 40 mL/hr (ช่วง 30–50)","เด็กหนัก 20 kg หลังผ่าตัด ปัสสาวะ 10 mL/hr — เพียงพอหรือไม่ → ไม่พอ (เป้าหมาย 1 mL/kg/hr = 20 mL/hr)","ผู้ป่วย 70 kg ถูกไฟฟ้าแรงสูง ปัสสาวะสีแดงเข้ม — เป้าหมาย urine output → ราว 1 mL/kg/hr (75–100 mL/hr) จนปัสสาวะใส"]}),
A({page:3, page2:3, orig:"Fluid and Electrolyte 2",
  stem:"In which condition is metabolic alkalosis LEAST likely to be found?",
  gray:"Which is LEAST likely to find metabolic alkalosis — A. vomiting B. Diuretics C. HypoK D. Hemorrhagic shock E. Volume depletion",
  opts:["Vomiting","Diuretic use","Hypokalemia","Hemorrhagic shock","Volume depletion"],
  ans:3, key:"D Hemorrhagic shock"+KS,
  interp:"คำถามปฏิเสธ (<b>LEAST likely</b>) — หาภาวะที่ทำให้เกิด acid-base แบบอื่น ไม่ใช่ metabolic alkalosis",
  why:"Hemorrhagic shock → tissue hypoperfusion → anaerobic metabolism → <b>lactic acidosis (high anion gap metabolic acidosis)</b> ซึ่งเป็นตัวบ่งชี้ความรุนแรงของช็อก (lactate, base deficit) ใช้ติดตาม resuscitation; ช้อยอื่นทั้งหมดเป็นสาเหตุหรือตัวคงสภาพของ metabolic alkalosis",
  wrong:[
    "Vomiting หรือ NG suction เสีย <b>HCl</b> → hypochloremic hypokalemic metabolic alkalosis; volume depletion กระตุ้น aldosterone ไตดูด Na แลก K และ H⁺ → <b>paradoxical aciduria</b>; เป็นสาเหตุคลาสสิก (gastric outlet obstruction, pyloric stenosis)",
    "Loop และ thiazide diuretics → เสีย NaCl และน้ำ (<b>contraction alkalosis</b>), เพิ่ม aldosterone, เสีย K และ H⁺ ทางปัสสาวะ → metabolic alkalosis; จะไม่ใช่ถ้าเป็น acetazolamide หรือ spironolactone (ทำให้ acidosis)",
    "Hypokalemia → K ออกจากเซลล์แลก H⁺ เข้าเซลล์, ไตเพิ่ม H⁺ secretion และ HCO₃⁻ reabsorption และสร้าง ammonium มากขึ้น → <b>คงสภาพ metabolic alkalosis</b>; ต้องแก้ K ร่วมด้วยจึงหาย",
    "Volume depletion (chloride depletion) → ไตดูด Na และ HCO₃⁻ กลับมากขึ้น เพิ่ม aldosterone → <b>contraction alkalosis</b> และคงสภาพ alkalosis; แก้ด้วย 0.9% NaCl (chloride-responsive)"],
  trap:"เห็น \"volume depletion\" กับ \"hemorrhagic shock\" แล้วคิดว่าเหมือนกัน — volume depletion แบบเสียน้ำและ Cl (ไม่ช็อก) → alkalosis แต่ hemorrhagic shock ที่ perfusion ไม่พอ → <b>lactic acidosis</b>; หลังได้เลือดปริมาณมาก citrate ถูกเปลี่ยนเป็น HCO₃⁻ จึงเกิด metabolic alkalosis ภายหลังได้",
  summary:[
    "Metabolic alkalosis แบ่งตาม urine Cl: <b>chloride-responsive</b> (urine Cl &lt;20: vomiting, NG suction, diuretic ที่หยุดแล้ว, contraction) → ให้ 0.9% NaCl + KCl; <b>chloride-resistant</b> (urine Cl &gt;20: hyperaldosteronism, Cushing, Bartter, Gitelman, diuretic ที่ยังใช้อยู่)",
    "Vomiting หรือ gastric outlet obstruction: <b>hypochloremic hypokalemic metabolic alkalosis + paradoxical aciduria</b>",
    "ปัจจัยคงสภาพ alkalosis: volume depletion, Cl depletion, hypokalemia, aldosterone สูง",
    "Shock ทุกชนิดที่ hypoperfusion → lactic acidosis (HAGMA); lactate &gt;2 mmol/L ผิดปกติ, &gt;4 รุนแรง; base deficit ใช้แบ่งระดับช็อก",
    "หลัง massive transfusion: citrate → HCO₃⁻ เกิด metabolic alkalosis ได้ และ citrate จับ Ca → hypocalcemia",
    "ดูข้อ 10, 12, 13 (fluid และ electrolyte), ข้อ 8 (hemorrhagic shock)"],
  notes:"ไฟล์เฉลย บท Fluid and Electrolyte แถว 2: <b>D</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดครบ 5 ช้อย เป็นภาษาอังกฤษ; ช้อย C ต้นฉบับเขียน \"HypoK\" (= hypokalemia), ช้อย B \"Diuretics\" เราเขียนเป็น Diuretic use",
  mnemonic:"<b>\"อาเจียน ขับปัสสาวะ K ต่ำ ขาดน้ำ = ด่าง; ช็อก = กรด (lactate)\"</b>",
  guide:"Schwartz's Principles of Surgery 11th ed.",
  opinion:"เห็นด้วยกับคีย์ D ความมั่นใจสูง — สอดคล้องกับข้อสอบชุด 77A และ 77D เรื่อง vomiting → metabolic alkalosis",
  variants:["ชายอายุ 60 ปี มี gastric outlet obstruction อาเจียนมา 1 สัปดาห์ — คาดว่าจะพบ acid-base แบบใด → hypochloremic hypokalemic metabolic alkalosis ร่วมกับ paradoxical aciduria","ผู้ป่วย trauma ช็อกนาน 2 ชั่วโมงก่อนถึงโรงพยาบาล — blood gas คาดว่าจะพบอะไร → high anion gap metabolic acidosis จาก lactate","ผู้ป่วย metabolic alkalosis จาก NG suction ควรให้สารน้ำใด → 0.9% NaCl ร่วมกับ KCl"]}),
A({page:4, page2:3, orig:"Fluid and Electrolyte 3",
  stem:"Which of the following is NOT a third-space fluid loss?",
  gray:"Which one is not 3rd space loss — A. Ascites B. Pleural effusion C. Peripheral edema D. Oozing burn E. Fluid leak in small bowel",
  opts:["Ascites","Pleural effusion","Peripheral edema","Oozing from a burn wound","Fluid leak into the small bowel"],
  ans:3, key:"D Oozing burn"+KS,
  interp:"คำถามปฏิเสธ — แยก <b>third-space loss</b> (สารน้ำยังอยู่ในร่างกายแต่ไม่อยู่ใน functional ECF) ออกจาก <b>external loss</b> (สารน้ำออกนอกร่างกาย)",
  why:"Third space = ECF ที่ย้ายออกจาก intravascular และ functional interstitial ไปอยู่ในช่องที่ไม่แลกเปลี่ยนกับ circulation (interstitial edema, ช่องท้อง, ช่องอก, lumen และผนังลำไส้ใน obstruction หรือ ileus, retroperitoneum ใน pancreatitis, tissue edema ใน burn หรือ crush) — สารน้ำ <b>ยังอยู่ในร่างกาย</b> และกลับคืนสู่ circulation ระยะ mobilization (ราววันที่ 3–5 หลังผ่าตัดทำให้ปัสสาวะออกมาก); ส่วน <b>สารน้ำที่ซึมออกจากผิวแผลไหม้</b> (exudate และ evaporative loss) ออกนอกร่างกายแล้ว = <b>external loss</b> ไม่ใช่ third space",
  wrong:[
    "Ascites คือสารน้ำสะสมในช่องท้อง (peritonitis, ตับแข็ง, หลังผ่าตัดใหญ่) ยังอยู่ในร่างกายแต่ไม่ได้อยู่ใน functional ECF = <b>third space</b>",
    "Pleural effusion สารน้ำสะสมในช่องเยื่อหุ้มปอด = <b>third space</b> (เป็นช่องที่ไม่มีส่วนร่วมใน circulation)",
    "Peripheral edema = สารน้ำรั่วเข้า interstitial space มากเกินจาก capillary leak (sepsis, burn, ผ่าตัดใหญ่) หรือ oncotic pressure ต่ำ = <b>third space</b>",
    "Fluid ที่รั่วเข้าใน lumen และผนังของลำไส้ใน bowel obstruction หรือ ileus = <b>third space</b> คลาสสิก (ลำไส้ที่อุดตันสะสมน้ำได้หลายลิตร) แม้จะอยู่ใน lumen แต่ยังไม่ออกนอกร่างกาย; จะเป็น external loss เมื่ออาเจียนหรือดูดออกทาง NG"],
  trap:"Burn เกี่ยวข้องทั้งสองแบบ — <b>edema ในเนื้อเยื่อที่ไหม้ = third space</b> แต่ <b>น้ำที่ซึมหรือระเหยออกจากผิวแผล = external loss</b>; โจทย์ถาม \"oozing\" จึงเป็น external",
  summary:[
    "Body water: TBW ราว 60% ของน้ำหนักชาย (หญิง 50%) = ICF 2/3 (40%) + ECF 1/3 (20%) แบ่งเป็น interstitial 15% และ plasma 5%",
    "Third space: สารน้ำอยู่ในร่างกายแต่ไม่ functional — interstitial edema, ascites, pleural effusion, bowel obstruction, ileus, pancreatitis, peritonitis, crush และ burn tissue edema, ผ่าตัดใหญ่",
    "External loss: vomiting, NG suction, diarrhea, fistula, stoma, เลือดออก, evaporation จากแผลไหม้และการหายใจ, เหงื่อ",
    "Third space ทำให้ intravascular volume ลดได้ แม้น้ำหนักตัวไม่ลด → ต้องทดแทนด้วย isotonic crystalloid (LRS)",
    "Mobilization ของ third-space fluid ราววันที่ 3–5 หลังผ่าตัด → ปัสสาวะออกมาก ต้องลด IV fluid ไม่เช่นนั้นเกิด fluid overload โดยเฉพาะผู้ป่วยโรคหัวใจหรือไต",
    "ดูข้อ 10, 11, 13 (fluid และ electrolyte)"],
  notes:"ไฟล์เฉลย บท Fluid and Electrolyte แถว 3: <b>D</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดครบ 5 ช้อยเป็นภาษาอังกฤษ; ช้อย D ต้นฉบับเขียน \"Oozing burn\" เราเขียนเป็น Oozing from a burn wound, ช้อย E \"Fluid leak in small bowel\" เขียนเป็น Fluid leak into the small bowel",
  mnemonic:"<b>\"ยังอยู่ในตัว = third space; ออกนอกตัว = external\"</b>",
  guide:"Schwartz's Principles of Surgery 11th ed.",
  opinion:"",
  variants:["ผู้ป่วย small bowel obstruction อาเจียนไม่มาก แต่ HR เร็ว ปัสสาวะออกน้อย — สารน้ำไปอยู่ที่ใด → third space ในผนังและ lumen ของลำไส้ ทดแทนด้วย isotonic crystalloid","ผู้ป่วยหลังผ่าตัด Whipple วันที่ 4 ปัสสาวะออกมากขึ้นเองโดยไม่ได้ให้ยาขับปัสสาวะ — อธิบายอย่างไร → mobilization ของ third-space fluid ควรลด IV fluid","ผู้ป่วย severe acute pancreatitis ต้องการสารน้ำมากในวันแรก — สาเหตุหลักของการเสียสารน้ำ → third space ใน retroperitoneum และ capillary leak"]}),
A({page:4, page2:3, orig:"Fluid and Electrolyte 4",
  stem:"A patient with chronic hyponatremia receives sodium correction that is too rapid. Which complication may occur?",
  gray:"ให้ Na ไวเกินไป เกิดอะไรขึ้น — A. Cerebral Pontine myelinolysis",
  opts:["Central pontine myelinolysis","Cerebral edema","Acute kidney injury","Generalized muscle weakness","Hyperkalemia"],
  ans:0, key:"A Cerebral Pontine myelinolysis"+KS,
  interp:"ถามภาวะแทรกซ้อนจากการ <b>แก้ hyponatremia เร็วเกินไป</b> — ทิศทางการแก้ (Na ขึ้นเร็ว) เป็นตัวตัดสิน",
  why:"ใน <b>chronic hyponatremia (&gt;48 ชม.)</b> เซลล์สมองปรับตัวโดยขับ osmolyte (glutamate, myo-inositol, taurine) ออกเพื่อลดบวม — ถ้าเพิ่ม serum Na เร็ว extracellular osmolality ขึ้นเร็วกว่าที่เซลล์จะสร้าง osmolyte กลับ น้ำจึงออกจากเซลล์ → oligodendrocyte เสียหาย → <b>osmotic demyelination syndrome</b> (central pontine และ extrapontine myelinolysis); อาการล่าช้า <b>2–6 วัน</b> หลังแก้: dysarthria, dysphagia, quadriparesis, behavioral change, locked-in syndrome; เสี่ยงสูงใน Na ≤105, alcoholism, malnutrition, hypokalemia, liver disease",
  wrong:[
    "Cerebral edema เกิดจากการ <b>ลด Na เร็วเกิน</b> (แก้ hypernatremia เร็วด้วยน้ำ) หรือ acute hyponatremia ที่ไม่ได้รักษา — ทิศทางตรงข้ามกับโจทย์; จะถูกถ้าโจทย์ถามผลของการให้ D5W เร็วในผู้ป่วย hypernatremia เรื้อรัง",
    "AKI ไม่ใช่ผลของการแก้ Na เร็ว; จะถูกถ้าโจทย์เป็น rhabdomyolysis, hypovolemia หรือ nephrotoxic drug",
    "Weakness ทั่วไปเป็นอาการของ electrolyte ผิดปกติหลายชนิด (hypokalemia, hypophosphatemia, hypermagnesemia) ไม่จำเพาะ — ODS ทำให้ quadriparesis จาก pons แต่ช้อยนี้ไม่ได้ระบุกลไก; จะถูกถ้าโจทย์ถามอาการของ hypokalemia",
    "Hyperkalemia ไม่สัมพันธ์กับการแก้ Na; จะถูกถ้าโจทย์เป็น AKI, rhabdomyolysis, succinylcholine ใน burn หรือ massive transfusion"],
  trap:"สับสนทิศทาง — <b>\"Low to high, pons will die; high to low, brains will blow\"</b>; ต้นฉบับเขียน \"Cerebral\" pontine myelinolysis แต่ชื่อจริงคือ <b>Central</b> pontine myelinolysis",
  summary:[
    "Hyponatremia อาการรุนแรง (ชัก ซึม) → 3% NaCl 100–150 mL IV ใน 10–20 นาที ซ้ำได้ เป้าเพิ่ม Na 4–6 mEq/L ใน 1–2 ชม. แรกเพื่อหยุดอาการ",
    "เพดานการแก้: European 2014 ≤10 mmol/L ใน 24 ชม.แรก และ ≤8 ในแต่ละ 24 ชม.ต่อมา; US 2013 เพดาน 10–12 mEq/L ต่อ 24 ชม. (กลุ่มเสี่ยงสูง ≤8)",
    "กลุ่มเสี่ยง ODS: chronic &gt;48 ชม., Na ≤105, alcoholism, malnutrition, hypokalemia, liver disease",
    "ODS อาการล่าช้า 2–6 วัน: dysarthria, dysphagia, quadriparesis, locked-in; MRI พบ T2 hyperintensity ที่ pons",
    "ถ้าแก้เกินเพดาน → re-lower ด้วย D5W ± desmopressin",
    "Hypernatremia: แก้ช้า ≤10–12 mEq/L ต่อวัน ถ้าลดเร็วเกินในรายเรื้อรัง → cerebral edema",
    "ดูข้อ 10, 11, 12 (fluid และ electrolyte)"],
  notes:"ไฟล์เฉลย บท Fluid and Electrolyte แถว 4: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดช้อยไว้ <b>ตัวเดียว</b> \"A. Cerebral Pontine myelinolysis\" — ชื่อที่ถูกคือ <b>Central</b> pontine myelinolysis (ปัจจุบันเรียก osmotic demyelination syndrome); ช้อย B–E แต่งเพิ่ม; stem เติมคำว่า chronic hyponatremia เพื่อให้เป็นประโยคเต็ม; ในไฟล์โจทย์บทนี้มีแถวข้อ 5 ว่าง (ไม่ใช่ข้อ)",
  mnemonic:"<b>\"From low to high, the pons will die; from high to low, the brains will blow\"</b>",
  guide:"European Clinical Practice Guideline on diagnosis and treatment of hyponatraemia 2014; US Expert Panel Recommendations on hyponatremia 2013",
  opinion:"เห็นด้วยกับคีย์ A ความมั่นใจสูง — ตรงกับข้อสอบชุด 77D เรื่องเดียวกัน (แก้ Na เร็วเกิน → CPM)",
  variants:["หญิงอายุ 70 ปี Na 112 จาก thiazide มา 1 สัปดาห์ ไม่มีอาการรุนแรง — ใน 24 ชม.แรกควรเพิ่ม Na ไม่เกินเท่าไร → ราว 8 mEq/L (กลุ่มเสี่ยงสูง)","ผู้ป่วยติดสุรา Na 108 ได้ 3% NaCl Na ขึ้นเป็น 125 ใน 24 ชม. 4 วันต่อมาพูดไม่ชัด กลืนลำบาก แขนขาอ่อนแรง — วินิจฉัยอะไร → osmotic demyelination syndrome","ผู้ป่วยแก้ Na เกินเพดานภายใน 12 ชม. — ควรทำอะไร → re-lower ด้วย D5W ร่วมกับ desmopressin"]}),
A({page:4, page2:3, orig:"Plastic surgery 1",
  flag:"⚠ ต้นฉบับถามแค่ \"เย็บ tendon\" — core suture มาตรฐานใช้ได้ทั้ง braided polyester (Ethibond) และ nylon (polyamide) → เติมใน stem ว่าเป็น running epitendinous suture (ใช้ monofilament nylon 6-0 หรือ polypropylene) ให้เหลือคำตอบเดียว; ถ้าถาม core suture ช้อย E ก็ถูก",
  stem:"During flexor tendon repair in the hand, the surgeon places a fine running epitendinous suture after the core suture. Which suture material is most appropriate for it?",
  gray:"เย็บ tendon — A. Silk B. catgut C. Polyglactin D. Polyamide E. Polyester",
  opts:["Silk","Catgut","Polyglactin","Polyamide","Polyester"],
  ans:3, key:"D Polyamide"+KS,
  interp:"ถามไหมสำหรับเย็บ <b>เอ็น</b> — tendon หายช้าและต้องทนแรงดึงและ glide ได้ ต้องเลือกไหม <b>non-absorbable</b> แรงดึงสูง reactivity ต่ำ; เราเติมว่าเป็น <b>epitendinous suture</b> เพื่อให้เหลือคำตอบเดียวระหว่าง nylon กับ polyester",
  why:"Tendon หายช้า (strength กลับราว <b>12 สัปดาห์</b>) ต้องใช้ไหม <b>non-absorbable synthetic</b> ที่คงแรงดึงนาน เนื้อเยื่อตอบสนองน้อย; <b>Polyamide (nylon) monofilament</b> ผิวเรียบ ลื่น ไม่ทำให้ tendon ติดกับ sheath — ใช้เป็น <b>running epitendinous suture ขนาด 6-0</b> (ร่วมกับ polypropylene) ซึ่งช่วยเพิ่มแรงต้านการแยกของรอยเย็บและทำให้ผิวเอ็นเรียบ glide ได้; nylon แบบ looped ยังใช้เป็น core suture ได้ด้วย",
  wrong:[
    "Silk เป็น natural protein (braided) <b>tissue reaction สูง</b> แรงดึงลดลงตามเวลา (ถือเป็น non-absorbable แต่ค่อย ๆ ถูกย่อยในเวลาหลายปี) มีช่องให้แบคทีเรียอยู่; จะถูกถ้าถามไหมผูกหลอดเลือดหรือยึด drain ที่ผิวหนัง",
    "Catgut (plain หรือ chromic) เป็น natural absorbable ถูกย่อยด้วย proteolysis เร็ว (plain 7–10 วัน) reaction สูง — ไม่พอสำหรับ tendon ที่ต้องการแรงดึงหลายสัปดาห์; จะถูกถ้าถามไหมเย็บ mucosa หรือเนื้อเยื่อที่หายเร็ว",
    "Polyglactin 910 (Vicryl) เป็น synthetic absorbable แบบ braided คงแรงดึงราว 50–75% ที่ 2 สัปดาห์และถูกดูดซึมหมด 56–70 วัน — เสียแรงดึงก่อน tendon หาย; จะถูกถ้าถามไหมเย็บ subcutaneous หรือ bowel anastomosis",
    "Polyester braided (Ethibond) แรงดึงสูงมาก ใช้เป็น <b>core suture</b> (3-0 หรือ 4-0) ได้ดี — แต่ braided มี friction สูงกว่า ไม่เหมาะเป็น epitendinous suture ที่ต้องการผิวลื่น; จะถูกถ้าโจทย์ถามไหม core suture ของ flexor tendon repair"],
  trap:"เลือก absorbable เพราะคิดว่าเย็บข้างในร่างกายต้องละลายได้ — tendon ต้องใช้ <b>non-absorbable</b> เสมอ; และจำว่า epitendinous = monofilament เล็ก (6-0 nylon หรือ prolene) ส่วน core = braided polyester หรือ looped nylon",
  summary:[
    "Tendon repair ใช้ไหม <b>non-absorbable synthetic</b>: core suture (polyester braided 3-0 หรือ 4-0, looped nylon) + <b>epitendinous running suture 6-0 nylon หรือ polypropylene</b>",
    "Repair strength ขึ้นกับจำนวน strand ที่ข้ามรอยต่อ (4–6 strand) มากกว่าชนิดไหมอย่างเดียว; epitendinous suture เพิ่มแรงต้านการแยกและ glide",
    "หลังผ่าตัด flexor tendon ต้องทำ early protected mobilization ลด adhesion; strength กลับราว 12 สัปดาห์",
    "Absorbable: catgut (plain 7–10 วัน, chromic 10–14 วัน), polyglactin (Vicryl), polyglecaprone (Monocryl), PDS (คงแรงดึงนานสุดในกลุ่ม absorbable)",
    "Non-absorbable: silk (reaction สูง), nylon (polyamide), polypropylene (Prolene: reaction ต่ำสุด ใช้หลอดเลือด, hernia), polyester (Ethibond), steel",
    "ดูข้อ 15 (ไหมเย็บผิวหนัง), ข้อ 5 (wound healing)"],
  notes:"ไฟล์เฉลย บท Plastic surgery แถว 1: <b>D</b> (ช่องคำอธิบายว่าง)<br>ในไฟล์โจทย์หัวบทพิมพ์ <b>สีแดง</b> ว่า <b>\"Plastic surgery (kuy) isus\"</b> (ผู้จดเขียนเอง); ต้นฉบับจดโจทย์แค่ \"เย็บ tendon\" ครบ 5 ช้อย — เราเติมใน stem ว่าเป็น flexor tendon repair และถามไหมสำหรับ running epitendinous suture หลังเย็บ core suture แล้ว; ช้อย B ต้นฉบับเขียน \"catgut\" ตัวพิมพ์เล็ก",
  mnemonic:"<b>\"Core = แข็ง (Ethibond), Epi = ลื่น (nylon 6-0)\"</b>",
  guide:"Green's Operative Hand Surgery 8th ed. 2022; Sabiston Textbook of Surgery 21st ed.",
  opinion:"เห็นด้วยกับคีย์ D ความมั่นใจปานกลาง — ต้นฉบับถามกว้าง ๆ ว่าเย็บ tendon ใช้ไหมอะไร ซึ่ง polyester (E) ก็เป็นไหม core suture ที่ใช้มากในทางปฏิบัติ จึงเติม stem ให้ถามเฉพาะ epitendinous suture ที่ต้องเป็น monofilament ลื่น (nylon) ให้เหลือคำตอบเดียวตามคีย์; ถ้าข้อสอบจริงถาม core suture จะตอบได้ทั้ง D และ E",
  variants:["ผู้ป่วยถูกมีดบาด flexor digitorum profundus ขาดที่ zone II — ไหมที่ใช้เย็บ core suture → non-absorbable braided polyester 3-0 หรือ 4-0 (หรือ looped nylon) แบบ multistrand","หลังเย็บ flexor tendon ควรทำอะไรเพื่อลด adhesion → early protected mobilization ภายใต้ splint","ไหม absorbable ชนิดใดคงแรงดึงนานที่สุดเหมาะกับการเย็บ fascia → polydioxanone (PDS)"]}),
A({page:4, page2:3, orig:"Plastic surgery 2",
  stem:"For skin closure, which suture material is associated with the lowest risk of wound infection?",
  gray:"เย็บสกิน ไหมไหนช่วยลด infection — A. polyamide B. Polyester",
  opts:["Polyamide","Polyester","Silk","Catgut","Polyglactin"],
  ans:0, key:"A polyamide"+KS,
  interp:"ถามคุณสมบัติไหมที่ลด infection — ประเด็นหลักคือ <b>monofilament vs multifilament (braided)</b> และ <b>synthetic vs natural</b>",
  why:"<b>Polyamide (nylon) monofilament</b> ผิวเรียบ ไม่มีช่องว่างระหว่างเส้นใยให้แบคทีเรียซ่อนจากเม็ดเลือดขาว และไม่มี <b>capillarity</b> (ไม่ดูดซับของเหลวและแบคทีเรียเข้าไปตามเส้นไหม) + เป็น synthetic ที่ tissue reaction ต่ำ → ความเสี่ยง infection ต่ำ; ใช้เย็บผิวหนังทั่วไป (4-0 ถึง 6-0) ตัดไหม 5–14 วันตามตำแหน่ง",
  wrong:[
    "Polyester เป็น <b>braided multifilament</b> → มีช่องให้แบคทีเรียอยู่และ wick เชื้อเข้าไปตามเส้นไหม เพิ่ม infection; ใช้ในงานที่ต้องการแรงดึงสูง (tendon core suture, valve); จะถูกถ้าถามไหมแรงดึงสูงสำหรับเย็บ tendon core",
    "Silk เป็น natural braided <b>reaction สูงที่สุดตัวหนึ่ง</b> + มี capillarity → infection สูง (ใช้น้อยลงในการเย็บผิวหนัง); จะถูกถ้าถามไหมที่ผูกง่าย knot security ดีที่ใช้ยึด drain หรือผูกหลอดเลือด",
    "Catgut เป็น natural absorbable ถูกย่อยด้วย proteolysis → <b>inflammation มาก</b> ไม่เหมาะเย็บผิวหนังที่ต้องการลด infection; จะถูกถ้าถามไหมละลายเร็วสำหรับเย็บ mucosa",
    "Polyglactin (Vicryl) เป็น synthetic absorbable แบบ braided — มี capillarity มากกว่า monofilament (มีรุ่นเคลือบ triclosan ที่ลด SSI แต่ช้อยไม่ได้ระบุ); จะถูกถ้าถามไหมเย็บ subcuticular หรือ subcutaneous แบบละลาย"],
  trap:"คิดว่าไหมละลายลด infection เพราะไม่ค้างในร่างกาย — สิ่งที่ลด infection คือ <b>monofilament + synthetic</b>; ในช้อยไม่มี polypropylene (Prolene) ซึ่ง reaction และ infection ต่ำที่สุด",
  summary:[
    "Monofilament (nylon, polypropylene, PDS, poliglecaprone): ผิวเรียบ ลอดเนื้อเยื่อง่าย infection ต่ำ แต่ knot security ต่ำกว่า ต้องผูกหลายปม และมี memory",
    "Multifilament braided (silk, polyester, polyglactin): ผูกง่าย knot security ดี แต่มี capillarity และช่องให้แบคทีเรียอยู่ → infection สูงกว่า ไม่ควรใช้ในแผลปนเปื้อน",
    "Natural (silk, catgut): tissue reaction สูง; synthetic: reaction ต่ำ (polypropylene ต่ำสุด)",
    "เย็บผิวหนัง: nylon 4-0 ถึง 6-0; ตัดไหม หน้า 3–5 วัน, หนังศีรษะ 7–10 วัน, ลำตัวและแขน 7–10 วัน, ขาและข้อต่อ 10–14 วัน",
    "<b>Triclosan-coated suture</b> ลด SSI (WHO 2018 conditional recommendation ทุก wound class)",
    "แผลปนเปื้อนมากหรือ dirty: ไม่ใช้ braided suture ในชั้นลึก หลีกเลี่ยงการปิดผิวหนังทันที",
    "ดูข้อ 14 (ไหมเย็บ tendon), ข้อ 16, 17, 18 (การป้องกัน SSI)"],
  notes:"ไฟล์เฉลย บท Plastic surgery แถว 2: <b>A</b> (ช่องคำอธิบายว่าง)<br>หัวบทในไฟล์โจทย์พิมพ์สีแดงว่า \"Plastic surgery (kuy) isus\"; ต้นฉบับจดช้อย 2 ตัว (A. polyamide B. Polyester) — ช้อย C–E แต่งเพิ่ม; ในไฟล์โจทย์บทนี้มีแถวข้อ 3, 4, 5 ว่าง (ไม่ใช่ข้อ)",
  mnemonic:"<b>\"เส้นเดียวเรียบ เชื้อไม่เกาะ; ถักเปีย เชื้อซ่อน\"</b>",
  guide:"WHO Global Guidelines for the Prevention of Surgical Site Infection 2nd ed. 2018; Schwartz's Principles of Surgery 11th ed.",
  opinion:"",
  variants:["แผลฉีกขาดที่ใบหน้าเด็กอายุ 6 ปี ไหมที่เหมาะสมเย็บผิวหนังและนัดตัดไหมเมื่อไร → nylon 6-0 ตัดไหม 3–5 วัน","ไหมชนิดใดมี tissue reaction ต่ำที่สุดเหมาะกับการเย็บหลอดเลือดและ hernia mesh → polypropylene","ศัลยแพทย์ต้องการไหมที่ช่วยลด SSI ในการปิดแผลหน้าท้องตามคำแนะนำ WHO → triclosan-coated suture"]}),
A({page:5, page2:3, orig:"Surgical infection 1",
  flag:"⚠ เล็กน้อย: หลักฐานใหม่ (RCT ไทย Siribumrungwong 2018, WSES 2020) พบ delayed primary closure ไม่ลด SSI ชัดเจนเทียบ primary closure ใน complicated appendicitis และ triclosan-coated suture (ช้อย E) มี conditional recommendation จาก WHO 2018 — คงคีย์เพราะเป็นมาตรการคลาสสิกสำหรับแผล dirty (class IV) ในตำรา",
  stem:"After appendectomy for ruptured appendicitis, what is the most important measure to reduce superficial incisional surgical site infection?",
  gray:"ruptured appendicitis อะไรสำคัญที่สุดเพื่อลด superficial surgical site infection — A. Delayed wound closure with wet dressing B. Post antibiotics 10-14 day C. Soak แผลด้วยน้ำเกลืออย่างชุ่มโชคก่อนปิดแผล D. ทา Iodine เยอะๆก่อนปิดแผล E. ใช้ไหมเคลือบ ABX เย็บแผล",
  opts:["Delayed wound closure with wet dressing","Postoperative antibiotics for 10 to 14 days","Soaking the wound with saline before closure","Applying generous iodine before closure","Closing the wound with antibiotic-coated sutures"],
  ans:0, key:"A Delayed wound closure with wet dressing"+KS,
  interp:"Ruptured appendicitis = แผล <b>dirty (class IV)</b> ถามมาตรการที่สำคัญที่สุดเพื่อลด <b>superficial incisional SSI</b> (ระดับผิวหนังและ subcutaneous)",
  why:"แผล dirty ที่ปิดผิวหนังทันทีมีโอกาส SSI สูง (ตำราเดิมราว 30–40%) เพราะแบคทีเรียที่ปนเปื้อนชั้น subcutaneous ถูกขังไว้ในช่องปิด → หลักคลาสสิกคือ <b>เย็บปิด fascia แต่เปิดผิวหนังและ subcutaneous ไว้</b> ปิดด้วย wet (saline) dressing เปลี่ยนวันละ 2 ครั้ง แล้วทำ <b>delayed primary closure ราววันที่ 3–5</b> เมื่อแผลสะอาด มี granulation (หรือปล่อยหายเองแบบ secondary intention) → ลด superficial SSI ได้มากที่สุดในทางทฤษฎี; อย่างไรก็ตาม RCT ไทย (Siribumrungwong 2018) และ WSES 2020 พบว่าใน complicated appendicitis การปิดแผลทันทีไม่ได้เพิ่ม SSI อย่างมีนัยสำคัญ และหายเร็วกว่า",
  wrong:[
    "Antibiotic หลังผ่าตัด 10–14 วัน <b>นานเกินจำเป็น</b> — complicated intra-abdominal infection ที่ source control ได้ ให้ <b>4 วัน</b> พอ (STOP-IT trial: fixed 4 วัน ผลเท่ากับให้จนไข้และ WBC หาย); ให้นานเพิ่ม resistance และ C. difficile; จะถูกถ้าคุม source ไม่ได้หรือมี bacteremia จากเชื้อบางชนิด",
    "WHO 2018 ระบุว่า <b>หลักฐานไม่พอ</b> จะแนะนำหรือคัดค้าน saline irrigation ของแผลก่อนปิด (ไม่มีคำแนะนำ) และแนะนำไม่ให้ irrigate ด้วย antibiotic; จะถูกน้อย — WHO มี conditional recommendation ให้ irrigate ด้วย aqueous povidone-iodine ใน clean และ clean-contaminated wound",
    "การทา antiseptic หรือ antimicrobial ลงบน incision ก่อนปิด <b>ไม่แนะนำ</b> (CDC 2017: do not apply antimicrobial agents to the surgical incision) และ iodine เข้มข้นทำลายเนื้อเยื่อ; จะถูกถ้าหมายถึงการเตรียมผิวหนังก่อนลงมีด (ปัจจุบันแนะนำ alcohol-chlorhexidine มากกว่า)",
    "Triclosan-coated suture มี <b>conditional recommendation</b> จาก WHO 2018 ลด SSI ทุก wound class (หลักฐานระดับปานกลาง) — เป็นมาตรการเสริม แต่ในแผล dirty ที่ยังปิดผิวหนังทันที ผลไม่เท่ากับการไม่ปิดผิวหนัง; จะถูกถ้าโจทย์ถามชนิดไหมที่แนะนำเพื่อลด SSI ในทุก wound class"],
  trap:"คิดว่า antibiotic นาน ๆ ช่วยลด SSI — ไม่ช่วยและมีโทษ; หลักสำคัญของแผล dirty คือ <b>source control + ไม่ปิดผิวหนังที่ปนเปื้อน</b>; และ superficial SSI สัมพันธ์กับการจัดการผิวหนัง ไม่ใช่ antibiotic ระยะยาว",
  summary:[
    "Wound class: I clean (SSI ~1–2%), II clean-contaminated (เปิดทางเดินอาหาร หายใจ ปัสสาวะแบบควบคุมได้), III contaminated (มีการรั่วไหลมาก, acute nonpurulent inflammation, traumatic wound สด), IV dirty (หนอง, perforated viscus, traumatic wound เก่า)",
    "แผล dirty: ปิด fascia, เปิดผิวหนังไว้ + wet dressing → <b>delayed primary closure วันที่ 3–5</b> หรือ secondary intention (หรือ negative pressure wound therapy)",
    "หลักฐานใหม่: complicated appendicitis การปิดผิวหนังทันทีมี SSI ไม่ต่างจาก DPC ชัดเจน (Siribumrungwong 2018, WSES 2020) — ตำราและข้อสอบยังถือ DPC เป็นคำตอบคลาสสิก",
    "Antibiotic หลัง source control ของ complicated intra-abdominal infection = <b>4 วัน</b> (STOP-IT); simple appendicitis ไม่ต้องให้ต่อหลังผ่าตัด",
    "WHO 2018: prophylactic antibiotic ภายใน 120 นาทีก่อนลงมีด, alcohol-chlorhexidine skin prep, triclosan-coated suture (conditional), ไม่ทา antimicrobial ลงแผล, ไม่ irrigate ด้วย antibiotic",
    "Laparoscopic appendectomy SSI ระดับแผลต่ำกว่า open แต่ intra-abdominal abscess ใกล้เคียงหรือสูงกว่าเล็กน้อย",
    "ดูข้อ 17, 18 (risk factor และการป้องกัน SSI), ข้อ 2 (wound infection หลังผ่าตัด)"],
  notes:"ไฟล์เฉลย บท Surgical infection แถว 1: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดครบ 5 ช้อย (A, B ภาษาอังกฤษ; C–E ภาษาไทย): C \"Soak แผลด้วยน้ำเกลืออย่างชุ่มโชคก่อนปิดแผล\" (ชุ่มโชค = ชุ่มโชก), D \"ทา Iodine เยอะๆก่อนปิดแผล\", E \"ใช้ไหมเคลือบ ABX เย็บแผล\" — เราแปลเป็นอังกฤษโดยไม่เปลี่ยนความหมาย",
  mnemonic:"<b>\"Dirty → ปิด fascia เปิดผิว รอ 3–5 วัน\"</b>; antibiotic หลัง source control = <b>4 วัน</b>",
  guide:"WHO Global Guidelines for the Prevention of Surgical Site Infection 2nd ed. 2018; WSES Jerusalem guidelines on acute appendicitis 2020",
  opinion:"เห็นด้วยกับคีย์ A ความมั่นใจปานกลาง — เป็นคำตอบคลาสสิกในตำราสำหรับแผล dirty; ข้อควรรู้คือ RCT ไทยปี 2018 และ WSES 2020 พบว่า delayed primary closure ไม่ได้ลด SSI ชัดเจนใน complicated appendicitis เมื่อเทียบการปิดทันที และ triclosan-coated suture (E) มี conditional recommendation จาก WHO — แต่ในบรรดาช้อยที่ให้ A ยังเป็นมาตรการที่ตรงกับหลักการจัดการแผล dirty มากที่สุด; สอดคล้องกับข้อสอบชุด 77C (gangrenous ไม่แตก → primary closure)",
  variants:["ผู้ป่วย perforated sigmoid diverticulitis มี fecal peritonitis หลังทำ Hartmann's procedure — การจัดการแผลผิวหนัง → ปิด fascia เปิดผิวหนังไว้ wet dressing แล้ว delayed primary closure","ผู้ป่วย perforated appendicitis หลังผ่าตัด source control ได้ดี — ควรให้ antibiotic นานเท่าไร → 4 วัน","ผู้ป่วย acute non-perforated appendicitis หลังผ่าตัด ต้องให้ antibiotic ต่อหรือไม่ → ไม่ต้อง ให้เฉพาะ prophylaxis ก่อนผ่าตัด"]}),
A({page:5, page2:3, orig:"Surgical infection 2",
  flag:"⚠ เล็กน้อย: เติม BMI 36 ใน stem (ต้นฉบับไม่บอกว่าอ้วน แต่ช้อย A คือ obesity)",
  stem:"A patient with diabetes and a BMI of 36 underwent elective surgery with appropriate antibiotic prophylaxis. Serous fluid is now draining from the wound. Which of the following is the greatest risk factor for surgical site infection in this patient?",
  gray:"คนไข้ DM s/p อะไรสักอย่าง มี serous ไหลออกมาจากแผล Risk มากที่สุดที่คนไข้คนนี้จะเกิด SSIs — A. Obesity B. Serous C. Abx prophylaxis D. Elective surgery",
  opts:["Obesity","Serous wound drainage","Antibiotic prophylaxis","Elective surgery","Short operative time"],
  ans:0, key:"A Obesity"+KS,
  interp:"ถาม <b>risk factor ของ SSI</b> ในผู้ป่วยรายนี้ — ต้องแยกว่าช้อยไหนเพิ่มความเสี่ยง (patient factor) ช้อยไหนเป็นอาการ และช้อยไหนเป็นปัจจัยป้องกัน",
  why:"<b>Obesity</b> เป็น patient-related risk factor ที่สำคัญของ SSI: ชั้นไขมันหนามีเลือดเลี้ยงน้อย (oxygen tension ต่ำ) เกิด dead space และ seroma ง่าย, ความตึงของแผลสูง, ระดับยา prophylactic ในเนื้อเยื่อต่ำถ้าไม่ปรับขนาด (cefazolin 3 g ถ้าน้ำหนัก ≥120 kg), ผ่าตัดยากและนานขึ้น และมักมี hyperglycemia หรือ DM ร่วม (รายนี้มีทั้ง DM และ BMI 36); ในช้อยที่ให้ obesity จึงเป็น risk factor ที่แท้จริง",
  wrong:[
    "Serous drainage เป็น <b>อาการของแผล</b> (seroma, fat necrosis ในคนอ้วน) ไม่ใช่ risk factor ของผู้ป่วย — แม้แผลที่มีน้ำซึมนานจะสัมพันธ์กับ SSI (drainage นาน &gt;5 วันควรประเมินหาการติดเชื้อหรือ seroma) แต่ไม่ใช่ตัวตั้งต้นที่โจทย์ถาม; จะถูกถ้าโจทย์ถามอาการเตือนที่ต้องเปิดแผลตรวจ",
    "Antibiotic prophylaxis ที่ให้ถูกเวลา (ภายใน 60 นาทีก่อนลงมีด) <b>ลด</b> SSI; จะเป็น risk factor เฉพาะเมื่อให้ผิดเวลา ขนาดไม่พอ หรือให้นานเกินไป",
    "Elective surgery มีความเสี่ยงต่ำกว่า <b>emergency surgery</b> (เตรียมผู้ป่วยได้ คุมน้ำตาล หยุดบุหรี่); จะถูกถ้าช้อยเป็น emergency surgery",
    "Operative time สั้น <b>ลด</b> SSI — ผ่าตัดนานกว่า 75th percentile ของหัตถการนั้น (T-time) จึงเป็น risk factor; จะถูกถ้าช้อยเป็น prolonged operative time"],
  trap:"เลือก serous discharge เพราะเห็นในโจทย์ — อาการของแผลไม่ใช่ risk factor; ต้องแยก <b>patient factor</b> (DM, obesity, smoking, malnutrition, steroid) กับ <b>procedure factor</b> และมาตรการป้องกัน",
  summary:[
    "Patient factor ของ SSI: อายุมาก, <b>DM และ hyperglycemia</b> (คุม glucose &lt;200 mg/dL รอบผ่าตัด), <b>obesity</b>, smoking (หยุด 4–6 สัปดาห์ก่อนผ่าตัด), malnutrition (albumin ต่ำ), immunosuppression, steroid, remote infection, S. aureus colonization",
    "Procedure factor: emergency, wound class สูง, ผ่าตัดนาน, hypothermia, เลือดออกมากหรือได้เลือด, hair removal ด้วยมีดโกน, drain, foreign body",
    "Risk index (NNIS): ASA ≥3, wound class III–IV, operative time &gt;T (75th percentile) — ข้อละ 1 คะแนน",
    "Prophylaxis: cefazolin 2 g IV (3 g ถ้า ≥120 kg) ภายใน 60 นาทีก่อนลงมีด, ให้ซ้ำทุก 4 ชม.หรือเสียเลือด &gt;1,500 mL, หยุดเมื่อจบผ่าตัด",
    "Serous drainage นานหลังผ่าตัดในคนอ้วน → seroma หรือ fat necrosis; ถ้ามีแดง หนอง ไข้ → เปิดแผลระบาย",
    "ดูข้อ 16, 18 (การป้องกัน SSI), ข้อ 2 (wound infection หลังผ่าตัด)"],
  notes:"ไฟล์เฉลย บท Surgical infection แถว 2: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดโจทย์ว่า \"คนไข้ DM s/p อะไรสักอย่าง\" (ผู้จดจำชนิดการผ่าตัดไม่ได้) และไม่ได้บอกว่าผู้ป่วยอ้วน — เราเติม BMI 36, elective surgery และได้ antibiotic prophylaxis ตามช้อย C, D; ช้อย B ต้นฉบับเขียนแค่ \"Serous\" เราเขียนเป็น Serous wound drainage; ช้อย E แต่งเพิ่ม",
  mnemonic:"",
  guide:"CDC Guideline for the Prevention of Surgical Site Infection 2017; WHO Global Guidelines for the Prevention of Surgical Site Infection 2nd ed. 2018",
  opinion:"เห็นด้วยกับคีย์ A ความมั่นใจปานกลางถึงสูง — ต้นฉบับไม่ได้บอกว่าผู้ป่วยอ้วน แต่ในบรรดาช้อยที่ผู้จดให้ obesity เป็นตัวเดียวที่เป็น risk factor ของ SSI (ช้อยอื่นเป็นอาการหรือมาตรการป้องกัน) จึงเติม BMI ให้ข้อมูลครบ",
  variants:["ชายอายุ 55 ปี สูบบุหรี่วันละ 1 ซอง นัดผ่าตัด elective ventral hernia repair — ควรแนะนำอะไรเพื่อลด SSI → หยุดบุหรี่อย่างน้อย 4–6 สัปดาห์ก่อนผ่าตัด","ผู้ป่วยหนัก 130 kg ผ่าตัด bariatric surgery — ขนาด cefazolin prophylaxis → 3 g IV ภายใน 60 นาทีก่อนลงมีด","ผู้ป่วยผ่าตัดนาน 6 ชั่วโมง ได้ cefazolin ก่อนลงมีด — ควรให้ซ้ำเมื่อไร → ทุก 4 ชม.ระหว่างผ่าตัด หรือเมื่อเสียเลือด &gt;1,500 mL"]}),
A({page:5, page2:3, orig:"Surgical infection 3",
  flag:"⚠ ตอบต่างจากคีย์ (คีย์ A saline irrigation) — WHO 2018 ให้ strong recommendation สำหรับ alcohol-based chlorhexidine skin preparation ส่วน saline wound irrigation หลักฐานไม่พอ (ไม่มีคำแนะนำ); ช้อย B ต้นฉบับเขียน \"Chlorhex เช็ดแผล\" ตีความเป็นการเตรียมผิวหนังบริเวณแผลผ่าตัด — ถ้าหมายถึงเช็ดแผลหลังผ่าตัด ทั้งสองช้อยไม่มีหลักฐานแข็ง",
  stem:"Which measure reduces the risk of surgical site infection the most?",
  gray:"อะไรช่วยลดโอกาส SSIs มากที่สุด — A. Irrigate แผลด้วยน้ำเกลือ B. Chlorhex เช็ดแผล",
  opts:["Wound irrigation with normal saline","Chlorhexidine-alcohol skin preparation","Razor shaving the night before surgery","Antibiotics continued until drain removal","Plastic adhesive incise drape"],
  ans:1, key:"A Irrigate แผลด้วยน้ำเกลือ"+KS,
  interp:"ถามมาตรการที่ <b>หลักฐานแข็งที่สุด</b> ในการลด SSI — ต้องเทียบกับระดับคำแนะนำของ WHO และ CDC",
  why:"<b>Alcohol-based chlorhexidine skin preparation</b> ก่อนลงมีดได้ <b>strong recommendation</b> จาก WHO 2018 (หลักฐานระดับ low ถึง moderate) และ CDC 2017 (Category IA สำหรับ alcohol-based agent) — ลด SSI ได้ดีกว่า povidone-iodine แบบ aqueous (RCT Darouiche 2010: chlorhexidine-alcohol ลด SSI ใน clean-contaminated surgery ราว 40%); chlorhexidine จับกับผิวหนังออกฤทธิ์ค้าง (residual activity) และ alcohol ฆ่าเชื้อเร็ว ต้องรอให้แห้งก่อนคลุมผ้า (ระวังไฟไหม้จาก cautery)",
  wrong:[
    "Saline wound irrigation ก่อนปิดแผล — WHO 2018 สรุปว่า <b>หลักฐานไม่พอ</b> ที่จะแนะนำหรือคัดค้าน; มีหลักฐานบ้างสำหรับ irrigation ด้วย aqueous povidone-iodine (conditional) ใน clean และ clean-contaminated; นี่คือช้อยที่คีย์เลือก; จะถูกถ้าโจทย์เทียบกับมาตรการที่ไม่มีประโยชน์ทั้งหมด หรือถามการล้างแผลอุบัติเหตุที่ปนเปื้อนก่อนเย็บ",
    "การโกนขนด้วยมีดโกน <b>เพิ่ม</b> SSI (micro-abrasion ให้เชื้อเข้าและเพิ่มจำนวน) — WHO strong recommendation ไม่ให้ใช้มีดโกน; ถ้าจำเป็นใช้ clipper ใกล้เวลาผ่าตัด หรือไม่ต้องกำจัดขนเลย; ไม่มีบริบทที่ถูก",
    "การให้ antibiotic ต่อจนถอด drain <b>ไม่ลด</b> SSI — WHO strong recommendation ไม่ให้ต่อ prophylaxis หลังจบผ่าตัด และ conditional recommendation ไม่ให้ต่อเพราะมี drain; เพิ่ม resistance และ C. difficile; ไม่มีบริบทที่ถูก",
    "Plastic adhesive incise drape (ทั้งแบบธรรมดาและแบบเคลือบ iodine) — WHO conditional recommendation <b>ไม่ใช้</b> เพื่อป้องกัน SSI เพราะไม่ลด SSI; ไม่มีบริบทที่ถูก"],
  trap:"เลือก saline irrigation เพราะฟังดูสมเหตุสมผลและคีย์ตอบ — แต่ในแนวทางปัจจุบันมาตรการที่หลักฐานแข็งที่สุดในช้อยคือ <b>alcohol-chlorhexidine skin prep</b>; ส่วนการโกนขนและให้ยาต่อจนถอด drain เพิ่มหรือไม่ลด SSI",
  summary:[
    "Preoperative: อาบน้ำด้วยสบู่ก่อนผ่าตัด, decolonization ด้วย mupirocin ± chlorhexidine ใน S. aureus carrier ที่ผ่าตัดหัวใจหรือ orthopedic, หยุดบุหรี่, คุมน้ำตาล, ไม่กำจัดขนหรือใช้ clipper",
    "Prophylactic antibiotic: ภายใน <b>120 นาที</b> (WHO) หรือ 60 นาที (แนวทางทั่วไป) ก่อนลงมีด, ให้ซ้ำเมื่อผ่าตัดนาน, <b>หยุดเมื่อจบผ่าตัด</b>",
    "Skin prep: <b>alcohol-based chlorhexidine</b> (strong recommendation) ดีกว่า povidone-iodine; surgical hand antisepsis ด้วยสบู่ antimicrobial หรือ alcohol hand rub",
    "Intraoperative: normothermia, FiO₂ 80% ใน intubated patient (WHO conditional), goal-directed fluid, triclosan-coated suture (conditional), ไม่ใช้ incise drape",
    "ไม่แนะนำ: antibiotic irrigation, ทา antimicrobial บนแผล, ต่อ antibiotic เพราะมี drain",
    "ดูข้อ 16, 17 (SSI ในแผลปนเปื้อนและ risk factor), ข้อ 15 (ไหมกับ infection)"],
  notes:"ไฟล์เฉลย บท Surgical infection แถว 3: <b>A</b> (ช่องคำอธิบายว่าง)<br>ต้นฉบับจดช้อย 2 ตัว (A. Irrigate แผลด้วยน้ำเกลือ B. Chlorhex เช็ดแผล) — ช้อย B เราตีความเป็น chlorhexidine-alcohol skin preparation (การเตรียมผิวหนังบริเวณผ่าตัด) และแต่งช้อย C–E (มาตรการที่ไม่ลดหรือเพิ่ม SSI); ต้นฉบับเขียน \"SSIs\"; ในไฟล์โจทย์บทนี้มีแถวข้อ 4, 5 ว่าง (ไม่ใช่ข้อ)",
  mnemonic:"<b>\"Clip, don't shave; Chlorhex-alcohol, let it dry; Stop antibiotics when you close\"</b>",
  guide:"WHO Global Guidelines for the Prevention of Surgical Site Infection 2nd ed. 2018; CDC Guideline for the Prevention of Surgical Site Infection 2017",
  opinion:"ไม่เห็นด้วยกับคีย์ (คีย์ตอบ A saline irrigation) — เราตอบ B ความมั่นใจปานกลาง: WHO 2018 ให้ strong recommendation สำหรับ alcohol-based chlorhexidine skin preparation ขณะที่ saline irrigation ของแผล WHO ระบุว่าหลักฐานไม่พอจะให้คำแนะนำ; ความไม่แน่นอนอยู่ที่ช้อยต้นฉบับ \"Chlorhex เช็ดแผล\" ซึ่งอาจหมายถึงการเช็ดแผลหลังผ่าตัด (ไม่มีหลักฐานว่าลด SSI ชัดเจนทั้งคู่) — ถ้าข้อสอบจริงหมายถึงแบบนั้น คำตอบของผู้ออกข้อสอบอาจเป็น A ตามคีย์; สอดคล้องกับข้อสอบชุด 77D (chlorhexidine สำหรับ surgical hand antisepsis)",
  variants:["ก่อนผ่าตัด open hernia repair บริเวณขาหนีบมีขนมาก — การกำจัดขนที่เหมาะสม → ไม่ต้องกำจัด หรือใช้ clipper ใกล้เวลาผ่าตัด ห้ามใช้มีดโกน","หลังผ่าตัด modified radical mastectomy ใส่ drain ไว้ — ควรให้ antibiotic จนถอด drain หรือไม่ → ไม่ควร หยุด prophylaxis เมื่อจบผ่าตัด","สารใดเหมาะที่สุดสำหรับเตรียมผิวหนังก่อนลงมีด และต้องระวังอะไร → alcohol-based chlorhexidine รอให้แห้งก่อนใช้ electrocautery เพื่อป้องกันไฟไหม้"]}),
A({page:5, page2:4, orig:"Surgical Oncology 1",
  stem:"A 2-cm gastrointestinal stromal tumor of the small bowel is found, with no metastasis. What is the most appropriate management?",
  gray:"GIST 2 cm ที่ small bowel ทำไรต่อดี — A. ทำ Resection B. ให้ Targeted therapy",
  opts:["Segmental resection","Targeted therapy","Endoscopic surveillance every 6 months","Radiotherapy","Doxorubicin-based chemotherapy"],
  ans:0, key:"A ทำ Resection"+KS,
  interp:"GIST ขนาดเล็ก (2 cm) ที่ <b>small bowel</b> ไม่มีการแพร่กระจาย — ต้องรู้ว่าตำแหน่งที่ไม่ใช่กระเพาะมี malignant potential สูงกว่าและต้องตัดออกทุกขนาด",
  why:"NCCN และ ESMO: GIST ที่ <b>non-gastric (small bowel, colon, rectum)</b> มี malignant potential สูงกว่า gastric GIST ขนาดเท่ากัน จึงควร <b>ตัดออกทุกขนาด</b> (ไม่ใช้ surveillance แบบ gastric &lt;2 cm); ทำ <b>segmental resection</b> ให้ได้ margin negative (R0) โดย <b>ไม่ต้องเลาะต่อมน้ำเหลือง</b> (GIST แพร่ทางกระแสเลือดไปตับและเยื่อบุช่องท้อง แทบไม่ไปต่อมน้ำเหลือง) และต้อง <b>ระวังก้อนแตก</b> (rupture = high risk ต้องได้ adjuvant imatinib); หลังผ่าตัดประเมิน risk ตาม site, size, mitotic rate (Miettinen/AFIP) ถ้า high risk ให้ adjuvant imatinib 400 mg/วัน <b>3 ปี</b>",
  wrong:[
    "Targeted therapy (imatinib) เป็น <b>adjuvant</b> หลังผ่าตัดในกลุ่ม high risk, <b>neoadjuvant</b> ในก้อนใหญ่หรือตำแหน่งยากเพื่อลดขนาดก่อนผ่าตัด หรือใช้ใน metastatic/unresectable; ก้อน 2 cm ที่ตัดได้ไม่ใช้ยาเป็นการรักษาหลัก; จะถูกถ้าเป็น metastatic GIST หรือก้อนใหญ่ที่ rectum ต้องลดขนาดก่อน",
    "Surveillance ด้วย EUS ทุก 6–12 เดือนใช้กับ <b>gastric GIST &lt;2 cm</b> ที่ไม่มี high-risk EUS features (ขอบไม่เรียบ, cystic space, ulceration, echogenic foci, heterogeneity); small bowel ไม่ใช่กลุ่มนี้และส่องกล้องเข้าถึงยาก; จะถูกถ้าเป็นก้อน 1.5 cm ที่กระเพาะไม่มี high-risk features",
    "Radiotherapy ไม่ได้ผลใน GIST (radioresistant) ใช้เพียงประคับประคองบางกรณีที่ปวดจาก metastasis; จะถูกถ้าโจทย์ถามการบรรเทาอาการปวดจากก้อนที่แพร่กระจายและดื้อยา",
    "Conventional chemotherapy (doxorubicin) <b>ไม่ได้ผล</b> ใน GIST (response &lt;5%) ต่างจาก soft tissue sarcoma อื่น; จะถูกถ้าโจทย์เป็น soft tissue sarcoma ชนิดอื่นที่แพร่กระจาย"],
  trap:"เอาเกณฑ์ <b>gastric GIST &lt;2 cm → surveillance</b> มาใช้กับ small bowel — non-gastric ตัดทุกขนาด; และอย่าเลาะต่อมน้ำเหลืองแบบผ่าตัดมะเร็ง adenocarcinoma",
  summary:[
    "GIST เกิดจาก <b>interstitial cell of Cajal</b>, mutation KIT (~80%) หรือ PDGFRA (~10%), ย้อม <b>CD117 (KIT) และ DOG1</b> positive; ตำแหน่ง: กระเพาะ 60%, small bowel 30%, colon-rectum ~5%",
    "วินิจฉัย: CT ช่องท้อง; ก้อนในกระเพาะใช้ EUS-guided FNA/biopsy; ก้อนที่ตัดได้ชัดเจนอาจผ่าตัดโดยไม่ต้อง biopsy ก่อน",
    "Gastric &lt;2 cm ไม่มี high-risk EUS features → surveillance; มี features หรือโตขึ้น → resect; ≥2 cm → resect; <b>non-gastric → resect ทุกขนาด</b>",
    "ผ่าตัด: wedge หรือ segmental resection margin negative (1–2 cm พอ), <b>ไม่ต้อง lymphadenectomy</b> (ยกเว้น SDH-deficient), หลีกเลี่ยงก้อนแตก, laparoscopic ได้ถ้าก้อนไม่ใหญ่",
    "Risk stratification: site + size + mitotic rate per 5 mm² + rupture → high risk → <b>adjuvant imatinib 3 ปี</b>",
    "Metastatic: imatinib 400 mg (exon 9 KIT 800 mg) → sunitinib → regorafenib → ripretinib; PDGFRA D842V ดื้อ imatinib ใช้ avapritinib; GIST ดื้อ chemotherapy และ radiotherapy",
    "ดูข้อ 20, 21, 22, 23 (oncology principles)"],
  notes:"ไฟล์เฉลย บท Surgical Oncology แถว 1: <b>A</b> (ช่องคำอธิบายว่าง) — แถวนี้อยู่หน้า 4 ของไฟล์เฉลย<br>ต้นฉบับจดช้อย 2 ตัว (A. ทำ Resection B. ให้ Targeted therapy) — ช้อย C–E แต่งเพิ่ม; stem เติม \"no metastasis\" เพื่อให้เป็นเคสที่ตัดได้",
  mnemonic:"<b>\"กระเพาะเล็กรอได้ ที่อื่นตัดหมด\"</b>; GIST ไม่ไปต่อมน้ำเหลือง ไม่กลัว chemo ไม่กลัวแสง กลัวแต่ imatinib",
  guide:"NCCN Clinical Practice Guidelines in Oncology: Gastrointestinal Stromal Tumors 2025; ESMO–EURACAN–GENTURIS GIST Clinical Practice Guidelines 2022",
  opinion:"เห็นด้วยกับคีย์ A ความมั่นใจสูง — สอดคล้องกับข้อสอบชุด 77B (GIST 2 cm ที่ EGJ → resection ไม่ต้องเลาะต่อมน้ำเหลือง) และชุด 76C (วินิจฉัย GIST ด้วย EUS-guided biopsy)",
  variants:["ก้อน 1.5 cm ใต้ mucosa ที่ gastric body จาก EUS ขอบเรียบ เนื้อสม่ำเสมอ biopsy เป็น GIST — การจัดการ → surveillance ด้วย EUS เป็นระยะ","หลังตัด GIST ลำไส้เล็กขนาด 8 cm mitotic rate 10 ต่อ 5 mm² — การรักษาต่อ → adjuvant imatinib 3 ปี","GIST ขนาด 12 cm ที่กระเพาะเกาะติดตับอ่อน — ทำอะไรก่อนผ่าตัด → neoadjuvant imatinib เพื่อลดขนาด (ตรวจ mutation ก่อน)"]}),
