A({page:1, page2:3, orig:"1", kimg:KI(1),
  stem:"Which gastrointestinal fluid has an electrolyte composition most similar to plasma?",
  gray:"Which of the following fluid has similar compositions to plasma ? — A. Saliva B. Stomach C. Small bowel D. Pancreatic juice E. Colon",
  opts:["Saliva","Gastric juice","Small bowel fluid","Pancreatic juice","Colonic fluid"],
  ans:2, key:"C Small bowel"+KS,
  interp:"ถามว่าสารคัดหลั่งในทางเดินอาหารชนิดใดมี <b>องค์ประกอบ electrolyte ใกล้ plasma</b> มากที่สุด (Na ~140, Cl ~100, HCO3 ~24 mEq/L) — ต้องจำ profile ของแต่ละชนิดว่าเด่น ion ตัวไหน เพราะใช้เลือก replacement fluid เมื่อเสียสารน้ำจาก NG, fistula หรือ stoma",
  why:"<b>Small intestine</b> (jejunum, ileum) มี Na 120–140, K 5–10, Cl 90–120, HCO3 30–40 mEq/L และปริมาณ 2,000–3,000 mL/วัน → เป็น <b>isotonic</b> ใกล้เคียง plasma ทั้ง Na, Cl และ HCO3 (ลายมือในเฉลย \"Small intestine = isotonic\") จึงทดแทนการเสียจาก small bowel fistula หรือ ileostomy ด้วย <b>LRS หรือ NSS</b> ได้ตรงที่สุด",
  wrong:[
    "Saliva เป็น <b>hypotonic</b> (Na ต่ำราว 10–40 mEq/L) แต่ K ค่อนข้างสูง (~20–30 mEq/L) ไม่คล้าย plasma และปริมาณที่เสียทางคลินิกมักน้อย; จะถูกถ้าโจทย์ถามสารคัดหลั่งที่ hypotonic และ K สูงในทางเดินอาหารส่วนบน",
    "Gastric juice มี Na 60–90 แต่ <b>Cl สูง 100–130 และ H⁺ สูง</b>, HCO3 = 0 (ลายมือ \"Stomach = Cl⁻ เยอะ (กรดเยอะ)\") → เสียมากเกิด hypochloremic hypokalemic metabolic alkalosis; ทดแทนด้วย 0.9% NaCl + KCl; จะถูกถ้าถามสารคัดหลั่งที่ Cl สูงที่สุด",
    "Pancreatic juice มี Na 135–145 ใกล้ plasma ก็จริง แต่ <b>HCO3 สูงมาก 95–115</b> และ Cl ต่ำ 70–90 (ลายมือ \"Pancreas = HCO3⁻↑\") → เสียมากเกิด metabolic acidosis (normal anion gap); ทดแทนด้วย LRS ± sodium bicarbonate; จะถูกถ้าถามสารคัดหลั่งที่ HCO3 สูงที่สุด",
    "Colonic fluid มี Na ~60, <b>K ~30 สูงที่สุด</b>, Cl ~40, HCO3 0 (ลายมือ \"Colon = K⁺↑\") → diarrhea หรือ villous adenoma ทำให้ hypokalemia; จะถูกถ้าถามสารคัดหลั่งที่ K สูงที่สุด"],
  trap:"เลือก pancreatic juice เพราะเห็นว่า Na 135–145 เท่า plasma — แต่ composition ต้องดูทั้ง anion ด้วย pancreatic juice มี HCO3 สูงมากจน Cl ต่ำ จึงไม่ isotonic แบบ plasma; อีกตัวที่ isotonic คือ bile แต่ไม่อยู่ในช้อย",
  summary:[
    "Stomach 1,000–2,000 mL/วัน: Na 60–90, K 10–30, Cl 100–130, HCO3 0 → Cl และ H⁺ สูง เสียแล้ว hypochloremic hypokalemic metabolic alkalosis → ทดแทน 0.9% NaCl + KCl",
    "Small intestine 2,000–3,000 mL/วัน: Na 120–140, K 5–10, Cl 90–120, HCO3 30–40 → isotonic ใกล้ plasma → ทดแทน LRS หรือ NSS",
    "Pancreas 600–800 mL/วัน: Na 135–145, K 5–10, Cl 70–90, HCO3 95–115 → HCO3 สูง เสียแล้ว metabolic acidosis → ทดแทน LRS ± bicarbonate",
    "Bile 300–800 mL/วัน: Na 135–145, K 5–10, Cl 90–110, HCO3 30–40 → isotonic เช่นกัน → biliary fistula ทดแทนด้วย LRS",
    "Colon: Na 60, K 30, Cl 40, HCO3 0 → K สูงที่สุด เสียแล้ว hypokalemia; saliva hypotonic และ K ค่อนข้างสูง",
    "หลักทดแทน: ตวงปริมาณที่ออกจริงแล้วทดแทนแยกจาก maintenance แบบ mL ต่อ mL ด้วย fluid ที่ composition ใกล้เคียง และตรวจ electrolyte เป็นระยะ",
    "ดูข้อ 2, 3, 4, 5, 36 (fluid, electrolyte และ acid-base)"],
  notes:"เฉลยในไฟล์ (มีรูป) = ตาราง <b>\"Table 3-3 Composition of GI Secretions\"</b> คอลัมน์ Type / Volume (mL/24 h) / Na⁺ / K⁺ / Cl⁻ / HCO3⁻ (mEq/L):<br>• Stomach 1000–2000 / 60–90 / 10–30 / 100–130 / 0<br>• Small intestine 2000–3000 / 120–140 / 5–10 / 90–120 / 30–40<br>• Colon — / 60 / 30 / 40 / 0<br>• Pancreas 600–800 / 135–145 / 5–10 / 70–90 / 95–115<br>• Bile 300–800 / 135–145 / 5–10 / 90–110 / 30–40<br>วงแดงที่ Cl ของ stomach, K ของ colon, HCO3 ของ pancreas; <b>วงเหลืองทั้งแถว small intestine</b><br>ลายมือข้างชื่อแต่ละแถว: <b>\"Stomach = Cl⁻ เยอะ (กรดเยอะ)\"</b>, <b>\"Small intestine = isotonic\"</b>, <b>\"Colon = K⁺↑\"</b>, <b>\"Pancreas = HCO3⁻↑\"</b>, <b>\"Bile = isotonic\"</b><br>ช้อยของเราแปลจากต้นฉบับ (Stomach → Gastric juice, Small bowel → Small bowel fluid, Colon → Colonic fluid) ไม่เปลี่ยนความหมาย",
  mnemonic:"<b>กระเพาะ = Cl, ลำไส้ใหญ่ = K, ตับอ่อน = HCO3, ลำไส้เล็กกับน้ำดี = isotonic</b>",
  guide:"Schwartz 11th ed.",
  opinion:"เห็นด้วยกับคีย์ C มั่นใจสูง — สอดคล้องกับข้อสอบชุด 76A และ 77B ที่ถามการทดแทน gastric loss ด้วย 0.9% NaCl",
  variants:[
    "ผู้ป่วยหลังผ่าตัดมี high-output ileostomy ออกวันละ 2,000 mL ควรทดแทนด้วยสารน้ำชนิดใด → LRS หรือ NSS mL ต่อ mL",
    "ผู้ป่วยมี pancreatic fistula ออกวันละ 700 mL ต่อเนื่อง ผลเลือดมี HCO3 ต่ำและ anion gap ปกติ → สาเหตุคือเสีย HCO3 จาก pancreatic juice ทดแทนด้วย LRS ± bicarbonate",
    "ผู้ป่วยใส่ NG tube ดูดออกวันละ 1,500 mL เป็นเวลา 4 วัน คาดว่าจะพบ acid-base แบบใด → hypochloremic hypokalemic metabolic alkalosis ทดแทนด้วย 0.9% NaCl + KCl"]}),

A({page:1, page2:3, orig:"2", kimg:KI(2),
  stem:"A patient with chronic hyponatremia has a serum sodium of 125 mEq/L. If the sodium is corrected too rapidly, which complication may occur?",
  gray:"Na 125 ต้องการให้ Correct Na ถามว่าถ้า load Na เร็วไปเกิด complication อะไร — A. renal failure B. weakness C. central pontine myelinolysis",
  opts:["Acute kidney injury","Generalized muscle weakness","Central pontine myelinolysis","Cerebral edema","Hyperkalemia"],
  ans:2, key:"C central pontine myelinolysis"+KS,
  interp:"ถามภาวะแทรกซ้อนจากการ <b>แก้ hyponatremia เร็วเกินไป</b> — ทิศทางของการแก้ (Na ขึ้นเร็ว) เป็นตัวตัดสิน ไม่ใช่ตัวภาวะ hyponatremia เอง",
  why:"ใน chronic hyponatremia (&gt;48 ชม.) เซลล์สมองปรับตัวโดยขับ osmolyte ออกเพื่อลดการบวม ถ้าเพิ่ม serum Na เร็ว serum osmolality ขึ้นเร็วกว่าที่เซลล์จะสร้าง osmolyte กลับ → น้ำออกจากเซลล์ <b>เซลล์สมองเหี่ยว</b> → demyelination ที่ pons (และ extrapontine) = <b>central pontine myelinolysis</b> ซึ่งปัจจุบันเรียก <b>osmotic demyelination syndrome (ODS)</b>; อาการมักล่าช้า 2–6 วันหลังแก้ dysarthria, dysphagia, quadriparesis จนถึง locked-in และ coma; ป้องกันโดยจำกัดการเพิ่ม Na ไม่เกิน 8–10 mEq/L ใน 24 ชม. (กลุ่มเสี่ยงสูง ≤8)",
  wrong:[
    "Acute kidney injury ไม่ได้เป็นผลจากการเพิ่ม Na เร็ว — hypertonic saline ไม่ทำให้ไตวายโดยตรง; จะถูกถ้าโจทย์ถามผลของ hypovolemia ที่ไม่ได้แก้ หรือ rhabdomyolysis ที่พบร่วมกับ hyponatremia รุนแรงบางราย",
    "Generalized weakness หรือ quadriparesis เป็น<b>อาการหนึ่ง</b>ของ ODS ได้ แต่เป็นอาการไม่จำเพาะ ไม่ใช่ชื่อภาวะแทรกซ้อนที่ถาม และ hyponatremia เองก็ทำให้อ่อนเพลียได้; จะถูกถ้าโจทย์ถามอาการของ hyponatremia ระดับปานกลาง",
    "Cerebral edema เกิดจาก<b>ทิศตรงข้าม</b> คือแก้ hypernatremia เร็วเกิน (ให้น้ำเปล่าเร็ว น้ำเข้าเซลล์) หรือ acute hyponatremia ที่ไม่ได้แก้; จะถูกถ้าโจทย์เป็น Na 165 แล้วให้ D5W เร็วเกินจนชัก",
    "Hyperkalemia ไม่สัมพันธ์กับการให้ hypertonic saline — การให้ NaCl และ volume มักเพิ่มการขับ K ทางไตด้วยซ้ำ; จะถูกถ้าโจทย์ถามภาวะแทรกซ้อนของ massive transfusion หรือ adrenal insufficiency ที่มาด้วย hyponatremia ร่วม hyperkalemia"],
  trap:"สับสนทิศทาง: แก้ hyponatremia เร็ว → สมอง<b>เหี่ยว</b> = ODS; แก้ hypernatremia เร็ว → สมอง<b>บวม</b> = cerebral edema; และลืมว่าเพดานคิดต่อ 24 ชม. ไม่ใช่แค่ต่อชั่วโมง",
  summary:[
    "Osmotic demyelination syndrome (ชื่อเดิม central pontine myelinolysis) เกิดจากเพิ่ม serum Na เร็วเกินใน chronic hyponatremia (&gt;48 ชม. หรือไม่ทราบระยะเวลา)",
    "กลุ่มเสี่ยงสูง: Na ≤105–110, alcoholism, malnutrition, hypokalemia, liver disease หรือหลังปลูกถ่ายตับ, thiazide",
    "เพดานการแก้: ไม่เกิน 8–10 mEq/L ใน 24 ชม. (กลุ่มเสี่ยงสูง ≤8); ตำราไทยในเฉลยใช้ &lt;0.5 mEq/L/ชม., ไม่เกิน 10 mEq/L/วัน, aim &lt;130 ในวันแรก",
    "Hyponatremia ที่มีอาการรุนแรง (ชัก ซึม): 3% NaCl 150 mL IV bolus ใน 20 นาที ซ้ำได้จน Na เพิ่มราว 5 mEq/L แล้วชะลอ",
    "อาการ ODS ล่าช้า 2–6 วัน: dysarthria, dysphagia, quadriparesis, pseudobulbar palsy, locked-in syndrome; วินิจฉัยด้วย MRI ซึ่งอาจเห็นช้ากว่าอาการ",
    "ถ้าแก้เกินเพดาน → re-lower ด้วย D5W ± desmopressin; ตรวจ Na ทุก 2–4 ชม. ช่วงแรก และระวัง aquaresis เมื่อแก้สาเหตุแล้ว",
    "ทิศตรงข้าม: แก้ hypernatremia เร็วเกิน → cerebral edema (ลดไม่เกิน ~10–12 mEq/L ต่อวันใน chronic)",
    "ดูข้อ 1, 3, 4, 5 (fluid และ electrolyte)"],
  notes:"เฉลยในไฟล์ (มีรูป) = สแกนข้อความตำราไทย:<br>\"- การให้ Na⁺ ทางหลอดเลือดดำ จะให้เมื่อมีอาการ โดยมักใช้ hypertonic saline เช่น 3% NaCl ไม่ควรให้เร็วจนเกินไป เพราะจะทำให้เกิดการเปลี่ยนแปลงของ serum osmolarity เร็ว → cell สมองเหี่ยว → <b>central pontine myelinolysis</b> (ผู้ป่วยมี quadriplegia และ coma ได้) ควรประมาณให้ plasma Na⁺ เพิ่มช้าๆ เช่น &lt; 0.5 mEq/L/hr และเพิ่มไม่เกิน 10 mEq/L/day, aim &lt; 130 mEq/L ในวันแรก\"<br>ต้นฉบับมีช้อยแค่ 3 ตัว (A. renal failure B. weakness C. central pontine myelinolysis) — ช้อย D (Cerebral edema) และ E (Hyperkalemia) แต่งเพิ่ม; stem เติมคำว่า chronic ให้ครบบริบทของคำถาม",
  mnemonic:"<b>\"From low to high, your pons will die; from high to low, your brains will blow\"</b>",
  guide:"European hyponatraemia guideline 2014; US expert panel 2013",
  opinion:"เห็นด้วยกับคีย์ C มั่นใจสูง — ชื่อปัจจุบันคือ osmotic demyelination syndrome",
  variants:[
    "ชายติดสุราเรื้อรัง Na 108 ได้ 3% NaCl จน Na เป็น 124 ใน 24 ชม. วันที่ 4 พูดไม่ชัด กลืนลำบาก แขนขาอ่อนแรงทั้งสี่ → osmotic demyelination syndrome",
    "หญิงหลังผ่าตัดได้ hypotonic fluid มาก Na 118 ชักเกร็ง → 3% NaCl 150 mL bolus ใน 20 นาที ซ้ำได้จน Na ขึ้น ~5 mEq/L",
    "ผู้ป่วย Na 168 ได้ D5W เร็วจน Na ลดลง 20 mEq/L ใน 12 ชม. แล้วชัก → cerebral edema"]}),

A({page:1, page2:4, orig:"3", kimg:KI(3),
  stem:"A 70-kg man has just undergone appendectomy. On the evening of surgery (postoperative day 0) he is NPO with no drains or ongoing losses. Which maintenance IV fluid order is most appropriate?",
  gray:"Maintenance fluid for patient 70 kg. post-appendectomy? — A. 5% DNSS/2 + KCl 20 mEq 80 mL/hr B. 5% DNSS/2 100 mL/hr C. 5% DNSS/2 + KCl 10 mEq 80 mL/hr D. 0.9 NaCl 100 ml/hr E. TPN",
  opts:["5% D/N/2 with KCl 20 mEq/L at 80 mL/hr","5% D/N/2 at 100 mL/hr","5% D/N/2 with KCl 10 mEq/L at 80 mL/hr","0.9% NaCl at 100 mL/hr","Total parenteral nutrition"],
  ans:1, key:"B 5% DNSS/2 100 mL/hr"+KS,
  flag:"⚠ เล็กน้อย: เติม \"postoperative day 0, NPO, no drains or ongoing losses\" ใน stem ให้เหตุผล \"ยังไม่ให้ K วันแรก\" ใช้ได้",
  interp:"โจทย์ให้น้ำหนัก 70 kg และเป็นวันผ่าตัด (POD 0) ไม่มี loss อื่น → คำนวณ <b>maintenance เท่านั้น</b> ทั้ง volume (rate), Na, K และ dextrose แล้วเลือกช้อยที่ตรงที่สุด",
  why:"Holliday-Segar ของคน 70 kg = (100×10)+(50×10)+(20×50) = <b>2,500 mL/วัน ≈ 100 mL/ชม.</b> (สูตร 4-2-1 = 40+20+50 = 110 mL/ชม.); Na ต้องการ 2–3 mEq/kg/วัน และ dextrose ~100 g/วันเพื่อ <b>protein sparing</b> → 5% D/N/2 (Na 77 mEq/L, dextrose 50 g/L) 2,500 mL ได้ Na ~190 mEq และ dextrose ~125 g พอดี; <b>K ยังไม่ให้ใน POD 0–1</b> ตามเฉลย เพราะ tissue injury ปล่อย K ออกจากเซลล์ ภาวะ oliguria จาก stress และยังไม่มี loss → B ครบทุกองค์ประกอบ",
  wrong:[
    "5% D/N/2 + KCl 20 mEq/L ที่ 80 mL/ชม. = 1,920 mL/วัน เป็น rate ของคน <b>~50 kg</b> (ตรงกับเคสในสแกนของเฉลย) ต่ำไปสำหรับ 70 kg และให้ K ตั้งแต่ POD 0; จะถูกถ้าผู้ป่วยหนัก ~50 kg อยู่ POD 2 ขึ้นไป ปัสสาวะดี ยังกินไม่ได้",
    "5% D/N/2 + KCl 10 mEq/L ที่ 80 mL/ชม. ผิดเหมือนกันทั้ง rate ต่ำสำหรับ 70 kg และให้ K ในวันแรก — KCl 10 mEq/L ได้ K เพียง ~19 mEq/วัน ต่ำกว่าความต้องการ 1 mEq/kg อยู่ดี; จะถูกเมื่อน้ำหนักน้อยกว่าและต้องการเสริม K เล็กน้อยในวันถัดไป",
    "0.9% NaCl 100 mL/ชม. rate พอ แต่<b>ไม่มี dextrose</b> (ไม่มี protein sparing) และให้ Na ~370 mEq/วัน กับ Cl สูงเกิน → เสี่ยง hyperchloremic acidosis และน้ำเกิน; จะถูกถ้าเป็น resuscitation หรือทดแทน deficit ใน hypovolemia หรือทดแทน gastric loss",
    "TPN ไม่จำเพาะต่อ maintenance และไม่จำเป็นหลัง appendectomy ที่คาดว่าจะกินได้ภายในไม่กี่วัน; จะถูกเมื่อคาดว่ากินหรือให้ enteral ไม่ได้นาน &gt;5–7 วัน หรือมี intestinal failure"],
  trap:"เลือกช้อยที่มี KCl เพราะคิดว่า maintenance ต้องมี K เสมอ หรือเลือก 80 mL/ชม. เพราะจำ rate จากเคสตัวอย่าง 50 kg — ต้องคำนวณตามน้ำหนักจริง 70 kg และดูวันหลังผ่าตัด",
  summary:[
    "Holliday-Segar: 100 mL/kg สำหรับ 10 kg แรก + 50 mL/kg สำหรับ 10 kg ถัดไป + 20 mL/kg ส่วนที่เกิน ต่อวัน; หรือ 4-2-1 mL/kg/ชม. → 70 kg ≈ 2,500 mL/วัน ≈ 100–110 mL/ชม.",
    "ความต้องการต่อวัน: Na 2–3 mEq/kg, K 1–2 mEq/kg, dextrose ~100 g เพื่อลด protein breakdown (protein sparing effect)",
    "ตำราไทยในเฉลย: ไม่ให้ K ใน POD 0–1 เพราะ tissue injury ปล่อย K, stress oliguria และยังไม่มี loss; เริ่ม K เมื่อปัสสาวะดีหรือมี loss",
    "5% D/N/2 (Na 77 mEq/L, dextrose 50 g/L) เป็น maintenance IV fluid ที่ใช้บ่อยใน adult เพราะได้ glucose ต่อเนื่องทั้งวัน",
    "NICE CG174: maintenance 25–30 mL/kg/วัน, Na K Cl อย่างละ ~1 mmol/kg/วัน, glucose 50–100 g/วัน — อนุญาตให้ K ได้ถ้าไตปกติ",
    "ปริมาณรวม = maintenance + deficit + ongoing loss (drain, NG, fistula, ไข้) ทดแทน loss แยกด้วย fluid ที่ composition ใกล้เคียง",
    "TPN ใช้เมื่อคาดว่าลำไส้ใช้ไม่ได้นาน &gt;5–7 วัน หรือ intestinal failure ไม่ใช่ maintenance หลังผ่าตัดทั่วไป",
    "ดูข้อ 1, 2, 7, 8 (fluid และ nutrition หลังผ่าตัด)"],
  notes:"เฉลยในไฟล์ (มีรูป) มีสองส่วน<br><b>(1) สแกนเอกสาร:</b> \"Case 1: ผู้ป่วยชาย 20 ปี ผ่าตัดไส้ติ่ง หนัก 50 kg, post op. day 1 (ไม่มี drain, ไม่มี deficit, ไม่มี insensible loss ที่มากขึ้น), V/S stable, NPO อยู่<br>1. Volume → MN = 2,100 cc/day<br>2. Concentration → Na⁺ 2-3 mEq/Kg/day = 100-150 mEq/day<br>3. Compositions → K⁺ ยังไม่ให้ใน postoperative day 0-1 → Energy อาจให้ Dextrose ~100 g/d (340 kcal) เพื่อ ↓ protein break down (protein sparing effect)<br>4. Type of IV fluid: IV fluid เพื่อให้ได้ Volume 2,000 cc/d, Na ประมาณ 150 mEq/day และ Glucose 100 g/day อาจให้เป็น – 10% D/W 1,000 cc + 0.9% NaCl 1,000 cc – 10% D/N/2 1,000 cc + 0.45% NaCl 1,000 cc – 5% DN/2 1,000 cc x II *ส่วนมากมักสั่งแบบนี้ เพราะจะได้ glucose ต่อเนื่องทั้งวัน **นี่จึงเป็นสาเหตุที่ <b>เรามักใช้ 5% DN/2 เป็น Maintenance IV fluid (MIVF) ใน adult</b><br>5. Rate → ให้สารน้ำต่อเนื่องตลอดทั้งวัน Volume ~2,000 cc, rate ~80 cc/hr<br>*สรุป: สั่ง 5% DN/2 1,000 cc iv drip 80 cc/hr x II ขวด ต่อวัน\"<br><b>(2) ข้อความพิมพ์ของผู้เฉลย:</b> \"1. <b>volume</b> = maintenance <s>+ deficit + insensible loss</s> โจทย์บอกไม่มี - Holiday Segar law for a 70 kg man (100x10)+(50x10)+(20x50) = <b>2500 mL/d</b><br>2. concentration - Na+ ~2-3 mEq/kg/d = ~140-210 mEq/d<br>3. compositions - K+ ~1-2 mEq/kg/d = ~70-140 mEq/d <b>ไม่ให้ในวันแรก</b> - energy อาจให้ dextrose ~100g/d เพื่อลด protein breakdown<br>4. type of IV fluids IV fluid เพื่อให้ได้ volume 2500 mL/d, Na 210 mEq/d, dextrose 100 g/d - มักให้ 5%DN/2 1000mL x3 - volume 2500mL/24h = <b>~100mL/1h</b>\" (ข้อความ \"+ deficit + insensible loss\" ถูกขีดฆ่าในไฟล์)<br>ต้นฉบับโจทย์มีแค่ \"Maintenance fluid for patient 70 kg. post-appendectomy?\" — เราเติม POD 0, NPO, no drains or ongoing losses ใน stem; ช้อยเขียน 5% DNSS/2 เป็น 5% D/N/2 และ KCl 20 mEq เป็น KCl 20 mEq/L",
  mnemonic:"<b>4-2-1</b>: 10 kg แรก 4 mL/kg/ชม., 10 kg ถัดไป 2, ที่เหลือ 1 → ผู้ใหญ่ ≈ น้ำหนัก + 40 mL/ชม.",
  guide:"NICE CG174 IV fluids in adults 2013 (updated 2017)",
  opinion:"เห็นด้วยกับคีย์ B มั่นใจสูงหลังเติมบริบท — Holliday-Segar 70 kg = 2,500 mL/วัน ≈ 104 mL/ชม. (4-2-1 = 110 mL/ชม.); A และ C ใช้ rate 80 mL/ชม. ซึ่งเป็นของคนราว 50 kg ตามเคสในสแกน; D ไม่มี dextrose และ Na เกิน; TPN ไม่จำเป็นถ้าคาดว่ากินได้ใน 5–7 วัน. NICE CG174 (25–30 mL/kg/วัน, Na K Cl ~1 mmol/kg/วัน, glucose 50–100 g/วัน) อนุญาตให้ K ตั้งแต่วันแรกถ้าไตปกติ แต่ใน POD 0 ที่ไม่มี loss ช้อย B ยังเหมาะที่สุด — จึงเติม POD 0 และไม่มี loss ใน stem เพื่อให้เหลือคำตอบเดียวชัดเจน",
  variants:[
    "หญิง 50 kg หลัง appendectomy POD 2 ยัง NPO ปัสสาวะดี ไม่มี drain → 5% D/N/2 + KCl 20 mEq/L ที่ ~80 mL/ชม.",
    "ชาย 80 kg POD 0 หลังผ่าตัดลำไส้ มี NG ออก 1,000 mL/วัน → maintenance 5% D/N/2 ~120 mL/ชม. และทดแทน NG loss ด้วย 0.9% NaCl + KCl mL ต่อ mL",
    "ผู้ป่วยหลังผ่าตัดใหญ่คาดว่าจะกินไม่ได้อย่างน้อย 10 วันและให้ enteral ไม่ได้ → พิจารณา parenteral nutrition"]}),

A({page:1, page2:4, orig:"4", kimg:KI(4),
  stem:"A patient vomits after every meal and appears dehydrated. Examination shows upper abdominal distension and a positive succussion splash. Which finding is LEAST likely?",
  gray:"คนไข้มาด้วยทานอาหารแล้วอาเจียนหลังทานอาหาร มาหาหมอ ดู dehydrate PE: มี upper abdominal distension splashing sound positive ถามว่าข้อไหนมีโอกาสจะเจอในคนไข้คนนี้<b>น้อยที่สุด</b> — A. Metabolic alkalosis B. Hypochloremia C. Hypokalemia D. Aciduria E. Respiratory acidosis",
  opts:["Metabolic alkalosis","Hypochloremia","Hypokalemia","Aciduria","Respiratory acidosis"],
  ans:4, key:"E Respiratory acidosis"+KS,
  interp:"อาเจียนหลังอาหาร + upper abdominal distension + succussion splash = <b>gastric outlet obstruction</b> → ผู้ป่วยเสีย HCl และน้ำจากกระเพาะ ถามสิ่งที่<b>พบน้อยที่สุด</b> ต้องแยก primary disorder ออกจาก compensation",
  why:"การเสีย gastric juice ทำให้เกิด <b>hypochloremic hypokalemic metabolic alkalosis</b>; respiratory system ชดเชยด้วย <b>hypoventilation</b> PaCO2 ขึ้นราว 0.7 mmHg ต่อ HCO3 ที่เพิ่ม 1 mEq/L — PaCO2 ที่สูงนี้เป็น<b>การชดเชย</b> ไม่ใช่ primary respiratory acidosis และ pH ยังเป็น alkalemia; respiratory acidosis แบบ primary ต้องมีปัญหาการหายใจ (ยากด, COPD, neuromuscular) ซึ่งโจทย์ไม่มี → พบน้อยที่สุด",
  wrong:[
    "Metabolic alkalosis พบแน่นอน — เสีย H⁺ และ Cl⁻ ไปกับอาเจียน ร่วมกับ volume contraction ทำให้ไตดูด HCO3 กลับ (ลายมือ \"Met alkalosis สื่อ ↑HCO3⁻\"); จะเป็นคำตอบเฉพาะเมื่อโจทย์ถามสิ่งที่พบ<b>มากที่สุด</b>หรือ primary disorder",
    "Hypochloremia พบเสมอ เพราะ gastric juice มี Cl 100–130 mEq/L และ Cl ที่ต่ำทำให้ alkalosis คงอยู่ (chloride-responsive, urine Cl &lt;20 mEq/L); จะไม่พบถ้าเป็น chloride-resistant alkalosis จาก mineralocorticoid excess",
    "Hypokalemia พบได้บ่อย — สาเหตุหลักคือ<b>ไตขับ K</b> (aldosterone สูงจาก volume depletion และ HCO3 ที่ไปถึง distal tubule) มากกว่าเสียใน gastric juice (K 10–30); จะไม่พบถ้าเป็นภาวะที่ aldosterone ต่ำหรือไตวาย",
    "Aciduria พบได้ในระยะหลัง = <b>paradoxical aciduria</b>: เมื่อ volume ลดมาก aldosterone เพิ่ม ไตดูด Na⁺ กลับโดยแลกขับ K⁺ และเมื่อ K หมด ก็ขับ H⁺ แทน ปัสสาวะจึงเป็นกรดทั้งที่เลือด alkalosis; ระยะแรก ปัสสาวะยัง alkaline (ขับ HCO3)"],
  trap:"เห็น PaCO2 สูงจาก compensation แล้วคิดว่าเป็น respiratory acidosis ร่วม หรือคิดว่า aciduria ขัดกับ alkalosis จึงเลือก aciduria — paradoxical aciduria เป็นลักษณะเด่นของ gastric outlet obstruction ที่เป็นมานาน",
  summary:[
    "Gastric outlet obstruction (PUD, มะเร็งกระเพาะ, pyloric stenosis): อาเจียนอาหารไม่มีน้ำดี หลังอาหาร, upper abdominal distension, succussion splash, dehydration",
    "Acid-base: hypochloremic hypokalemic metabolic alkalosis — ระยะแรกปัสสาวะ alkaline, ระยะหลัง paradoxical aciduria",
    "กลไก paradoxical aciduria: volume ลด → aldosterone ↑ → ดูด Na⁺ แลกขับ K⁺ และ H⁺; K ต่ำทำให้ขับ H⁺ มากขึ้นอีก",
    "Respiratory compensation: hypoventilation PaCO2 ↑ ~0.7 mmHg ต่อ HCO3 ↑1 mEq/L (ไม่ค่อยเกิน ~55 mmHg) — เป็นการชดเชย ไม่ใช่ primary respiratory acidosis",
    "Chloride-responsive alkalosis (urine Cl &lt;20 mEq/L) → รักษาด้วย 0.9% NaCl + KCl เมื่อปัสสาวะออก (เฉลย: volume replacement ด้วย NSS ไม่ต้องสนใจกรด-เบส)",
    "ร่วมกับ NG decompression, แก้ electrolyte, แล้วหาสาเหตุด้วย endoscopy (biopsy แยกมะเร็ง) ก่อนรักษา definitive",
    "ดูข้อ 1, 5, 36 (ข้อ 36 แนวเดียวกัน — gastric outlet obstruction ไม่พบ respiratory acidosis)"],
  notes:"เฉลยในไฟล์ (มีรูป): ข้อความพิมพ์ <b>\"Gastric outlet obstruction\"</b> + ภาพกระดานดำลายมือ:<br>\"Met alkalosis สื่อ ↑HCO3⁻, อาการแสดงสามารถมี hypokalemia ได้ อันนี้ไม่ค่อยอันตราย ให้รักษาที่สาเหตุ<br>ตัวอย่าง Gastric outlet obstruction มีการอาเจียนเสียน้ำเสีย HCl ออกเยอะ โดยมีการขับ HCO3⁻ โดยไต แต่พอเสียน้ำออกเยอะ ร่างกายก็ Aldosterone หลั่ง ร่างกายดูด Na⁺ และขับ K⁺ กับ H⁺ ทำให้มี Aciduria ทั้งที่ Alkalosis เรียกว่า <b>Paradoxical aciduria</b><br>Treatment: Volume replacement ด้วย NSS ไม่ต้องสนใจกรด-เบส\" (คำท้ายบรรทัดอ่านไม่ชัด ถอดตามที่เห็น)<br>ต้นฉบับโจทย์เน้นคำว่า \"น้อยที่สุด\"; stem ของเราใช้ LEAST และแปล splashing sound เป็น succussion splash",
  mnemonic:"อาเจียนกระเพาะ = <b>\"ต่ำ Cl ต่ำ K สูง HCO3\"</b> แล้วปัสสาวะกลับเป็นกรด (paradoxical)",
  guide:"Schwartz 11th ed.",
  opinion:"เห็นด้วยกับคีย์ E มั่นใจสูง",
  variants:[
    "ชายมีประวัติ PUD อาเจียนอาหารที่กินเมื่อวาน ABG pH 7.52 HCO3 38 PaCO2 48 urine pH 5.5 → ถาม urine pH ที่เป็นกรดเรียกว่าอะไร → paradoxical aciduria",
    "ผู้ป่วยอาเจียนมาก 5 วัน urine Cl 8 mEq/L → chloride-responsive metabolic alkalosis รักษาด้วย 0.9% NaCl + KCl",
    "ทารก 4 สัปดาห์ อาเจียนพุ่งไม่มีน้ำดี คลำได้ก้อน olive → hypochloremic hypokalemic metabolic alkalosis แก้ fluid ก่อนทำ pyloromyotomy"]}),

A({page:1, page2:4, orig:"5",
  stem:"A patient has been vomiting repeatedly for 3 days and is clinically dehydrated with dry mucosa and tachycardia. Serum Na 135, K 3.5, Cl 90 and HCO3 34 mEq/L. Which choice of initial IV fluid, with its rationale, is correct?",
  gray:"คนไข้ Na 135 K 3.5 Cl 90 (ไม่แน่ใจ แต่ Cl ดูต่ำ) ข้อไหนบอกการให้สารน้ำและเหตุผลได้ถูกต้อง — A. ให้ Cl เนื่องจาก Chloride ต่ำ B. ให้ NSS เนื่องจากช่วยแก้ hypovolemia C. ให้ KCl เนื่องจาก K ต่ำ D. ให้ HCO3",
  opts:["Ammonium chloride because chloride is low","0.9% NaCl because it corrects hypovolemia","Potassium chloride alone because potassium is low","Sodium bicarbonate","5% dextrose in water"],
  ans:1, key:"B ให้ NSS เนื่องจากช่วยแก้ hypovolemia (คีย์เขียน B มั้ง)"+KS,
  flag:"⚠ ต้นฉบับจดโจทย์ไม่ครบ ผู้จดไม่แน่ใจค่า Cl และคีย์เขียน 'B มั้ง' — เติมบริบทใน stem",
  interp:"ผู้ป่วยอาเจียนหลายวัน มี dehydration, Cl ต่ำ, HCO3 สูง = <b>chloride-responsive metabolic alkalosis</b> ร่วม hypovolemia — ถามสารน้ำเริ่มต้น<b>พร้อมเหตุผล</b>ที่ถูก ต้องดูทั้งชนิดสารน้ำและเหตุผลที่จับคู่มา",
  why:"<b>0.9% NaCl</b> แก้ปัญหาหลักคือ <b>volume depletion</b> และให้ Cl⁻ (154 mEq/L) ไปพร้อมกัน เมื่อ volume กลับมา aldosterone ลด และ Cl ที่ไปถึง distal tubule พอ ไตจะ<b>ขับ HCO3 ส่วนเกินออก</b>ได้เอง alkalosis จึงหาย; เสริม KCl ใน NSS เมื่อปัสสาวะออกดี (K 3.5 อยู่ขอบล่าง และจะลดลงเมื่อแก้ alkalosis)",
  wrong:[
    "Ammonium chloride (ต้นฉบับ \"ให้ Cl เนื่องจาก Chloride ต่ำ\") เป็น acidifying agent ที่ใช้เฉพาะ metabolic alkalosis รุนแรงที่ไม่ตอบสนองหรือให้ NSS ไม่ได้ ไม่ใช่ขั้นแรก และ<b>ไม่แก้ volume</b>; NSS ก็ให้ Cl อยู่แล้ว; จะถูกถ้าโจทย์เป็น alkalosis รุนแรง pH &gt;7.6 ที่ volume overload ให้ saline ไม่ได้ (ทางเลือกอื่นคือ acetazolamide หรือ HCl เจือจางทาง central line)",
    "Potassium chloride อย่างเดียว (ต้นฉบับ \"ให้ KCl เนื่องจาก K ต่ำ\") — K 3.5 ยังอยู่ขอบล่างของค่าปกติ และ KCl อย่างเดียวไม่แก้ hypovolemia ซึ่งเป็นตัวขับเคลื่อน alkalosis; ควรเสริม KCl <b>ใน</b> NSS; จะถูกถ้าโจทย์ให้ K &lt;3.0 ใน euvolemic patient ที่ปัสสาวะดี",
    "Sodium bicarbonate (ต้นฉบับ \"ให้ HCO3\" ไม่ได้ระบุเหตุผล) ทำให้ <b>alkalosis แย่ลง</b> เพราะผู้ป่วย HCO3 สูงอยู่แล้ว; จะถูกในการเสีย HCO3 ทาง pancreatic fistula หรือ diarrhea ที่มี normal anion gap metabolic acidosis",
    "5% dextrose in water ไม่มี Na และ Cl จึงไม่อยู่ใน intravascular space นาน ไม่แก้ hypovolemia และไม่ให้ Cl ที่ไตต้องการเพื่อขับ HCO3 ยังเสี่ยง hyponatremia; จะถูกถ้าแก้ hypernatremia หรือ free water deficit"],
  trap:"เห็น Cl ต่ำแล้วเลือก \"ให้ Cl\" หรือเห็น K 3.5 แล้วเลือก KCl — ปัญหาหลักคือ volume depletion ซึ่ง NSS แก้ทั้ง volume และ Cl ได้ในคราวเดียว",
  summary:[
    "Metabolic alkalosis แบ่งตาม urine Cl: &lt;20 mEq/L = chloride-responsive (อาเจียน, NG suction, diuretic ระยะหลัง) / &gt;20 mEq/L = chloride-resistant (hyperaldosteronism, Cushing, Bartter/Gitelman, hypokalemia รุนแรง)",
    "การคงอยู่ของ alkalosis จาก volume contraction, Cl ต่ำ และ K ต่ำ ทำให้ไตดูด HCO3 กลับ",
    "รักษา chloride-responsive: 0.9% NaCl แก้ volume และ Cl → ไตขับ HCO3 ได้ + KCl เมื่อปัสสาวะออก",
    "รักษาสาเหตุร่วม: NG decompression, หยุด diuretic, PPI ลดการเสียกรดจาก NG",
    "Alkalosis รุนแรงหรือ volume overload: acetazolamide, ammonium chloride หรือ HCl เจือจางทาง central line, หรือ dialysis",
    "ห้ามให้ bicarbonate และระวัง D5W ใน hypovolemia",
    "ดูข้อ 1, 4, 36 (gastric loss และ metabolic alkalosis)"],
  notes:"<b>ต้นฉบับจดโจทย์ไม่ครบ</b>: มีแค่ \"คนไข้ Na 135 K 3.5 Cl 90\" และผู้จดเขียนในวงเล็บว่า <b>\"(ไม่แน่ใจ แต่ Cl ดูต่ำ)\"</b> — ไม่มีประวัติ ไม่มีค่า HCO3; เราเติมใน stem ว่าอาเจียน 3 วัน, dehydrated (dry mucosa, tachycardia) และ HCO3 34 mEq/L เพื่อให้ตีความเป็น chloride-responsive metabolic alkalosis ร่วม hypovolemia ได้<br>ไฟล์เฉลยข้อ 5: <b>\"B มั้ง โจทย์ไม่ครบ\"</b> (ไม่มีคำอธิบายเพิ่มหรือรูป)<br>ปรับช้อย: A ต้นฉบับ \"ให้ Cl เนื่องจาก Chloride ต่ำ\" → Ammonium chloride because chloride is low; B ต้นฉบับ \"ให้ NSS เนื่องจากช่วยแก้ hypovolemia\"; C ต้นฉบับ \"ให้ KCl เนื่องจาก K ต่ำ\" → Potassium chloride alone because potassium is low; D ต้นฉบับ \"ให้ HCO3\" (ไม่มีเหตุผล) → Sodium bicarbonate; ต้นฉบับมีช้อยแค่ 4 ตัว — E (5% dextrose in water) แต่งเพิ่ม",
  mnemonic:"",
  guide:"Schwartz 11th ed.",
  opinion:"เห็นด้วยกับคีย์ B แต่<b>ความมั่นใจปานกลาง</b>เพราะโจทย์ต้นฉบับจดไม่ครบและคีย์เองเขียน \"B มั้ง โจทย์ไม่ครบ\". ด้วยค่า Na 135, K 3.5, Cl 90 ที่ผู้จดให้ Cl ดูต่ำ บริบทที่เข้ากันที่สุดคือผู้ป่วยเสีย gastric fluid (แนวเดียวกับข้อ 4 และข้อ 36) — เมื่อเติมอาเจียน, dehydration และ HCO3 34 แล้ว NSS เป็นคำตอบเดียวที่ถูกทั้งสารน้ำและเหตุผล. ถ้าโจทย์จริงเป็นผู้ป่วยที่ไม่มี hypovolemia (euvolemic) และ K ต่ำกว่านี้มาก ช้อย KCl อาจเป็นคำตอบได้ แต่ต้นฉบับ K 3.5 ยังไม่ต่ำ",
  variants:[
    "ผู้ป่วยใส่ NG ดูดต่อเนื่อง 5 วัน HCO3 36 Cl 88 K 3.0 urine Cl 10 → 0.9% NaCl + KCl",
    "ผู้ป่วย primary hyperaldosteronism HCO3 32 K 2.8 ความดันสูง urine Cl 40 → chloride-resistant ให้ NSS ไม่ช่วย ต้องแก้ K และรักษาสาเหตุ",
    "ผู้ป่วย heart failure ได้ furosemide ขนาดสูงจน HCO3 38 บวมทั่วตัว → ให้ NSS ไม่ได้ พิจารณา acetazolamide และ KCl"]}),

A({page:1, page2:5, orig:"6", kimg:KI(6),
  stem:"A patient with acute appendicitis has been kept NPO for 5 days while awaiting surgery, without nutritional support. Which pair of metabolic processes is predominantly increased at this stage?",
  gray:"ผู้ป่วย Appendicitis NPO 5 วัน รอผ่า which metabolic process increase — A. Gluconeogenesis, B. Glycolysis, C. Proteolysis, Ketogenesis D. Glycogenolysis, E. Lipolysis,",
  opts:["Glycogenolysis and glycolysis","Glycogenolysis and gluconeogenesis","Glycogenesis and lipogenesis","Lipolysis and ketogenesis","Proteolysis and glycogenolysis"],
  ans:3, key:"D lipolysis+ketogenesis"+KS,
  flag:"⚠ ช้อยต้นฉบับจดเป็นคำเดี่ยวมีจุลภาคค้าง และ C จด \"Proteolysis, Ketogenesis\" แสดงว่าช้อยจริงเป็นคู่ — เราทำช้อยเป็นคู่ทั้งหมด มีคู่ที่ถูกตามคีย์คู่เดียว",
  interp:"ถามกระบวนการ metabolic ที่<b>เด่นในวันที่ 5 ของการอดอาหาร</b> (ยังไม่ผ่าตัด ไม่ได้ให้ nutrition) — ต้องรู้ timeline ของ starvation ว่าแต่ละช่วงร่างกายใช้พลังงานจากไหน",
  why:"Timeline ของ starvation: glycogen ในตับหมดใน ~24–36 ชม. (glycogenolysis 0–24 ชม.) → gluconeogenesis จาก alanine, lactate, glycerol เด่นช่วง 1–3 วัน (สลาย protein มาก) → หลัง ~3–5 วัน <b>keto-adaptation</b>: insulin ต่ำ glucagon สูง ทำให้ <b>lipolysis</b> ปล่อย fatty acid และตับเปลี่ยนเป็น ketone (<b>ketogenesis</b>) ให้สมองและกล้ามเนื้อใช้แทน glucose → ลดความต้องการ glucose และลด proteolysis (<b>protein sparing</b>); ตารางในเฉลยให้ ketogenesis และ lipolysis ช่วง 3–7 วัน และเขียนว่า \"คู่กัน\" → วันที่ 5 ตอบ lipolysis + ketogenesis",
  wrong:[
    "Glycogenolysis และ glycolysis — glycogenolysis เด่นแค่ 0–24 ชม. แรกและ glycogen หมดแล้วในวันที่ 5; glycolysis (การใช้ glucose) ลดลงเมื่อเนื้อเยื่อหันไปใช้ fatty acid และ ketone; จะถูก (ครึ่งแรก) ถ้าโจทย์ถามช่วงอดอาหาร 12–24 ชม. แรก",
    "Glycogenolysis และ gluconeogenesis เป็นคู่ของช่วง<b>ต้น</b> (0–3 วัน) — วันที่ 5 glycogen หมด และ gluconeogenesis เริ่มลดลงเมื่อสมองใช้ ketone; จะถูกถ้าโจทย์ถามผู้ป่วย NPO 1–2 วัน หรือระยะแรกหลังการบาดเจ็บ",
    "Glycogenesis และ lipogenesis เป็นกระบวนการ<b>สะสม</b>พลังงานในภาวะ fed state ที่ insulin สูง ตรงข้ามกับ starvation; จะถูกถ้าโจทย์ถามภาวะหลังกินอาหารหรือ overfeeding จาก TPN",
    "Proteolysis และ glycogenolysis — proteolysis เด่นช่วงแรก (ส่ง amino acid ไปทำ gluconeogenesis) แล้ว<b>ลดลง</b>หลัง keto-adaptation และเพิ่มอีกครั้งในระยะท้ายเมื่อไขมันหมด (&gt;7 วันในตารางเฉลย); ในภาวะ injury หรือ sepsis proteolysis จะเด่นตลอด; จะถูกถ้าโจทย์เป็นผู้ป่วย sepsis หรือหลังผ่าตัดใหญ่ (stress catabolism)"],
  trap:"เอาภาวะ <b>simple starvation</b> ไปปนกับ <b>stress (injury, sepsis)</b>: ใน starvation หลังวันที่ 3 ketogenesis เพิ่มและ proteolysis ลด แต่ใน injury ketogenesis ถูกกดด้วย insulin และ cytokine ขณะที่ proteolysis และ gluconeogenesis เด่น",
  summary:[
    "0–24 ชม.: glycogenolysis (glucagon, epinephrine, cortisol) — glycogen ในตับหมดใน ~24–36 ชม.",
    "1–3 วัน: gluconeogenesis จาก alanine, lactate (Cori cycle), glycerol — สลาย protein มาก",
    "3–7 วัน: lipolysis + ketogenesis (keto-adaptation) — สมองใช้ ketone ลดการใช้ glucose → protein sparing",
    "&gt;7 วัน หรือเมื่อไขมันหมด: proteolysis เพิ่มอีกครั้ง → กล้ามเนื้อฝ่อ ภูมิต้านทานลด",
    "Stress หรือ injury (ผ่าตัดใหญ่, sepsis, trauma): catecholamine, cortisol, glucagon, cytokine → hypermetabolism, proteolysis และ gluconeogenesis เด่น, insulin resistance, ketogenesis ถูกกด → ร่างกายไม่ protein sparing",
    "ทางคลินิก: ผู้ป่วยที่คาดว่ากินไม่ได้นาน ควรเริ่ม nutrition support (enteral ก่อน) และให้ dextrose ~100 g/วันใน maintenance เพื่อลด protein breakdown",
    "ดูข้อ 3, 7, 8 (metabolism และ nutrition)"],
  notes:"เฉลยในไฟล์: คอลัมน์คำตอบเขียน <b>\"lipolysis+ketogenesis\"</b> (ไม่ได้ระบุตัวอักษร) + รูปตารางลายมือน้ำเงิน:<br>\"<b>ลำดับต่ำหลัก</b> / <b>timeline</b> / <b>Driven by</b><br>1. glycogenolysis / 0-24hrs / Glucagon, Epinephrine (cortisol)<br>2. gluconeogenesis / 1-3 days / Alanine, Lactate use (brain)<br>3. ketogenesis / 3-7 days / Carbohydrate↓<br>4. lipolysis / 3-7 days / Ketone use, carbohydrate↓<br>5. proteolysis / &gt;7 days / Lipid stores↓\"<br>ลายมือโยงข้อ 3 กับ 4 ว่า <b>\"คู่กัน\"</b>; มีเศษตัวอักษร \"D.\" \"E.\" และ \"***\" สีแดงติดมาจากภาพที่ตัดมา<br><b>ปรับช้อย</b>: ต้นฉบับจดช้อยเป็นคำเดี่ยวมีจุลภาคค้าง \"A. Gluconeogenesis, B. Glycolysis, C. Proteolysis, Ketogenesis D. Glycogenolysis, E. Lipolysis,\" — C มีสองคำและทุกตัวมีจุลภาคค้าง แสดงว่าช้อยจริงน่าจะเป็นคู่; เราจึงทำช้อยเป็นคู่ทั้งหมด ให้ D = Lipolysis and ketogenesis ตรงกับคีย์ และไม่ใช้คู่ \"Proteolysis and ketogenesis\" ตามต้นฉบับ C เพราะถูกครึ่งหนึ่ง",
  mnemonic:"<b>\"Glycogen 1 วัน → Gluconeo 3 วัน → Keto + Lipo 1 สัปดาห์ → Protein สุดท้าย\"</b>",
  guide:"Sabiston 21st ed.",
  opinion:"เห็นด้วยกับคีย์ lipolysis + ketogenesis มั่นใจปานกลางถึงสูง (ช้อยจริงจดไม่ครบ). โจทย์นี้เป็นภาวะ <b>fasting เด่น</b> (ยังไม่ผ่าตัด และโจทย์ไม่ได้บอก sepsis) จึงตอบ lipolysis + ketogenesis ตาม timeline ของ starvation — สอดคล้องกับข้อสอบชุด 76D (simple fasting → ketogenesis เพิ่ม) และไม่ขัดกับข้อสอบชุด 76A ที่ถามหลังผ่าตัดใหญ่ (ketogenesis ลดลงเมื่อเทียบกับ starvation เพราะ insulin และ cytokine). ถ้าโจทย์จริงบอกว่าไส้ติ่งแตกมี peritonitis หรือ sepsis คำตอบจะเอนไปทาง proteolysis และ gluconeogenesis — เราจึงเขียน stem ว่ารอผ่าตัดโดยไม่ได้ให้ nutrition และไม่เติม sepsis",
  variants:[
    "ชายอดอาหารประท้วง 3 สัปดาห์ กล้ามเนื้อลีบมาก ไขมันใต้ผิวหนังแทบไม่เหลือ → proteolysis เด่นอีกครั้งในระยะท้าย",
    "ผู้ป่วยหลังผ่าตัดลำไส้ใหญ่วันที่ 2 มี sepsis → proteolysis และ gluconeogenesis เด่น ketogenesis ถูกกด",
    "ผู้ป่วย NPO 18 ชม. ก่อนผ่าตัด → glycogenolysis เป็นแหล่ง glucose หลัก"]}),

A({page:2, page2:5, orig:"7", kimg:KI(7),
  stem:"A patient without known diabetes is NPO on postoperative day 3 after major abdominal surgery and is receiving dextrose-containing maintenance fluid. Capillary blood glucose is 220 mg/dL on repeated measurements. What is the most appropriate management?",
  gray:"คนไข้ NPO post-op day 3 เจาะน้ำตาล 220 mg/dL จะ manage ยังไง — A. sliding insulin + dextrose B. ปล่อยไว้ เพราะเป็น normal stress response หลังผ่า",
  opts:["Sliding-scale insulin with dextrose-containing fluid","No treatment, as this is a normal stress response","Stop all dextrose and observe","Start an oral sulfonylurea","IV sodium bicarbonate"],
  ans:0, key:"A sliding insulin + dextrose"+KS,
  interp:"น้ำตาลสูงซ้ำ ๆ 220 mg/dL หลังผ่าตัดใหญ่ใน NPO patient ที่ได้ dextrose = <b>stress hyperglycemia</b> ที่<b>เกินเกณฑ์ต้องรักษา</b> — ถามว่าต้องคุมหรือปล่อย และคุมอย่างไรโดยยังให้ glucose พื้นฐาน",
  why:"หลังผ่าตัด catecholamine, cortisol, glucagon และ cytokine ทำให้ <b>insulin resistance</b> และ gluconeogenesis เพิ่ม → stress hyperglycemia ซึ่งสัมพันธ์กับ SSI, sepsis, anastomotic leak และ mortality ที่สูงขึ้น; ADA 2025 แนะนำเริ่ม insulin เมื่อ glucose <b>≥180 mg/dL ต่อเนื่อง</b> เป้า <b>140–180 mg/dL</b> → ให้ insulin (correction หรือ sliding scale ± basal) โดย<b>ยังคง dextrose</b> ไว้ ~100 g/วันเพื่อกัน catabolism, ketosis และ hypoglycemia; เฉลยบนกระดาน: \"Glucose intolerance: อาจให้ Human insulin IV keep DTX 110-160 mg/dL\"",
  wrong:[
    "ปล่อยไว้เพราะเป็น normal stress response (ต้นฉบับ \"ปล่อยไว้ เพราะเป็น normal stress response หลังผ่า\") — stress hyperglycemia เกิดจริงแต่ระดับ 220 mg/dL ซ้ำ ๆ <b>เกิน 180</b> สัมพันธ์กับ infection และ mortality จึงต้องคุม; จะถูกถ้าน้ำตาลสูงชั่วคราวไม่เกิน ~180 ครั้งเดียวในวันแรก",
    "หยุด dextrose ทั้งหมด — NPO patient ต้องได้ glucose ~100 g/วันเพื่อ protein sparing และกัน ketosis; หยุดแล้วยังเสี่ยง hypoglycemia ถ้าให้ insulin ร่วม และไม่แก้ insulin resistance; จะถูก (บางส่วน) ถ้าได้ dextrose เกินจริง เช่น ได้ D10 หรือ TPN overfeeding ต้องลดปริมาณลง",
    "Oral sulfonylurea ใช้ไม่ได้ใน NPO patient ไม่เหมาะใน inpatient เพราะออกฤทธิ์นาน เสี่ยง hypoglycemia เมื่อการกินไม่แน่นอน และปรับขนาดไม่ได้; จะถูก (ยาเม็ด) เฉพาะผู้ป่วย type 2 DM ที่กลับบ้านและกินได้ปกติ",
    "IV sodium bicarbonate ไม่มีข้อบ่งชี้ — ไม่มี acidosis ในโจทย์ และแม้แต่ DKA ก็ให้เฉพาะ pH &lt;6.9; จะถูกถ้าโจทย์เป็น severe metabolic acidosis จากการเสีย HCO3 หรือ hyperkalemia ร่วม acidosis"],
  trap:"คิดว่า hyperglycemia หลังผ่าตัดเป็นเรื่องปกติไม่ต้องรักษา หรือคิดว่าให้ insulin แล้วต้องหยุด dextrose — ใน NPO patient ต้องให้ทั้ง glucose พื้นฐานและ insulin; อีกกับดักคือคุมแน่นเกิน 80–110 ซึ่งเพิ่ม hypoglycemia และ mortality",
  summary:[
    "Stress hyperglycemia: catecholamine, cortisol, glucagon, GH, IL-6 และ TNF → insulin resistance + gluconeogenesis + glycogenolysis",
    "ผลเสีย: SSI, pneumonia, sepsis, anastomotic leak, ระยะนอน รพ. และ mortality เพิ่ม",
    "ADA 2025 (inpatient): เริ่ม insulin เมื่อ glucose ≥180 mg/dL ต่อเนื่อง เป้า 140–180 mg/dL สำหรับผู้ป่วยส่วนใหญ่; ICU ใช้ IV insulin infusion",
    "Non-ICU NPO: basal insulin + correction insulin เป็นแนวทางที่แนะนำ ส่วน sliding scale อย่างเดียวระยะยาวไม่แนะนำ; ยังให้ dextrose ~100 g/วัน",
    "NICE-SUGAR 2009: tight control 81–108 mg/dL เพิ่ม mortality และ severe hypoglycemia เทียบกับ ≤180 — เป้า 110–160 บนกระดานในเฉลยเป็นแนวทางเดิม",
    "การจัดการ hypermetabolic state หลังบาดเจ็บ: volume พอ, ให้ความอบอุ่น, caloric และ protein พอ, ระงับปวด, mobilization, enteral nutrition เร็ว, แก้ hypoxia, electrolyte, acid-base",
    "ตรวจ HbA1c ในผู้ป่วยที่ไม่เคยรู้ว่าเป็นเบาหวาน เพื่อแยก undiagnosed diabetes ออกจาก stress hyperglycemia",
    "ดูข้อ 3, 6, 8 (metabolic response และ nutrition)"],
  notes:"เฉลยในไฟล์ (มีรูป) = กระดานดำลายมือ <b>\"Management after trauma\"</b>:<br>• <b>Hypermetabolic state:</b> - พยายามให้มี Volume ในพอเพียงต่อ metabolism ของร่างกาย - พยายามให้ร่างกายอยู่ในสภาพแวดล้อมที่อุ่นๆ - ↑Caloric intake ให้เป็นพลังงานให้เพียงพอ - ให้ Sedation/Analgesia ที่เหมาะสม ลด Pain<br>• <b>Muscle wasting:</b> - ↑Protein &amp; Amino acid ทดแทน Protein breakdown ที่มี - แก้ Electrolyte ให้ไว - Ambulation, Mobilisation, Active-Passive exercise<br>• <b>Glucose intolerance:</b> - อาจให้ Human insulin IV keep DTX 110-160 mg/dL<br>• <b>Inflammatory response:</b> - ↓Degree of trauma, ↓infection, Enteral nutrition - Controlling pain - แก้ hypovolemia, Acid-base, Electrolyte - แก้ Hypoxia<br>ต้นฉบับมีช้อยแค่ 2 ตัว (A. sliding insulin + dextrose B. ปล่อยไว้ เพราะเป็น normal stress response หลังผ่า) — C, D, E แต่งเพิ่ม; stem เติมว่าไม่เคยเป็นเบาหวาน หลังผ่าตัดช่องท้องใหญ่ ได้ dextrose-containing fluid และวัดซ้ำหลายครั้ง",
  mnemonic:"เป้าน้ำตาลใน รพ. <b>\"140–180\"</b> — เริ่ม insulin เมื่อเกิน 180",
  guide:"ADA Standards of Care 2025; NICE-SUGAR 2009",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง — หมายเหตุว่าแนวทางปัจจุบันแนะนำ basal + correction insulin มากกว่า sliding scale อย่างเดียว แต่ในช้อยที่มี การให้ insulin ร่วมกับคง dextrose ถูกต้องที่สุด",
  variants:[
    "ผู้ป่วย ICU หลังผ่าตัด aortic aneurysm น้ำตาล 250 mg/dL ซ้ำ → IV insulin infusion เป้า 140–180 mg/dL",
    "ผู้ป่วยได้ TPN แล้วน้ำตาลขึ้น 300 mg/dL → ลด dextrose load ใน TPN เพิ่ม insulin และตรวจหาการติดเชื้อ",
    "ผู้ป่วยหลังผ่าตัดได้ insulin infusion เป้า 80–110 mg/dL แล้วซึมเหงื่อแตก น้ำตาล 45 → tight control เสี่ยง hypoglycemia"]}),

A({page:2, page2:6, orig:"8", kimg:KI(8),
  stem:"A patient with short bowel syndrome has received home total parenteral nutrition for 2 years. Which pair of long-term metabolic complications is most characteristic of this therapy?",
  gray:"complication of TPN — A. cholestasis, osteoporosis B. Hypervitamin, refeeding syndrome C. Nausea, Catheter clogged",
  opts:["Cholestasis and metabolic bone disease","Hypervitaminosis and refeeding syndrome","Nausea and catheter occlusion","Aspiration pneumonia and diarrhea","Dumping and bezoar formation"],
  ans:0, key:"A cholestasis, osteoporosis, B Hypervitamin, refeeding syndrome"+KS,
  flag:"⚠ คีย์ตอบ A,B — เปลี่ยน stem เป็น home TPN ระยะยาวให้เหลือคำตอบเดียว (A)",
  interp:"ผู้ป่วย short bowel ได้ home TPN นาน 2 ปี → ถาม <b>metabolic complication ระยะยาว</b> ที่จำเพาะต่อ TPN — ต้องแยกจาก complication ช่วงเริ่มให้ (refeeding), mechanical (catheter) และของ enteral feeding",
  why:"TPN ระยะยาวทำให้เกิด <b>parenteral nutrition-associated liver disease (PNALD หรือ IFALD)</b>: steatosis, <b>cholestasis</b> จนถึง fibrosis และ cirrhosis — จากไม่มีอาหารกระตุ้น CCK และการบีบตัวของถุงน้ำดี, overfeeding (dextrose, lipid ที่มี phytosterol), bacterial overgrowth และ sepsis; และ <b>metabolic bone disease</b> (osteopenia, osteoporosis, osteomalacia) จาก Ca, PO4, vitamin D ไม่พอ, aluminum contamination, การขับ Ca ทางปัสสาวะจาก amino acid load และโรคพื้นฐาน",
  wrong:[
    "Refeeding syndrome เป็นภาวะช่วง<b>เริ่ม</b>ให้อาหาร (วันแรก ๆ) ในผู้ป่วยขาดอาหาร ไม่ใช่ long-term — PO4, K, Mg shift เข้าเซลล์ ต้องเสริม thiamine; hypervitaminosis พบน้อย (vit A หรือ D ในบางราย โดยเฉพาะผู้ป่วยไตวาย) ต้นฉบับคีย์ให้ B ถูกด้วยเพราะถามแค่ \"complication of TPN\"; จะถูกถ้าโจทย์ถามผู้ป่วย anorexia nervosa ที่เพิ่งเริ่ม TPN 2 วันแล้วหัวใจเต้นผิดจังหวะ",
    "Catheter occlusion เป็น <b>mechanical (catheter-related) complication</b> ไม่ใช่ metabolic และ nausea ไม่จำเพาะ; complication ของ catheter ที่สำคัญกว่าคือ CLABSI และ central vein thrombosis; จะถูก (บางส่วน) ถ้าโจทย์ถาม catheter-related complication",
    "Aspiration pneumonia และ diarrhea เป็น complication ของ <b>enteral tube feeding</b> (NG feeding, osmotic diarrhea จาก formula) ไม่ใช่ TPN ซึ่งไม่ผ่านทางเดินอาหาร; จะถูกถ้าโจทย์เป็นผู้ป่วย stroke ให้อาหารทาง NG แล้วมีไข้ หอบ",
    "Dumping และ bezoar เป็น complication <b>หลังผ่าตัดกระเพาะ</b> (gastrectomy, vagotomy) ไม่เกี่ยวกับ TPN; จะถูกถ้าโจทย์เป็นผู้ป่วยหลัง gastrectomy ใจสั่นเหงื่อออกหลังกินอาหาร 15–30 นาที"],
  trap:"เลือก refeeding syndrome เพราะเป็น complication ของ TPN ที่ถูกสอนบ่อย — แต่เกิดช่วงเริ่มให้อาหาร ไม่ใช่ระยะยาว; ถ้าโจทย์ถามกว้าง ๆ แค่ \"complication of TPN\" ทั้ง A และ B ถูก (ตามคีย์)",
  summary:[
    "ข้อบ่งชี้ PN: ลำไส้ใช้ไม่ได้ (malabsorption, obstruction, bowel rest, motility disorder, ใส่ NG หรือ NJ ไม่ได้) และคาดว่าจะกินหรือให้ enteral ไม่ได้นาน; ห้ามให้ใน V/S unstable, severe metabolic derangement, ระหว่างผ่าตัด, end-stage cancer ที่ไม่มีประโยชน์",
    "TPN ต้องให้ทาง central vein (subclavian, internal jugular, PICC) เพราะ osmolarity สูง; ทาง peripheral ไม่ควรเกิน ~900 mOsm/L",
    "Catheter-related: pneumothorax ตอนใส่, CLABSI, thrombosis, occlusion",
    "Metabolic ระยะสั้น: hyperglycemia, refeeding syndrome (PO4, K, Mg ต่ำ, ขาด thiamine → Wernicke, cardiac beriberi, arrhythmia), overfeeding (hyperglycemia, CO2 retention, fatty liver), electrolyte imbalance",
    "ระยะยาว: PNALD หรือ IFALD (steatosis, cholestasis, cirrhosis), gallstone หรือ sludge, metabolic bone disease, intestinal mucosal atrophy, trace element และ vitamin deficiency หรือ excess",
    "Monitoring: electrolyte, glucose, LFT, TG, nitrogen balance; ป้องกัน PNALD โดยเลี่ยง overfeeding, cycling TPN, ให้ enteral บ้างถ้าทำได้, ลด soybean lipid ใช้ fish oil หรือ mixed lipid",
    "Refeeding: เริ่มช้า 10–20 kcal/kg/วันในกลุ่มเสี่ยง, ให้ thiamine ก่อนเริ่ม, ตรวจ PO4 K Mg ทุกวันช่วงแรก",
    "ดูข้อ 3, 6, 7 (fluid, metabolism และ nutrition)"],
  notes:"เฉลยในไฟล์: คอลัมน์คำตอบเขียน <b>\"A,B\"</b> + รูปกระดานดำลายมือ:<br>\"ถ้าให้ Enteral ไม่ได้ ก็ต้องให้ Parenteral เราให้ในพวกที่ bowel function ไม่ดี เช่น Malabsorption, Obstruction, Bowel rest, Motility disorder, ใส่ NG, NJ ไม่ได้ แต่ห้ามให้ในคนมี severe metabolic disorder เพราะจะมี response ต่ออาหาร ห้ามให้ในคน V/S unstable, ห้ามให้ในขณะผ่าตัด, ห้ามให้ใน End stage cancer<br>เราสามารถให้ Parenteral nutrition มีสองทาง คือ TPN ต้องให้ทาง Large vein เท่านั้น ต้องให้ทาง central line เพราะ TPN มี Dext สูงมาก ถ้าให้ small vein จะเกิด phlebitis ง่าย Osmolarity ไม่ควรเกิน 900 mOsm<br>เส้นที่เอามาแทง TPN คือ Subclavian v., Internal jugular v. แต่มี complication คือ Sepsis, Thrombophlebitis จาก Osmolarity เยอะ, และจากน้ำตาลเยอะก็สามารถมี hyperglycemia ได้ ต้อง DTX บ่อยๆ, และมันมี Calories สูงกว่าที่ควรได้รับ ก็สามารถมี fatty liver ได้ และเพราะไม่มีอาหารผ่าน GI นานๆ ก็สามารถมี intestinal atrophy ได้<br>ดังนั้น ต้อง monitor สิ่งต่างๆ คือ E'lyte, LFT, TG, Nitrogen balance<br>นอกจากนี้ยังมี Complication ที่สำคัญคือ Overfeeding, Refeeding syndrome<br><b>Refeeding syndrome</b> เกิดจาก การได้กินอาหารหลัง starvation มานาน จนร่างกายรับอาหารไม่ไหว ทำให้เกิด Anabolism อย่างรุนแรง, K⁺ shift เข้าเซลล์มากมาย → เกิด hypokalemia, นอกจากนี้ยังมี PO4, Mg, B1 ลดด้วย จึงต้องเสริม Thiamine ด้วย ไม่งั้นเป็น Wernicke-Korsakoff syndrome, Cardiac beriberi, Arrhythmia (จาก hypokalemia)<br><b>Overfeeding</b> ทำให้เกิด hyperglycemia, CO2 retention, Diet-induced thermogenesis\"<br><b>ปรับ</b>: ต้นฉบับ stem มีแค่ \"complication of TPN\" และมีช้อย 3 ตัว (A. cholestasis, osteoporosis B. Hypervitamin, refeeding syndrome C. Nausea, Catheter clogged) — เราเปลี่ยน stem เป็นผู้ป่วย short bowel ได้ home TPN 2 ปี ถามระยะยาว ให้เหลือคำตอบเดียว; ช้อย A \"osteoporosis\" ใช้คำว่า metabolic bone disease; D และ E แต่งเพิ่ม",
  mnemonic:"TPN ระยะยาว = <b>\"ตับกับกระดูก\"</b>; refeeding = <b>\"PO4 ตกช่วงเริ่ม\"</b>",
  guide:"ESPEN chronic intestinal failure guideline 2016",
  opinion:"คีย์ตอบ <b>A,B</b> เพราะต้นฉบับถามแค่ \"complication of TPN\" ซึ่งทั้ง cholestasis, metabolic bone disease และ refeeding syndrome เป็น complication ของ TPN จริง (hypervitaminosis พบน้อย). เพื่อให้เหลือคำตอบเดียว เราเปลี่ยน stem เป็น home TPN ระยะยาว 2 ปี ถาม long-term metabolic complication → A ชัดเจน; ถ้าโจทย์ถามผู้ป่วยขาดอาหารรุนแรงที่<b>เพิ่งเริ่ม</b> TPN ไม่กี่วัน B (refeeding) จะเป็นคำตอบ. มั่นใจสูงหลังเปลี่ยน stem — สอดคล้องกับข้อสอบชุด 76D ที่ถาม TPN ระยะยาวต้องให้ vitamin K และ trace elements",
  variants:[
    "หญิง anorexia nervosa BMI 13 เริ่ม TPN ได้ 2 วัน หอบ ใจสั่น PO4 0.8 mg/dL → refeeding syndrome ควรเริ่มอาหารช้าและให้ thiamine ก่อน",
    "ผู้ป่วยได้ TPN 6 เดือน ALP และ bilirubin สูงขึ้นเรื่อย ๆ → PNALD ลด lipid ที่เป็น soybean, cycling, เลี่ยง overfeeding, เริ่ม enteral บ้าง",
    "ผู้ป่วย home TPN มีไข้หนาวสั่นขณะให้ TPN → CLABSI เจาะ hemoculture จาก catheter และ peripheral"]}),

A({page:2, page2:7, orig:"9", kimg:KI(9),
  stem:"A patient undergoes elective colectomy within an enhanced recovery pathway. Which measure applied in the postoperative period reduces postoperative complications and speeds recovery?",
  gray:"ข้อใดลด post op complication และ ทำให้ผู้ป่วยฟื้นตัสเร็วขึ้น — A. ให้ยาแก้ปวด post op เป็นยาแก้ปสด nsaids, acetaminophen B. เปลี่ยนจาก ga เป็น spinal block C. พูดคุยกับผู้ป่วยเตรียมการดูแลหลังผ่าตัด",
  opts:["Postoperative NSAIDs and acetaminophen for analgesia","Changing general anesthesia to spinal block","Discussing postoperative care with the patient","Routine nasogastric decompression until flatus","Strict bed rest for 48 hours"],
  ans:0, key:"A ให้ยาแก้ปวด post op เป็น nsaids, acetaminophen"+KS,
  flag:"⚠ เล็กน้อย: pre-admission counselling (C) ก็เป็นองค์ประกอบ ERAS — เติมใน stem ให้ถามมาตรการช่วงหลังผ่าตัด",
  interp:"โจทย์ถามมาตรการใน <b>ERAS ช่วงหลังผ่าตัด</b> ที่ลด complication และเร่งการฟื้นตัว — ต้องรู้ว่าองค์ประกอบใดอยู่ช่วงไหน (pre, intra, post) และองค์ประกอบใดขัดกับ ERAS",
  why:"<b>Multimodal opioid-sparing analgesia</b> (acetaminophen + NSAIDs ตามเวลา, ใช้ opioid เมื่อจำเป็น) เป็นองค์ประกอบหลักของ ERAS ช่วงหลังผ่าตัด (\"Non-opioid oral analgesia\" ในแผนภาพของเฉลย) — ลดการใช้ opioid จึงลด <b>postoperative ileus, PONV, sedation และ respiratory depression</b> ทำให้กินอาหารและลุกเดินได้เร็ว ลด pulmonary complication และระยะนอนโรงพยาบาล",
  wrong:[
    "เปลี่ยน GA เป็น spinal block เป็นการเลือกวิธีระงับความรู้สึก<b>ช่วง intraoperative</b> และ colectomy ส่วนใหญ่ต้องทำภายใต้ GA; ERAS ใช้ standardized anesthetic protocol (อาจร่วม thoracic epidural ใน open surgery หรือ spinal analgesia ใน laparoscopic) ไม่ใช่แทน GA ด้วย spinal และหลักฐานว่าลด complication ในการผ่าตัดช่องท้องทั่วไปยังไม่ชัด; จะถูกถ้าโจทย์ถามการผ่าตัดสะโพกหรือขาในผู้สูงอายุที่ regional anesthesia ลด delirium ได้",
    "พูดคุยเตรียมการดูแลหลังผ่าตัด (pre-admission counselling) <b>เป็นองค์ประกอบ ERAS จริง</b> แต่อยู่ช่วง <b>preoperative</b> — ต้นฉบับไม่ได้ระบุช่วงเวลา C จึงอาจถูกด้วย เราจึงเติม \"in the postoperative period\" ใน stem; จะถูกถ้าโจทย์ถามมาตรการก่อนผ่าตัดที่ลดความวิตกกังวลและช่วยให้ผู้ป่วยร่วมมือกับ early feeding และ mobilization",
    "Routine NG decompression จนผายลม<b>ขัดกับ ERAS</b> (avoid routine NG tubes) — เพิ่ม pulmonary complication, ไข้, atelectasis และไม่ช่วยให้ลำไส้ทำงานเร็วขึ้น; จะถูกเมื่อมี ileus ที่อาเจียนมากหรือท้องอืดจริง หรือ bowel obstruction",
    "Strict bed rest 48 ชม. ขัดกับ <b>early mobilization</b> — เพิ่ม VTE, pneumonia, กล้ามเนื้อลีบ, insulin resistance; ERAS ให้ลุกนั่งวันผ่าตัดและเดินใน POD 1; จะไม่ถูกในการผ่าตัดช่องท้องทั่วไป (ใช้เฉพาะสถานการณ์พิเศษบางอย่าง เช่น หลังผ่าตัดบางชนิดที่ศัลยแพทย์สั่งจำกัดการเคลื่อนไหว)"],
  trap:"เลือกการพูดคุยเตรียมผู้ป่วยเพราะเป็น ERAS เหมือนกัน — ต้องอ่านว่าถามช่วงไหน; อีกกับดักคือคิดว่า NG decompression และ bed rest ช่วยการฟื้นตัว ซึ่ง ERAS เลิกทำแบบ routine แล้ว",
  summary:[
    "ERAS ช่วง preoperative: pre-admission counselling, optimize โรคประจำตัว, หลีกเลี่ยง mechanical bowel prep (colon: oral antibiotic ± MBP ตามบริบท), ไม่อดอาหารนาน (solid 6 ชม., clear fluid 2 ชม., carbohydrate loading), non-opioid analgesia ก่อนผ่าตัด",
    "ช่วง intraoperative: standardized anesthesia, goal-directed fluid หลีกเลี่ยง fluid overload, VTE prophylaxis, antibiotic prophylaxis ภายใน 60 นาที, minimally invasive surgery, หลีกเลี่ยง drain และ NG แบบ routine, ป้องกัน hypothermia, multimodal PONV prophylaxis",
    "ช่วง postoperative: early oral nutrition (ภายใน 24 ชม.), early mobilization, ถอดสายสวนปัสสาวะเร็ว, กระตุ้น gut motility, non-opioid oral analgesia, คุมน้ำตาล, audit compliance",
    "Multimodal analgesia: acetaminophen + NSAIDs ตามเวลา, regional technique (TAP block, wound infiltration), opioid เมื่อจำเป็น → ลด ileus, PONV, respiratory depression",
    "NSAIDs ระวังใน AKI, bleeding risk, peptic ulcer; ข้อกังวลเรื่อง anastomotic leak ยังไม่ชัด",
    "ผลของ ERAS: ลด complication ราว 30–50% และลดระยะนอนโรงพยาบาล โดยไม่เพิ่ม readmission",
    "ดูข้อ 10, 11, 12, 17 (perioperative care)"],
  notes:"เฉลยในไฟล์ (มีรูป) = แผนภาพ ERAS<br>• <b>Pre-operative:</b> Pre-admission counselling, Optimisation of medical conditions, Avoid bowel preparation, Avoid prolonged fasting, Administration of non-opioid analgesia<br>• <b>Intra-operative:</b> Standardised anaesthetic protocol, Perioperative fluid management, Thromboembolism prophylaxis, Antibiotic prophylaxis, Minimally invasive surgery, Avoid intraperitoneal drains, Avoid routine use of NG tubes, Prevent hypothermia, Multi-modal approach to PONV<br>• <b>Post-operative:</b> Early oral nutrition, Early mobilization, Early urinary catheter removal, Stimulate gut motility, Non-opioid oral analgesia, Optimise glycaemic control with insulin, Audit compliance and outcomes<br>+ ข้อความ <b>\"ลด post op complication → non-opioid oral analgesia e.g. paracetamol, NSAID\"</b><br>ต้นฉบับพิมพ์ผิด \"ยาแก้ปสด\" = ยาแก้ปวด และ \"ฟื้นตัส\" = ฟื้นตัว; ต้นฉบับมีช้อย 3 ตัว — D และ E แต่งเพิ่ม (ขัดกับ ERAS); stem เติมว่าเป็น elective colectomy ใน ERAS pathway และถามมาตรการช่วงหลังผ่าตัด",
  mnemonic:"",
  guide:"ERAS Society colorectal guideline 2018",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูงหลังเติมช่วงเวลา — ในต้นฉบับ C (pre-admission counselling) ก็เป็นองค์ประกอบ ERAS ที่อยู่ในแผนภาพของเฉลยเอง จึงอาจโต้แย้งได้; เราเติม \"in the postoperative period\" ให้เหลือคำตอบเดียว ถ้าโจทย์ถามมาตรการก่อนผ่าตัด C จะเป็นคำตอบ. สอดคล้องกับข้อสอบชุด 76A และ 76C เรื่อง ERAS",
  variants:[
    "ผู้ป่วยจะผ่าตัด laparoscopic right hemicolectomy แบบ elective ควรงดอาหารก่อนผ่าตัดอย่างไร → solid 6 ชม., clear fluid ได้ถึง 2 ชม. และ carbohydrate loading",
    "หลัง colectomy วันที่ 1 ผู้ป่วยรู้สึกตัวดี ไม่คลื่นไส้ → เริ่มอาหารทางปากและลุกเดิน ถอดสายสวนปัสสาวะ",
    "ผู้ป่วยหลังผ่าตัดได้ morphine PCA ขนาดสูง ท้องอืด ไม่ผายลม 4 วัน → opioid-induced ileus ควรใช้ multimodal analgesia"]}),

A({page:2, page2:7, orig:"10", kimg:KI(10),
  stem:"A smoker is scheduled for elective inguinal hernia repair. For how long before surgery should he stop smoking to achieve the greatest reduction in postoperative pulmonary complications?",
  gray:"ต้องงดบุหรี่นานแค่ไหน ก่อนผ่า hernia ถึงจะลดความเสี่ยงหลังผ่าตัดได้ — A. 1 wk B. 3 wk C. 5 wk D. 8 wk E. ไม่ต้องหยุด",
  opts:["1 week","3 weeks","5 weeks","8 weeks","No need to stop"],
  ans:3, key:"D 8 wk"+KS,
  flag:"⚠ เล็กน้อย: 5 สัปดาห์ (C) ก็เกินเกณฑ์ขั้นต่ำ ~4 สัปดาห์ที่เริ่มเห็นประโยชน์ — ปรับ stem ให้ถามระยะที่ลด pulmonary complication ได้มากที่สุด",
  interp:"ถามระยะเวลางดบุหรี่ก่อนผ่าตัดที่<b>ลด postoperative pulmonary complication ได้มากที่สุด</b> — ช้อยเป็นตัวเลขหลายระดับ ต้องรู้ทั้งเกณฑ์ขั้นต่ำและระยะที่ได้ประโยชน์สูงสุด",
  why:"การสูบบุหรี่เพิ่ม carboxyhemoglobin, ลด mucociliary clearance, เพิ่มเสมหะและ airway reactivity, ลด tissue oxygenation และการหายของแผล; CO และ nicotine หมดใน 1–2 วัน แต่ <b>ciliary function และการผลิตเสมหะต้องใช้หลายสัปดาห์</b>จึงกลับมา — การหยุด ≥4 สัปดาห์เริ่มลด wound และ respiratory complication, <b>หยุด ≥8 สัปดาห์ลด pulmonary complication ได้มากที่สุด</b> (สไลด์ในเฉลย \"Smoking cessation for 8 weeks\") และประโยชน์เพิ่มขึ้นตามระยะเวลาที่หยุด",
  wrong:[
    "1 สัปดาห์ช่วยให้ CO และ nicotine ลดลง (oxygen delivery ดีขึ้น) แต่ยังไม่พอให้ ciliary function และเสมหะดีขึ้น — ไม่ลด pulmonary complication อย่างมีนัยสำคัญ แต่ก็<b>ไม่เพิ่ม</b> complication จึงควรแนะนำให้หยุดเสมอแม้เหลือเวลาน้อย; จะถูกถ้าโจทย์ถามระยะที่ carboxyhemoglobin กลับสู่ปกติ (ราว 12–48 ชม.)",
    "3 สัปดาห์ยังต่ำกว่าเกณฑ์ขั้นต่ำราว 4 สัปดาห์ที่เริ่มเห็นการลด wound และ respiratory complication ชัดเจน; จะถูก (ใกล้เคียง) ถ้าโจทย์ถามระยะขั้นต่ำที่แนะนำและไม่มีช้อย 4 สัปดาห์",
    "5 สัปดาห์เกินเกณฑ์ขั้นต่ำ ~4 สัปดาห์ จึงลด complication ได้บ้าง (โดยเฉพาะ wound complication) แต่ยังน้อยกว่า 8 สัปดาห์ซึ่งให้ผลต่อปอดมากที่สุด; จะถูกถ้าโจทย์ถามระยะเวลาน้อยที่สุดที่เริ่มลด wound complication",
    "\"ไม่ต้องหยุด\" ผิด — ผู้สูบบุหรี่มีความเสี่ยง SSI, wound dehiscence, pulmonary complication และ hernia recurrence สูงกว่า และการผ่าตัดเป็น teachable moment ให้เลิกบุหรี่; แนวคิดเก่าที่ว่าหยุดระยะสั้นทำให้เสมหะมากขึ้นและแย่ลงไม่ได้รับการยืนยัน"],
  trap:"เลือก 1 สัปดาห์ หรือคิดว่าหยุดระยะสั้นทำให้แย่ลง (paradoxical) จึงไม่ต้องหยุด — ปัจจุบันแนะนำให้หยุดเสมอ ยิ่งนานยิ่งดี โดย ≥8 สัปดาห์ให้ผลต่อปอดดีที่สุด",
  summary:[
    "ผลของบุหรี่ต่อการผ่าตัด: carboxyhemoglobin ↑, mucociliary clearance ↓, เสมหะ ↑, tissue hypoxia, ภูมิคุ้มกัน ↓ → SSI, wound dehiscence, pulmonary complication, hernia recurrence",
    "หลังหยุด 12–48 ชม.: CO และ nicotine ลดลง; หลายสัปดาห์: ciliary function และเสมหะดีขึ้น",
    "หยุด ≥4 สัปดาห์ เริ่มลด wound และ respiratory complication; ≥8 สัปดาห์ ลด pulmonary complication ได้มากที่สุด; ทุกสัปดาห์ที่หยุดเพิ่มประโยชน์ (WHO 2020)",
    "การหยุดระยะสั้นไม่เพิ่ม complication → แนะนำให้หยุดเสมอ ใช้ nicotine replacement, varenicline หรือ bupropion ร่วมกับ counselling",
    "Prevention of postoperative pulmonary complication: เลิกบุหรี่, รักษา COPD ให้ดีที่สุด, เลื่อน elective surgery เมื่อมี viral URI, สอน lung expansion (incentive spirometry หรือ Triflow, deep breathing, coughing) ก่อนและหลังผ่าตัด, ระงับปวดให้พอ",
    "Elective hernia repair: แนะนำ optimize risk factor ที่แก้ได้ก่อนผ่าตัด ทั้งเลิกบุหรี่ ลดน้ำหนัก คุมเบาหวาน",
    "ดูข้อ 9, 11 (perioperative pulmonary care และ ERAS)"],
  notes:"เฉลยในไฟล์ (มีรูป) = สไลด์ <b>\"PREVENTION OF POSTOPERATIVE PULMONARY COMPLICATION\"</b> (ลายมือ = จัดการ risk ทั้งหมด)<br>• <b>Smoking cessation for 8 weeks</b><br>• COPD should be aggressively treated to best possible baseline level of function<br>• Delay elective surgery in the presence of a viral URI<br>• Patient education - Lung expansion maneuvers such as coughing, incentive spirometry (ลายมือ: <b>Triflow → ฝึกก่อนผ่า + ใช้หลังผ่า</b>), and voluntary deep breaths (ลายมือ: <b>ฝึกให้คนไข้หายใจลึกก่อนผ่าตัด</b>)<br>• Adequate pain control (ลายมือ: <b>∵ pain = หายใจลึกไม่ไหว</b>)<br>+ รูป incentive spirometer 3 ลูก<br>stem ปรับจากต้นฉบับ \"ต้องงดบุหรี่นานแค่ไหน ก่อนผ่า hernia ถึงจะลดความเสี่ยงหลังผ่าตัดได้\" ให้ถามระยะที่ลด pulmonary complication ได้มากที่สุด เพราะ 5 สัปดาห์ก็ลดความเสี่ยงได้บ้าง; ช้อย E ต้นฉบับ \"ไม่ต้องหยุด\"",
  mnemonic:"<b>\"4 สัปดาห์เริ่มได้ผล 8 สัปดาห์ปอดดีที่สุด\"</b>",
  guide:"WHO tobacco and postsurgical outcomes 2020",
  opinion:"เห็นด้วยกับคีย์ D มั่นใจสูงหลังปรับ stem — ต้นฉบับถามแค่ \"ถึงจะลดความเสี่ยงได้\" ซึ่ง 5 สัปดาห์ก็เกินเกณฑ์ขั้นต่ำ ~4 สัปดาห์; เราจึงถามระยะที่ลด pulmonary complication ได้มากที่สุด ถ้าโจทย์ถามระยะขั้นต่ำที่เริ่มเห็นประโยชน์ C จะใกล้เคียงที่สุด. สอดคล้องกับข้อสอบชุด 77A (เลิกบุหรี่ก่อน hernia repair — ชุดนั้นมีช้อยแค่ 2 สัปดาห์ และ flag ว่าดีที่สุด ≥8 สัปดาห์)",
  variants:[
    "ชายสูบบุหรี่ 30 pack-years นัดผ่าตัด elective cholecystectomy ใน 2 สัปดาห์ ถามว่าควรแนะนำอย่างไร → ให้หยุดทันทีเพราะไม่เพิ่ม complication และยิ่งนานยิ่งดี",
    "ผู้ป่วยมีไข้หวัด น้ำมูก ไอ 3 วันก่อน elective hernia repair → เลื่อนผ่าตัดออกไปจนหาย",
    "ผู้ป่วยหลังผ่าตัดช่องท้องส่วนบนปวดแผลมาก หายใจตื้น → ระงับปวดให้พอและใช้ incentive spirometry ป้องกัน atelectasis"]}),

A({page:2, page2:8, orig:"11", kimg:KI(11),
  stem:"On postoperative day 1 after open splenectomy, a patient who has stayed in bed develops a fever of 38.2°C. Urine output is normal and the wound looks clean. Otherwise the examination is unremarkable. What is the most likely cause?",
  gray:"S/p splenectomy, pod1, lay in bed, normal urine output, อย่างอื่นปกติ ผู้ป่วยมี fever น่าจะเกิดจากสาเหตุใด — A. SSI B. Atelectasis C. UTI D. post-splenectomy fever",
  opts:["Surgical site infection","Atelectasis","Urinary tract infection","Post-splenectomy fever","Deep vein thrombosis"],
  ans:1, key:"B Atelectasis"+KS,
  flag:"⚠ เล็กน้อย: คงคีย์ตามแนวคิด 5W (POD 1–2 = Wind) แต่รูปในเฉลยเองระบุว่า atelectasis no longer thought to cause fever",
  interp:"ไข้ <b>POD 1</b> หลังผ่าตัดช่องท้องส่วนบน ผู้ป่วยนอนบนเตียง แผลสะอาด ปัสสาวะปกติ — ใช้ <b>timeline ของไข้หลังผ่าตัด (5W)</b> ในการเลือกสาเหตุที่เข้ากับวันที่เกิดไข้",
  why:"ตาม 5W ไข้ใน <b>POD 1–2 = Wind</b> (pulmonary) — splenectomy เป็นแผล upper abdomen ใกล้กระบังลมซ้าย ปวดแผลจนหายใจตื้น ไม่ลุกเดิน จึงเกิด <b>atelectasis</b> (มักที่ left lower lobe ร่วม left pleural effusion) ได้บ่อย; โจทย์ตัดสาเหตุอื่นออก (แผลสะอาด ปัสสาวะปกติ) และสาเหตุอื่นใน 5W เกิดช้ากว่า → ตามคีย์ตอบ atelectasis",
  wrong:[
    "SSI มักเกิด <b>POD 4–7</b> (Wound) และแผลในโจทย์สะอาด; ยกเว้น necrotizing infection จาก Streptococcus group A หรือ Clostridium ที่เกิดได้ใน 24–48 ชม. แต่แผลจะปวดมาก บวมแดง มีน้ำเหลืองขุ่น; จะถูกถ้าโจทย์เป็นไข้ POD 5 แผลบวมแดงมีหนอง",
    "UTI มักเกิด <b>POD 3–5</b> (Water) โดยเฉพาะผู้ที่คาสายสวนปัสสาวะนาน และโจทย์บอกปัสสาวะปกติ; จะถูกถ้าโจทย์เป็นไข้ POD 4 ในผู้ป่วยคาสายสวน ปัสสาวะขุ่น",
    "Post-splenectomy fever เป็น <b>diagnosis of exclusion</b> มักเกิดช้ากว่า (ราว POD 5–10) ต้องตัด subphrenic abscess, pancreatic tail injury (pancreatic fistula), pneumonia ออกก่อน; จะถูกถ้าไข้ต่ำ ๆ ต่อเนื่องหลังตัดสาเหตุอื่นด้วย CT แล้วไม่พบ",
    "DVT มักเกิด<b>หลัง POD 5</b> (Walking) จาก immobility และมักมีขาบวมหรือปวดน่อง; ไข้มักต่ำ; จะถูกถ้าไข้ POD 7 ร่วมกับน่องบวมข้างเดียว"],
  trap:"เลือก post-splenectomy fever เพราะชื่อตรงกับการผ่าตัด — แต่เป็นการวินิจฉัยหลังตัดสาเหตุอื่นออกและเกิดช้ากว่า; และอีกกับดักคือเชื่อว่า atelectasis เป็นสาเหตุของไข้เสมอ ปัจจุบันไข้ POD 1 ส่วนใหญ่คือ inflammatory response ต่อการผ่าตัด",
  summary:[
    "5W ของไข้หลังผ่าตัด: Wind (pulmonary, POD 1–2), Water (UTI, POD 3–5), Wound (SSI, POD 4–7), Walking (VTE, หลัง POD 5), Wonder drugs (drug fever, transfusion reaction, malignant hyperthermia — เมื่อไรก็ได้หลังสัมผัส), Waterway (catheter-related bloodstream infection — เมื่อไรก็ได้)",
    "ไข้ภายใน 48 ชม. ส่วนใหญ่เป็น inflammatory response ต่อการผ่าตัด (IL-6) หายเอง; หลักฐานปัจจุบันไม่ยืนยันว่า atelectasis เป็นสาเหตุของไข้",
    "ไข้ใน 24–48 ชม. ที่ต้องรีบหา: necrotizing SSI (Streptococcus group A, Clostridium), anastomotic leak ระยะแรก, aspiration pneumonia, malignant hyperthermia, transfusion reaction",
    "หลัง splenectomy: left lower lobe atelectasis และ left pleural effusion พบบ่อย; subphrenic abscess และ pancreatic tail injury เป็นสาเหตุไข้ที่ต้องตัดออก",
    "Post-splenectomy fever: diagnosis of exclusion มักเกิด POD 5–10; ระยะยาว OPSI ป้องกันด้วยวัคซีน pneumococcus, meningococcus, Hib",
    "การป้องกัน atelectasis: ระงับปวดให้พอ, incentive spirometry, deep breathing, early mobilization",
    "ดูข้อ 9, 10 (perioperative pulmonary care)"],
  notes:"เฉลยในไฟล์ (มีรูป) = รูป <b>\"COMMON CAUSES of POSTOPERATIVE FEVER ~ follows time frame after surgery\"</b>:<br>• WIND ~ pulmonary conditions (e.g. pneumonia) ~ <b>atelectasis no longer thought to cause fever</b> ~ postoperative days 1-2<br>• WATER ~ urinary tract infections ~ postoperative days 3-5<br>• WOUND ~ surgical site infections ~ postoperative days 4-7<br>• WALKING ~ venous thromboembolisms (e.g. deep vein thrombosis or pulmonary embolism) ~ immobility ~ after postoperative day 5<br>• WONDER DRUGS ~ febrile reactions to blood products/medications (e.g. malignant hyperthermia, drug fever) ~ anytime upon exposure to triggering agent<br>• WATERWAY ~ bloodstream infection due to intravascular catheter ~ anytime<br>+ ข้อความ <b>\"day 1-2 = wind\"</b><br>ต้นฉบับมีช้อย 4 ตัว — E (Deep vein thrombosis) แต่งเพิ่ม; stem แปลจากต้นฉบับ เติมไข้ 38.2°C, open splenectomy และแผลสะอาด (ต้นฉบับ \"อย่างอื่นปกติ\") โดยไม่เติมผลตรวจปอด",
  mnemonic:"<b>5W: Wind 1–2, Water 3–5, Wound 4–7, Walking 5+, Wonder drugs เมื่อไรก็ได้</b>",
  guide:"Sabiston 21st ed.",
  opinion:"คงคีย์ B ตามแนวคิด 5W ซึ่งเป็นสิ่งที่ข้อสอบต้องการ (โจทย์ตัด SSI, UTI ด้วยแผลสะอาดและปัสสาวะปกติ และผู้ป่วยนอนบนเตียงหลังแผล upper abdomen) — ความมั่นใจว่าเป็น<b>คำตอบที่ข้อสอบต้องการ</b>สูง แต่ต้องรู้ว่ารูปในเฉลยเองและหลักฐานปัจจุบันระบุว่า atelectasis no longer thought to cause fever: ไข้ POD 1 ส่วนใหญ่คือ inflammatory response ต่อการผ่าตัด (IL-6) ที่หายเอง. Post-splenectomy fever เป็น diagnosis of exclusion มักเกิดช้ากว่า (~POD 5–10) หลังตัด subphrenic abscess และ pancreatic tail injury ออกแล้ว; SSI POD 4–7, UTI POD 3–5, DVT หลัง POD 5. สอดคล้องกับข้อสอบชุด 77B (ไข้ POD 1 → decreased breath sounds ที่ฐานปอด)",
  variants:[
    "ผู้ป่วยหลัง laparoscopic splenectomy POD 7 มีไข้ ปวดใต้ชายโครงซ้าย WBC สูง → CT หา subphrenic abscess",
    "ผู้ป่วยหลัง open colectomy POD 5 คาสายสวนปัสสาวะ ไข้ 38.5°C ปัสสาวะขุ่น → catheter-associated UTI",
    "ผู้ป่วยหลังผ่าตัด 12 ชม. แผลปวดมาก ผิวรอบแผลคล้ำ มีน้ำใสสีน้ำล้างเนื้อ ไข้สูง → necrotizing SSI ต้องเปิดแผล debride ทันที"]}),

A({page:3, page2:8, orig:"12",
  stem:"Before scrubbing in for an operation, which agent should be used for surgical hand antisepsis?",
  gray:"scrub in เข้า field ผ่าตัด ต้องใช้อะไรในการล้างมือ — A. soap B. Chlorhexidine C. Tincture iodine D. ใช้พยาบาล",
  opts:["Plain soap","Chlorhexidine","Tincture of iodine","Hydrogen peroxide","Sterile water alone"],
  ans:1, key:"B Chlorhexidine"+KS,
  interp:"ถามสารที่ใช้ทำ <b>surgical hand antisepsis</b> ก่อน scrub เข้าผ่าตัด — ต้องแยกสารที่ใช้ล้างมือศัลยแพทย์ออกจากสารเตรียมผิวผู้ป่วยและสารทำความสะอาดแผล",
  why:"Surgical hand antisepsis ใช้ <b>antimicrobial soap</b> คือ <b>chlorhexidine gluconate (2–4%)</b> หรือ povidone-iodine 7.5% scrub 2–5 นาที หรือใช้ alcohol-based surgical hand rub — chlorhexidine ออกฤทธิ์กว้างต่อ Gram-positive, Gram-negative และ enveloped virus และมี <b>residual (persistent) activity</b> ยึดติดผิวหนังได้หลายชั่วโมงใต้ถุงมือ ไม่ถูก inactivate ด้วยเลือดหรือ organic matter มากเท่า iodine",
  wrong:[
    "Plain soap ลบสิ่งสกปรกและเชื้อชั่วคราวได้ด้วยกลไก mechanical แต่<b>ไม่มีฤทธิ์ฆ่าเชื้อและไม่มี residual activity</b> จึงไม่พอสำหรับการผ่าตัด; ใช้ล้างมือทั่วไปเมื่อมือเปื้อนชัดเจน หรือล้างก่อนใช้ alcohol hand rub ครั้งแรกของวัน",
    "Tincture of iodine คือ iodine ในแอลกอฮอล์ <b>ระคายผิวมาก</b> ใช้ทาเตรียมผิวผู้ป่วยหรือทาแผลเล็ก ไม่ใช้ล้างมือศัลยแพทย์ — สารกลุ่ม iodine ที่ใช้ scrub คือ povidone-iodine 7.5% (iodophor) ซึ่งระคายน้อยกว่า; จะถูกถ้าโจทย์ถามสารทาเตรียมผิวผู้ป่วยในบางสถาบัน",
    "Hydrogen peroxide ใช้ทำความสะอาดแผลและฆ่าเชื้อพื้นผิวหรืออุปกรณ์ ไม่ใช้ล้างมือ และทำลายเนื้อเยื่อ ไม่มี residual activity; จะถูกถ้าโจทย์ถามสารที่เกิดฟองช่วยชะล้างเศษเนื้อตายในแผลบางชนิด",
    "Sterile water อย่างเดียวไม่มีฤทธิ์ฆ่าเชื้อ — ไม่ได้ลดจำนวน resident flora; ใช้ล้างแผลหรือล้างมือก่อนใช้ alcohol hand rub ได้ แต่ไม่ใช่ antiseptic"],
  trap:"เลือก tincture iodine เพราะรู้ว่ากลุ่ม iodine ใช้ scrub ได้ — สารที่ใช้ scrub คือ povidone-iodine (iodophor) ไม่ใช่ tincture iodine ที่ระคายผิว",
  summary:[
    "Surgical hand antisepsis: antimicrobial soap (chlorhexidine gluconate 2–4% หรือ povidone-iodine 7.5%) scrub 2–5 นาที หรือ alcohol-based surgical hand rub ตามเวลาที่ผู้ผลิตกำหนด — WHO ให้เทียบเท่ากัน",
    "Chlorhexidine: ออกฤทธิ์เร็วปานกลาง มี residual activity นาน, ระคายน้อย, ไม่ถูก inactivate ด้วยเลือดมากนัก; ห้ามโดนตาและหูชั้นกลาง",
    "Povidone-iodine: ฤทธิ์กว้าง แต่ residual activity สั้นกว่าและถูก inactivate ด้วยเลือดและ organic matter",
    "Alcohol (60–80%): ออกฤทธิ์เร็วที่สุด แต่ไม่มี residual effect ถ้าใช้เดี่ยว จึงมักผสม chlorhexidine; ใช้กับมือที่ไม่เปื้อนเห็นชัด",
    "Skin preparation ของผู้ป่วย: alcohol-based chlorhexidine ดีกว่า povidone-iodine ในการลด SSI (WHO SSI 2018)",
    "ขั้นตอน: ถอดเครื่องประดับ ไม่ทาเล็บหรือใส่เล็บปลอม, ล้างมือด้วยสบู่ถ้ามือเปื้อน, scrub จากปลายนิ้วถึงข้อศอก มือสูงกว่าศอก",
    "ดูข้อ 13, 17 (surgical infection และ infection control)"],
  notes:"ไฟล์เฉลยข้อ 12: คำตอบ <b>B</b> + ข้อความ <b>\"Scrub ใช้ chlorhexidine in alc. หรือ povidone iodine (ไม่ใช่ tincture iodine)\"</b> (ไม่มีรูป)<br>ช้อย D ต้นฉบับเขียนว่า <b>\"ใช้พยาบาล\"</b> (มุกของผู้จด) — เราแทนด้วย Hydrogen peroxide; ต้นฉบับมีช้อย 4 ตัว — E (Sterile water alone) แต่งเพิ่ม",
  mnemonic:"",
  guide:"WHO Guidelines on Hand Hygiene in Health Care 2009; WHO SSI 2018",
  opinion:"เห็นด้วยกับคีย์ B มั่นใจสูง — สอดคล้องกับข้อสอบชุด 77A เรื่อง scrub in กับผู้ป่วย HBsAg บวก",
  variants:[
    "ก่อนผ่าตัด ควรใช้สารใดเตรียมผิวหนังผู้ป่วยเพื่อลด SSI ได้ดีที่สุด → alcohol-based chlorhexidine",
    "แพทย์ scrub ด้วย povidone-iodine แล้วผื่นแพ้ที่มือ → เปลี่ยนเป็น chlorhexidine หรือ alcohol-based surgical hand rub",
    "ระหว่างผ่าตัดเปลี่ยนถุงมือที่ขาด มือไม่เปื้อนเลือด → ใช้ alcohol-based surgical hand rub ก่อนสวมถุงมือใหม่"]}),

A({page:3, page2:8, orig:"13", img:QI(13),
  imgNote:"ภาพผิวหนังมีตุ่มนูนแดงอักเสบ ตรงกลางมีหัวสีเหลืองขาว ผิวรอบๆ แดง มีนิ้วบีบสองข้าง",
  stem:"A patient has a painful inflamed skin lesion as shown. Which group of organisms is the most likely cause?",
  gray:"เป็นตุ่มอักเสบที่ skin ถาม causative pathogens (+ รูป) — A. Gram positive cocci B. Gram positive bacilli C. Gram negative bacilli D. Gram negative coccobacilli E. Mixed Anaerobe",
  opts:["Gram-positive cocci","Gram-positive bacilli","Gram-negative bacilli","Gram-negative coccobacilli","Mixed anaerobes"],
  ans:0, key:"A Gram positive cocci"+KS,
  interp:"รูปเป็นตุ่มนูนแดงอักเสบมีหัวหนองตรงกลางที่ผิวหนัง = <b>purulent skin infection</b> (furuncle หรือ skin abscess) — ถามกลุ่มเชื้อก่อโรคที่พบบ่อยที่สุด",
  why:"Skin and soft tissue infection ที่พบบ่อยเกิดจากเชื้อในกลุ่ม <b>Gram-positive cocci</b>: ตุ่มที่มีหนอง (furuncle, carbuncle, abscess) ส่วนใหญ่เกิดจาก <b>Staphylococcus aureus</b> (รวม MRSA) ที่เข้าทาง hair follicle; ส่วน non-purulent cellulitis และ erysipelas มักเกิดจาก <b>β-hemolytic Streptococcus</b> — ทั้งสองเป็น Gram-positive cocci (เฉลย: \"มักเกิดจากเชื้อกลุ่ม strep, staph\")",
  wrong:[
    "Gram-positive bacilli เช่น Clostridium (gas gangrene หลังแผลลึกปนเปื้อน), Bacillus anthracis (cutaneous anthrax แผลดำไม่เจ็บ), Corynebacterium — ไม่ใช่สาเหตุของตุ่มหนองทั่วไป; จะถูกถ้าโจทย์เป็นแผลกล้ามเนื้อมีก๊าซ crepitus กลิ่นเหม็นหลังอุบัติเหตุ",
    "Gram-negative bacilli (E. coli, Klebsiella, Pseudomonas) พบใน SSI ของการผ่าตัดลำไส้ ฝีที่ perineum, diabetic foot ที่เรื้อรัง, แผลไหม้ และ Vibrio vulnificus หลังสัมผัสน้ำทะเล; จะถูกถ้าโจทย์เป็นแผลติดเชื้อหลังผ่าตัดลำไส้ใหญ่ หรือแผลไหม้มีหนองสีเขียว",
    "Gram-negative coccobacilli เช่น Pasteurella multocida (หลังสุนัขหรือแมวกัด), Haemophilus influenzae, Acinetobacter — จะถูกถ้าโจทย์เป็น cellulitis ที่ลุกลามเร็วภายใน 24 ชม. หลังแมวกัด",
    "Mixed anaerobes พบใน necrotizing fasciitis type I (polymicrobial), Fournier gangrene, ฝีที่ perianal หรือ pilonidal, diabetic foot และ human bite; จะถูกถ้าโจทย์เป็นผิวหนังที่ perineum บวมแดงลุกลาม ปวดเกินกว่าที่เห็น มี crepitus"],
  trap:"คิดถึงเชื้อที่ซับซ้อนกว่า เพราะโจทย์ให้ดูรูป — ตุ่มหนองที่ผิวหนังธรรมดาเกือบทั้งหมดเป็น S. aureus ซึ่งเป็น Gram-positive cocci",
  summary:[
    "Purulent SSTI (furuncle, carbuncle, abscess): S. aureus รวม MRSA → incision and drainage เป็นหลัก",
    "IDSA 2014: purulent mild → I&amp;D อย่างเดียว; moderate (มีอาการทาง systemic) → I&amp;D + antibiotic ตามผลเพาะเชื้อหรือ empiric ครอบคลุม MRSA ในบางบริบท; severe → I&amp;D + IV vancomycin หรือเทียบเท่า",
    "Non-purulent cellulitis และ erysipelas: β-hemolytic Streptococcus → penicillin, cephalexin, dicloxacillin หรือ clindamycin",
    "Necrotizing soft tissue infection: type I polymicrobial (anaerobe + Gram-negative), type II Streptococcus group A ± S. aureus → surgical debridement ด่วน + broad-spectrum antibiotic",
    "เชื้อเฉพาะบริบท: แมวหรือสุนัขกัด → Pasteurella; น้ำทะเล → Vibrio; น้ำจืด → Aeromonas; แผลไหม้ → Pseudomonas",
    "ตุ่มหนองที่เป็นซ้ำ: หา MRSA colonization, เบาหวาน, ภูมิคุ้มกันบกพร่อง",
    "ดูข้อ 12, 17 (surgical infection)"],
  notes:"ไฟล์เฉลยข้อ 13: คำตอบ <b>A</b> + ข้อความ <b>\"ตุ่มอักเสบที่ skin : มักเกิดจากเชื้อกลุ่ม strep, staph ซึ่งเป็น Gram positive cocci\"</b> (ไม่มีรูปในฝั่งเฉลย)<br>ไฟล์โจทย์มีรูปผิวหนังตุ่มอักเสบประกอบโจทย์ (ใส่ไว้ในรูปโจทย์ของข้อนี้)",
  mnemonic:"<b>\"หนอง = Staph, ลาม = Strep\"</b> — ทั้งคู่ Gram-positive cocci",
  guide:"IDSA SSTI 2014",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง",
  variants:[
    "ชายเป็นฝีที่ต้นขา คลำได้ fluctuation ขนาด 3 cm ไม่มีไข้ → incision and drainage อย่างเดียว",
    "หญิงขาแดงร้อนลุกลาม ขอบชัดนูน ไม่มีหนอง มีไข้ → erysipelas จาก β-hemolytic Streptococcus ให้ penicillin",
    "ผู้ป่วยเบาหวาน perineum บวมแดงคล้ำ ปวดมาก มี crepitus → Fournier gangrene เชื้อ polymicrobial ต้อง debride ด่วน"]}),

A({page:3, page2:8, orig:"14",
  stem:"A patient is started on a continuous intravenous unfractionated heparin infusion. Which test is used to monitor its therapeutic effect?",
  gray:"ให้ heparin IV อยากติดตามว่ายาได้ผลดีมั้ย ตรวจอะไร — A. aPTT B. PT C. Bleeding time D. Platelet count E. D-dimer",
  opts:["aPTT","PT","Bleeding time","Platelet count","D-dimer"],
  ans:0, key:"A aPTT"+KS,
  interp:"ถามการตรวจที่ใช้ <b>ติดตามประสิทธิภาพ (therapeutic effect)</b> ของ unfractionated heparin (UFH) IV — ต้องจับคู่ยากับ test ให้ถูก และแยกจาก test ที่ใช้ติดตามผลข้างเคียง",
  why:"UFH จับกับ <b>antithrombin</b> เร่งการยับยั้ง thrombin (IIa) และ factor Xa (รวม IXa, XIa) ซึ่งอยู่ใน <b>intrinsic และ common pathway</b> → ยืด <b>aPTT</b>; ปรับขนาดให้ aPTT ราว <b>1.5–2.5 เท่าของ control</b> (หรือใช้ anti-Xa 0.3–0.7 IU/mL) ตรวจ 6 ชม. หลังเริ่มหรือหลังปรับขนาดจนอยู่ในเป้า แล้วตรวจวันละครั้ง",
  wrong:[
    "PT (INR) ใช้ติดตาม <b>warfarin</b> ซึ่งลด factor II, VII, IX, X ที่ขึ้นกับ vitamin K — factor VII มี half-life สั้นที่สุด PT จึงไวต่อ warfarin; เป้า INR 2–3 ส่วนใหญ่; UFH ขนาดรักษาทำให้ PT ยืดเล็กน้อยเท่านั้น; จะถูกถ้าโจทย์ถามการติดตามผู้ป่วย AF ที่ได้ warfarin",
    "Bleeding time ประเมิน <b>platelet function</b> และหลอดเลือด (platelet dysfunction, vWD, aspirin) ปัจจุบันแทบไม่ใช้แล้ว (ใช้ PFA-100 หรือ platelet aggregation test แทน); จะถูกถ้าโจทย์ถามการตรวจคัดกรอง platelet dysfunction แบบเก่า",
    "Platelet count ใช้<b>เฝ้าระวัง HIT</b> (heparin-induced thrombocytopenia) — เกล็ดเลือดลด &gt;50% ในวันที่ 5–10 หลังเริ่ม heparin ไม่ได้บอกประสิทธิภาพของยา; จะถูกถ้าโจทย์ถามสิ่งที่ต้องติดตามเพื่อตรวจหาผลข้างเคียงสำคัญของ heparin",
    "D-dimer เป็น fibrin degradation product บอกว่ามีการสร้างและสลาย clot (เพิ่มใน DVT, PE, DIC, หลังผ่าตัด) — ใช้ <b>rule out</b> VTE ในผู้ป่วยความเสี่ยงต่ำ ไม่ใช้ติดตามขนาด heparin; จะถูกถ้าโจทย์ถามการตรวจแรกในผู้ป่วยสงสัย DVT ที่ Wells score ต่ำ"],
  trap:"สลับ PT กับ aPTT — จำว่า \"Heparin–aPTT (ชื่อยาวคู่ยาว), Warfarin–PT (ชื่อสั้นคู่สั้น)\"; และสับสนว่า platelet count ใช้ติดตามประสิทธิภาพ ทั้งที่ใช้เฝ้า HIT",
  summary:[
    "UFH: antithrombin-dependent ยับยั้ง IIa และ Xa → ติดตามด้วย aPTT 1.5–2.5 เท่าของ control หรือ anti-Xa 0.3–0.7 IU/mL; ตรวจ 6 ชม. หลังเริ่มหรือปรับขนาด",
    "UFH เหมาะเมื่อ CrCl &lt;30, เสี่ยงเลือดออกสูงหรือต้องหยุดยาเร็ว (half-life ~60–90 นาที), ก่อนหัตถการ; reverse ด้วย protamine sulfate (~1 mg ต่อ heparin 100 units ที่ให้ในช่วง 2–3 ชม.)",
    "LMWH (enoxaparin): ไม่ต้อง monitor ยกเว้น CKD, อ้วนมาก, ตั้งครรภ์, เด็ก → anti-Xa; protamine reverse ได้บางส่วน",
    "Warfarin: PT หรือ INR เป้า 2–3 (mechanical mitral valve 2.5–3.5); reverse ด้วย vitamin K, FFP หรือ PCC",
    "HIT: platelet ลด &gt;50% วันที่ 5–10 (เร็วกว่าถ้าเคยได้ heparin ใน 100 วัน) และมี thrombosis → หยุด heparin ทุกชนิด เปลี่ยนเป็น argatroban, bivalirudin หรือ fondaparinux; ใช้ 4T score และ anti-PF4 antibody",
    "DOAC (rivaroxaban, apixaban, dabigatran) ไม่ต้อง monitor ประจำ; dabigatran ยืด aPTT และ thrombin time; reverse dabigatran ด้วย idarucizumab",
    "ดูข้อ 15, 16 (hemostasis และ transfusion)"],
  notes:"ไฟล์เฉลยข้อ 14: คำตอบ <b>A</b> + ข้อความ (ไม่มีรูป):<br>\"<b>Heparin ดู aPTT</b><br>PT : warfarin<br>Bleeding time : Platelet dysfunction<br>Platelet count : Thrombocytopenia<br>D-dimer : ใช้ดูการสลายตัวของ clot โดยค่านี้จะเพิ่มใน e.g. DVT, DIC\"",
  mnemonic:"<b>\"HEP-ap, WAR-PT\"</b> — Heparin ↔ aPTT (intrinsic), Warfarin ↔ PT (extrinsic) หรือ <b>PeT WaR</b>",
  guide:"ACCP antithrombotic guideline 9th ed. 2012",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง",
  variants:[
    "ผู้ป่วยได้ UFH IV เพื่อรักษา PE วันที่ 7 เกล็ดเลือดลดจาก 250,000 เป็น 90,000 และขาบวมข้างใหม่ → HIT หยุด heparin เปลี่ยนเป็น argatroban",
    "ผู้ป่วยได้ warfarin INR 8 ไม่มีเลือดออก → หยุดยาและให้ vitamin K ทางปาก",
    "ผู้ป่วย CKD eGFR 20 ได้ enoxaparin ขนาดรักษา → ติดตามด้วย anti-Xa level หรือเปลี่ยนเป็น UFH"]}),

A({page:3, page2:8, orig:"15",
  stem:"After a car accident, a patient in hypovolemic shock requires massive blood transfusion. Which complication is LEAST likely?",
  gray:"คนไข้ Car accident Hypovolemic shock. Need massive blood transfusion. Which of the following complication is LEAST likely to happen ? — A. Air embolism B. Hyperkalemia C. Hypothermia D. Hypercalcemia E. Dilutional coagulopathy",
  opts:["Air embolism","Hyperkalemia","Hypothermia","Hypercalcemia","Dilutional coagulopathy"],
  ans:3, key:"D Hypercalcemia"+KS,
  interp:"ถามภาวะแทรกซ้อนที่<b>พบน้อยที่สุด</b>ของ massive transfusion — ต้องรู้กลไกของเลือดที่เก็บไว้ (citrate, K, อุณหภูมิ, ไม่มีเกล็ดเลือดและ coagulation factor) แล้วหาตัวที่กลับทิศ",
  why:"เลือดที่เก็บไว้ใช้ <b>citrate</b> เป็น anticoagulant ซึ่งจับ ionized Ca²⁺ และ Mg²⁺ — เมื่อให้เลือดจำนวนมากเร็ว ๆ โดยเฉพาะในผู้ป่วย shock หรือตับทำงานลดลงที่ metabolize citrate ไม่ทัน จะเกิด <b>hypocalcemia</b> (citrate toxicity) ทำให้หัวใจบีบตัวลด ความดันต่ำ และ coagulopathy แย่ลง — จึงไม่ใช่ hypercalcemia (เฉลย: \"Hypercalcemia -&gt; ต้อง Hypocalcemia\")",
  wrong:[
    "Air embolism เกิดได้จริงจากการใช้ <b>pressure bag หรือ rapid infuser</b> ที่ไม่ไล่อากาศ หรือสาย central line เปิด; พบไม่บ่อยแต่ยังมากกว่า hypercalcemia; จะเป็นคำตอบถ้าโจทย์ถามภาวะที่ป้องกันได้ด้วยการไล่อากาศในสายและใช้ rapid infuser ที่มี air detector",
    "Hyperkalemia เกิดได้ เพราะ K รั่วออกจาก RBC ระหว่างเก็บ (ยิ่งเก็บนานหรือฉายรังสี K ยิ่งสูง) ร่วมกับ acidosis และ AKI ในผู้ป่วย shock; ให้เร็วผ่าน central line เสี่ยง arrhythmia; ภายหลังอาจกลับเป็น hypokalemia เมื่อ K กลับเข้า RBC",
    "Hypothermia พบบ่อยมาก — RBC เก็บที่ 1–6°C และ platelet ที่อุณหภูมิห้อง ทำให้อุณหภูมิร่างกายลดลง เป็นส่วนหนึ่งของ <b>lethal triad</b> (hypothermia, acidosis, coagulopathy); ป้องกันด้วย blood warmer และ warming blanket",
    "Dilutional coagulopathy พบบ่อย — PRC ไม่มีเกล็ดเลือดและ coagulation factor ที่พอ การให้ PRC และ crystalloid จำนวนมากเจือจาง factor และ platelet; ร่วมกับ trauma-induced coagulopathy → ใช้ massive transfusion protocol อัตราส่วน PRC:FFP:platelet 1:1:1"],
  trap:"จำได้ว่า citrate เกี่ยวกับ calcium แต่สลับทิศ — citrate <b>จับ</b> Ca จึงเกิด <b>hypo</b>calcemia; และบางคนเลือก air embolism เพราะคิดว่าเป็นของ central line ไม่เกี่ยวกับ transfusion",
  summary:[
    "Massive transfusion: ≥10 units PRC ใน 24 ชม. หรือ ≥4 units ใน 1 ชม. หรือแทนที่ blood volume ทั้งหมดใน 24 ชม.",
    "Metabolic: hypocalcemia และ hypomagnesemia (citrate), hyperkalemia (ระยะแรก) และ hypokalemia ภายหลัง, acidosis ระยะแรกแล้ว metabolic alkalosis ภายหลัง (citrate → bicarbonate)",
    "Hypothermia: ใช้ blood warmer, warm fluid, warming blanket — ส่วนหนึ่งของ lethal triad ร่วม acidosis และ coagulopathy",
    "Coagulopathy: dilutional + trauma-induced → massive transfusion protocol อัตราส่วน 1:1:1, ติดตามด้วย TEG หรือ ROTEM, fibrinogen (cryoprecipitate)",
    "ตรวจ ionized Ca บ่อย ๆ และให้ calcium chloride หรือ calcium gluconate",
    "TXA ภายใน 3 ชม. หลังบาดเจ็บ (CRASH-2): 1 g IV ใน 10 นาที ตามด้วย 1 g ใน 8 ชม.",
    "อื่น ๆ: TACO, TRALI, hemolytic และ febrile reaction, infection, air embolism จาก pressure infusion",
    "ดูข้อ 14, 16 (hemostasis และ transfusion)"],
  notes:"ไฟล์เฉลยข้อ 15: คำตอบ <b>D</b> + ข้อความ (ไม่มีรูป):<br>\"<b>Massive transfusion is also associated with hypocalcemia due to citrate toxicity</b><br>A. Air embolism<br>B. Hyperkalemia<br>C. Hypothermia<br>D. Hypercalcemia -&gt; <b>ต้อง Hypocalcemia</b><br>E. Dilutional coagulopathy\"",
  mnemonic:"เลือดถุง <b>\"เย็น K สูง Ca ต่ำ ไม่มี factor\"</b>",
  guide:"ATLS 10th ed.",
  opinion:"เห็นด้วยกับคีย์ D มั่นใจสูง",
  variants:[
    "ผู้ป่วย trauma ได้ PRC 12 units ใน 2 ชม. แล้วความดันต่ำลง QT ยาว มือเกร็ง → hypocalcemia จาก citrate ให้ calcium chloride",
    "ผู้ป่วยได้ massive transfusion อุณหภูมิ 34°C เลือดซึมทุกจุดแทงเข็ม → lethal triad ต้อง warm และใช้ 1:1:1",
    "ผู้ป่วยได้เลือด 2 units ใน 6 ชม. แล้วหอบเหนื่อย ความดันสูง crepitation สองข้าง → TACO"]}),

A({page:4, page2:8, orig:"16", kimg:KI(16),
  stem:"Which molecule mediates platelet adhesion to the exposed subendothelium after vascular injury?",
  gray:"(ช่อง No ในไฟล์โจทย์เขียน \"c\") What is used for platelet adhesion? — A. Von willebrand factor B. GP2b3a C. (ว่าง)",
  opts:["von Willebrand factor","Glycoprotein IIb/IIIa","Fibrinogen","Thromboxane A2","Adenosine diphosphate"],
  ans:0, key:"A Von willebrand factor"+KS,
  interp:"ถามโมเลกุลที่ใช้ใน <b>platelet adhesion</b> (เกล็ดเลือดเกาะกับ subendothelium ที่เปิดออก) — ต้องแยกขั้นตอน adhesion, activation และ aggregation ของ primary hemostasis",
  why:"เมื่อหลอดเลือดบาดเจ็บ collagen ใน subendothelium ถูกเปิดออก <b>von Willebrand factor (vWF)</b> จะจับกับ collagen และเป็นสะพานเชื่อมกับ <b>glycoprotein Ib (GPIb-IX-V)</b> บนผิวเกล็ดเลือด โดยเฉพาะในหลอดเลือดที่มี shear stress สูง → เกล็ดเลือดเกาะติด = adhesion (เฉลย: \"vWF เชื่อม subendothelial กับ GpIb บน platelets\"); collagen ยังจับกับ GPVI และ integrin α2β1 โดยตรงร่วมด้วย",
  wrong:[
    "Glycoprotein IIb/IIIa เป็น receptor ของ <b>platelet aggregation</b> — เมื่อเกล็ดเลือด activate แล้ว GPIIb/IIIa เปลี่ยนรูปร่างจับ fibrinogen (และ vWF) เชื่อมเกล็ดเลือดกับเกล็ดเลือด (เฉลย: \"Gp2b3a เกี่ยวกับ platelet aggregation\"); ขาดเป็น Glanzmann thrombasthenia; ยา abciximab, eptifibatide, tirofiban; จะถูกถ้าโจทย์ถามโมเลกุลที่ทำให้เกล็ดเลือดเกาะกันเอง",
    "Fibrinogen เป็น ligand ของ GPIIb/IIIa ใน <b>aggregation</b> (เชื่อมเกล็ดเลือดสองตัว) และเป็นสารตั้งต้นของ fibrin ใน secondary hemostasis ไม่ใช่ตัวหลักของ adhesion กับ subendothelium; จะถูกถ้าโจทย์ถามสะพานเชื่อมระหว่างเกล็ดเลือดใน aggregation",
    "Thromboxane A2 สร้างจาก arachidonic acid ผ่าน COX-1 หลั่งออกมาตอน <b>activation</b> เพื่อกระตุ้นเกล็ดเลือดตัวอื่นและหดหลอดเลือด; aspirin ยับยั้ง COX-1 อย่างถาวร; จะถูกถ้าโจทย์ถามเป้าหมายของ aspirin หรือสารที่หลั่งจากเกล็ดเลือดและทำให้หลอดเลือดหดตัว",
    "ADP หลั่งจาก dense granule ตอน <b>activation</b> จับกับ P2Y12 กระตุ้นเกล็ดเลือดตัวอื่นและการแสดง GPIIb/IIIa; clopidogrel, prasugrel, ticagrelor ยับยั้ง P2Y12; จะถูกถ้าโจทย์ถามเป้าหมายของ clopidogrel"],
  trap:"สลับ adhesion กับ aggregation — adhesion = เกล็ดเลือดเกาะผนังหลอดเลือด (vWF + GPIb); aggregation = เกล็ดเลือดเกาะกันเอง (fibrinogen + GPIIb/IIIa)",
  summary:[
    "Primary hemostasis 3 ขั้น: adhesion → activation (shape change, granule release) → aggregation → platelet plug",
    "Adhesion: vWF เชื่อม collagen กับ GPIb-IX-V (สำคัญเมื่อ shear stress สูง) + collagen กับ GPVI และ α2β1 โดยตรง",
    "Activation: ADP (P2Y12), thromboxane A2, thrombin (PAR-1), serotonin → เปลี่ยนรูปร่างและ activate GPIIb/IIIa",
    "Aggregation: fibrinogen (และ vWF) เชื่อม GPIIb/IIIa ระหว่างเกล็ดเลือด",
    "โรค: Bernard-Soulier (ขาด GPIb, เกล็ดเลือดใหญ่และต่ำ), von Willebrand disease (พบบ่อยที่สุดในกลุ่ม inherited bleeding disorder — รักษาด้วย desmopressin หรือ vWF concentrate), Glanzmann thrombasthenia (ขาด GPIIb/IIIa, เกล็ดเลือดปกติ)",
    "ยา: aspirin (COX-1, ถาวร — หยุด 7–10 วันก่อนผ่าตัดถ้าจำเป็น), clopidogrel (P2Y12, หยุด 5 วัน), abciximab (GPIIb/IIIa)",
    "ดูข้อ 14, 15 (hemostasis และ transfusion)"],
  notes:"ไฟล์เฉลยข้อ 16: คำตอบ <b>A</b> + ข้อความ:<br>\"<b>A. vWF เชื่อม subendothelial กับ GpIb บน platelets</b><br><b>B. Gp2b3a เกี่ยวกับ platelet aggregation</b>\"<br>+ รูปเล็ก \"Platelet Activation Proteins and Ligands — AssayGenie\" (แผนภาพ receptor บนผิวเกล็ดเลือด ตัวอักษรเล็กอ่านไม่ออก)<br>ในไฟล์โจทย์ ช่อง No ของข้อนี้พิมพ์ว่า <b>\"c\"</b> (ข้ออื่นหลังข้อ 5 ช่อง No ว่าง); ต้นฉบับจดช้อยได้แค่ A. Von willebrand factor B. GP2b3a และ C. ว่างไว้ — ช้อย C (Fibrinogen), D (Thromboxane A2), E (Adenosine diphosphate) แต่งเพิ่ม; stem ขยายจาก \"What is used for platelet adhesion?\" เป็นการเกาะกับ subendothelium หลังหลอดเลือดบาดเจ็บ",
  mnemonic:"<b>\"Ib = I bind ผนัง, IIb/IIIa = เกาะกันเอง\"</b> — adhesion ใช้ vWF + GPIb, aggregation ใช้ fibrinogen + GPIIb/IIIa",
  guide:"Sabiston 21st ed.",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูง — สอดคล้องกับข้อสอบชุด 77A และ 77B (vWF = adhesion)",
  variants:[
    "หญิงประจำเดือนมามาก เลือดกำเดาบ่อย platelet count ปกติ aPTT ยาวเล็กน้อย ristocetin cofactor ต่ำ → von Willebrand disease",
    "เด็กมีเลือดออกง่าย เกล็ดเลือดขนาดใหญ่และต่ำ ไม่ agglutinate กับ ristocetin → Bernard-Soulier syndrome ขาด GPIb",
    "ผู้ป่วยได้ clopidogrel หลังใส่ stent จะผ่าตัด elective → ยานี้ยับยั้ง ADP receptor P2Y12 ควรหยุด 5 วันหลังปรึกษาแพทย์โรคหัวใจ"]}),

A({page:4, page2:9, orig:"17",
  stem:"You are going to examine a ward patient with hospital-acquired pneumonia caused by a multidrug-resistant organism. A COVID-19 test is negative. Which set of personal protective equipment is most appropriate?",
  gray:"ผู้ป่วย nosocomial pneumonia ใส่ PPE อะไรดีบ้าง covid19 negative — (ไม่มีช้อยตัวอักษร ผู้จดเขียนคำตอบไว้ในช่อง Choices: \"surgical mask, plastic coat, gloves, hair cover\")",
  opts:["Surgical mask, plastic gown, gloves and cap","N95 respirator, coverall, face shield and double gloves","Gloves only","Hand hygiene only without PPE","Powered air-purifying respirator and coverall"],
  ans:0, key:"A Surgical mask, plastic coat, gloves, hair cover"+KS,
  flag:"⚠ เล็กน้อย: ต้นฉบับไม่มีช้อย และเติม \"caused by a multidrug-resistant organism\" ใน stem ตามคำอธิบายในเฉลย",
  interp:"ผู้ป่วย <b>HAP จากเชื้อดื้อยา (MDRO)</b> และ COVID-19 negative → ถามชุด PPE ที่เหมาะ — ต้องเลือกตามทางแพร่เชื้อ (contact, droplet, airborne) ไม่ใช่ใส่มากที่สุดไว้ก่อน",
  why:"เชื้อดื้อยา (MRSA, CRE, Acinetobacter, Pseudomonas ดื้อยา) แพร่ทาง<b>สัมผัส</b>เป็นหลัก → <b>contact precautions</b>: gown (เสื้อพลาสติกกันน้ำ) และ gloves; ผู้ป่วยปอดอักเสบที่ไอมีเสมหะ ต้องกันละอองและสารคัดหลั่งกระเด็น → <b>surgical mask</b> (droplet หรือ standard precautions) ± eye protection; หมวกคลุมผมช่วยกันการปนเปื้อน — ตรงกับชุดที่เฉลยบอก \"แบบที่พวกเราใส่เวลาไปทำหัตถการให้คนไข้เชื้อดื้อยา\"; เชื้อเหล่านี้ไม่ได้แพร่ทาง airborne จึงไม่ต้องใช้ N95 หรือ PAPR",
  wrong:[
    "N95 respirator + coverall + face shield + double gloves เป็นชุดสำหรับ <b>airborne</b> หรือโรคติดต่อร้ายแรง (TB, measles, varicella, COVID-19 ระหว่าง aerosol-generating procedure, Ebola) — มากเกินจำเป็นสำหรับ MDRO pneumonia เปลืองทรัพยากรและใส่ถอดยุ่งยาก; จะถูกถ้าโจทย์เป็นผู้ป่วย COVID-19 positive ที่จะใส่ท่อช่วยหายใจ",
    "Gloves อย่างเดียวไม่พอ — contact precautions สำหรับ MDRO ต้องใส่ gown ด้วยเพราะเสื้อผ้าบุคลากรปนเปื้อนเชื้อจากผู้ป่วยและสิ่งแวดล้อมได้ และผู้ป่วยปอดอักเสบไอมีเสมหะต้องใส่ mask; จะถูก (ตาม standard precautions) เมื่อสัมผัสเลือดหรือสารคัดหลั่งในผู้ป่วยที่ไม่มีเชื้อดื้อยาหรือโรคติดต่อพิเศษ",
    "Hand hygiene อย่างเดียวเป็นส่วนหนึ่งของ standard precautions ที่ต้องทำทุกครั้ง แต่ไม่พอสำหรับผู้ป่วย MDRO ซึ่งต้องใช้ contact precautions; จะถูกถ้าแค่พูดคุยหรือวัดสัญญาณชีพในผู้ป่วยทั่วไปที่ไม่มีเชื้อดื้อยา",
    "PAPR + coverall ใช้สำหรับ airborne pathogen ที่เสี่ยงสูง หรือบุคลากรที่ fit test กับ N95 ไม่ผ่าน และในหัตถการที่สร้าง aerosol กับโรคร้ายแรง — ไม่จำเป็นสำหรับ MDRO; จะถูกถ้าโจทย์ถามการทำ bronchoscopy ในผู้ป่วย MDR-TB และบุคลากร fit test N95 ไม่ผ่าน"],
  trap:"ใส่ PPE เต็มชุดแบบ COVID ทุกครั้งที่ได้ยินคำว่า pneumonia — ต้องดูทางแพร่เชื้อ: MDRO = contact (+ droplet ในปอดอักเสบที่ไอ); airborne (N95) ใช้กับ TB, measles, varicella",
  summary:[
    "Standard precautions: ใช้กับผู้ป่วยทุกราย — hand hygiene, PPE ตามความเสี่ยงสัมผัสเลือดหรือสารคัดหลั่ง, respiratory hygiene, safe injection, การจัดการเข็มและของมีคม",
    "Contact precautions (MDRO, C. difficile, scabies, rotavirus): gown + gloves ทุกครั้งที่เข้าห้อง, ห้องเดี่ยวหรือ cohort, อุปกรณ์เฉพาะผู้ป่วย; C. difficile ล้างมือด้วยสบู่และน้ำ",
    "Droplet precautions (influenza, pertussis, meningococcus, mumps): surgical mask ในระยะ ~1–2 เมตร, ห้องเดี่ยว",
    "Airborne precautions (TB, measles, varicella, disseminated zoster): N95 respirator ที่ fit test แล้ว, negative pressure room (AIIR); PAPR สำหรับผู้ที่ fit test ไม่ผ่าน",
    "Eye protection หรือ face shield เมื่อมีโอกาสสารคัดหลั่งกระเด็น เช่น suction, ใส่ท่อช่วยหายใจ",
    "ลำดับใส่: hand hygiene → gown → mask → goggles → gloves; ลำดับถอด: gloves → goggles → gown → mask → hand hygiene (หรือถอด gown กับ gloves พร้อมกัน)",
    "ดูข้อ 12, 13, 80 (infection control และ antibiotic)"],
  notes:"ไฟล์โจทย์: ต้นฉบับ<b>ไม่มีช้อยตัวอักษร</b> — ผู้จดเขียนคำตอบไว้ในช่อง Choices ว่า <b>\"surgical mask, plastic coat, gloves, hair cover\"</b><br>ไฟล์เฉลยข้อ 17: คำตอบ <b>\"A.\"</b> + ข้อความ (ไม่มีรูป): <b>\"Personal Protective Equipment (PPE) : Surgical mask, plastic coat, gloves, hair cover แบบที่พวกเราใส่เวลาไปทำหัตถการให้คนไข้เชื้อดื้อยาอ่ะ\"</b><br>ช้อย A ของเราแปลจากคำตอบของผู้จด (plastic coat → plastic gown, hair cover → cap); ช้อย B–E แต่งเองทั้งหมด; stem เติม \"caused by a multidrug-resistant organism\" ตามคำอธิบายในเฉลยที่บอกว่าเป็นคนไข้เชื้อดื้อยา",
  mnemonic:"<b>\"ดื้อยา = สัมผัส (gown + gloves), ไอ = mask, ลอยในอากาศ = N95\"</b>",
  guide:"CDC Isolation Precautions 2007",
  opinion:"เห็นด้วยกับคีย์ A มั่นใจสูงหลังเติม MDRO ใน stem — ต้นฉบับบอกแค่ nosocomial pneumonia และ COVID-19 negative; ถ้าไม่ใช่เชื้อดื้อยา standard precautions + surgical mask ก็อาจพอ ส่วน gown จำเป็นเมื่อมีเชื้อดื้อยาหรือคาดว่าจะสัมผัสสารคัดหลั่ง จึงเติม MDRO ตามที่เฉลยอธิบาย",
  variants:[
    "ผู้ป่วยไอเรื้อรัง น้ำหนักลด AFB smear บวก กำลังรอผลเพาะเชื้อ → airborne precautions: N95 และ negative pressure room",
    "ผู้ป่วยท้องเสียหลังได้ antibiotic ตรวจพบ C. difficile toxin → contact precautions ใส่ gown และ gloves ล้างมือด้วยสบู่และน้ำ",
    "ผู้ป่วย COVID-19 positive จะใส่ท่อช่วยหายใจ → N95, face shield, gown, gloves ในห้อง AIIR"]}),
