A({page:8, page2:8, orig:"38", kimg:KI("38"),
  stem:"A patient has a low serum TSH. A radionuclide thyroid scan shows a solitary cold nodule. What is the most likely diagnosis?",
  gray:"38. Low tsh+cold nodule — A. Thyroid cancer B. Thyroid adenoma C. Toxic adenoma goiter",
  opts:["Thyroid cancer","Thyroid adenoma","Toxic adenoma","Graves disease","Multinodular goiter"],
  ans:3, key:NK, flag:"⚠ ต้นฉบับไม่มี Graves disease ในช้อย (แต่งเพิ่ม) และเติมคำว่า solitary ใน stem; รุ่นพี่ขีดฆ่าทั้งข้อเพราะซ้ำกับข้อ 18 จึงไม่มีคีย์",
  interp:"TSH ต่ำ = มี thyrotoxicosis (มี thyroid hormone เกินจน feedback กด TSH) แต่ nodule บน scan เป็น <b>cold</b> = ก้อนนั้นไม่จับ tracer จึงไม่ใช่ตัวสร้าง hormone เกิน ต้องหาว่าเนื้อต่อมส่วนไหนเป็นตัวสร้าง hormone",
  why:"ใน <b>Graves disease</b> TRAb (TSH receptor stimulating antibody) กระตุ้นเนื้อต่อมทั้งต่อม → scan เห็น diffuse ↑ uptake และ TSH ถูกกด; nodule ที่อยู่ร่วมในต่อม (benign nodule, cyst หรือมะเร็ง) ไม่ทำงานจึงเห็นเป็น cold nodule บนพื้นหลังที่จับ tracer จัด → เป็นคำอธิบายเดียวในช้อยที่ครอบคลุมทั้ง TSH ต่ำและ cold nodule; cold nodule ส่วนใหญ่ benign แต่เป็นมะเร็งได้ราว 10% จึงต้องประเมินด้วย US ± FNA ตาม ATA 2015 โดยเฉพาะก่อนให้ RAI",
  wrong:[
    "Thyroid cancer: มะเร็งเป็น cold nodule จริง แต่ผู้ป่วยมะเร็ง thyroid เกือบทั้งหมด euthyroid (TSH ปกติ) จึงอธิบาย TSH ต่ำไม่ได้ — จะเป็นคำตอบถ้าโจทย์ให้ TSH ปกติ + cold nodule + US suspicious (solid hypoechoic, microcalcification, irregular margin, taller-than-wide) หรือถามว่าโรคที่ต้อง exclude ใน cold nodule คืออะไร",
    "Thyroid adenoma (follicular adenoma ที่ไม่ทำงาน): เป็น cold nodule ได้ แต่ไม่สร้าง hormone → TSH ปกติ — จะเป็นคำตอบเมื่อ TSH ปกติ + cold nodule และผลผ่าตัดเป็น follicular lesion ที่ไม่มี capsular/vascular invasion",
    "Toxic adenoma: ก้อนที่ทำงานอิสระจะเป็น <b>hot nodule</b> และเนื้อต่อมที่เหลือถูกกด (suppressed) — จะเป็นคำตอบเมื่อ TSH ต่ำ + solitary hot nodule; hot nodule แทบไม่เป็นมะเร็ง จึงไม่ต้อง FNA (ATA 2015)",
    "Multinodular goiter: ถ้าเป็น nontoxic MNG TSH จะปกติ; ถ้าเป็น toxic MNG (Plummer disease) scan จะเห็นหลาย nodule มีทั้ง hot และ cold เป็นหย่อม ๆ (heterogeneous) ไม่ใช่ solitary cold nodule — จะเป็นคำตอบเมื่อผู้สูงอายุ ต่อมโตเป็นก้อนหลายก้อน TSH ต่ำ และ scan เห็น patchy uptake"],
  trap:"เห็น cold nodule แล้วตอบ thyroid cancer ทันทีโดยไม่ดู TSH — TSH ต่ำบอกว่าต้องมีเนื้อต่อมที่ทำงานเกินอยู่ที่อื่น; และอย่าจำสลับว่า toxic adenoma เป็น cold (จริง ๆ เป็น hot)",
  summary:[
    "ขั้นแรกของ thyroid nodule = ตรวจ TSH: TSH ต่ำ → radionuclide scan (I-123 หรือ Tc-99m pertechnetate); TSH ปกติหรือสูง → US แล้วตัดสิน FNA ตามขนาดและ US pattern (ATA 2015)",
    "Scan pattern เมื่อ TSH ต่ำ: Graves = diffuse ↑ uptake; toxic adenoma = solitary hot nodule + เนื้อที่เหลือถูกกด; toxic MNG = hot และ cold หลายจุดเป็นหย่อม ๆ; thyroiditis (subacute, painless, postpartum) หรือได้ hormone จากภายนอก = uptake ต่ำทั้งต่อม",
    "Hot (hyperfunctioning) nodule ความเสี่ยงมะเร็งต่ำมาก → ไม่ต้อง FNA; cold (nonfunctioning) nodule มะเร็งราว 10% → ประเมินด้วย US ± FNA ตามเกณฑ์เดียวกับคน euthyroid",
    "Graves ที่มี cold nodule: ทำ US ± FNA ก่อนให้ RAI ถ้าลักษณะ suspicious; ถ้า cytology indeterminate หรือ malignant → total thyroidectomy ซึ่งรักษา Graves ไปพร้อมกัน",
    "Marine-Lenhart syndrome = Graves ร่วมกับ autonomously functioning nodule (ก้อนที่ทำงาน ไม่ใช่ cold nodule ที่ไม่ทำงาน) — ก้อนอาจดูจับ tracer น้อยกว่าพื้นหลังที่จับจัดมาก จึงถูกเรียกว่า cold ได้ ต้องแยกให้ออก",
    "Graves: TRAb บวก, diffuse goiter, ophthalmopathy, pretibial myxedema; รักษาด้วย antithyroid drug (methimazole), RAI หรือ total thyroidectomy",
    "ดูข้อ 18 (โจทย์เดียวกันที่ถูกจดซ้ำในไฟล์นี้)"],
  notes:"<b>รุ่นพี่ขีดฆ่าทั้งข้อ</b> (กากบาทใหญ่ทับทั้งโจทย์และช้อย) เพราะโจทย์ซ้ำกับข้อ 17 ในไฟล์ (= ข้อ 18 ในแอป) — ไม่ได้วงคำตอบและไม่มีลายมืออื่น; ช้อยต้นฉบับมีเพียง 3 ช้อย: Thyroid cancer, Thyroid adenoma, Toxic adenoma goiter (ไม่มี Graves)",
  mnemonic:"TSH ต่ำ + cold nodule = 'พื้นหลังร้อน ก้อนเย็น' → Graves ที่มีก้อนอยู่ร่วม",
  guide:"ATA 2015 Thyroid Nodules and Differentiated Thyroid Cancer; ATA 2016 Hyperthyroidism and Other Causes of Thyrotoxicosis",
  opinion:"ข้อนี้รุ่นพี่ขีดฆ่าทิ้งเพราะซ้ำ จึงไม่มีคีย์ — ตอบ Graves disease ให้สอดคล้องกับข้อ 18. ช้อยต้นฉบับ 3 ตัว (thyroid cancer, thyroid adenoma, toxic adenoma) ไม่มีตัวไหนอธิบาย TSH ต่ำ + cold nodule ได้ จึงต้องแต่ง Graves disease เพิ่ม และเติมคำว่า solitary เพื่อกัน toxic MNG ที่มี cold area ปนกับ hot area. ถ้าผู้ออกข้อสอบตั้งใจถามว่า 'โรคที่ต้องระวังหรือต้อง exclude' คำตอบจะเป็น thyroid cancer (ความมั่นใจปานกลาง)",
  variants:["TSH ต่ำ + solitary hot nodule → toxic adenoma ไม่ต้อง FNA รักษาด้วย RAI หรือ lobectomy","TSH ต่ำ + uptake ต่ำทั้งต่อม + เจ็บคอ ESR สูง → subacute thyroiditis","Graves + cold nodule ที่ US suspicious → FNA ก่อน RAI ถ้า malignant → total thyroidectomy"]}),
A({page:8, page2:8, orig:"39", kimg:KI("39"),
  stem:"Which of the following conditions does NOT cause hyperthyroidism?",
  gray:"39. Hyperparathyroid ข้อไหนไม่ทำให้เกิด — A. Plummer B. Grave C. Hashimoto D. Medullary thyroid carcinoma",
  opts:["Plummer disease","Graves disease","Hashimoto thyroiditis","Medullary thyroid carcinoma","Toxic adenoma"],
  ans:3, key:"D Medullary thyroid carcinoma"+KS, flag:"⚠ ต้นฉบับเขียน 'Hyperparathyroid' แต่รุ่นพี่ตีความว่าถาม hyperthyroidism — stem ใช้ตามการตีความนี้ และแต่งช้อย E Toxic adenoma เพิ่ม",
  interp:"ถามโรคที่ไม่ทำให้ thyroid hormone เกิน — ต้องรู้ว่าแต่ละโรคเกิดจากเซลล์ชนิดไหนของต่อมไทรอยด์",
  why:"<b>Medullary thyroid carcinoma</b> มาจาก parafollicular C cell (neural crest) สร้าง <b>calcitonin</b> และ CEA ไม่สร้าง T3/T4 และไม่จับ radioiodine (ตามที่รุ่นพี่เขียน) → ผู้ป่วยเกือบทั้งหมด euthyroid; ส่วนอีก 4 ช้อยเป็นโรคของ follicular cell ที่ทำให้ hormone เกินได้ทั้งหมด (Hashimoto ทำได้ในระยะแรกแบบ Hashitoxicosis)",
  wrong:[
    "Plummer disease = toxic multinodular goiter: nodule หลายก้อนทำงานอิสระ สร้าง hormone เกิน พบในผู้สูงอายุและพื้นที่ขาด iodine — ทำให้ hyperthyroidism จริง; จะเป็นคำตอบถ้าถามสาเหตุ hyperthyroidism ในผู้สูงอายุที่มี multinodular goiter และ scan เห็น patchy uptake",
    "Graves disease: สาเหตุ hyperthyroidism ที่พบบ่อยที่สุด จาก TRAb กระตุ้น TSH receptor — จะเป็นคำตอบถ้าถาม most common cause ของ hyperthyroidism หรือมี ophthalmopathy, pretibial myxedema",
    "Hashimoto thyroiditis: ส่วนใหญ่ diffuse goiter กับ hypothyroid แต่ช่วงแรกที่ follicle ถูกทำลายจะปล่อย hormone ที่เก็บไว้ออกมาเกิด thyrotoxicosis ชั่วคราว (Hashitoxicosis) จึงยังนับว่าทำให้เกิดได้ — จะเป็นคำตอบถ้าถาม most common cause ของ hypothyroidism ในพื้นที่ที่ได้ iodine พอ หรือถ้าช้อยไม่มี MTC และถามโรคที่ 'มักไม่' ทำให้ hyperthyroidism",
    "Toxic adenoma: solitary autonomous hot nodule (มักมี TSH receptor activating mutation) สร้าง hormone เกิน — จะเป็นคำตอบถ้าถาม TSH ต่ำ + solitary hot nodule"],
  trap:"อ่านตามตัวอักษรว่า hyperparathyroidism แล้วตัด MTC ออกเพราะนึกถึง MEN2A — MTC ไม่ได้ทำให้เกิด hyperparathyroidism แต่เกิดร่วมกันจาก RET mutation; อีกกับดักคือตัด Hashimoto ออกเพราะคิดว่าต้อง hypothyroid เสมอ",
  summary:[
    "Thyrotoxicosis แบ่งตาม radioiodine uptake: high uptake = Graves (พบบ่อยที่สุด), toxic MNG (Plummer), toxic adenoma, TSH-secreting pituitary adenoma, hCG-mediated (molar pregnancy); low uptake = thyroiditis (subacute, painless, postpartum, Hashitoxicosis), exogenous hormone, iodine-induced, struma ovarii",
    "Graves: TRAb, diffuse goiter, ophthalmopathy, pretibial myxedema; toxic adenoma: solitary hot nodule; toxic MNG: ผู้สูงอายุ หลาย nodule patchy uptake",
    "MTC: จาก parafollicular C cell → tumor marker calcitonin และ CEA; ไม่จับ RAI จึงรักษาด้วย RAI ไม่ได้; ส่วนใหญ่ sporadic ราว 1 ใน 4 hereditary (RET germline)",
    "MEN2A = MTC + pheochromocytoma + primary hyperparathyroidism; MEN2B = MTC + pheochromocytoma + mucosal neuroma + marfanoid habitus — ต้อง R/O pheochromocytoma ก่อนผ่าตัดทุกราย",
    "MTC treatment: total thyroidectomy + central neck dissection (± lateral ตาม staging); hereditary RET carrier ทำ prophylactic thyroidectomy ตามระดับความเสี่ยงของ codon",
    "Hashimoto: anti-TPO, anti-Tg (เป็น marker ไม่ใช่ตัวก่อโรคโดยตรง), หญิงวัยกลางคน, goiter euthyroid หรือ hypothyroid, ระยะแรกอาจ Hashitoxicosis, เพิ่มความเสี่ยง primary thyroid lymphoma",
    "ถ้าอ่านตามตัวอักษร: thyrotoxicosis ทำให้ hypercalcemia จาก bone resorption โดย PTH ถูกกด (ไม่ใช่ hyperparathyroidism)",
    "ดูข้อ 8, 18, 20, 39 (ข้อ thyroid อื่นในชุดนี้)"],
  notes:"ลายมือรุ่นพี่: ลูกศรจากโจทย์ '<b>→ ข้อไหนไม่ทำให้เกิด hyperthyroidism</b>'; A Plummer ✓, B Grave ✓; C Hashimoto '→ most diffuse + hypothyroid แต่ช่วงแรก hyperthyroid ได้'; วง <b>D</b> Medullary thyroid carcinoma + เขียน '[do not accumulate radioiodine but secretes calcitonin]'. แปะสไลด์ 'Common causes of hyperthyroidism' (Graves' disease, toxic adenoma, toxic multinodular goiter = Plummer's disease) และสไลด์ 'Hashimoto's thyroiditis': middle-aged woman; pregnancy, anti-cancer (anti-IFN-α, kinase inhibitor); goiter at presentation + eu- or hypothyroid (rarely hyperthyroid: Hashitoxicosis) → almost universal hypothyroidism (chronic form); anti-thyroglobulin (TG) and anti-thyroid peroxidase (TPO) are not causative (มีลายมือเล็ก ๆ กำกับว่าเกิดจากเซลล์ถูกทำลายแล้วเกิด auto Ag); polygenic mutations: several HLAs, ethnic dependence",
  mnemonic:"MTC = 'C' cell → Calcitonin, CEA — ไม่ใช่ follicular cell จึงไม่สร้าง T3/T4 และไม่จับ iodine",
  guide:"ATA 2016 Hyperthyroidism and Other Causes of Thyrotoxicosis; ATA 2015 Revised Guidelines for Medullary Thyroid Carcinoma",
  opinion:"เห็นด้วยกับคีย์ D ภายใต้การตีความว่าโจทย์จริงถาม hyperthyroidism (ค่อนข้างมั่นใจว่าผู้จดพิมพ์ผิด เพราะช้อย Plummer, Graves, Hashimoto เป็นโรคที่ถามเรื่อง thyroid function). ถ้าอ่านตามตัวอักษรว่า 'ข้อไหนไม่ทำให้เกิด hyperparathyroidism' จะตอบไม่ได้: Graves กับ Plummer ไม่ทำให้ hyperparathyroidism (hypercalcemia จาก thyrotoxicosis กด PTH), Hashimoto ก็ไม่เกี่ยว ส่วน MTC ถูกโยงกับ PHPT ใน MEN2A แต่เป็นโรคร่วมจาก RET mutation ไม่ใช่สาเหตุ — ตอบได้หลายช้อย การตีความแบบรุ่นพี่จึงสมเหตุสมผลกว่า",
  variants:["Which cause of thyrotoxicosis has low radioiodine uptake? → subacute thyroiditis","MTC + hypertension + paroxysmal headache → R/O pheochromocytoma ก่อน thyroidectomy (MEN2A)","Tumor marker for postoperative surveillance of MTC → calcitonin และ CEA"]}),
A({page:8, page2:8, orig:"40", kimg:KI("40"),
  stem:"A patient presents with jaundice and epigastric discomfort. Which of the following investigations is not useful for this patient?",
  gray:"40. ข้อไหนไม่มีปยกับคนไข้ มาด้วยเหลืองขึ้น+epigastrium discomfort — A. CT B. Biopsy C. CA19-9,PSA,… D. Colonoscope E. Viral profile",
  opts:["CT of the abdomen","Tissue biopsy","Serum tumor markers","Colonoscopy","Viral hepatitis serology"],
  ans:1, key:"B Tissue biopsy"+KS, flag:"⚠ รุ่นพี่ไฮไลต์เลขข้อ (ไม่ชัวร์) — colonoscopy ก็ไม่ได้ช่วยประเมินภาวะเหลืองโดยตรง ต้นฉบับจึงตอบได้ 2 ช้อย; คงคีย์ Biopsy (ดู opinion)",
  interp:"เหลือง + epigastric discomfort → ต้องแยก hepatocellular กับ post-hepatic (obstructive) jaundice และหาสาเหตุที่อุดตัน; ถามการตรวจที่ไม่มีบทบาทในการประเมิน",
  why:"แนวทางประเมิน: LFT pattern + imaging (US → CT หรือ MRCP) เพื่อดูว่ามีท่อน้ำดีขยายไหม อุดที่ระดับไหน จากอะไร; tumor marker (CA 19-9) ใช้ประกอบเมื่อสงสัยมะเร็งตับอ่อนหรือท่อน้ำดี; viral serology ใช้หา viral hepatitis. ส่วน <b>tissue biopsy ไม่ใช่การตรวจเพื่อวินิจฉัย</b>ในผู้ป่วยกลุ่มนี้: (1) ถ้าเป็น periampullary หรือ pancreatic head mass ที่ resectable ต้องผ่าตัดอยู่แล้ว ไม่จำเป็นต้องมีผลชิ้นเนื้อก่อน และผลลบก็ไม่ exclude มะเร็ง (2) liver mass ส่วนใหญ่วินิจฉัยด้วย imaging การเจาะตับเสี่ยง bleeding และ tumor seeding จึงทำเฉพาะเมื่อผลจะ<b>เปลี่ยนแผนการรักษา</b> (imaging equivocal หรือก่อนให้ systemic therapy) — ตรงกับที่รุ่นพี่เขียน",
  wrong:[
    "CT of the abdomen: มีประโยชน์มาก — บอก level ของการอุดตัน หาก้อน ประเมิน staging และ resectability; จะไม่ใช้เฉพาะเมื่อต้องเลี่ยง contrast/radiation (ตั้งครรภ์, ไตวาย) ซึ่งใช้ US หรือ MRCP แทน",
    "Serum tumor markers: CA 19-9 ช่วยประกอบการวินิจฉัยและติดตาม pancreatic CA หรือ cholangiocarcinoma (สูงขึ้นได้จาก obstruction หรือ cholangitis เอง ต้องวัดซ้ำหลัง drainage), AFP ใน HCC, CEA — ส่วน PSA ที่ต้นฉบับพิมพ์ไว้ไม่เกี่ยว; จะเป็นคำตอบถ้าช้อยระบุเฉพาะ marker ที่ไม่เกี่ยวอย่าง PSA",
    "Colonoscopy: ไม่ได้ประเมินทางเดินน้ำดีหรือตับอ่อนโดยตรง แต่ถ้า imaging พบ liver mass หลายก้อนสงสัย metastasis (CEA สูง) colonoscopy ใช้หา primary colorectal cancer ได้ — จะเป็นคำตอบถ้าโจทย์ระบุชัดว่า imaging เป็นนิ่วหรือก้อนที่หัวตับอ่อนอุดท่อน้ำดีโดยไม่มีรอยโรคในตับ",
    "Viral hepatitis serology: ช่วยแยก hepatocellular jaundice (HAV, HBV, HCV, HEV) และ HBV/HCV ยังเป็น risk ของ HCC — จะเป็นคำตอบถ้า LFT เป็น cholestatic pattern ชัดและ imaging เห็นท่อน้ำดีขยายจากก้อนอุดตันแล้ว"],
  trap:"คิดว่า biopsy เป็น gold standard ต้องทำก่อนรักษาทุกก้อน — ในระบบ hepatobiliary และตับอ่อน ก้อนที่ผ่าตัดได้ไม่ต้อง biopsy ก่อน และการเจาะตับเสี่ยง seeding/bleeding; อีกกับดักคือ colonoscopy ที่ดูไม่เกี่ยวแต่บางบริบทใช้หา primary",
  summary:[
    "Approach jaundice: แยก unconjugated (hemolysis, Gilbert) กับ conjugated; LFT pattern hepatocellular (AST/ALT ขึ้นเด่น) vs cholestatic (ALP, GGT ขึ้นเด่น); US เป็นการตรวจแรกเพื่อดู bile duct dilatation",
    "ท่อน้ำดีขยาย → CT (pancreas protocol) หรือ MRCP หา level และสาเหตุ: นิ่ว CBD, periampullary CA, pancreatic head CA, hilar cholangiocarcinoma (Klatskin); painless progressive jaundice + weight loss + palpable gallbladder (Courvoisier sign) นึกถึงมะเร็ง",
    "Tumor markers ใช้ประกอบ ไม่ใช้วินิจฉัยเดี่ยว: CA 19-9 (pancreas, biliary; สูงปลอมได้จาก obstruction และไม่สร้างในคน Lewis-negative), CEA, AFP (HCC)",
    "Resectable pancreatic head หรือ periampullary mass → ผ่าตัด pancreaticoduodenectomy ได้โดยไม่ต้องมีผลชิ้นเนื้อ; ต้องมีผลชิ้นเนื้อ (EUS-FNA หรือ FNB ดีกว่าทางผิวหนังเพราะ seeding น้อยกว่า) เมื่อจะให้ neoadjuvant หรือ palliative chemotherapy หรือก้อน unresectable",
    "Liver mass biopsy: invasive, เสี่ยง bleeding และ needle-track seeding (meta-analysis ใน HCC ราว 2–3%; สไลด์อ้าง 5.1% จาก Takamori), แยก well-differentiated HCC จาก adenoma, FNH และตับปกติได้ยาก → ทำเฉพาะเมื่อ imaging equivocal และผลจะเปลี่ยนการรักษา",
    "Preoperative biliary drainage ไม่ทำ routine (เพิ่ม complication) ยกเว้น cholangitis, จะให้ neoadjuvant therapy หรือผ่าตัดต้องล่าช้า",
    "ดูข้อ 28, 50, 56, 58 (biliary obstruction และ liver mass)"],
  notes:"ลายมือรุ่นพี่ (เลขข้อไฮไลต์เหลือง = ไม่ชัวร์): ที่โจทย์ '→ Hepatic/Post hepatic jaundice?'; A CT '✓ obstructive? อะไรอุด'; วง <b>B</b> Biopsy; C '→ CA อุด?'; E '→ Hepatitis'; ลูกศรจาก B ลงมา: '<b>ทำ biopsy ถ้าเป็น liver CA แต่ในกรณีที่ทำ biopsy เพื่อเปลี่ยน plan Tx เท่านั้น</b> [ไม่นิยมทำ liver Bx เพื่อ diag ∵ กลัว tumor seeding/bleeding]; ส่วนกรณีที่ถ้าเป็น periampullary CA ทำไงก็ต้องตัดออก/รักษาอยู่แล้ว (สงสัยว่าเป็น malignant) Bx ไม่ช่วยอะไร'. แปะสไลด์ 'Liver mass biopsy': invasive, complication: seeding tumor (Takamori et al 5.1% HCC), แยก well diff. HCC–adenoma–FNH–normal liver cell ได้ยาก (มีลายมือเล็ก ๆ ว่าผลชิ้นเนื้ออาจแยกจากเซลล์ตับปกติไม่ได้) และ algorithm Phase III: liver mass → clinical/lab/basic imaging → benign / equivocal / suspected malignancy → additional imaging and special laboratory test → ถ้ายัง equivocal → liver mass biopsy",
  mnemonic:"Biopsy ทำเมื่อ 'ผลจะเปลี่ยนการรักษา' เท่านั้น",
  guide:"NCCN Pancreatic Adenocarcinoma 2025; AASLD Practice Guidance on HCC 2023; ACG Clinical Guideline: Evaluation of Abnormal Liver Chemistries 2017",
  opinion:"คงคีย์ B ความมั่นใจปานกลาง. ต้นฉบับมี 2 ช้อยที่ถือว่า 'ไม่มีประโยชน์' ได้: biopsy (ไม่ใช่ขั้นตอนวินิจฉัยของ obstructive jaundice ที่สงสัยมะเร็งซึ่งผ่าตัดได้ และเสี่ยง seeding/bleeding ตามที่รุ่นพี่อธิบาย) กับ colonoscopy (ไม่ได้ดูทางเดินน้ำดีหรือตับอ่อน). ถ้ามองเชิงความเกี่ยวข้อง colonoscopy ดู 'ไม่เกี่ยว' ชัดกว่า แต่ยังมีที่ใช้หา primary เมื่อสงสัย liver metastasis ขณะที่ biopsy เป็นสิ่งที่ 'ไม่ควรทำ' เพราะไม่เปลี่ยนการรักษา — ข้อสอบน่าจะวัดประเด็นนี้ จึงคงคีย์. ไม่เติมข้อมูลใน stem เพราะข้อมูลที่จะทำให้เหลือคำตอบเดียวจะกลายเป็นการใบ้; ถ้าโจทย์จริงบอกว่ามี liver mass หลายก้อน + CEA สูง colonoscopy จะมีประโยชน์ชัดเจนและ biopsy ของก้อนตับก็อาจมีบทบาท",
  variants:["Painless jaundice + resectable pancreatic head mass on CT → pancreaticoduodenectomy โดยไม่ต้อง biopsy ก่อน","Borderline resectable pancreatic mass ก่อนให้ neoadjuvant chemotherapy → EUS-guided FNA หรือ FNB","Cirrhosis + 2.5 cm APHE + washout → LI-RADS 5 วินิจฉัย HCC ไม่ต้อง biopsy"]}),
A({page:9, page2:9, orig:"41", kimg:KI("41"), img:QI(41), imgNote:"รูปในข้อสอบ: ผิวหนังบริเวณร่องก้นใกล้ปากทวารหนัก มีก้อนแดง บวม นูน",
  stem:"A man presents with perianal pain and fever for 3 days. The lesion is shown in the image. Which of the following groups of organisms is commonly isolated from this lesion?",
  gray:"41. — A. Gram pos rod B. Gram pos cocci C. Gram neg rod D. Gram neg cocci E. ตอบได้หลายข้อ",
  opts:["Gram-positive rods","Gram-positive cocci","Gram-negative rods","Gram-negative cocci","More than one of these"],
  ans:4, key:"E More than one of these"+KS, flag:"⚠ ต้นฉบับมีแค่รูปกับช้อย ไม่มีตัวโจทย์ — แต่ง stem เอง (ไม่บอกชื่อโรค)",
  interp:"รูปเป็นก้อนแดงบวมข้างปากทวาร + ปวด + ไข้ → perianal abscess (cryptoglandular infection); ถามกลุ่มเชื้อที่เพาะได้ → polymicrobial จาก gut flora และ skin flora",
  why:"Anal gland ที่ dentate line อุดตันและติดเชื้อ → หนองลามใน intersphincteric plane ออกมาเป็น perianal abscess; ผลเพาะเชื้อเป็น <b>mixed flora</b>: aerobes ราว 3/4 — E. coli (มากที่สุด ราว 27%, gram-negative rod), coagulase-negative Staphylococcus, Enterococcus, S. aureus (gram-positive cocci), Klebsiella, Pseudomonas, Enterobacter, Proteus (gram-negative rods) และ anaerobes ราว 1/4 — Bacteroides (gram-negative rod), Peptostreptococcus (gram-positive coccus), Fusobacterium ตามตารางที่รุ่นพี่แปะ → ทั้ง GPC และ GNR เป็นกลุ่มที่พบบ่อย จึงตอบมากกว่าหนึ่งข้อ",
  wrong:[
    "Gram-positive rods: พบน้อย (Corynebacterium ราว 1.5%, Propionibacterium acnes, Clostridium บางราย) ไม่ใช่กลุ่มหลัก — จะเป็นคำตอบเดี่ยวเมื่อถามเชื้อของ gas gangrene จากบาดแผล (Clostridium perfringens)",
    "Gram-positive cocci: ถูกบางส่วน (Enterococcus, S. aureus รวม MRSA, CoNS, Streptococcus, Peptostreptococcus) แต่ไม่ครบ — จะเป็นคำตอบเดี่ยวเมื่อเป็น skin abscess หรือ furuncle ทั่วไปที่ไม่เกี่ยวกับ anal gland ซึ่ง S. aureus เด่น",
    "Gram-negative rods: ถูกบางส่วน (E. coli พบบ่อยที่สุด, Bacteroides, Klebsiella) แต่ไม่ครบ — จะเป็นคำตอบถ้าถาม 'single most common organism' หรือกลุ่มเชื้อที่พบมากที่สุด",
    "Gram-negative cocci: Neisseria gonorrhoeae ทำ proctitis ได้แต่ไม่ใช่เชื้อหลักของฝีรอบทวาร — จะเป็นคำตอบเมื่อถาม proctitis มี mucopurulent discharge ในผู้มีเพศสัมพันธ์ทางทวารหนัก"],
  trap:"เลือก gram-negative rods เพราะจำว่า E. coli พบบ่อยที่สุด — โจทย์ถามกลุ่มเชื้อที่พบบ่อยซึ่งเป็น polymicrobial; และจำผิดว่า Bacteroides เป็น gram-positive (จริง ๆ เป็น anaerobic gram-negative rod)",
  summary:[
    "Anorectal abscess ราว 90% เป็น cryptoglandular (anal gland ที่ dentate line); ที่เหลือจาก Crohn disease, TB, malignancy, trauma, HIV",
    "แบ่งตำแหน่ง: perianal (พบบ่อยที่สุด), ischiorectal, intersphincteric, supralevator; horseshoe abscess ลามผ่าน deep postanal space; ฝีลึกอาจไม่เห็นก้อนภายนอก → PR, EUA, CT หรือ MRI",
    "อาการ: ปวดตุบ ๆ ต่อเนื่อง นั่งไม่ได้ ก้อนแดงร้อนกดเจ็บ ± ไข้",
    "การรักษาหลัก = incision and drainage โดยเร็ว ไม่ต้องรอ fluctuation; antibiotics เสริมเมื่อมี cellulitis กว้าง, systemic sepsis, immunosuppression, DM หรือ valvular heart disease หรือ prosthetic valve (ASCRS 2022)",
    "เชื้อ polymicrobial: E. coli ราว 27%, Bacteroides ราว 15%, CoNS, Enterococcus, S. aureus รวม MRSA, Klebsiella, Pseudomonas, Peptostreptococcus → ถ้าให้ยาต้องคลุม gram-negative และ anaerobe",
    "หลัง drainage ราว 1/3 เกิด fistula-in-ano; Goodsall rule: external opening ด้านหน้าเส้นขวาง → tract ตรงเข้าหา anal canal, ด้านหลัง → tract โค้งไป posterior midline",
    "Fournier gangrene = necrotizing soft tissue infection ของ perineum เชื้อ polymicrobial เช่นกัน ต้อง emergency debridement + broad-spectrum antibiotics"],
  notes:"ไฟล์โจทย์มีแค่รูปกับช้อย <b>ไม่มีตัวโจทย์</b>. ลายมือรุ่นพี่ (เลขข้อไฮไลต์เหลือง): B Gram pos cocci '✓ enterococcus'; C Gram neg rod '✓ E. coli'; วง <b>E</b> ตอบได้หลายข้อ. แปะตารางเชื้อที่เพาะได้จาก perianal abscess — Anaerobic organisms: Bacteroides spp. 20 (15.2%), Peptostreptococcus spp. 6 (4.5%), Fusobacterium spp. 4 (3%), Propionibacterium acnes 1 (0.8%), total 31 (23.5%); Aerobic organisms: Escherichia coli 36 (27.3%), coagulase-negative Staphylococci 16 (12.1%), Enterococcus spp. 11 (8.3%), Staphylococcus aureus 10 (7.6%) [MRSA 3 (2.3%), MSSA 7 (5.3%)], Klebsiella pneumoniae 4 (3%), Pseudomonas aeruginosa 4 (3%), Enterobacter cloacae 3 (2.3%), Group A β-hemolytic Streptococci 3 (2.3%), Proteus mirabilis 2 (1.5%), Corynebacterium spp. 2 (1.5%), total 101 (76.5%); รวม 132",
  mnemonic:"ฝีรอบก้น = เชื้อลำไส้ + เชื้อผิวหนัง → ผสมหลายกลุ่มเสมอ",
  guide:"ASCRS Clinical Practice Guidelines for the Management of Anorectal Abscess, Fistula-in-Ano, and Rectovaginal Fistula 2022",
  opinion:"เห็นด้วยกับคีย์ E (มั่นใจสูง) — ตารางที่รุ่นพี่แปะแสดงชัดว่าผลเพาะเชื้อมีทั้ง GPC และ GNR ทั้ง aerobe และ anaerobe. ต้นฉบับไม่มีตัวโจทย์ จึงแต่ง stem ให้ตรงกับรูปโดยไม่บอกชื่อโรค",
  variants:["Most common single organism isolated from perianal abscess → E. coli","Perianal abscess in a diabetic patient with spreading cellulitis → I&amp;D + antibiotics คลุม gram-negative และ anaerobe","Painful perianal swelling ที่ยังไม่ fluctuant → ทำ incision and drainage ได้เลยไม่ต้องรอ"]}),
A({page:9, page2:9, orig:"42", kimg:KI("42"),
  stem:"A previously healthy 50-year-old patient presents with right upper quadrant pain and is hemodynamically stable. There is no jaundice. WBC is 26,000/mm3 and urinalysis is normal. Imaging shows air in the gallbladder wall. What is the most appropriate management?",
  gray:"42. RUQ pain, no jaundice wbc 26,000 ua normal. Air in gallbladder wall — A. Emer cholecystectomy B. IV abx + elective cholecystectomy C. Emer cholecystostomy D. Elective cholecystostomy",
  opts:["Emergency cholecystectomy","IV antibiotics and elective cholecystectomy","Emergency cholecystostomy","Elective cholecystostomy","Observation with oral antibiotics"],
  ans:0, key:"B IV antibiotics and elective cholecystectomy"+KS, flag:"⚠ คีย์รุ่นพี่ B — ตอบ A ตาม TG18: emphysematous cholecystitis เป็น serious local complication และผู้ป่วยแข็งแรงควรผ่าตัดเร็ว; เติม previously healthy 50-year-old, hemodynamically stable",
  interp:"Air ในผนังถุงน้ำดี = emphysematous cholecystitis; WBC 26,000 (&gt;18,000) + marked local inflammation → TG18 Grade II (moderate); ไม่มี organ dysfunction จึงไม่ใช่ Grade III; ผู้ป่วยแข็งแรง = low surgical risk",
  why:"Emphysematous cholecystitis เกิดจาก gas-forming organisms (Clostridium, E. coli, Klebsiella) ร่วมกับ ischemia ของผนังถุงน้ำดี → เสี่ยง gangrene และ perforation สูงกว่า acute cholecystitis ทั่วไปมาก และ mortality สูงกว่า จึงถือเป็น surgical emergency: broad-spectrum IV antibiotics + <b>emergency หรือ early cholecystectomy</b>. TG18 ระบุว่า Grade II ที่มี serious local complications (gangrenous, emphysematous, pericholecystic abscess, hepatic abscess, biliary peritonitis, GB torsion) ให้ผ่าตัดฉุกเฉินร่วมกับ supportive care; และแม้ Grade II ทั่วไป ถ้า low risk (CCI ≤5 และ ASA ≤2) ก็ให้ early LC ที่ advanced center ไม่ใช่รอ elective",
  wrong:[
    "IV antibiotics + elective cholecystectomy: รอผ่าตัดทีหลังทำให้ผนังที่ขาดเลือดเสี่ยงเน่าและแตก; delayed LC ตาม TG18 สำหรับ Grade II ที่ not low risk (CCI ≥6 หรือ ASA ≥3) ที่ตอบสนองต่อยา — จะเป็นคำตอบเมื่อเป็น acute calculous cholecystitis Grade II ธรรมดา (ไม่มี gas หรือ gangrene) ในผู้ป่วยโรคร่วมมาก หรือมาช้าและรพ.ไม่พร้อมทำ early LC",
    "Emergency cholecystostomy: percutaneous GB drainage สำหรับผู้ป่วย high surgical risk หรือ unfit เช่น Grade III ที่ไม่ได้มี favorable organ failure, ผู้สูงอายุ ASA IV, septic shock — จะเป็นคำตอบถ้าโจทย์เป็นผู้ป่วยสูงอายุโรคร่วมมากหรือ unstable",
    "Elective cholecystostomy: ไม่มีที่ใช้ เพราะ drainage ทำเพื่อแก้ภาวะเฉียบพลันในคนที่ผ่าตัดไม่ได้ ไม่ทำแบบนัดล่วงหน้า — ไม่มีสถานการณ์ที่เป็นคำตอบ",
    "Observation with oral antibiotics: ไม่พอสำหรับ cholecystitis ที่ WBC 26,000 และมี gas ในผนัง; ยากินใช้ได้แค่ช่วงต่อหลังผ่าตัดหรือ drainage ในบางราย — biliary colic ธรรมดาไม่ต้องใช้ antibiotic เลย จึงไม่มีสถานการณ์ที่เป็นคำตอบใน acute cholecystitis"],
  trap:"เห็นว่าเป็น Grade II แล้วตอบ antibiotics + elective (interval 6–8 สัปดาห์) ตามความเคยชิน — TG18 แนะนำ early LC ในผู้ป่วย low risk และ emphysematous เป็น serious local complication ที่ไม่ควรรอ; อีกกับดัก: air ในผนัง GB ต่างจาก pneumobilia (air ในท่อน้ำดี = biliary-enteric fistula หรือหลัง sphincterotomy)",
  summary:[
    "TG18 diagnosis: A local sign (Murphy sign, RUQ mass, pain, tenderness) + B systemic sign (fever, CRP ↑, WBC ↑) + C imaging; definite = A + B + C",
    "Grade III = organ dysfunction: hypotension ต้องใช้ dopamine ≥5 µg/kg/min หรือ norepinephrine ขนาดใดก็ได้, ซึมลง, PaO2/FiO2 &lt;300, oliguria หรือ Cr &gt;2.0 mg/dL, PT-INR &gt;1.5, platelet &lt;100,000/mm3",
    "Grade II = WBC &gt;18,000/mm3, palpable tender RUQ mass, อาการ &gt;72 ชม., marked local inflammation (gangrenous, pericholecystic abscess, hepatic abscess, biliary peritonitis, emphysematous cholecystitis); Grade I = ไม่เข้าเกณฑ์ II และ III",
    "Treatment TG18: Grade I → early LC; Grade II → antibiotics + supportive care → low risk (CCI ≤5 และ ASA ≤2) early LC ที่ advanced center, not low risk → delayed LC, ยาไม่ได้ผล → GB drainage, มี serious local complication → ผ่าตัดฉุกเฉิน; Grade III → organ support, early LC ได้เฉพาะ favorable organ failure ที่ advanced center ไม่เช่นนั้น urgent GB drainage",
    "Emphysematous cholecystitis: gas ในผนังหรือในถุงน้ำดีบน X-ray, US หรือ CT; Clostridium, E. coli, Klebsiella; พบบ่อยในชายสูงอายุ, DM, vascular disease; gangrene และ perforation สูง → IV antibiotics คลุม anaerobe + emergency cholecystectomy; unfit → percutaneous cholecystostomy",
    "ปัจจัยที่ทำนายว่ารักษาด้วยยาไม่สำเร็จ (สไลด์รุ่นพี่): อายุ &gt;70, DM, tachycardia, GB distended, WBC &gt;15,000",
    "ดูข้อ 6, 30 (biliary)"],
  notes:"รุ่นพี่เขียน '<b>Grade II</b>' เหนือโจทย์ และวง <b>B</b> (IV abx + elective cholecystectomy). แปะสไลด์ TG18 GRADING — Grade III (severe): sepsis-induced organ dysfunction: cardiovascular hypotension requiring treatment with dopamine ≥5 µg/kg/min or any dose of norepinephrine, neurological decreased level of consciousness, respiratory PaO2/FiO2 ratio &lt;300, renal oliguria, creatinine &gt;2.0 mg/dL, hepatic PT-INR &gt;1.5, hematological platelet count &lt;100,000/mm3; Grade II (moderate): severe local inflammation — elevated WBC count (&gt;18,000/mm3), palpable tender mass in the right upper abdominal quadrant, duration of complaints &gt;72 h, marked local inflammation (gangrenous cholecystitis, pericholecystic abscess, hepatic abscess, biliary peritonitis, emphysematous cholecystitis); Grade I (mild). และสไลด์ TREATMENT Grade II (moderate): antibiotic and supportive care → advanced center → low risk for surgery (CCI ≤5 and/or ASA ≤2) → Early LC; not low risk for surgery (CCI ≥6 and/or ASA ≥3) → Delayed LC; failed ATB → GB drainage; Risk: Age &gt;70, DM, tachycardia, distended GB, WBC &gt;15,000. มีลายมือสีน้ำเงินใต้ช้อย D ที่ถูกตัดขอบภาพ อ่านไม่ได้",
  mnemonic:"Air in the wall = ผนังกำลังเน่า → อย่ารอ",
  guide:"Tokyo Guidelines 2018 (TG18) — diagnostic criteria, severity grading and management flowchart of acute cholecystitis",
  opinion:"⚠ ไม่เห็นด้วยกับคีย์ B (ความมั่นใจค่อนข้างสูง). รุ่นพี่จัดเป็น Grade II ถูกต้อง (WBC &gt;18,000 + emphysematous) แต่ flowchart TG18 ที่รุ่นพี่แปะเองบอกว่า Grade II ที่ low surgical risk ให้ early LC ที่ advanced center ส่วน delayed LC มีไว้สำหรับกลุ่ม not low risk. นอกจากนี้ TG18 ระบุว่า Grade II ที่มี serious local complication ซึ่งรวม emphysematous cholecystitis ควรผ่าตัดฉุกเฉินร่วมกับ supportive care เพราะเสี่ยง gangrene และ perforation. ต้นฉบับไม่บอกอายุและโรคประจำตัว จึงเติม 'previously healthy 50-year-old, hemodynamically stable' เพื่อให้ low surgical risk ชัด — ถ้าโจทย์เป็นผู้สูงอายุโรคร่วมมาก (CCI ≥6 หรือ ASA ≥3) หรือมี organ dysfunction ที่ผ่าตัดไม่ได้ คำตอบจะเปลี่ยนเป็น emergency cholecystostomy (C) ไม่ใช่ B",
  variants:["Elderly ASA IV with emphysematous cholecystitis and septic shock → percutaneous cholecystostomy + IV antibiotics","Healthy 40-year-old with Grade I acute cholecystitis → early laparoscopic cholecystectomy","Grade III cholecystitis with jaundice and respiratory failure → urgent GB drainage"]}),
A({page:9, page2:9, orig:"43", kimg:KI("43"),
  stem:"A patient develops calf pain after walking 200 meters. The dorsalis pedis pulse is 1+. Which of the following is the most appropriate next step?",
  gray:"43. เดิน 200 เมตรปวดน่อง dorsalis pedis 1+ — A. CT angiography B. Endovascular treatment",
  opts:["CT angiography","Endovascular treatment","Surgical bypass","Below-knee amputation","Warfarin anticoagulation"],
  ans:0, key:"A CT angiography"+KS, flag:"⚠ ในทางปฏิบัติขั้นแรกคือ ABI (ไม่มีในช้อย) ร่วมกับ supervised exercise และคุม risk factor; CTA ใช้เมื่อวางแผน revascularization — คงคีย์เพราะเป็นช้อยที่ดีที่สุดที่มี",
  interp:"ปวดน่องเมื่อเดินได้ระยะหนึ่ง + pulse ที่เท้าเบาลง → intermittent claudication จาก PAD ระดับ femoropopliteal; ถามขั้นตอนถัดไปจากช้อยที่มี",
  why:"ในช้อยทั้งหมด CTA เป็นการตรวจเพียงอันเดียว — ใช้ยืนยันตำแหน่ง ความยาว และความรุนแรงของ stenosis หรือ occlusion และทำ anatomic 'mapping' ก่อนตัดสินใจ revascularize (ตามที่รุ่นพี่เขียน); endovascular และ bypass ต้องมี imaging ก่อนเสมอ และใน claudication ทำเมื่ออาการรบกวนชีวิต (lifestyle-limiting) แม้ได้ GDMT + supervised exercise แล้ว; amputation และ warfarin ไม่มีที่ใช้",
  wrong:[
    "Endovascular treatment: เป็นการรักษาที่ต้องมี anatomic imaging ก่อน และใน claudication ทำเมื่อ lifestyle-limiting หลัง GDMT + SET ไม่ดีขึ้น — จะเป็นคำตอบเมื่อโจทย์ให้ CTA แล้วเห็น short-segment iliac หรือ SFA stenosis ในผู้ป่วยที่ยังปวดหลัง exercise therapy 3 เดือน หรือเป็น CLTI",
    "Surgical bypass: สำหรับ long-segment occlusion หรือ CLTI ในผู้ป่วยที่ fit และมี autologous vein (GSV) ดี — จะเป็นคำตอบเมื่อ CLTI (rest pain, tissue loss) กับ long femoropopliteal occlusion ที่ endovascular ไม่เหมาะ",
    "Below-knee amputation: ไม่ใช่การรักษา claudication — จะเป็นคำตอบเมื่อขาเกินเยียวยา: extensive gangrene, irreversible acute limb ischemia (Rutherford III: paralysis, profound sensory loss, inaudible arterial และ venous Doppler) หรือ infected foot ที่ revascularize ไม่ได้",
    "Warfarin anticoagulation: ไม่มีประโยชน์ใน stable PAD และเพิ่ม bleeding (WAVE trial) — ใช้ antiplatelet + statin แทน; anticoagulation จะเป็นคำตอบใน acute limb ischemia จาก embolism (IV heparin ทันที) หรือมี AF"],
  trap:"กระโดดไปทำ revascularization ตั้งแต่ claudication ครั้งแรก — claudication ส่วนใหญ่ไม่ลุกลามไปเสียขา การรักษาแรกคือ risk factor control + exercise; และขั้นแรกจริงคือ ABI ซึ่งไม่มีในช้อย",
  summary:[
    "Intermittent claudication: ปวดกล้ามเนื้อซ้ำ ๆ เมื่อเดินระยะเท่าเดิม หายเมื่อพักไม่กี่นาที; ตำแหน่งปวดบอกระดับ: buttock หรือ thigh = aortoiliac, calf = femoropopliteal (พบบ่อยที่สุด), foot = tibial",
    "Diagnosis: resting ABI ≤0.90 = PAD, 0.91–0.99 borderline, 1.00–1.40 ปกติ, &gt;1.40 = non-compressible (DM, CKD) → ใช้ toe-brachial index (≤0.70 ผิดปกติ); ABI ปกติแต่อาการชัด → exercise ABI",
    "Fontaine: I asymptomatic, IIa claudication &gt;200 m, IIb &lt;200 m, III rest pain, IV ulcer หรือ gangrene; CLTI = rest pain หรือ tissue loss + objective ischemia",
    "GDMT ทุกราย: เลิกบุหรี่, high-intensity statin, antiplatelet (aspirin หรือ clopidogrel), คุม BP และ DM; supervised exercise therapy 30–45 นาที ≥3 ครั้งต่อสัปดาห์ นาน ≥12 สัปดาห์; cilostazol ช่วยระยะเดิน (ห้ามใน heart failure); low-dose rivaroxaban 2.5 mg bid + aspirin ในผู้ป่วยที่ bleeding risk ต่ำ",
    "Anatomic imaging (duplex US, CTA, MRA, DSA) ทำเมื่อวางแผน revascularization: lifestyle-limiting claudication ที่ไม่ตอบสนองต่อ GDMT + SET หรือ CLTI",
    "Revascularization: endovascular สำหรับ lesion สั้นหรือ aortoiliac; bypass ด้วย GSV สำหรับ occlusion ยาวหรือ CLTI ในผู้ป่วยที่ fit",
    "Acute limb ischemia (6P) ต่างจาก claudication: IV heparin ทันที + emergency revascularization ตาม Rutherford class"],
  notes:"รุ่นพี่เขียน '<b>Claudication</b>' เหนือโจทย์ (เลขข้อไฮไลต์เหลือง = ไม่ชัวร์); วง <b>A</b> + เขียน '1st' ข้าง CT angiography; ลายมือ '→ ประเมินว่าควร revascularize มั้ย' ที่ท้ายโจทย์ และ 'เพื่อไปเตรียม mapping imaging ก่อน' ใต้ช้อย B",
  mnemonic:"Claudication: ABI ยืนยัน → เดิน + ยา 3 เดือน → ยังแย่ค่อย CTA แล้ว revascularize",
  guide:"2024 ACC/AHA Multisociety Guideline for the Management of Lower Extremity Peripheral Artery Disease; ESC 2024 Guidelines for Peripheral Arterial and Aortic Diseases",
  opinion:"คงคีย์ A (ความมั่นใจปานกลาง) เพราะ CTA เป็นการตรวจเพียงอันเดียวในช้อย และ endovascular หรือ bypass ต้องมี imaging ก่อนเสมอ. ⚠ แต่ตามแนวทาง 2024 ACC/AHA และ ESC 2024 ขั้นแรกของผู้ป่วยที่สงสัย claudication คือ resting ABI เพื่อยืนยัน PAD แล้วเริ่ม GDMT (เลิกบุหรี่, statin, antiplatelet) + supervised exercise therapy อย่างน้อย 12 สัปดาห์; CTA ไม่ได้ทำ routine ทุกราย (contrast, radiation) แต่ทำเมื่อวางแผน revascularize ในผู้ป่วย lifestyle-limiting claudication ที่ไม่ดีขึ้นหรือ CLTI. ถ้าข้อสอบมีช้อย ABI ให้ตอบ ABI; ถ้ามีช้อย supervised exercise + risk factor modification ก็ถูกกว่า CTA สำหรับการจัดการขั้นแรก",
  variants:["Calf claudication at 200 m — next step to confirm diagnosis → ABI","ABI 1.6 in a diabetic patient → non-compressible vessels → toe-brachial index","Lifestyle-limiting claudication despite 3 months of SET and GDMT → CTA then revascularization"]}),
A({page:9, page2:9, orig:"44", kimg:KI("44"),
  stem:"A patient taking warfarin is found to have an expanding epidural hematoma. What is the most appropriate preoperative management?",
  gray:"44. Expanding epidural hematoma ใช้ยา warfarinอยู่ — A. VitK B. FFP C. Bridging heparin D. ผ่าเลยแล้วให้ heparin หลังผ่า",
  opts:["Vitamin K alone","Fresh frozen plasma","Bridging with heparin","Operate now then give heparin","Platelet transfusion"],
  ans:1, key:"B Fresh frozen plasma"+KS,
  interp:"Intracranial bleeding ที่กำลังขยาย (expanding EDH) ในผู้ป่วยกิน warfarin → ต้อง reverse anticoagulation ทันทีเพื่อให้ผ่าตัด evacuate ได้อย่างปลอดภัย",
  why:"Warfarin ยับยั้ง vitamin K epoxide reductase → factor II, VII, IX, X (และ protein C, S) ทำงานไม่ได้; life-threatening bleeding ต้องให้ <b>factor สำเร็จรูปทันที</b> — ในช้อยมีเพียง FFP (ราว 10–15 mL/kg) ซึ่งมี coagulation factor ครบ ทำให้ผ่าตัดได้เร็ว (ตามที่รุ่นพี่เขียน 'ได้ factor ไปเลย'); ต้องให้คู่กับ IV vitamin K 10 mg เสมอ เพราะ factor ที่ให้ไปอยู่ได้สั้น (factor VII half-life ราว 6 ชม.) INR จะ rebound. ตาม guideline ปัจจุบัน 4-factor PCC (25–50 IU/kg ตาม INR) ดีกว่า FFP เพราะเร็วกว่า ปริมาตรน้อย ไม่ต้อง thaw",
  wrong:[
    "Vitamin K alone: ต้องรอตับสร้าง factor ใหม่ — IV เริ่มลด INR ในราว 4–6 ชม. และใช้ 12–24 ชม. กว่าจะปกติ ช้าเกินไปสำหรับ expanding EDH (รุ่นพี่: 'ช้าไป'); จะเป็นคำตอบเมื่อ INR สูงเกินเป้าโดยไม่มี bleeding (INR &gt;10 → หยุด warfarin + oral vitamin K) หรือ elective surgery ที่ INR ยังสูงวันก่อนผ่าตัด",
    "Bridging with heparin: ใช้กับ elective surgery ในผู้ป่วย thrombotic risk สูง (mechanical mitral valve, VTE หรือ stroke ภายใน 3 เดือน) โดยหยุด warfarin 5 วันแล้วให้ LMWH — ไม่ใช้ขณะมีเลือดออก เพราะยิ่งทำให้เลือดออกมากขึ้น",
    "Operate now then give heparin: ผ่าตัดขณะ INR สูงทำให้เลือดออกคุมไม่ได้ และห้ามให้ heparin ทันทีหลังผ่าตัด intracranial bleeding — การกลับมาให้ anticoagulant หลัง ICH ต้องรอหลายวันถึงหลายสัปดาห์ตาม thrombotic risk",
    "Platelet transfusion: warfarin ไม่ได้กระทบ platelet — จะเป็นคำตอบเมื่อผู้ป่วยต้องผ่าตัดสมองแต่ platelet &lt;100,000/mm3 หรือในบางกรณีของผู้ป่วยกิน antiplatelet ที่ต้องผ่าตัด"],
  trap:"ตอบ vitamin K เพราะเป็น antidote ของ warfarin — antidote จริงแต่ออกฤทธิ์ช้า; ภาวะฉุกเฉินต้องให้ factor (PCC หรือ FFP) คู่กับ IV vitamin K",
  summary:[
    "Warfarin = vitamin K antagonist → ↓ factor II, VII, IX, X, protein C และ S; ติดตามด้วย INR (เป้าส่วนใหญ่ 2–3, mechanical mitral valve 2.5–3.5)",
    "Life-threatening bleeding หรือต้องผ่าตัดฉุกเฉิน: หยุด warfarin + IV vitamin K 10 mg ช้า ๆ + 4F-PCC 25–50 IU/kg ตาม INR (หรือ FFP 10–15 mL/kg ถ้าไม่มี PCC); เช็ค INR ซ้ำ เป้า ≤1.4",
    "PCC vs FFP: PCC แก้ INR ได้ในไม่กี่นาที ปริมาตรน้อย ไม่ต้อง thaw หรือ ABO; FFP ต้องปริมาตรมาก (เสี่ยง TACO, TRALI) และใช้เวลา thaw และ infusion นาน",
    "Vitamin K: IV ออกฤทธิ์ใน 4–6 ชม. INR ปกติใน 12–24 ชม.; oral ช้ากว่า; ต้องให้คู่ PCC หรือ FFP เสมอเพื่อกัน INR rebound",
    "Elective surgery: หยุด warfarin 5 วันก่อน ตรวจ INR วันก่อนผ่าตัด; bridging เฉพาะ high thrombotic risk (BRIDGE trial: AF ส่วนใหญ่ไม่ต้อง bridge); เริ่มยาใหม่ 12–24 ชม. หลังผ่าตัดถ้า hemostasis ดี",
    "EDH: lucid interval, biconvex ไม่ข้าม suture, มักจาก middle meningeal artery; volume &gt;30 mL ควรผ่าตัด evacuate ไม่ว่า GCS เท่าไร (BTF surgical guideline 2006)",
    "DOAC reversal: dabigatran → idarucizumab; factor Xa inhibitor → andexanet alfa หรือ 4F-PCC",
    "ดูข้อ 75 (โจทย์เดียวกันที่ถูกจดซ้ำ)"],
  notes:"ลายมือรุ่นพี่: '<b>ด่วน!</b>' เหนือคำว่า epidural; วงคำว่า warfarin + เขียน 'เพิ่ม risk epidural hematoma'; A VitK 'ช้าไป จะต้องรอ factor ใหม่สร้าง'; วง <b>B</b> FFP '→ ได้ factor ไปเลย! จะได้ Sx ได้เลย ☺'",
  mnemonic:"Warfarin bleed ฉุกเฉิน: 'K + factor' — vitamin K ช้าแต่ยั่งยืน, PCC หรือ FFP เร็วแต่สั้น ต้องให้คู่กัน",
  guide:"Neurocritical Care Society/SCCM Guideline for Reversal of Antithrombotics in Intracranial Hemorrhage 2016; ACC Expert Consensus Decision Pathway on Management of Bleeding in Patients on Oral Anticoagulants 2020",
  opinion:"เห็นด้วยกับคีย์ B ภายในช้อยที่มี (มั่นใจสูง) — แต่ควรรู้ว่า guideline ปัจจุบันเลือก 4F-PCC + IV vitamin K เหนือ FFP; FFP เป็นทางเลือกเมื่อไม่มี PCC",
  variants:["Warfarin + ICH, choices include 4F-PCC → 4F-PCC + IV vitamin K","Warfarin INR 12 without bleeding → hold warfarin + oral vitamin K","Dabigatran + traumatic subdural hematoma needing surgery → idarucizumab"]}),
A({page:9, page2:9, orig:"45", kimg:KI("45"),
  stem:"Which of the following is the correct sequence of hemostasis after a blood vessel is injured?",
  gray:"45. เรียงลำดับถูก — A. Vasocon plt aggregation cog",
  opts:["Vasoconstriction → platelet aggregation → coagulation","Platelet aggregation → vasoconstriction → coagulation","Coagulation → platelet aggregation → vasoconstriction","Vasoconstriction → coagulation → platelet aggregation","Platelet aggregation → coagulation → vasoconstriction"],
  ans:0, key:"A Vasoconstriction → platelet aggregation → coagulation"+KS,
  interp:"ถามลำดับขั้นของ hemostasis ตั้งแต่หลอดเลือดบาดเจ็บ — primary hemostasis (หลอดเลือดหด + platelet plug) มาก่อน secondary hemostasis (coagulation → fibrin)",
  why:"(1) <b>Vasoconstriction</b> เกิดทันทีจาก reflex ของ smooth muscle + endothelin, เสริมด้วย TXA2 และ serotonin จาก platelet (2) <b>Platelet plug</b>: adhesion (GPIb จับ vWF บน subendothelial collagen) → activation (shape change, หลั่ง ADP, TXA2) → aggregation (GPIIb/IIIa จับ fibrinogen เชื่อม platelet) (3) <b>Coagulation</b>: tissue factor–VIIa เริ่ม cascade → thrombin burst บนผิว platelet → fibrin ซึ่ง factor XIIIa crosslink ให้ plug แข็งแรง (4) ตามด้วย fibrinolysis ทีหลัง (Sabiston)",
  wrong:[
    "Platelet aggregation ก่อน vasoconstriction: ผิด เพราะการหดของหลอดเลือดเป็น reflex ที่เกิดภายในวินาทีก่อน platelet เกาะ; สาร TXA2 และ serotonin จาก platelet เพียงช่วยให้หดต่อเนื่อง — จะเป็นคำตอบถ้าถามว่าสารจาก platelet ตัวไหนเสริม vasoconstriction (TXA2, serotonin)",
    "Coagulation ก่อน platelet และ vasoconstriction: กลับลำดับทั้งหมด; coagulation ต้องอาศัยผิว phospholipid ของ platelet ที่ activate แล้วเป็นที่ประกอบ tenase และ prothrombinase — ไม่มีบริบทที่ถูก; ถ้าถามลำดับภายใน secondary hemostasis จะเป็น initiation → amplification → propagation → fibrin stabilization",
    "Vasoconstriction → coagulation → platelet aggregation: สลับ primary กับ secondary — fibrin มาเสริมความแข็งแรงให้ platelet plug ที่เกิดก่อน; จะเป็นคำตอบไม่ได้ (แต่ถ้าถามว่า PT และ aPTT วัดขั้นไหน คือ coagulation)",
    "Platelet aggregation → coagulation → vasoconstriction: vasoconstriction ไม่ได้มาเป็นขั้นสุดท้าย; ขั้นสุดท้ายจริงคือ fibrinolysis — ถ้าโจทย์ให้ 4 ขั้น ลำดับคือ vasoconstriction → platelet plug → fibrin formation → fibrinolysis"],
  trap:"คิดว่า platelet เป็นขั้นแรกจนลืม vasoconstriction ที่เกิดทันที; หรือสับสนว่า coagulation เป็น primary hemostasis",
  summary:[
    "Hemostasis 4 ขั้น (Sabiston): vascular constriction → platelet plug formation → fibrin formation → fibrinolysis",
    "Primary hemostasis = vasoconstriction + platelet plug; ความผิดปกติ → mucocutaneous bleeding, petechiae, เลือดออกทันทีหลังแผล (vWD, thrombocytopenia, antiplatelet drug); ตรวจ platelet count, PFA-100",
    "Platelet: adhesion (GPIb-IX-V กับ vWF) → activation (ADP, TXA2, serotonin) → aggregation (GPIIb/IIIa กับ fibrinogen); Bernard-Soulier = ขาด GPIb, Glanzmann thrombasthenia = ขาด GPIIb/IIIa",
    "Secondary hemostasis = coagulation cascade: extrinsic (tissue factor + VII; PT/INR), intrinsic (XII, XI, IX, VIII; aPTT), common (X, V, II, fibrinogen); thrombin เปลี่ยน fibrinogen เป็น fibrin, XIIIa crosslink; ความผิดปกติ → เลือดออกในข้อและกล้ามเนื้อ, delayed bleeding (hemophilia)",
    "Fibrinolysis: tPA เปลี่ยน plasminogen เป็น plasmin ย่อย fibrin → D-dimer; ยับยั้งโดย PAI-1, α2-antiplasmin; tranexamic acid ยับยั้งการกระตุ้น plasminogen",
    "ยาตามขั้น: aspirin (COX-1 → ↓TXA2), clopidogrel (P2Y12), eptifibatide (GPIIb/IIIa), warfarin (II, VII, IX, X), heparin (เสริม antithrombin)",
    "ดูข้อ 17 (การประเมิน hemostasis ก่อนผ่าตัด)"],
  notes:"ต้นฉบับจำช้อยได้เพียงช้อยเดียว (Vasocon plt aggregation cog) — ตัวลวงอีก 4 ช้อยแต่งเป็นลำดับสลับ; รุ่นพี่วง <b>A</b> และเขียนเครื่องหมายถูก ✓ ข้างช้อย",
  mnemonic:"'หด → แปะ → แข็ง → ละลาย' = vasoconstriction → platelet plug → fibrin clot → fibrinolysis",
  guide:"Sabiston Textbook of Surgery 21st ed. 2022 — Hemostasis, Surgical Bleeding, and Transfusion",
  opinion:"",
  variants:["Which step is impaired by aspirin? → platelet aggregation จาก ↓TXA2","Glanzmann thrombasthenia → GPIIb/IIIa defect → impaired platelet aggregation","Final step after stable clot formation → fibrinolysis โดย plasmin"]}),
A({page:10, page2:10, orig:"46", kimg:KI("46"),
  stem:"Which of the following patients should receive tetanus immune globulin?",
  gray:"46. ต้องให้tetanus Ig — A. ไม่เคยได้toxoid+แก้วแตกตำขา B. ไม่เคยได้toxoid+abrasion dorsum foot",
  opts:["Never immunized, deep glass puncture wound of the leg","Never immunized, clean superficial abrasion of the foot","Three primary doses, booster 3 years ago, dirty wound","Three primary doses, booster 7 years ago, clean minor cut","Three primary doses, booster 12 years ago, clean minor cut"],
  ans:0, key:"A Never immunized, deep glass puncture wound of the leg"+KS, flag:"⚠ ต้นฉบับมี 2 ช้อย แต่งเพิ่ม C–E และเติมคำว่า clean superficial ในช้อย B ให้ชัดว่าเป็นแผลสะอาด",
  interp:"TIG ให้เมื่อครบ 2 เงื่อนไข: (1) แผล tetanus-prone และ (2) ไม่เคยได้วัคซีน ได้ไม่ครบ 3 doses หรือไม่ทราบประวัติ (ยกเว้น HIV หรือ immunodeficiency รุนแรงที่ให้เมื่อแผล tetanus-prone เสมอ)",
  why:"ตาม CDC: ประวัติไม่ทราบหรือได้ &lt;3 doses + แผลสะอาดเล็ก → Td หรือ Tdap อย่างเดียว; + แผลอื่น ๆ (ปนเปื้อนดิน มูลสัตว์ น้ำลาย, <b>puncture</b>, avulsion, crush, burn, frostbite) → Td หรือ Tdap + <b>TIG 250 units IM</b> คนละตำแหน่ง; ถ้าได้ ≥3 doses ไม่ต้องให้ TIG. ผู้ป่วย A ไม่เคยได้วัคซีนและมีแผลแทงลึก (ภาวะ anaerobic เหมาะกับ C. tetani) จึงเป็นคนเดียวที่ต้องได้ TIG",
  wrong:[
    "ไม่เคยได้วัคซีน + แผลถลอกสะอาดตื้น: ให้ Td หรือ Tdap แล้วฉีดให้ครบ primary series โดยไม่ต้องให้ TIG — จะต้องให้ TIG ถ้าแผลสกปรก ปนดินหรือมูลสัตว์ หรือเป็นแผลลึก",
    "≥3 doses + booster 3 ปีก่อน + แผลสกปรก: booster &lt;5 ปีจึงไม่ต้องให้อะไร (ไม่ต้องวัคซีน ไม่ต้อง TIG) — ถ้า booster ≥5 ปีจะให้ Td หรือ Tdap อย่างเดียว; TIG จะจำเป็นเฉพาะถ้าเป็น HIV หรือ immunodeficiency รุนแรง",
    "≥3 doses + booster 7 ปีก่อน + แผลสะอาดเล็ก: booster &lt;10 ปีจึงไม่ต้องให้อะไร — ถ้าแผลเดียวกันเป็น tetanus-prone จะต้องให้ Td หรือ Tdap เพราะเกิน 5 ปี แต่ยังไม่ต้อง TIG",
    "≥3 doses + booster 12 ปีก่อน + แผลสะอาดเล็ก: เกิน 10 ปี → ให้ Td หรือ Tdap booster อย่างเดียว ไม่ต้อง TIG"],
  trap:"คิดว่า 'ไม่เคยฉีด' ต้องได้ TIG ทุกแผล — แผลสะอาดเล็กให้แค่วัคซีน; และสับสน cutoff booster 5 ปี (แผลสกปรก) กับ 10 ปี (แผลสะอาด)",
  summary:[
    "Tetanus-prone wound: ปนเปื้อนดิน มูลสัตว์ น้ำลาย, puncture, avulsion, crush, missile, burn, frostbite, มีเนื้อตายมาก หรือได้รับการดูแลล่าช้า",
    "CDC: ประวัติไม่ทราบหรือ &lt;3 doses → แผลสะอาดเล็กให้ Td/Tdap, แผลอื่นให้ Td/Tdap + TIG; ≥3 doses → แผลสะอาดเล็กให้ Td/Tdap ถ้า booster ≥10 ปี, แผลอื่นให้ถ้า ≥5 ปี, ไม่ต้อง TIG",
    "HIV หรือ severe immunodeficiency + tetanus-prone wound → ให้ TIG ทุกครั้งไม่ว่าประวัติวัคซีน",
    "Human TIG 250 units IM คนละตำแหน่งกับวัคซีน; ในไทยถ้าไม่มี HTIG ใช้ equine tetanus antitoxin (TAT) ซึ่งต้องระวัง hypersensitivity",
    "Wound care (debridement เอาเนื้อตายและสิ่งแปลกปลอมออก) สำคัญเท่ากับ immunoprophylaxis; ผู้ใหญ่ที่ยังไม่เคยได้ Tdap ให้ใช้ Tdap; หญิงตั้งครรภ์ให้ Tdap",
    "ผู้ใหญ่ที่ไม่เคยฉีด: primary series 3 doses (0, 4 สัปดาห์, 6–12 เดือน) แล้ว booster ทุก 10 ปี",
    "Clinical tetanus: trismus, risus sardonicus, opisthotonus; รักษาด้วย HTIG, metronidazole, debridement, benzodiazepine และดูแล airway"],
  notes:"รุ่นพี่วง <b>A</b> (ไม่เคยได้ toxoid + แก้วแตกตำขา). แปะตาราง (แนวทางแบบ UK) แบ่งตาม immunisation status × แผล — คอลัมน์ Vaccine (clean wound), Vaccine (tetanus-prone wound), Human tetanus immunoglobulin: Fully immunised (5 total doses) → none required / none required / only if high risk; Primary immunisations complete, boosters incomplete but up to date → none required unless next booster is due soon and it is convenient / เหมือนกัน / only if high risk; Primary immunisation incomplete or boosters not up to date → a reinforcing dose of vaccine and further doses as required to complete the recommended schedule (to ensure future immunity) / เหมือนกัน / yes: one dose of human tetanus immunoglobulin in a different site; Not immunised or immunisation status not known or uncertain → an immediate dose of vaccine followed, if records confirm the need, by completion of a full five-dose course to ensure future immunity / เหมือนกัน / yes: one dose of human tetanus immunoglobulin in a different site (ตารางต่อไปถึงภาพของข้อถัดไป)",
  mnemonic:"TIG ต้องครบ 2 อย่าง: 'แผลเสี่ยง + วัคซีนไม่ครบ'; booster: สกปรก 5 ปี สะอาด 10 ปี",
  guide:"CDC Tetanus Clinical Guidance — wound management 2024; ACIP Tdap/Td recommendations 2020; UKHSA Green Book Chapter 30 Tetanus",
  opinion:"เห็นด้วยกับคีย์ A (มั่นใจสูง). ต้นฉบับช้อย B เขียนแค่ 'abrasion dorsum foot' — ถ้าแผลถลอกที่เท้าปนดินจะถือเป็น tetanus-prone และต้องให้ TIG เช่นกัน จึงเติม clean superficial เพื่อให้เหลือคำตอบเดียว; ช้อย C–E แต่งให้ครอบคลุม cutoff 5 และ 10 ปี",
  variants:["≥3 doses, last booster 6 years ago, rusty nail puncture → Td หรือ Tdap อย่างเดียว","Unknown history + clean small laceration → Tdap อย่างเดียว แล้วฉีดให้ครบ series","Fully immunized HIV patient with tetanus-prone wound → TIG + booster ถ้าถึงกำหนด"]}),
A({page:10, page2:10, orig:"47", kimg:KI("47"),
  stem:"A 25-year-old patient undergoes colonoscopy, which shows hundreds of adenomatous polyps throughout the colon. What is the most important advice?",
  gray:"47. Adenomatous polypเจอ advice ทำอะไรสำคัญสุด — A. ตรวจgene family B. Discuss C. Psychotherapy เพราะผู้ป่วยเป็นมะเร็ง?",
  opts:["Genetic testing of family members","Repeat colonoscopy in 10 years","Psychotherapy","Low-fiber diet","Daily aspirin alone"],
  ans:0, key:"A Genetic testing of family members"+KS, flag:"⚠ ต้นฉบับบอกแค่ 'adenomatous polyp' — เติม 25-year-old และ hundreds of adenomatous polyps ตามที่รุ่นพี่ระบุว่าเป็น FAP",
  interp:"คนอายุน้อยมี adenoma หลายร้อยก้อน = familial adenomatous polyposis (FAP) — โรคพันธุกรรม autosomal dominant ที่เกือบทุกคนเป็นมะเร็งถ้าไม่รักษา",
  why:"FAP เกิดจาก germline <b>APC</b> mutation (chromosome 5q21) autosomal dominant penetrance เกือบ 100% → CRC เกือบ 100% ถ้าไม่ผ่าตัด (อายุเฉลี่ยราว 39 ปี); first-degree relatives มีโอกาสเป็น 50% → genetic counseling + ตรวจ APC ใน proband แล้วทำ <b>cascade testing</b> ในญาติ; ญาติที่เป็นพาหะหรือไม่ได้ตรวจ gene เริ่มส่องกล้องทุก 1–2 ปีตั้งแต่อายุ 10–15 ปี เพื่อผ่าตัดก่อนเป็นมะเร็ง — เป็นคำแนะนำที่ป้องกันมะเร็งได้ทั้งครอบครัว จึงสำคัญที่สุด",
  wrong:[
    "Repeat colonoscopy in 10 years: เป็น interval ของ average risk ที่ colonoscopy ปกติ; ใน FAP ต้องวางแผนผ่าตัดและติดตามทุกปี — จะเป็นคำตอบเมื่อ colonoscopy ปกติในคน average risk (หรือ 1–2 tubular adenoma &lt;10 mm → 7–10 ปี ตาม USMSTF 2020)",
    "Psychotherapy: การดูแลด้านจิตใจเป็นส่วนหนึ่งของ genetic counseling แต่ไม่ใช่คำแนะนำสำคัญที่สุด และผู้ป่วยยังไม่ได้วินิจฉัยว่าเป็นมะเร็ง — ไม่มีบริบทที่เป็นคำตอบหลัก",
    "Low-fiber diet: ไม่มีหลักฐานว่าป้องกัน polyp หรือมะเร็ง — ใช้ช่วงสั้น ๆ ก่อนเตรียมลำไส้ส่องกล้อง หรือในผู้ป่วยที่มี stricture",
    "Daily aspirin alone: chemoprevention (aspirin, NSAID) ลดจำนวน polyp ได้บ้างแต่ไม่สามารถแทน colectomy — aspirin มีหลักฐานลดมะเร็งใน Lynch syndrome (CAPP2) ไม่ใช่ทางเลือกเดี่ยวใน FAP"],
  trap:"ตอบแค่ส่องกล้องติดตามเหมือน sporadic adenoma — เมื่อมี polyposis (adenoma สะสม ≥10 ก้อน) ต้องคิดถึงกลุ่มโรคพันธุกรรมและส่งตรวจ genetic ทั้งตัวผู้ป่วยและครอบครัว",
  summary:[
    "Classic FAP: adenoma ≥100 (มักหลายร้อยถึงหลายพัน) เริ่มวัยรุ่น; APC gene autosomal dominant ราว 1 ใน 4 เป็น de novo; CRC เกือบ 100% อายุเฉลี่ยราว 39 ปีถ้าไม่ผ่าตัด; attenuated FAP มี 10–99 ก้อน มักอยู่ด้านขวาและอายุมากกว่า",
    "MUTYH-associated polyposis: autosomal recessive มี 10–100 ก้อน — ผู้ที่มี adenoma สะสม ≥10 ก้อนควรได้ genetic counseling + multigene panel",
    "ญาติ: genetic counseling → ตรวจ APC mutation ที่รู้แล้วในครอบครัว; พาหะหรือไม่ได้ตรวจ → colonoscopy ทุก 1–2 ปี เริ่มอายุ 10–15 ปี",
    "ผ่าตัด: total proctocolectomy with IPAA (rectum มี polyp มาก) หรือ total colectomy with ileorectal anastomosis (rectal polyp น้อย ต้องส่องติดตาม rectum ทุก 6–12 เดือน); มักทำช่วงปลายวัยรุ่นถึงต้นวัย 20 หรือเร็วกว่าถ้ามี high-grade dysplasia",
    "Extracolonic: duodenal และ periampullary adenoma (ส่องกล้อง side-viewing เริ่มอายุ 20–25 ปี จัด Spigelman stage), desmoid tumor (สาเหตุตายสำคัญหลัง colectomy), fundic gland polyps, papillary thyroid CA (cribriform-morular variant), hepatoblastoma ในเด็ก, CHRPE; Gardner = + osteoma และ epidermoid cyst; Turcot = + medulloblastoma",
    "แยกจาก Lynch syndrome: MMR genes, ไม่มี polyposis, Amsterdam II (3–2–1 rule), right colon CA + endometrial CA"],
  notes:"รุ่นพี่เขียน '<b>FAP</b>' (สีม่วง) เหนือโจทย์ และวง <b>A</b> (ตรวจ gene family); ด้านขวาของภาพเป็นตารางวัคซีนบาดทะยักที่ต่อจากข้อก่อนหน้า",
  mnemonic:"FAP = 'Family APC Polyps' — เจอคนเดียว ตรวจทั้งบ้าน",
  guide:"NCCN Genetic/Familial High-Risk Assessment: Colorectal, Endometrial, and Gastric 2024; ACG Clinical Guideline: Genetic Testing and Management of Hereditary GI Cancer Syndromes 2015",
  opinion:"เห็นด้วยกับคีย์ A (มั่นใจสูงเมื่อเป็นบริบท FAP). ต้นฉบับบอกแค่ 'adenomatous polyp' ซึ่งถ้าเป็น adenoma 1–2 ก้อนในคนทั่วไป คำตอบจะเป็น polypectomy + ส่องติดตามตาม interval ไม่ใช่ตรวจ gene ครอบครัว จึงเติมอายุ 25 ปีและ polyp หลายร้อยก้อนตามที่รุ่นพี่ระบุว่าเป็น FAP; ช้อย B ต้นฉบับ 'Discuss' ไม่ชัดว่าหมายถึงอะไร จึงแปลงเป็น interval ของ average risk",
  variants:["Child of an FAP parent with a known APC mutation → APC testing; positive → colonoscopy ทุก 1–2 ปีตั้งแต่ 10–15 ปี","FAP with few rectal adenomas → total colectomy with ileorectal anastomosis","Patient with 15 cumulative adenomas at age 50 → genetic counseling for attenuated FAP หรือ MUTYH"]}),
A({page:10, page2:10, orig:"48", kimg:KI("48"),
  stem:"A patient has ongoing loss of gastric content. Which intravenous fluid is most appropriate to replace this loss?",
  gray:"48. Loss gastric content — A. 0.9% B. Ringer lactate C. DN/2",
  opts:["0.9% NaCl","Ringer lactate","5% dextrose in 0.45% NaCl","3% NaCl","5% dextrose in water"],
  ans:0, key:"A 0.9% NaCl"+KS,
  interp:"เสียน้ำย่อยกระเพาะ (อาเจียน, NG drainage, gastric outlet obstruction) → เสีย H+, Cl-, K+, Na+ และน้ำ → hypochloremic hypokalemic metabolic alkalosis; เลือกสารน้ำทดแทน",
  why:"Gastric juice มี Cl สูง (ราว 100–150 mEq/L), Na ราว 20–80, K ราว 5–20 และ H+ สูง; <b>0.9% NaCl</b> (Na 154, Cl 154 mEq/L) เป็น isotonic fluid ที่มี Cl มากที่สุด → แก้ทั้ง volume และ Cl depletion ซึ่งเป็นตัวที่ทำให้ alkalosis คงอยู่ (chloride-responsive alkalosis) แล้วเติม KCl (20–40 mEq/L) เมื่อมี urine output",
  wrong:[
    "Ringer lactate: Cl 109 mEq/L และมี lactate ซึ่งเปลี่ยนเป็น HCO3- → แก้ alkalosis ได้ไม่ดี — เหมาะกับการเสียสารน้ำจาก small bowel, biliary, pancreatic fistula หรือ diarrhea และ resuscitation ทั่วไป",
    "5% dextrose in 0.45% NaCl: hypotonic (Na 77) ใช้เป็น maintenance ไม่ใช่ replacement ของ volume ที่เสียไป — จะเป็นคำตอบถ้าถาม maintenance fluid (ร่วมกับ KCl) หรือขั้นต่อจาก bolus ในทารก pyloric stenosis",
    "3% NaCl: hypertonic ใช้ใน severe symptomatic hyponatremia (ชัก, ซึม) หรือ raised ICP — ไม่ใช่ fluid ทดแทนการสูญเสีย",
    "5% dextrose in water: ไม่มี electrolyte กลายเป็น free water — ใช้แก้ hypernatremia (free water deficit) ไม่ทดแทน volume หรือ Cl"],
  trap:"เห็นคำว่าเสียสารน้ำแล้วตอบ Ringer lactate ตามความเคยชินว่า balanced crystalloid ดีกว่า — gastric loss ต้องการ Cl และ RL มี base (lactate) ทำให้ alkalosis ไม่ดีขึ้น",
  summary:[
    "Gastric loss → hypochloremic hypokalemic metabolic alkalosis; ไตพยายามรักษา volume (aldosterone) → ดูด Na กลับแลกกับ K และ H → paradoxical aciduria; urine Cl &lt;20 mEq/L = chloride-responsive",
    "Gastric juice (Sabiston): Na 20–80, K 5–20, Cl 100–150 mEq/L + H+; ส่วน small bowel, bile, pancreatic juice มี Na และ HCO3 สูง → ทดแทนด้วย RL",
    "Treatment: 0.9% NaCl + KCl หลังมี urine output (peripheral line ไม่เกินราว 10 mEq/h); ทดแทน NG output แบบ mL ต่อ mL และติดตาม electrolytes",
    "Diarrhea หรือ lower GI loss → เสีย HCO3 และ K → normal anion gap metabolic acidosis (ตรงข้ามกับ gastric loss)",
    "Gastric outlet obstruction (PUD, gastric CA) ต้องแก้ fluid และ electrolyte ก่อนผ่าตัด",
    "Infantile hypertrophic pyloric stenosis: resuscitate ด้วย NSS bolus แล้วตามด้วย dextrose + 0.45% NaCl + KCl ให้ alkalosis หายก่อน pyloromyotomy (ลด postoperative apnea)",
    "ดูข้อ 16, 22, 25, 32 (fluid และ electrolyte)"],
  notes:"รุ่นพี่วง <b>A</b> และเขียนต่อท้าย 0.9% ว่า '<b>NaCl</b>' (= 0.9% NaCl); ด้านขวาของภาพเป็นสไลด์ liver abscess ของข้อถัดไป",
  mnemonic:"กระเพาะเสีย Cl → เติม Cl (NSS) + K",
  guide:"Sabiston Textbook of Surgery 21st ed. 2022 — Fluid and Electrolyte Management of the Surgical Patient; NICE CG174 Intravenous Fluid Therapy in Adults (updated 2017)",
  opinion:"",
  variants:["Persistent vomiting from gastric outlet obstruction with pH 7.52, Cl 85, K 2.8 → 0.9% NaCl + KCl","High-output pancreatic fistula → Ringer lactate (เสีย HCO3)","Infant with projectile vomiting and hypochloremic alkalosis → แก้ด้วย NSS + KCl ก่อน pyloromyotomy"]}),
A({page:10, page2:10, orig:"49", kimg:KI("49"),
  stem:"A patient has fever and right upper quadrant pain for 1 week with leukocytosis. CT shows a 10-cm low-attenuation, mixed solid and cystic liver lesion with rim enhancement. What is the most likely diagnosis?",
  gray:"49. Pale, rim enhance 10 cm , mix-solid,cystic — A. Liver abscess B. Tumor bleedในก้อน",
  opts:["Liver abscess","Hemorrhage within a hepatic tumor","Simple hepatic cyst","Hepatic hemangioma","Focal nodular hyperplasia"],
  ans:0, key:"A Liver abscess"+KS, flag:"⚠ เติม fever + RUQ pain 1 สัปดาห์ + leukocytosis (ต้นฉบับให้แค่ลักษณะ CT ซึ่งแยก abscess กับ tumor bleed ได้ไม่ชัด); ตีความ 'Pale' ว่าเป็น low attenuation",
  interp:"ก้อนในตับขนาดใหญ่ hypodense ผสม solid และ cystic + rim enhancement ร่วมกับไข้ ปวดชายโครงขวา WBC สูง → การติดเชื้อเป็นหนองในตับ",
  why:"Pyogenic liver abscess บน CT = <b>low-attenuation complex hypodense mass with peripheral (rim) enhancement</b> (ตามสไลด์ที่รุ่นพี่แปะ) อาจมี septation, cluster sign, double target sign หรือ gas; ไข้ + RUQ pain + leukocytosis เป็นอาการหลัก; ในเอเชียเชื้อสำคัญคือ Klebsiella pneumoniae (โดยเฉพาะผู้ป่วย DM) ส่วนตะวันตกเป็น E. coli และ polymicrobial",
  wrong:[
    "Hemorrhage within a hepatic tumor (HCC rupture หรือ adenoma bleed): ปวดเฉียบพลันรุนแรง, hypotension, Hb ลด, เห็นเลือดใหม่ hyperdense บน non-contrast CT และมีส่วน tumor ที่ enhance; ไม่มีไข้นานเป็นสัปดาห์ — จะเป็นคำตอบถ้า 'pale' หมายถึงซีด + ปวดทันที + shock ในผู้ป่วย cirrhosis หรือ HBV หรือหญิงกินยาคุม",
    "Simple hepatic cyst: ผนังบาง homogeneous water density ไม่ enhance ไม่มี solid part และมักไม่มีอาการ — จะเป็นคำตอบเมื่อเป็น incidental anechoic lesion มี posterior acoustic enhancement บน US",
    "Hepatic hemangioma: peripheral nodular discontinuous enhancement แล้วค่อย ๆ fill-in เข้ากลาง (centripetal) ใน delayed phase, T2 สว่างมาก; ไม่มีไข้ — จะเป็นคำตอบเมื่อ incidental lesion ที่มี pattern นี้; ก้อนใหญ่มากอาจเกิด Kasabach-Merritt (consumptive coagulopathy)",
    "Focal nodular hyperplasia: หญิงสาว homogeneous arterial enhancement, iso ใน portal phase, central stellate scar ที่ T2 สว่างและ enhance ช้า; ไม่มีไข้ — จะเป็นคำตอบเมื่อหญิงสาวมี incidental lesion + central scar"],
  trap:"เห็น mixed solid-cystic + rim enhancement แล้วตอบ tumor (necrotic tumor ก็ rim enhance ได้) — ต้องดูบริบทไข้และ WBC; และอย่าลืมแยก pyogenic กับ amebic และ melioidosis ในไทย",
  summary:[
    "Pyogenic liver abscess แหล่งที่มา: biliary (พบบ่อยที่สุด — cholangitis, นิ่ว, มะเร็งอุดตัน), portal vein (appendicitis, diverticulitis), hematogenous (endocarditis), direct extension, cryptogenic",
    "เชื้อ: เอเชีย → Klebsiella pneumoniae (hypervirulent, DM, อาจมี endophthalmitis หรือ meningitis); ตะวันตก → E. coli, polymicrobial, anaerobe (B. fragilis), Streptococcus anginosus group; SBE → Streptococcus, Staphylococcus; HIV → Candida",
    "อาการ: ไข้ RUQ pain ตับโตกดเจ็บ; lab: WBC, ALP, CRP สูง; imaging: US ก่อน (hypoechoic ขอบไม่เรียบ) แล้ว CT (hypodense + rim enhancement ± gas)",
    "Treatment: IV antibiotics (3rd-generation cephalosporin + metronidazole) รวมราว 4–6 สัปดาห์ + drainage — percutaneous needle aspiration หรือ catheter drainage (catheter เหมาะกับก้อน &gt;5 cm หรือหลายช่อง); surgical drainage เมื่อ percutaneous ล้มเหลว, rupture, หนองข้นหลายช่อง หรือต้องแก้ต้นเหตุในช่องท้อง",
    "Amebic abscess: Entamoeba histolytica, ชายวัยทำงาน ดื่มสุรา, ก้อนเดี่ยวที่ right lobe, หนองแบบ anchovy paste, serology บวก; รักษา metronidazole + luminal agent; เจาะดูดเฉพาะก้อนใหญ่มาก, left lobe ใกล้ pericardium, ไม่ตอบสนองต่อยาใน 3–5 วัน หรือแยกจาก pyogenic ไม่ได้",
    "ไทย: melioidosis (Burkholderia pseudomallei) ในภาคอีสาน เกษตรกร DM → ฝีเล็กหลายก้อนในตับและม้าม (honeycomb หรือ Swiss cheese appearance); รักษาด้วย ceftazidime หรือ meropenem แล้วตามด้วย co-trimoxazole",
    "ดูข้อ 41, 56, 57 (liver mass อื่น ๆ)"],
  notes:"รุ่นพี่วง <b>A</b> (เลขข้อไฮไลต์เหลือง = ไม่ชัวร์). แปะสไลด์ liver abscess — Organism: E. coli, B. fragilis; Asia → Klebsiella; SBE → Streptococcus, Staphylococcus; HIV → Candida (มีลายมือเล็ก ๆ กำกับข้าง organism อ่านไม่ชัด); CT: low attenuation complex hypodense mass with peripheral or rim enhancement",
  mnemonic:"ฝีตับไทย: เบาหวาน → Klebsiella; ชาวนาอีสาน → melioidosis; ชายดื่มเหล้า ก้อนเดียว → amebic",
  guide:"Sabiston Textbook of Surgery 21st ed. 2022 — The Liver (hepatic abscess)",
  opinion:"เห็นด้วยกับคีย์ A เมื่อมีข้อมูลทางคลินิก (มั่นใจสูง). ต้นฉบับให้แค่ 'Pale, rim enhance 10 cm, mix-solid, cystic' ซึ่งเข้าได้ทั้ง abscess และเนื้องอกที่มี hemorrhage หรือ necrosis (ซึ่งก็ heterogeneous และมีขอบ enhance ได้) รุ่นพี่จึงไฮไลต์ว่าไม่ชัวร์ — จึงเติมไข้, RUQ pain 1 สัปดาห์ และ leukocytosis. ถ้า 'Pale' ในต้นฉบับหมายถึงผู้ป่วยซีด + ปวดเฉียบพลัน + Hb ลดในผู้ป่วย cirrhosis หรือกินยาคุม จะตอบ tumor hemorrhage",
  variants:["Thai rice farmer with DM, fever, multiple small liver and splenic abscesses → melioidosis","Young man, single right-lobe abscess, anchovy-paste aspirate → amebic liver abscess, metronidazole","Liver abscess 8 cm not improving with IV antibiotics → percutaneous catheter drainage"]}),
A({page:10, page2:10, orig:"50", kimg:KI("50"),
  stem:"Which of the following does not indicate the severity of acute pancreatitis?",
  gray:"50. อันไหนบอกseverity ของ acute pan ไม่ได้ — A. Amylase B. WBC count C. Glucose D. Hypocalcemia",
  opts:["Amylase","WBC count","Glucose","Hypocalcemia","Blood urea nitrogen"],
  ans:0, key:"A Amylase"+KS,
  interp:"ถามตัวแปรที่ใช้วินิจฉัยแต่ไม่ได้บอกความรุนแรงของ acute pancreatitis",
  why:"<b>Amylase</b> (และ lipase) ใช้ <b>วินิจฉัย</b> (≥3 เท่าของ upper limit of normal) แต่ระดับไม่สัมพันธ์กับความรุนแรงหรือ prognosis และไม่ต้องตรวจซ้ำเพื่อติดตาม; ส่วน WBC, glucose (Ranson on admission), calcium (Ranson ที่ 48 ชม.) และ BUN (BISAP, Ranson ที่ 48 ชม.) อยู่ใน scoring system ที่ใช้ประเมินความรุนแรง",
  wrong:[
    "WBC count: Ranson on admission (&gt;16,000 non-gallstone, &gt;18,000 gallstone) และเป็นส่วนหนึ่งของ SIRS ใน BISAP — จะเป็นคำตอบถ้าถามตัวที่ไม่อยู่ใน Ranson criteria ช่วง 48 ชม.",
    "Glucose: Ranson on admission (&gt;200 mg/dL non-gallstone, &gt;220 gallstone) — จะเป็นคำตอบถ้าถามตัวที่ไม่อยู่ใน BISAP",
    "Hypocalcemia: Ranson ที่ 48 ชม. (Ca &lt;8 mg/dL) สะท้อน fat saponification และความรุนแรง — จะเป็นคำตอบถ้าถามตัวที่ไม่อยู่ใน Ranson on admission",
    "Blood urea nitrogen: BISAP (BUN &gt;25 mg/dL) และ Ranson ที่ 48 ชม. (BUN เพิ่ม &gt;5 mg/dL); BUN ที่สูงขึ้นใน 24 ชม. แรกทำนาย mortality — จะเป็นคำตอบถ้าถามตัวที่ไม่อยู่ใน Ranson on admission"],
  trap:"คิดว่า amylase หรือ lipase ยิ่งสูงยิ่งรุนแรง — ไม่จริง; และ amylase อาจปกติได้ใน hypertriglyceridemia-induced หรือ alcohol-related pancreatitis ที่มาช้า (lipase ไวกว่า)",
  summary:[
    "Diagnosis (Revised Atlanta 2012): ≥2 ใน 3 — epigastric pain ร้าวไปหลัง, lipase หรือ amylase ≥3×ULN, imaging (CECT, MRI, US) เข้าได้",
    "Ranson non-gallstone on admission: age &gt;55, WBC &gt;16,000, glucose &gt;200 mg/dL, LDH &gt;350 IU/L, AST &gt;250 IU/L; ภายใน 48 ชม.: Hct ลด &gt;10%, BUN เพิ่ม &gt;5 mg/dL, Ca &lt;8 mg/dL, PaO2 &lt;60 mmHg, base deficit &gt;4 mEq/L, fluid sequestration &gt;6 L; ≥3 ข้อ = severe (gallstone version ใช้ age &gt;70, WBC &gt;18,000, glucose &gt;220, LDH &gt;400)",
    "BISAP (ภายใน 24 ชม.): BUN &gt;25 mg/dL, Impaired mental status, SIRS, Age &gt;60, Pleural effusion; ≥3 = mortality สูง",
    "Revised Atlanta severity: mild = ไม่มี organ failure และไม่มี local หรือ systemic complication; moderately severe = transient organ failure &lt;48 ชม. และ/หรือ local complication หรือ comorbidity กำเริบ; severe = persistent organ failure &gt;48 ชม. (modified Marshall score ≥2 ในระบบหายใจ หัวใจ หรือไต)",
    "Marker อื่น: Hct &gt;44% แรกรับ, CRP &gt;150 mg/L ที่ 48 ชม., APACHE II ≥8, CT severity index (Balthazar + necrosis), obesity",
    "Local complications: APFC (&lt;4 สัปดาห์) → pseudocyst (&gt;4 สัปดาห์ ไม่มี necrosis); ANC (&lt;4 สัปดาห์) → walled-off necrosis (&gt;4 สัปดาห์); infected necrosis → step-up approach (antibiotics → percutaneous หรือ endoscopic drainage → necrosectomy)",
    "ดูข้อ 13, 58 (pancreas)"],
  notes:"รุ่นพี่ขีด <b>A</b> (Amylase). แปะสไลด์ Ranson Prognostic Criteria for Non-Gallstone Pancreatitis และ for Gallstone Pancreatitis (Box 55-1, 55-2; มีลายมือเล็ก ๆ บนสไลด์อ่านไม่ชัด), สไลด์ BISAP scoring system (BUN &gt;25 mg/dL, impaired mental status, SIRS, age &gt;60, pleural effusion) และสไลด์ Atlanta Criteria for Acute Pancreatitis (Box 55-3: organ failure, systemic complications, local complications — necrosis, abscess, pseudocyst) (สไลด์ BISAP และ Atlanta ต่อไปถึงภาพของข้อถัดไป)",
  mnemonic:"BISAP = BUN, Impaired mental, SIRS, Age, Pleural effusion; 'Amylase วินิจฉัย ไม่ได้วัดความรุนแรง'",
  guide:"Revised Atlanta Classification of Acute Pancreatitis 2012; ACG Clinical Guideline: Management of Acute Pancreatitis 2024",
  opinion:"",
  variants:["Which is a component of BISAP? → BUN &gt;25 mg/dL","Which Ranson criterion is assessed at 48 hours? → serum Ca &lt;8 mg/dL","Severe acute pancreatitis by revised Atlanta → persistent organ failure &gt;48 ชม."]}),
A({page:10, page2:10, orig:"51", kimg:KI("51"),
  stem:"Which of the following indicates malnutrition?",
  gray:"51 ข้อไหนคือmalnutrition — A. Glucose&lt;90 B. นน&lt;50kg C. นนลด 10%ใน3เดือน",
  opts:["Glucose below 90 mg/dL","Body weight below 50 kg","10% weight loss in 3 months","Serum albumin 3.8 g/dL","BMI 22 kg/m2"],
  ans:2, key:"C 10% weight loss in 3 months"+KS,
  interp:"ถามเกณฑ์ที่บอกภาวะทุพโภชนาการ — ตัวชี้วัดที่ดีที่สุดคืออัตราการลดน้ำหนักโดยไม่ตั้งใจเทียบกับเวลา",
  why:"GLIM 2019 phenotypic criterion: unintentional weight loss &gt;5% ภายใน 6 เดือน หรือ &gt;10% เกิน 6 เดือน → ลด <b>10% ใน 3 เดือน</b>เข้าเกณฑ์และจัดเป็น severe (stage 2: &gt;10% ภายใน 6 เดือน); ASPEN/AND 2012 ในโรคเฉียบพลัน ลด &gt;7.5% ใน 3 เดือน = severe malnutrition; ESPEN surgery ถือว่าลด &gt;10–15% ใน 6 เดือนเป็น severe nutritional risk ก่อนผ่าตัด",
  wrong:[
    "Glucose below 90 mg/dL: อยู่ในช่วงปกติของ fasting glucose และระดับน้ำตาลไม่ใช่เกณฑ์วินิจฉัย malnutrition ใน guideline ใด — ไม่มีบริบทที่เป็นคำตอบ",
    "Body weight below 50 kg: น้ำหนักสัมบูรณ์ไม่บอกอะไรถ้าไม่รู้ส่วนสูง (คนสูง 150 cm หนัก 48 kg มี BMI ราว 21 ปกติ) — จะเป็นคำตอบถ้าเปลี่ยนเป็น BMI &lt;18.5 kg/m2",
    "Serum albumin 3.8 g/dL: เป็นค่าปกติ และ albumin เป็น negative acute phase reactant สะท้อน inflammation มากกว่า nutrition — ESPEN ใช้ albumin &lt;3.0 g/dL (ไม่มีโรคตับหรือไต) เป็นเกณฑ์ severe nutritional risk ก่อนผ่าตัด จึงจะเป็นคำตอบถ้า albumin &lt;3.0",
    "BMI 22 kg/m2: ปกติ — GLIM ใช้ BMI &lt;20 (อายุ &lt;70) หรือ &lt;22 (≥70) ในคนตะวันตก และ &lt;18.5 (อายุ &lt;70) หรือ &lt;20 (≥70) ในเอเชีย; จะเป็นคำตอบถ้า BMI &lt;18.5 ในคนเอเชียอายุ &lt;70"],
  trap:"ใช้น้ำหนักสัมบูรณ์หรือ albumin ตัดสิน — สิ่งที่สำคัญคืออัตราการลดน้ำหนักโดยไม่ตั้งใจ ซึ่งบอกทั้งการวินิจฉัยและความรุนแรง",
  summary:[
    "ขั้นตอน: screening (NRS-2002, MUST, SPENT ในไทย) → assessment; GLIM 2019 วินิจฉัยเมื่อมี ≥1 phenotypic + ≥1 etiologic criterion",
    "GLIM phenotypic: weight loss &gt;5% ใน 6 เดือน หรือ &gt;10% เกิน 6 เดือน; low BMI; reduced muscle mass; etiologic: กินได้ ≤50% ของความต้องการ &gt;1 สัปดาห์ หรือกินลดลงใด ๆ &gt;2 สัปดาห์ หรือ malabsorption; inflammation หรือ disease burden",
    "GLIM severe (stage 2): weight loss &gt;10% ใน 6 เดือน หรือ &gt;20% เกิน 6 เดือน",
    "ESPEN surgery: severe nutritional risk = weight loss &gt;10–15% ใน 6 เดือน, BMI &lt;18.5, SGA grade C หรือ NRS ≥5, albumin &lt;30 g/L (ไม่มี hepatic หรือ renal dysfunction) → nutrition therapy 7–14 วันก่อนผ่าตัดใหญ่ (enteral ก่อน)",
    "SPENT ของไทย 4 คำถาม: น้ำหนักลดโดยไม่ตั้งใจใน 6 เดือน, กินน้อยลงกว่าปกติ &gt;7 วัน, BMI &lt;18.5 หรือ ≥25, มีภาวะวิกฤตหรือกึ่งวิกฤต; ตอบใช่ ≥2 ข้อ → ประเมินต่อด้วย NAF หรือ NT",
    "Albumin และ prealbumin สะท้อน inflammation มากกว่าภาวะโภชนาการ แต่ albumin ต่ำทำนาย postoperative complication",
    "Refeeding syndrome ในผู้ป่วยขาดอาหารรุนแรง: hypophosphatemia, hypokalemia, hypomagnesemia, thiamine deficiency → เริ่มให้อาหารช้า ๆ + thiamine"],
  notes:"รุ่นพี่ขีด <b>C</b> (นน ลด 10% ใน 3 เดือน) ด้วยหมึกแดง. แปะสไลด์ 'แนวทางปฏิบัติของการคัดกรองและการประเมินภาวะโภชนาการที่เหมาะสมสำหรับประเทศไทย': ผู้ป่วยทุกรายที่รับไว้ → คัดกรองด้วย 4 คำถาม (1) น้ำหนักตัวลดลงโดยไม่ได้ตั้งใจในช่วง 6 เดือน (2) ได้รับอาหารน้อยกว่าที่เคยได้ เกิน 7 วัน (3) ดัชนีมวลกาย &lt;18.5 หรือ ≥25 (4) มีภาวะวิกฤตหรือกึ่งวิกฤต → ใช่ ≥2 ข้อ ประเมินต่อด้วย NAF หรือ NT → ความเสี่ยงต่ำ (NAF A, NT 1–2) ประเมินซ้ำใน 7 วัน; ความเสี่ยงปานกลาง (NAF B, NT 3); ความเสี่ยงสูง (NAF C, NT 4) → ส่งนักกำหนดอาหาร/ทีมโภชนบำบัด (ข้อความในกล่องผลลัพธ์อ่านไม่ชัดทั้งหมด); มุมขวาบนเป็นสไลด์ BISAP และ Atlanta ของข้อก่อนหน้า",
  mnemonic:"'ลดเร็ว ลดมาก' สำคัญกว่าน้ำหนักตอนนี้",
  guide:"GLIM Criteria for the Diagnosis of Malnutrition 2019; ESPEN Guideline: Clinical Nutrition in Surgery 2021; ASPEN/AND Consensus Statement on Adult Malnutrition 2012",
  opinion:"",
  variants:["Preoperative patient lost 12% in 4 months with albumin 2.8 g/dL → เลื่อนผ่าตัด 7–14 วันเพื่อให้ nutrition therapy","Which is not a GLIM phenotypic criterion? → serum albumin","Thai SPENT positive 2 items → ประเมินต่อด้วย NAF หรือ NT"]}),
A({page:11, page2:11, orig:"52", kimg:KI("52"),
  stem:"A patient with diabetes takes aspirin 325 mg daily for primary prevention and has no history of coronary stent placement. He is scheduled for elective hernia repair. What is the most appropriate plan for the aspirin?",
  gray:"52.DM,on ยา ASA gr 5จะ elective hernia — A. หยุด 7 วัน B. ไม่ต้องหยุด C. Bridgingด้วย",
  opts:["Stop 7 days before surgery","Continue without interruption","Bridge with heparin","Stop 1 day before surgery","Switch to clopidogrel"],
  ans:0, key:"A Stop 7 days before surgery"+KS, flag:"⚠ เติม primary prevention + no coronary stent (ต้นฉบับไม่บอกข้อบ่งชี้ของ aspirin); guideline ปัจจุบันยอมให้ continue aspirin ได้ในหลายกรณี — ดู opinion",
  interp:"ASA gr 5 = aspirin 5 grains = 325 mg; ใช้เพื่อ primary prevention (ไม่มี CAD, stent, stroke) → ประโยชน์ต่อหัวใจช่วงผ่าตัดน้อย แต่เพิ่ม bleeding; elective surgery จึงหยุดได้",
  why:"Aspirin acetylate COX-1 แบบ <b>irreversible</b> → platelet เสียการทำงานตลอดอายุ (7–10 วัน); ร่างกายสร้าง platelet ใหม่ราว 10% ต่อวัน → หยุด <b>7 วัน</b>ก่อนผ่าตัดให้ platelet ใหม่ทำงานได้พอ; POISE-2 (2014) พบว่า perioperative aspirin ไม่ลด death หรือ MI แต่เพิ่ม major bleeding ใน noncardiac surgery → ในกลุ่ม primary prevention ที่ไม่มี stent การหยุดยาจึงสมเหตุสมผล แล้วเริ่มกลับเมื่อ hemostasis ดี (ราว 24 ชม. หลังผ่าตัด)",
  wrong:[
    "Continue without interruption: เหมาะกับ secondary prevention (CAD, MI, stroke, PAD) และผู้ป่วยมี coronary stent (ห้ามหยุด aspirin เพราะเสี่ยง stent thrombosis) — จะเป็นคำตอบถ้าโจทย์บอกว่ากิน aspirin เพราะเคยใส่ stent หรือเป็น secondary prevention ที่ bleeding risk ของการผ่าตัดยอมรับได้",
    "Bridge with heparin: bridging ใช้กับ warfarin ในผู้ป่วย thrombotic risk สูง ไม่ใช่ antiplatelet; heparin ไม่ทดแทนฤทธิ์ต้าน platelet และเพิ่ม bleeding — ไม่มีบริบทที่ถูกสำหรับ aspirin",
    "Stop 1 day before surgery: สั้นเกินไป เพราะ platelet ส่วนใหญ่ยังถูกยับยั้งแบบถาวร — จะเป็นคำตอบสำหรับ NSAID แบบ reversible ฤทธิ์สั้นอย่าง ibuprofen",
    "Switch to clopidogrel: clopidogrel ยับยั้ง P2Y12 แบบ irreversible เช่นกัน ต้องหยุด 5 วัน และ bleeding risk ไม่ได้น้อยกว่า — clopidogrel ใช้แทน aspirin เมื่อแพ้ aspirin ในข้อบ่งชี้ secondary prevention ไม่ใช่เพื่อเตรียมผ่าตัด"],
  trap:"คิดว่า bridging ใช้กับยาต้านการแข็งตัวของเลือดทุกชนิด; หรือหยุด aspirin ในผู้ป่วยมี coronary stent ซึ่งอันตราย",
  summary:[
    "Aspirin: irreversible COX-1 inhibitor → ↓TXA2 ฤทธิ์อยู่ตลอดอายุ platelet 7–10 วัน; ถ้าต้องหยุดให้หยุดราว 7 วัน (ACCP 2022: ≤7 วันก่อนผ่าตัด)",
    "Primary prevention: ประโยชน์ช่วงผ่าตัดไม่คุ้ม bleeding → หยุดได้ (POISE-2); secondary prevention: ส่วนใหญ่ continue ยกเว้นผ่าตัดที่เลือดออกในที่ปิด (intracranial, spinal canal, posterior chamber ของตา)",
    "Coronary stent: elective noncardiac surgery ควรเลื่อนจนครบช่วง DAPT ขั้นต่ำ (BMS ≥30 วัน, DES ≥6 เดือนตาม ACC/AHA 2016); ช่วงผ่าตัด continue aspirin หยุดเฉพาะ P2Y12 inhibitor",
    "P2Y12 inhibitor: clopidogrel หยุด 5 วัน, ticagrelor 3–5 วัน, prasugrel 7 วัน",
    "Warfarin: หยุด 5 วัน; bridging เฉพาะ high thrombotic risk (mechanical mitral valve, VTE หรือ stroke ภายใน 3 เดือน)",
    "DOAC: หยุด 1–2 วันตาม bleeding risk ของการผ่าตัด (นานขึ้นถ้าไตเสื่อมสำหรับ dabigatran) ไม่ต้อง bridge (PAUSE trial)",
    "ดูข้อ 45, 75 (warfarin กับเลือดออกฉุกเฉิน)"],
  notes:"รุ่นพี่ขีดเส้นใต้ 'ASA gr 5' และเขียน '<b>ASA gr 5 = 325 mg</b>' (aspirin 5 grains); ขีด <b>A</b> (หยุด 7 วัน) ด้วยหมึกแดง",
  mnemonic:"Aspirin irreversible → หยุด 7 วัน ≈ อายุ platelet; มี stent ห้ามหยุด",
  guide:"ACCP (CHEST) Perioperative Management of Antithrombotic Therapy 2022; ESC 2022 Guidelines on Cardiovascular Assessment and Management of Patients Undergoing Non-cardiac Surgery; POISE-2 (NEJM 2014)",
  opinion:"คงคีย์ A ความมั่นใจปานกลาง. ⚠ ต้นฉบับไม่บอกว่ากิน aspirin เพื่ออะไร — ถ้าเป็น secondary prevention หรือมี coronary stent คำตอบจะเป็น continue (B) จึงเติม primary prevention + no stent. ข้อควรรู้: ACCP 2022 แนะนำแบบ conditional (หลักฐานต่ำ) ให้ continue aspirin มากกว่าหยุดในผู้ป่วย noncardiac surgery และถ้าจะหยุดให้หยุด ≤7 วันก่อนผ่าตัด; ESC 2022 ให้พิจารณาหยุด aspirin ในผู้ที่ไม่เคยทำ PCI ถ้า bleeding risk มากกว่า ischemic risk. ดังนั้นในทางปฏิบัติ hernia repair ซึ่ง bleeding risk ต่ำ การ continue ก็ยอมรับได้ แต่ในข้อสอบที่เป็น primary prevention และตัวเลือกอื่นเป็น bridging หรือหยุด 1 วัน คำตอบ A สอดคล้องกับสรีรวิทยาของ platelet และผลของ POISE-2",
  variants:["DES placed 2 months ago, elective hernia repair → เลื่อนผ่าตัด continue DAPT","Aspirin for secondary prevention after MI, elective cholecystectomy → continue aspirin","Clopidogrel before elective surgery → หยุด 5 วัน"]}),
A({page:11, page2:11, orig:"53", kimg:KI("53"),
  stem:"Which of the following does not help postoperative recovery?",
  gray:"53. ข้อไหนไม่ช่วยใน post op recovery. — A. Epidural anesthesia B. รีบเอาNGออก C. O2 supplement D. Non-opoid E. Post op gum chewing",
  opts:["Epidural anesthesia","Early removal of nasogastric tube","Routine supplemental oxygen","Non-opioid analgesia","Postoperative gum chewing"],
  ans:2, key:"C Routine supplemental oxygen"+KS,
  interp:"ถาม component ของ ERAS (enhanced recovery after surgery) — ข้อไหนไม่ได้อยู่ใน pathway",
  why:"ทุกช้อยยกเว้น O2 เป็น ERAS element ที่มีหลักฐาน; <b>supplemental oxygen แบบ routine</b> หลังผ่าตัดไม่ได้ช่วยให้ฟื้นตัวเร็วขึ้น ให้เฉพาะเมื่อมีข้อบ่งชี้ (SpO2 ต่ำ) — ตามที่รุ่นพี่เขียน 'only in certain case' เพราะ hypoxemia หลังผ่าตัดพบน้อยลงมากเมื่อใช้ opioid-sparing analgesia และยาดมสลบออกฤทธิ์สั้น; การติดสาย O2 ยังทำให้ผู้ป่วยลุกเดินช้า. (แยกจาก intraoperative FiO2 80% ที่ WHO แนะนำเพื่อลด SSI ซึ่งเป็นคนละประเด็น)",
  wrong:[
    "Epidural anesthesia: thoracic epidural ใน open abdominal surgery ให้ analgesia ดี ลด opioid, ลด ileus และ pulmonary complication → เป็น ERAS element ใน open surgery — จะเป็นคำตอบถ้าถามสิ่งที่ไม่จำเป็นใน laparoscopic ERAS (ใช้ spinal หรือ TAP block แทนได้)",
    "Early removal of nasogastric tube: ERAS ไม่ใส่ NG routine หรือถอดก่อนตื่น → ลด pneumonia, atelectasis และกินได้เร็ว (รุ่นพี่: ลด complication of prolonged NG) — จะเป็นคำตอบถ้าเปลี่ยนเป็น routine prolonged NG decompression",
    "Non-opioid analgesia: multimodal opioid-sparing (paracetamol, NSAID, regional block) ลด ileus, PONV และอาการง่วง → ลุกเดินเร็ว — จะเป็นคำตอบถ้าเปลี่ยนเป็น routine high-dose opioid",
    "Postoperative gum chewing: sham feeding กระตุ้น cephalic-vagal reflex → flatus และ bowel movement เร็วขึ้น มีหลักฐานจาก meta-analysis และอยู่ใน ERAS 2018 (รุ่นพี่ให้ ±) — ถ้าไม่มีช้อย O2 บางคนอาจเลือกข้อนี้เพราะหลักฐานอ่อนกว่าข้ออื่น"],
  trap:"คิดว่าให้ O2 'ไม่เสียหาย' จึงต้องช่วย — สิ่งที่ไม่มีหลักฐานว่าเร่ง recovery ไม่ใช่ ERAS element; ในทางกลับกัน gum chewing ที่ดูแปลกกลับมีหลักฐาน",
  summary:[
    "ERAS preop: counseling, เลิกบุหรี่และสุรา, prehabilitation, nutrition optimization, ไม่งดอาหารนาน (solid 6 ชม., clear fluid 2 ชม.), carbohydrate loading, ไม่ให้ long-acting sedative premedication",
    "ERAS intraop: minimally invasive surgery, short-acting anesthetic, goal-directed หรือ near-zero fluid balance, normothermia, PONV prophylaxis, หลีกเลี่ยง drain และ NG routine",
    "ERAS postop: early oral intake, early mobilization, ถอด urinary catheter เร็ว, multimodal opioid-sparing analgesia, glycemic control, gum chewing",
    "Analgesia: open → thoracic epidural; laparoscopic → spinal, TAP block, wound infiltration; ร่วมกับ paracetamol + NSAID ตามเวลา",
    "ป้องกัน postoperative ileus: เลี่ยง fluid overload และ opioid, MIS, gum chewing, alvimopan, early feeding",
    "Oxygen ให้ตามข้อบ่งชี้ ไม่ต้อง routine; intraoperative FiO2 80% เพื่อลด SSI (WHO 2016) เป็นคนละเรื่องกับ recovery",
    "ดูข้อ 53, 55 (perioperative care)"],
  notes:"ลายมือรุ่นพี่: A Epidural anesthesia '✓ ลด pain → active!'; B รีบเอา NG ออก '✓ ลด complication of prolonged NG'; ขีด <b>C</b> O2 supplement '— <b>only in certain case</b> (incidence ของ hypoxemia ในระยะหลัง ๆ ต่ำลงมาก)'; D Non-opioid ✓; E Post op gum chewing '(±) ✓ ช่วยให้ bowel function กลับมาไวขึ้น [มีหลายเปเปอร์บอก แต่ยังไม่เคยเห็นที่ไทย]'",
  mnemonic:"ERAS = 'ลุกไว กินไว ถอดสายไว ปวดน้อยโดยไม่พึ่ง opioid'",
  guide:"ERAS Society Guidelines for Perioperative Care in Elective Colorectal Surgery 2018; WHO Global Guidelines for the Prevention of Surgical Site Infection 2016 (updated 2018)",
  opinion:"เห็นด้วยกับคีย์ C (มั่นใจค่อนข้างสูง) — gum chewing ที่รุ่นพี่ให้ ± มีหลักฐานว่าลดระยะ ileus และอยู่ใน ERAS 2018 จึงไม่ใช่คำตอบ",
  variants:["Which is an ERAS element? → carbohydrate loading 2 ชม. ก่อนผ่าตัด","Which increases postoperative ileus? → IV fluid เกินและ opioid","Analgesia for laparoscopic colectomy under ERAS → TAP block หรือ spinal + multimodal oral analgesics"]}),
A({page:11, page2:11, orig:"54", kimg:KI("54"),
  stem:"Which of the following is not an advantage of minimally invasive surgery?",
  gray:"54. MIS ไม่ใช่ — A. Recoveryเร็ว B. เจ็บแผลน้อย C. ดมยาสั้นกว่า",
  opts:["Faster recovery","Less wound pain","Shorter anesthesia time","Better cosmesis","Fewer wound complications"],
  ans:2, key:"C Shorter anesthesia time"+KS,
  interp:"ถามข้อที่ไม่ใช่ข้อดีของการผ่าตัดแบบ minimally invasive (laparoscopic, robotic)",
  why:"MIS มักใช้เวลาผ่าตัดและ<b>ดมยานานกว่า</b> open surgery (setup, pneumoperitoneum, learning curve) ไม่ใช่สั้นกว่า; ข้อดีจริงมาจากแผลเล็ก: ปวดน้อย ใช้ opioid น้อย ฟื้นตัวและกลับบ้านเร็ว SSI และ incisional hernia น้อย adhesion น้อย แผลสวย และ stress response น้อยกว่า",
  wrong:[
    "Faster recovery: เป็นข้อดีหลัก (ileus สั้น, LOS สั้น, กลับไปทำงานเร็ว) — จะไม่เป็นข้อดีเมื่อต้อง convert to open หรือเกิด complication",
    "Less wound pain: แผลเล็กปวดน้อยกว่าและใช้ opioid น้อยกว่า — เป็นข้อดีจริง; ข้อที่อาจถูกถามแทนคือ shoulder tip pain จาก CO2 ระคายกะบังลม",
    "Better cosmesis: แผลเล็กหลายแผลหรือ single-incision ดูดีกว่า — เป็นข้อดีจริง",
    "Fewer wound complications: SSI และ incisional hernia น้อยกว่า open — เป็นข้อดีจริง แต่ยังเกิด port-site hernia ได้ (port ≥10 mm ต้องเย็บปิด fascia)"],
  trap:"คิดว่าแผลเล็กแปลว่าผ่าเร็ว — ตรงกันข้าม MIS มักใช้เวลานานกว่าโดยเฉพาะช่วงเรียนรู้",
  summary:[
    "ข้อดี MIS: ปวดน้อย, opioid น้อย, ileus สั้น, LOS สั้น, กลับไปทำงานเร็ว, SSI น้อย, incisional hernia น้อย, adhesion น้อย, cosmesis ดี, ภาพขยายชัด",
    "ข้อเสีย: operative และ anesthesia time นานขึ้น, ค่าอุปกรณ์สูง, ขาด tactile feedback, ภาพ 2D (ยกเว้น 3D หรือ robot), learning curve, trocar injury (vascular, bowel) ขณะ entry, port-site hernia, CO2 embolism",
    "Pneumoperitoneum CO2 12–15 mmHg: hypercarbia + respiratory acidosis, ↓ venous return และ cardiac output (โดยเฉพาะถ้า hypovolemic), ↑ SVR, ↓ FRC และ ↑ airway pressure, ↓ renal blood flow และ urine output, ↑ ICP",
    "Relative contraindications: severe cardiopulmonary disease (EF ต่ำมาก), raised ICP, uncorrected coagulopathy, hemodynamic instability, adhesion มาก",
    "Pregnancy: laparoscopy ทำได้อย่างปลอดภัยทุกไตรมาส (SAGES 2017) ใช้ pressure 10–15 mmHg และ left lateral tilt",
    "ดูข้อ 15, 54 (ข้อห้าม laparoscopy และ ERAS)"],
  notes:"รุ่นพี่ขีด <b>C</b> (ดมยาสั้นกว่า) ด้วยหมึกแดง — ไม่มีลายมืออื่น",
  mnemonic:"MIS: แผลเล็ก แต่เวลาไม่เล็ก",
  guide:"Sabiston Textbook of Surgery 21st ed. 2022 — Minimally Invasive Surgery; SAGES Guidelines for the Use of Laparoscopy During Pregnancy 2017",
  opinion:"",
  variants:["Physiologic effect of CO2 pneumoperitoneum → ↓ venous return และ hypercarbia","Port ≥10 mm → ต้องเย็บปิด fascia เพื่อป้องกัน port-site hernia","Contraindication to laparoscopy → severe heart failure EF 15%"]}),
A({page:11, page2:11, orig:"55", kimg:KI("55"),
  stem:"A 28-year-old woman has been taking oral contraceptive pills for 10 years. Imaging shows a liver mass with rapid washout. What is the most likely diagnosis?",
  gray:"55. ผญอายุ 28 กินยาคุม 10 ปี rapid wash out — A. Hepatic adenoma B. FNH C. HCC",
  opts:["Hepatic adenoma","Focal nodular hyperplasia","Hepatocellular carcinoma","Hepatic hemangioma","Liver metastasis"],
  ans:0, key:"A Hepatic adenoma"+KS,
  interp:"หญิงอายุน้อย + กินยาคุมนาน + liver mass → hepatocellular adenoma; washout ไม่ได้เฉพาะ HCC",
  why:"Hepatocellular adenoma สัมพันธ์กับ estrogen (ยาคุม — เสี่ยงมากขึ้นตามระยะเวลาและขนาดยา), anabolic steroid, glycogen storage disease, obesity; imaging: arterial hyperenhancement และ washout ได้ (โดยเฉพาะ hypointense ใน hepatobiliary phase ของ gadoxetate MRI) ซึ่ง<b>ซ้อนกับ HCC</b> — ตามที่รุ่นพี่เขียน แยกกันด้วยประวัติ: ไม่มี cirrhosis หรือ HBV + หญิงสาวกินยาคุม → adenoma",
  wrong:[
    "Focal nodular hyperplasia: หญิงสาวเหมือนกันแต่ยาคุมไม่ใช่สาเหตุ; imaging: homogeneous arterial enhancement, iso ใน portal และ delayed phase (ไม่ washout), central stellate scar, iso หรือ hyper ใน hepatobiliary phase — จะเป็นคำตอบเมื่อมี central scar และไม่มี washout",
    "Hepatocellular carcinoma: APHE + washout + capsule ในผู้ป่วย cirrhosis หรือ chronic HBV (LI-RADS 5) — จะเป็นคำตอบเมื่อมี risk factor เช่น HBV, HCV, cirrhosis, AFP สูง",
    "Hepatic hemangioma: benign liver tumor ที่พบบ่อยที่สุด; peripheral nodular discontinuous enhancement แล้ว centripetal fill-in, T2 สว่างมาก ไม่มี washout — จะเป็นคำตอบเมื่อเห็น pattern นี้",
    "Liver metastasis: hypovascular (colorectal) เป็น rim enhancement หรือ target; hypervascular (NET, RCC, melanoma, thyroid, breast) อาจ washout ได้ — จะเป็นคำตอบเมื่อมีประวัติมะเร็งหรือมีหลายก้อน"],
  trap:"เห็น rapid washout แล้วตอบ HCC ทันที — washout ต้องตีความร่วมกับ risk factor; LI-RADS ใช้ได้เฉพาะ high-risk population",
  summary:[
    "Hepatocellular adenoma: หญิงอายุ 20–40 กินยาคุม, anabolic steroid, GSD type I, obesity หรือ metabolic syndrome; ความเสี่ยงหลักคือ hemorrhage หรือ rupture และ malignant transformation (ราว 5%)",
    "Subtypes: HNF1α-inactivated (มีไขมันในก้อน signal drop บน opposed-phase MRI, malignant risk ต่ำ), inflammatory (พบบ่อยที่สุด, T2 สว่าง, atoll sign, เลือดออกง่าย), β-catenin-activated (malignant transformation สูงสุด, ผู้ชาย, ใช้ steroid), sonic hedgehog (เลือดออก), unclassified",
    "Management (EASL 2016): หยุดยาคุม + ลดน้ำหนัก แล้วตรวจซ้ำที่ 6 เดือน; resection เมื่อยัง ≥5 cm หลังปรับ lifestyle, ทุกขนาดในผู้ชาย, β-catenin mutation หรือโตขึ้น; เลือดออก → transarterial embolization แล้วผ่าตัดภายหลัง",
    "FNH: central scar ไม่มี malignant potential ไม่ต้องรักษาและไม่ต้องหยุดยาคุม",
    "HCC วินิจฉัยด้วย imaging ได้เฉพาะ high-risk (cirrhosis, chronic HBV, prior HCC): APHE + washout ± capsule (LI-RADS 5); นอกกลุ่มนี้ต้องใช้ pathology",
    "Hemangioma: centripetal fill-in, observe; ก้อนใหญ่มากอาจเกิด Kasabach-Merritt (พบน้อย)",
    "ดูข้อ 57 (โจทย์คู่กัน), 50"],
  notes:"รุ่นพี่ขีดเส้นใต้ '<b>กินยาคุม 10 ปี</b>'; ขีด <b>A</b>; ลากลูกศรจาก Hepatic adenoma และ HCC ไปที่ข้อความ '<b>imaging pattern เหมือนกัน (A-enhance, Rapid washout) แยกกันที่ Hx</b> — ถ้ามี cirrhosis, HBV history จะนึกถึง HCC มากกว่า'",
  mnemonic:"Adenoma = สาว + ยาคุม; FNH = Fine, No Harm, central scar",
  guide:"EASL Clinical Practice Guidelines on the Management of Benign Liver Tumours 2016; ACR LI-RADS v2018",
  opinion:"",
  variants:["Young woman with 7-cm adenoma persisting 6 months after stopping OCP → resection","Ruptured hepatic adenoma with hypotension → resuscitation + transarterial embolization","Young woman with central stellate scar and no washout → FNH, observe"]}),
A({page:11, page2:11, orig:"56", kimg:KI("56"),
  stem:"A patient with chronic hepatitis C infection has a liver mass with rapid washout. The surrounding liver parenchyma appears normal. What is the most likely diagnosis?",
  gray:"56. Chronic HCV, liver parenchyma normal , rapid wash out — A. HCC B. FNH C. Hepatic adenoma",
  opts:["Hepatocellular carcinoma","Focal nodular hyperplasia","Hepatic adenoma","Liver metastasis","Hepatic hemangioma"],
  ans:0, key:NK, flag:"⚠ ไม่มีคีย์ — รุ่นพี่ไม่ได้วงคำตอบ เขียนว่าแยกด้วย imaging ไม่ได้; ตอบ HCC ตาม risk factor (chronic HCV)",
  interp:"chronic HCV = risk factor ของ HCC + ก้อนที่มี washout; ข้อมูลว่าเนื้อตับดูปกติทำให้ลังเลระหว่าง HCC กับ adenoma",
  why:"Chronic HCV ก่อ HCC ส่วนใหญ่ผ่าน cirrhosis หรือ advanced fibrosis (F3) แต่ <b>imaging ไม่ไวต่อ fibrosis ระยะต้นถึงกลาง</b> 'ตับดูปกติ' จึงไม่ได้แปลว่าไม่มี fibrosis และ HCC ราว 1 ใน 5 เกิดในตับที่ไม่ใช่ cirrhosis; ก้อนที่ washout ในผู้ป่วยมี chronic viral hepatitis จึงต้องนึกถึง <b>HCC</b> ก่อน ขณะที่โจทย์ไม่มีปัจจัยของ adenoma (หญิงสาว ยาคุม steroid) — แต่ผู้ป่วย HCV ที่ไม่มี cirrhosis ไม่อยู่ใน LI-RADS population จึงควรยืนยันด้วย multiphasic MRI ± biopsy",
  wrong:[
    "Focal nodular hyperplasia: ไม่ washout มี central scar และพบในหญิงสาว — จะเป็นคำตอบเมื่อ incidental lesion ที่มี central stellate scar",
    "Hepatic adenoma: เนื้อตับปกติ + washout เข้าได้ (รุ่นพี่เขียนว่า 'favor Hep. adenoma') แต่โจทย์ไม่มีบริบทของ adenoma และ chronic HCV เป็น risk ที่ชัดกว่า — จะเป็นคำตอบเมื่อเป็นหญิงอายุน้อยกินยาคุมนานโดยไม่มี viral hepatitis (ข้อ 56)",
    "Liver metastasis: hypervascular metastasis washout ได้ แต่โจทย์ไม่มีประวัติมะเร็งและเป็นก้อนเดียว — จะเป็นคำตอบเมื่อมีประวัติ NET, RCC, melanoma หรือมีหลายก้อน",
    "Hepatic hemangioma: centripetal fill-in ไม่มี washout — จะเป็นคำตอบเมื่อเห็น peripheral nodular enhancement ที่ค่อย ๆ เติมเข้ากลาง"],
  trap:"ตีความ 'liver parenchyma normal' ว่าตัด HCC ทิ้งได้ — HCC เกิดในตับที่ไม่ใช่ cirrhosis ได้ (HBV, MASLD, HCV ที่มี advanced fibrosis) และ imaging ประเมิน fibrosis ไม่ไว",
  summary:[
    "HCC risk factors: cirrhosis ทุกสาเหตุ (HCV, alcohol, MASLD), chronic HBV แม้ไม่มี cirrhosis, aflatoxin, hemochromatosis; chronic HCV เสี่ยงสูงเมื่อมี F3 หรือ cirrhosis และความเสี่ยงลดลงแต่ไม่หมดหลัง SVR",
    "Surveillance (AASLD 2023): US ± AFP ทุก 6 เดือนใน cirrhosis และ chronic HBV กลุ่มเสี่ยง (เช่น ชายเอเชียอายุ ≥40, หญิง ≥50, มีประวัติ HCC ในครอบครัว)",
    "LI-RADS v2018 (CT หรือ MRI) ใช้ได้เฉพาะ cirrhosis, chronic HBV หรือเคยเป็น HCC: LR-5 = 10–19 mm APHE + nonperipheral washout หรือ threshold growth, หรือ ≥20 mm APHE + major feature ≥1 อย่าง (washout, capsule, threshold growth)",
    "นอก high-risk population (เช่น HCV ที่ไม่มี cirrhosis หรือตับปกติ) วินิจฉัย HCC จาก imaging อย่างเดียวไม่ได้ → MRI with hepatobiliary agent ± biopsy",
    "Adenoma กับ HCC: imaging คล้ายกัน (APHE + washout) แยกด้วยบริบท — หญิงสาวกินยาคุมตับปกติ → adenoma; ไวรัสตับอักเสบ, cirrhosis, AFP สูง → HCC",
    "Treatment HCC (BCLC 2022): very early หรือ early → resection (Child-Pugh A ไม่มี portal hypertension), ablation (≤3 cm), transplant (Milan: ก้อนเดียว ≤5 cm หรือ ≤3 ก้อนแต่ละก้อน ≤3 cm ไม่มี vascular invasion); intermediate → TACE; advanced → atezolizumab + bevacizumab",
    "ดูข้อ 56 (โจทย์คู่กัน), 24 (Milan criteria)"],
  notes:"รุ่นพี่<b>ไม่ได้วงคำตอบ</b> แต่ขีดเส้นใต้และเขียน: 'Chronic HCV' → '<b>favor HCC</b>'; 'liver parenchyma normal' (มี ?? ข้างคำว่า normal) → '<b>favor Hep. adenoma</b>'; ลากใต้ช้อย A–C ว่า '<b>แยกกันด้วย imaging ไม่ได้</b>'; และเขียนด้านล่างว่า '(chronic HCV ไม่น่าตับปกตินะ)'",
  mnemonic:"Pattern เหมือน แต่คนต่าง: ไวรัสหรือตับแข็ง → HCC, สาวกินยาคุม → adenoma",
  guide:"AASLD Practice Guidance on Prevention, Diagnosis, and Treatment of HCC 2023; ACR LI-RADS v2018 CT/MRI; BCLC Strategy 2022 Update",
  opinion:"⚠ ไม่มีคีย์ในไฟล์ — รุ่นพี่ไม่ได้วงคำตอบ แต่วิเคราะห์ว่า chronic HCV favor HCC ส่วนตับปกติ favor adenoma และแยกด้วย imaging ไม่ได้ พร้อมตั้งข้อสังเกตว่า 'chronic HCV ไม่น่าตับปกติ'. ตอบ HCC (ความมั่นใจปานกลาง) เพราะ (1) chronic HCV เป็น risk factor เดียวที่โจทย์ให้ (2) ไม่มีข้อมูลเพศ อายุ หรือยาคุมที่ชี้ไปทาง adenoma (3) ตับที่ดูปกติบน imaging ไม่ได้ exclude fibrosis และ HCC เกิดในตับที่ไม่ใช่ cirrhosis ได้ (4) ข้อนี้น่าจะเป็นคู่กับข้อ 56 เพื่อสอนว่า pattern เดียวกันแยกด้วยประวัติ. ในทางปฏิบัติ HCV ที่ไม่มี cirrhosis ไม่อยู่ใน LI-RADS population จึงควรยืนยันด้วย biopsy ก่อนรักษา",
  variants:["Chronic HBV without cirrhosis, 3-cm mass with APHE and washout → HCC (LI-RADS ใช้ได้ใน HBV)","Cirrhosis with 2.5-cm APHE + washout → LR-5 HCC ไม่ต้อง biopsy","Liver mass with APHE + washout in a patient without risk factors → biopsy"]}),
