A({page:4, page2:4, orig:"19", kimg:KI("19"),
  stem:"A patient presents with a goiter. Evaluation shows a multinodular goiter involving both thyroid lobes, and the patient has compressive symptoms. What is the most appropriate treatment?",
  gray:"19. ผู้ป่วยเป็น goiter. รักษาอะไร. — A. Total thyroidectomy B. Subtotal thyroidectomy",
  opts:["Total thyroidectomy","Subtotal thyroidectomy","Lobectomy","Radioactive iodine","Levothyroxine suppression"],
  ans:0, key:NK, flag:"⚠ ต้นฉบับบอกแค่ 'goiter' และมีช้อยแค่ total vs subtotal — เติม multinodular goiter ทั้งสองกลีบ + compressive symptoms ให้มีข้อบ่งชี้ผ่าตัดและเหลือคำตอบเดียว; ไฟล์เฉลยไม่ได้วงคำตอบ",
  interp:"ต้นฉบับถามสั้นมาก (goiter รักษาอะไร) ระหว่าง total กับ subtotal thyroidectomy — แก่นของข้อคือ goiter ที่มีข้อบ่งชี้ผ่าตัดและเป็นทั้งสองกลีบ ปัจจุบันผ่าแบบไหน",
  why:"Goiter ไม่ได้ต้องผ่าทุกราย — ข้อบ่งชี้ผ่าตัดคือ <b>compressive symptoms</b> (dysphagia, dyspnea, stridor, หายใจลำบากตอนนอนราบ), retrosternal extension, สงสัยหรือเป็นมะเร็ง, toxic MNG ที่เลือกผ่า และ cosmetic concern. เมื่อ MNG เป็น<b>ทั้งสองกลีบ</b> → <b>total (หรือ near-total) thyroidectomy</b>: ไม่เหลือเนื้อต่อมให้โตซ้ำ (subtotal มี recurrence สูงเมื่อติดตามนาน และ reoperation ในแผลเป็นเสี่ยง RLN injury และ hypoparathyroidism มากกว่าการผ่าครั้งแรกหลายเท่า). Cochrane review 2015 พบว่า total/near-total ลด recurrence เมื่อเทียบกับ subtotal โดย permanent RLN palsy และ permanent hypoparathyroidism ไม่ต่างกัน (transient hypocalcemia อาจมากกว่า) — หลังผ่าต้องให้ levothyroxine ตลอดชีวิต",
  wrong:["เหลือเนื้อต่อมไว้ → goiter กลับเป็นซ้ำได้สูงเมื่อติดตามนาน และการผ่าซ้ำเสี่ยง RLN injury/hypoparathyroidism มากกว่า; เดิมนิยมเพื่อเลี่ยง hypothyroidism — ปัจจุบันแทบไม่ใช้ใน MNG ทั้งสองกลีบ (near-total ที่เหลือเนื้อเพียงเล็กน้อยยังพอรับได้ในบางศูนย์)",
         "เหมาะกับโรคข้างเดียว: toxic adenoma, solitary nodule ที่ indeterminate, DTC 1–4 cm low risk — ใน MNG ทั้งสองกลีบจะเหลือ nodule อีกข้างที่ยังกดเบียดหรือโตต่อ; จะถูกถ้าโจทย์บอกว่าเป็น nodule หรือ goiter ข้างเดียว",
         "RAI ลดขนาด goiter ได้บางส่วนและช้า (เป็นเดือน) อาจบวมชั่วคราวช่วงแรก ไม่เหมาะเมื่อมีอาการกดหลอดลม — ใช้ใน toxic MNG (ATA 2016 ให้ RAI หรือผ่าตัด) หรือผู้สูงอายุที่เสี่ยงผ่าตัดสูงและไม่มีอาการกดเบียดรุนแรง",
         "ATA 2015 ไม่แนะนำ TSH suppression เป็น routine ใน benign nodule ในพื้นที่ที่ได้ไอโอดีนเพียงพอ — ลดขนาดได้น้อย เสี่ยง AF และ osteoporosis และไม่แก้ compressive symptom; ไม่มีกรณีที่เป็นคำตอบของข้อนี้"],
  trap:"คิดว่า subtotal 'ปลอดภัยกว่า' เพราะเหลือต่อมไว้ — ในมือผู้ชำนาญ total ปลอดภัยพอ ๆ กัน และ subtotal ทำให้ต้องผ่าซ้ำซึ่งอันตรายกว่า; อีกกับดักคือ goiter ที่ไม่มีอาการ euthyroid และ FNA benign ไม่ต้องผ่าเลย",
  summary:["Goiter workup: TSH ก่อนเสมอ → US คอ → FNA nodule ตามลักษณะ US (ATA 2015); TSH ต่ำ → thyroid scan หา hot หรือ cold nodule",
    "ข้อบ่งชี้ผ่าตัด goiter: compressive symptoms, retrosternal extension, สงสัยหรือพิสูจน์ว่าเป็นมะเร็ง, toxic MNG หรือ toxic adenoma ที่เลือกผ่า, cosmetic concern",
    "MNG ทั้งสองกลีบ → total thyroidectomy เป็นมาตรฐานแทน subtotal — ลด recurrence และเลี่ยง reoperation; ให้ levothyroxine ตลอดชีวิต",
    "โรคข้างเดียว (toxic adenoma, solitary nodule) → lobectomy",
    "Toxic MNG (ATA 2016): RAI หรือ near-total/total thyroidectomy (เลือกผ่าถ้าก้อนใหญ่กดเบียด สงสัยมะเร็ง หรือต้องการผลเร็ว); antithyroid drug ใช้คุมให้ euthyroid ก่อน หรือ low-dose ระยะยาวในบางราย — remission หลังหยุดยาน้อยมากเมื่อเทียบกับ Graves",
    "Complication ของ total thyroidectomy: hypocalcemia จาก hypoparathyroidism (ส่วนใหญ่ชั่วคราว), RLN injury (เสียงแหบ; สองข้าง → stridor), external branch of superior laryngeal nerve (เสียงสูงไม่ได้), neck hematoma (กดทางเดินหายใจ → เปิดแผลทันที)",
    "Levothyroxine suppression ไม่แนะนำ routine; RAI สำหรับ nontoxic goiter ใช้ในผู้เสี่ยงผ่าตัดสูง",
    "ดูข้อ 8, 18, 39, 40 (thyroid)"],
  notes:"ไฟล์เฉลย<b>ไม่ได้วงคำตอบ</b> — ลายมือข้างโจทย์: '=โต? ดูยังไง??' (สงสัยว่า goiter ในโจทย์หมายถึงแค่ต่อมโต) และ '<b>ถ้าตอบได้ต้องมี compressive symptom</b>'; ด้านขวาเขียน '<b>toxic MNG: ① ยา → 2 ปีไม่หาย → ② I-131 or ③ ไปผ่า</b>'; แปะ flowchart thyroid nodule (History/Physical examination, Serum TSH, Thyroid sonography → FNA → Non-diagnostic: repeat FNA; Benign: follow up — cyst re-accumulate ×3, continued growth, compressive symptoms → lobectomy; AUS/FLUS: repeat FNA หรือ lobectomy; FN/SFN: lobectomy หรือ TT; Suspicious for malignancy: lobectomy &amp; frozen section หรือ TT; Malignancy: TT)",
  mnemonic:"",
  guide:"ATA 2015 Thyroid Nodules and Differentiated Thyroid Cancer; ATA 2016 Hyperthyroidism and Other Causes of Thyrotoxicosis; Cochrane review total/near-total vs subtotal thyroidectomy for multinodular non-toxic goitre 2015",
  opinion:"เห็นด้วยกับ total thyroidectomy เมื่อเติมว่าเป็นทั้งสองกลีบและมีอาการกดเบียด (ความมั่นใจสูง). ต้นฉบับไม่ระบุชนิด goiter — รุ่นพี่เองก็เขียนว่าต้องมี compressive symptom ถึงจะตอบได้. ถ้าโจทย์เป็น nodule ข้างเดียว → lobectomy; ถ้าเป็น toxic MNG ในผู้สูงอายุเสี่ยงผ่าตัดและไม่กดเบียด → RAI. โน้ตรุ่นพี่ 'ยา 2 ปีไม่หาย' เป็น pathway แบบ Graves (ATD 12–18 เดือนแล้วประเมิน remission) — toxic MNG แทบไม่ remission ด้วยยา จึงมักไป RAI หรือผ่าตัดเป็น definitive treatment",
  variants:["Retrosternal goiter หายใจลำบากตอนนอนราบ → total thyroidectomy ผ่านแผลที่คอ (ส่วนใหญ่ไม่ต้อง sternotomy)","Toxic adenoma ก้อนเดียว เป็น hot nodule → lobectomy หรือ RAI","Benign nodule 2 cm ไม่มีอาการ euthyroid → ติดตามด้วย US ไม่ต้องผ่าและไม่ต้อง levothyroxine"]}),
A({page:4, page2:4, orig:"20", kimg:KI("20"),
  stem:"Which of the following is NOT considered prophylactic antibiotic use?",
  gray:"20. what is NOT considered “prophylactic antibiotics” — A. ceftriaxone and metronidazole given to patient with acute appendicitis while waiting for appendectomy B. vancomycin given 20 mins prior to herniorrhaphy with mesh ?? to patient allergic to penicillin C. cefazolin given 1 hour prior to athroplasty",
  opts:["Ceftriaxone and metronidazole given to a patient with uncomplicated acute appendicitis while awaiting appendectomy","Vancomycin given 20 minutes before mesh herniorrhaphy to a patient allergic to penicillin","Cefazolin given 1 hour before arthroplasty","Cefazolin given 30 minutes before mastectomy","None of the above"],
  ans:4, key:NK, flag:"⚠ ไฟล์เฉลยไม่ได้วง (รุ่นพี่เขียนครอบทุกช้อยว่า 'ถูกทุกข้อ' = ทุกข้อเป็น prophylaxis); ต้นฉบับมี 3 ช้อย — แต่ง D, E เพิ่ม และเติม 'uncomplicated' ในช้อย A ให้เหลือคำตอบเดียว",
  interp:"ถามนิยาม prophylactic antibiotics — ทุกช้อยเป็นการให้ยา<b>ก่อน</b>ผ่าตัดเพื่อป้องกัน SSI ในผู้ที่ไม่มีการติดเชื้อที่ต้องรักษาต่อ (หรือการอักเสบจำกัดอยู่ในอวัยวะที่จะตัดออก)",
  why:"Prophylaxis = ให้ยาก่อนลงมีด (ส่วนใหญ่ภายใน 60 นาที; vancomycin และ fluoroquinolone ภายใน 120 นาทีเพราะต้องหยดนาน) และหยุดภายใน 24 ชม. เพื่อลด SSI. ใน <b>uncomplicated appendicitis</b> การอักเสบจำกัดอยู่ในไส้ติ่งที่จะถูกตัดออก ยาก่อนผ่าตัดจึงนับเป็น prophylaxis (ASHP 2013 จัด appendectomy for uncomplicated appendicitis ไว้ในตาราง prophylaxis และไม่ให้ยาต่อหลังผ่า). Vancomycin 20 นาทีก่อนผ่า = <b>เริ่มช้าเกินไป</b> (ควรเริ่มหยด 60–120 นาทีก่อน incision) แต่เจตนายังเป็น prophylaxis. Cefazolin 1 ชม. ก่อน arthroplasty และ 30 นาทีก่อน mastectomy อยู่ในเกณฑ์ → ทุกข้อเป็น prophylaxis → <b>None of the above</b>",
  wrong:["ใน uncomplicated appendicitis ยาก่อนผ่า = prophylaxis และไม่ต้องให้ต่อหลังผ่า — ช้อยนี้จะเป็นคำตอบ (= therapeutic ไม่ใช่ prophylaxis) ถ้าเป็น <b>complicated appendicitis</b>: perforated, gangrenous, abscess หรือ peritonitis ซึ่งต้องให้ยาต่อหลัง source control (~4 วันตาม STOP-IT trial 2015)",
         "ยังเป็น prophylaxis — vancomycin เป็นทางเลือกในผู้แพ้ beta-lactam รุนแรงหรือมี MRSA colonization (รุ่นพี่: 'OK! if MRSA suspected') แต่ 20 นาทีก่อนผ่า timing ไม่เหมาะ → ผิดเรื่องเวลา ไม่ใช่ผิดประเภท; จะเป็นคำตอบถ้าโจทย์ถามว่า 'ข้อใดให้ prophylaxis ไม่ถูกต้อง'",
         "Cefazolin 2 g IV ภายใน 60 นาทีก่อน incision (3 g ถ้าน้ำหนัก ≥120 kg) = prophylaxis มาตรฐานของ arthroplasty; จะผิดก็ต่อเมื่อให้หลังลงมีดแล้ว หรือให้ต่อเนื่องเกิน 24 ชม.",
         "Breast cancer surgery เป็น clean procedure; cefazolin ภายใน 60 นาทีก่อนผ่าเป็น prophylaxis ที่ ASHP แนะนำ — จะไม่ใช่ prophylaxis ถ้าให้เพื่อรักษา mastitis หรือ breast abscess ที่มีอยู่แล้ว"],
  trap:"คิดว่า 'มีโรคติดเชื้ออยู่แล้ว = ยาที่ให้คือยารักษา' — ต้องแยก uncomplicated appendicitis (prophylaxis ไม่ต้องให้ต่อ) กับ complicated (treatment); และอย่าสับสน 'ให้ยาผิดเวลา' กับ 'ไม่ใช่ prophylaxis'",
  summary:["หลักการ prophylaxis: ยาครอบคลุมเชื้อที่คาดว่าจะปนเปื้อน ให้ IV ภายใน 60 นาทีก่อน incision (vancomycin, fluoroquinolone ภายใน 120 นาที), redose cefazolin ทุก 4 ชม. หรือเมื่อเสียเลือด &gt;1,500 mL, หยุดภายใน 24 ชม. (WHO และ CDC 2017 แนะนำไม่ให้ต่อหลังปิดแผล)",
    "Cefazolin เป็นยาหลักใน clean และ clean-contaminated ส่วนใหญ่ (2 g; 3 g ถ้า ≥120 kg); appendectomy และ colorectal ต้องครอบคลุม anaerobe → cefazolin + metronidazole, cefoxitin หรือ ceftriaxone + metronidazole",
    "แพ้ penicillin ที่ไม่ใช่ anaphylaxis หรือ severe cutaneous reaction → ให้ cefazolin ได้ (cross-reactivity ต่ำมาก); แพ้รุนแรง → clindamycin หรือ vancomycin; MRSA colonization → เพิ่ม vancomycin",
    "Uncomplicated appendicitis: ยาก่อนผ่า = prophylaxis ไม่ต้องให้ต่อ; complicated (perforated, abscess, peritonitis) = therapeutic ให้ต่อหลัง source control ราว 4 วัน",
    "ตารางยาไทยที่รุ่นพี่สรุป: appendectomy → ceftriaxone + metronidazole หรือ cefoxitin; colorectal → ceftriaxone + metronidazole; biliary tract → cefazolin หรือ ciprofloxacin; vascular graft → cloxacillin",
    "Open inguinal mesh repair: HerniaSurge 2018 ไม่แนะนำ prophylaxis routine ในผู้ป่วยความเสี่ยงเฉลี่ยในสถานที่ที่ SSI ต่ำ แต่แนะนำในผู้ป่วยหรือสถานที่ที่เสี่ยงสูง",
    "ดูข้อ 17, 33, 37 (perioperative)"],
  notes:"ไฟล์เฉลย<b>ไม่ได้วงคำตอบ</b> — วงคำว่า NOT ในโจทย์; ขีดเส้นใต้ 'while waiting' (เขียน '?' กำกับ), '20 mins', '1 hour prior'; ข้าง B เขียน '→ OK! if MRSA suspected'; วงเล็บปีกกาครอบช้อย A–C เขียนว่า '<b>ถูกทุกข้อ</b>'; แปะตาราง Table 1 antimicrobial recommended prophylaxis suitable for surgical practice in Thailand (ไฮไลต์บางแถว) และเขียนสรุป: appendectomy: ceftri + metro OR cefoxitin; colorectal: ceftri + metro; biliary tract: cefazolin OR ciprofloxacin; vascular graft: cloxacillin",
  mnemonic:"'60–120–4–24': ให้ภายใน 60 นาที (vanco/FQ 120), redose cefazolin ทุก 4 ชม., หยุดภายใน 24 ชม.",
  guide:"ASHP/IDSA/SIS/SHEA Clinical Practice Guidelines for Antimicrobial Prophylaxis in Surgery 2013; WHO Global Guidelines for the Prevention of SSI 2018; CDC SSI Guideline 2017; HerniaSurge 2018",
  opinion:"⚠ ไฟล์เฉลยไม่ได้วง แต่รุ่นพี่เขียนครอบทุกช้อยว่า 'ถูกทุกข้อ' (ทุกข้อเป็น prophylaxis) จึงเพิ่ม D (cefazolin ก่อน mastectomy) และ E None of the above ให้ครบ 5 ช้อยแล้วตอบ E. ต้นฉบับเขียนแค่ 'acute appendicitis' — ถ้าผู้ออกข้อสอบตั้งใจว่า 'ให้ยาในคนที่มีการอักเสบติดเชื้ออยู่แล้ว = รักษา' คำตอบจะเป็น A; ความต่างอยู่ที่ uncomplicated (prophylaxis ตาม ASHP 2013) กับ complicated (therapeutic) จึงเติม 'uncomplicated' ในช้อย A ให้เหลือคำตอบเดียว. ความมั่นใจปานกลาง: ข้อสอบจริงอาจต้องการคำตอบ A",
  variants:["Perforated appendicitis ได้ ceftriaxone + metronidazole ต่อหลังผ่า 4 วัน → therapeutic ไม่ใช่ prophylaxis","ผู้ป่วยแพ้ penicillin แบบผื่นธรรมดา จะผ่าตัด clean surgery → ให้ cefazolin ได้","ผ่าตัดนาน 5 ชม. ได้ cefazolin ก่อนลงมีด → ต้อง redose ที่ 4 ชม."]}),
A({page:5, page2:5, orig:"21", kimg:KI("21"),
  stem:"In SIADH, which serum electrolyte is abnormal?",
  gray:"21. SIADH อะไรผิดปกติ — A. Na B. K C. Mg",
  opts:["Sodium","Potassium","Magnesium","Calcium","Phosphate"],
  ans:0, key:"A Sodium"+KS,
  interp:"SIADH = ADH หลั่งเกินโดยไม่สัมพันธ์กับ osmolality → เก็บน้ำอิสระ → electrolyte ตัวไหนเปลี่ยน",
  why:"ADH↑ → V2 receptor ที่ collecting duct → aquaporin-2 → ดูดน้ำอิสระกลับ → <b>dilutional hyponatremia</b> แบบ euvolemic. เกณฑ์วินิจฉัย: serum Na &lt;135 mmol/L, serum osmolality &lt;275 mOsm/kg, urine osmolality &gt;100 mOsm/kg (เข้มข้นอย่างไม่เหมาะสม), urine Na &gt;30 mmol/L ขณะกินเกลือปกติ, euvolemia, ไม่มี hypothyroidism หรือ adrenal insufficiency และไม่ได้ใช้ diuretic — K, Mg, Ca, phosphate โดยทั่วไปปกติ",
  wrong:["SIADH ไม่มี aldosterone excess จึงไม่กระทบ K โดยตรง — hyponatremia ร่วมกับ K ผิดปกติให้นึกถึง adrenal insufficiency (Na↓ K↑) หรือ thiazide และการอาเจียน (Na↓ K↓)",
         "ไม่เกี่ยวกับ ADH — hypomagnesemia พบใน diuretic, PPI ระยะยาว, alcoholism, diarrhea, cisplatin และมักมาคู่ hypokalemia, hypocalcemia",
         "ไม่เกี่ยว — hypercalcemia กลับทำให้เกิด nephrogenic DI (ปัสสาวะมาก ตรงข้าม SIADH); hypocalcemia พบหลัง thyroidectomy/parathyroidectomy, pancreatitis",
         "ไม่เกี่ยว — hypophosphatemia พบใน refeeding syndrome และระหว่างรักษา DKA; hyperphosphatemia พบใน CKD, tumor lysis, rhabdomyolysis"],
  trap:"คิดว่า Na ในร่างกายหายไป — จริง ๆ total body Na เกือบปกติ แต่<b>น้ำเกิน</b>จึงเจือจาง; และอย่าสับสนกับ cerebral salt wasting ซึ่ง hypovolemic และต้องให้ NaCl ไม่ใช่จำกัดน้ำ",
  summary:["SIADH = euvolemic hypotonic hyponatremia: Na &lt;135, Posm &lt;275, Uosm &gt;100, UNa &gt;30, ไม่บวมไม่ขาดน้ำ, thyroid-adrenal-renal function ปกติ; uric acid และ BUN มักต่ำ",
    "สาเหตุ: CNS (head injury, SAH, meningitis), pulmonary (pneumonia, TB, positive-pressure ventilation), malignancy (small cell lung cancer), ยา (SSRI, carbamazepine, cyclophosphamide, vincristine, opioid), หลังผ่าตัด (ปวด คลื่นไส้)",
    "Cerebral salt wasting แยกจาก SIADH ด้วย volume status: CSW hypovolemic → ให้ NaCl; SIADH euvolemic → จำกัดน้ำ",
    "รักษา: จำกัดน้ำ (ราว 800–1,000 mL/วัน), salt tablets, urea, tolvaptan; อาการรุนแรง (ชัก ซึมมาก) → 3% NaCl bolus 100–150 mL ซ้ำได้ เป้าเพิ่ม Na 4–6 mmol/L แรก",
    "เพิ่ม Na ไม่เกิน 10–12 mmol/L ใน 24 ชม. (≤8 ในกลุ่มเสี่ยง: alcoholism, malnutrition, hypokalemia, liver disease) เพื่อป้องกัน osmotic demyelination syndrome",
    "หลังผ่าตัด ADH สูงจาก surgical stress → การให้ hypotonic fluid เสี่ยง hyponatremia; ใช้ isotonic fluid เป็นหลัก",
    "ดูข้อ 16, 25, 32, 49 (fluids/electrolytes)"],
  notes:"วง A. Na และเขียน '<b>ADH↑</b>'; แปะสไลด์ SIADH: Syndrome of inappropriate ADH secretion (SIAD, syndrome of inappropriate antidiuresis); the most common cause of euvolemic hyponatremia; excessive secretion of ADH; generation of hyponatremia: persistent intake of free water at serum osmolalities that are lower than the usual threshold for thirst; common causes: pulmonary disease, CNS disease",
  mnemonic:"SIADH = 'น้ำเกิน ไม่ใช่เกลือหาย' → Na เจือจาง แต่ปัสสาวะเข้มข้นผิดที่",
  guide:"European Clinical Practice Guideline on Hyponatraemia 2014 (ESE/ESICM/ERBP); US Expert Panel Recommendations on Hyponatremia 2013; Sabiston 21st ed. (2022)",
  opinion:"",
  variants:["ผู้ป่วย head injury Na 125, ขาดน้ำ, ปัสสาวะมาก urine Na สูง → cerebral salt wasting → ให้ NaCl","ผู้ป่วย small cell lung cancer Na 120 euvolemic → SIADH → จำกัดน้ำ","Na 118 ชัก → 3% NaCl bolus แล้วระวังไม่ให้ Na ขึ้นเกิน 10 ใน 24 ชม."]}),
A({page:5, page2:5, orig:"22", kimg:KI("22"),
  stem:"Which of the following is required when matching a donor liver to a recipient for liver transplantation?",
  gray:"22. Liver transplantต้องทำอะไร — A. Cross matching B. HLA C. ABO",
  opts:["Lymphocytotoxic crossmatch","HLA matching","ABO compatibility","Rh compatibility","Donor-recipient sex matching"],
  ans:2, key:"C ABO compatibility"+KS,
  interp:"ถามว่าในการจับคู่ตับ ต้องดูความเข้ากันได้อะไร — แยกจาก kidney transplant ที่ต้องดูหลายอย่าง",
  why:"ตับเป็น <b>immune privileged organ</b>: ทนต่อ hyperacute และ antibody-mediated rejection ได้ดี (ขนาดใหญ่ มี dual blood supply, Kupffer cells กรองแอนติบอดีและ immune complex, หลั่ง soluble HLA class I) จึง<b>ไม่ต้อง HLA matching และไม่ต้องรอผล crossmatch</b> ก่อนผ่า — จัดสรรด้วย <b>ABO compatibility</b> (เหมือนหรือเข้ากันได้) + ขนาด + ความรุนแรงของโรค (MELD/PELD). ABO-incompatible LT เสี่ยง antibody-mediated rejection, hepatic artery thrombosis และ ischemic cholangiopathy",
  wrong:["ไม่ต้องทำก่อนจัดสรรตับ (positive crossmatch ไม่ใช่ข้อห้ามของ LT) — จำเป็นใน kidney transplant (และ pancreas, heart ในผู้ที่ sensitized) เพราะ positive CDC crossmatch → hyperacute rejection",
         "ไม่ต้องจับคู่ HLA ในตับ (ผลต่อ graft survival น้อย และไม่มีเวลารอระหว่าง cold ischemia) — HLA matching สำคัญใน kidney transplant และ HSCT",
         "Rh (D antigen) อยู่บนเม็ดเลือดแดง ไม่ใช่ endothelium ของอวัยวะ จึงไม่ใช้ใน solid organ transplant — สำคัญใน blood transfusion และการตั้งครรภ์",
         "เพศไม่ใช่เกณฑ์จับคู่ — ที่ใช้คือ size matching (น้ำหนักตัว, ใน LDLT ใช้ graft-to-recipient weight ratio ≥0.8%)"],
  trap:"เอาหลักของ kidney transplant (ABO + HLA + crossmatch) มาใช้กับตับ — ตับต้องการแค่ ABO + ขนาด",
  summary:["Liver = immune privileged organ: ทนต่อ hyperacute rejection, ไม่ต้อง HLA matching หรือ crossmatch ก่อนผ่า — จับคู่ด้วย ABO + ขนาด + ความรุนแรงของโรค",
    "Allocation policy: patient-based (sickest first ตาม MELD/PELD) เทียบกับ center-based",
    "Kidney transplant ต้อง ABO compatible + HLA typing + crossmatch (CDC หรือ flow) negative; PRA สูง = sensitized รอนาน",
    "ABO-incompatible LT ทำได้ในภาวะฉุกเฉินหรือ LDLT ร่วมกับ desensitization (rituximab, plasmapheresis) — เสี่ยง AMR, hepatic artery thrombosis, biliary complication",
    "LDLT: graft-to-recipient weight ratio ≥0.8% (หรือ graft ≥40% ของ standard liver volume) เพื่อเลี่ยง small-for-size syndrome",
    "ดูข้อ 24 (orthotopic, indications ของ liver transplantation)"],
  notes:"วง C. ABO; แปะสไลด์ Liver transplantation: allocate by same blood group; no need for HLA typing and crossmatch; immune privilege organ (มีลายมือเล็ก ๆ กำกับเหตุผล); allocation policy: patient based (sickest first) vs center based",
  mnemonic:"ตับ 'ABO พอ' — ไต 'ABO + HLA + crossmatch ครบชุด'",
  guide:"EASL Clinical Practice Guidelines: Liver Transplantation 2016; Sabiston 21st ed. (2022)",
  opinion:"",
  variants:["Kidney transplant ต้องทำอะไรก่อนผ่า → ABO, HLA typing และ crossmatch negative","ทำไม liver ไม่ค่อยเกิด hyperacute rejection → immune privileged (Kupffer cells, soluble HLA class I, dual blood supply)"]}),
A({page:5, page2:5, orig:"23", kimg:KI("23"),
  stem:"In liver transplantation, the recipient's diseased liver is removed and the donor liver is placed in the same anatomical position. Which term describes this transplantation according to the position of the graft?",
  gray:"23. เปลี่ยนตับ — A. Orthotopic B. Allograft C. Autograft",
  opts:["Orthotopic","Heterotopic","Allograft","Autograft","Xenograft"],
  ans:0, key:"A Orthotopic"+KS, flag:"⚠ ต้นฉบับมีแค่ 'เปลี่ยนตับ' — ตับจากผู้บริจาคก็เป็น allograft ด้วย จึงเติม stem ให้ถามชื่อเรียกตาม<b>ตำแหน่ง</b>ของ graft",
  interp:"แยกศัพท์ 2 แกน: ตามตำแหน่ง (orthotopic/heterotopic) กับตามแหล่งผู้ให้ (auto/iso/allo/xenograft)",
  why:"<b>Orthotopic</b> = ตัดอวัยวะเดิมของผู้รับออกแล้ววาง graft ในตำแหน่งกายวิภาคเดิม (ortho = ถูกที่) — liver, heart, lung transplant เป็นแบบนี้; ตรงกับที่รุ่นพี่เขียนว่า 'มาแทนที่ที่เดิม'",
  wrong:["Heterotopic = วาง graft ในตำแหน่งอื่นโดยไม่ตัดอวัยวะเดิม — kidney (iliac fossa), pancreas; heterotopic/auxiliary liver หรือ heart ทำน้อยมาก",
         "ถูกในแง่ชนิดผู้ให้ (คนละคน สายพันธุ์เดียวกัน) — ตับจาก deceased หรือ living donor เป็น allograft; จะเป็นคำตอบถ้าโจทย์ถามว่า graft จากผู้บริจาคสมองตายจัดเป็นชนิดใด แต่ไม่ได้บอกตำแหน่ง",
         "Autograft = เนื้อเยื่อของตัวเอง — skin graft, saphenous vein graft, parathyroid autotransplantation, islet autotransplant หลัง total pancreatectomy; ไม่ใช่ตับจากผู้อื่น",
         "Xenograft = ต่างสายพันธุ์ (pig-to-human kidney หรือ heart ยังเป็นงานทดลอง) — ไม่ใช่ liver transplant มาตรฐาน"],
  trap:"Allograft ก็ 'ถูก' สำหรับ liver transplant — ต้องอ่านว่าโจทย์ถามแกนไหน (ตำแหน่ง vs แหล่งผู้ให้)",
  summary:["Orthotopic = ตัดอวัยวะเดิมแล้ววาง graft ตำแหน่งเดิม: liver (มัก piggyback technique เก็บ IVC ของผู้รับไว้), heart, lung",
    "Heterotopic = วางตำแหน่งอื่นและไม่ตัดอวัยวะเดิม: kidney ที่ iliac fossa, pancreas",
    "ชนิดตามผู้ให้: autograft (ตัวเอง), isograft (แฝดเหมือน), allograft (คนอื่นสายพันธุ์เดียวกัน), xenograft (ต่างสายพันธุ์)",
    "ชนิด graft ตับ: deceased vs living donor; whole vs split (แบ่งตับหนึ่งให้ 2 คน) vs reduced-size",
    "ข้อบ่งชี้: เด็ก → biliary atresia (หลัง Kasai ล้มเหลว) มากที่สุด; ผู้ใหญ่ → decompensated cirrhosis (HBV, HCV, alcohol, MASLD), HCC ใน Milan criteria (ก้อนเดียว ≤5 cm หรือ ≤3 ก้อน แต่ละก้อน ≤3 cm, ไม่มี vascular invasion หรือ extrahepatic spread), acute liver failure (King's College criteria)",
    "ดูข้อ 23 (ABO matching), 31 (donor contraindications)"],
  notes:"วง A. Orthotopic เขียนว่า '<b>มาแทนที่ที่เดิม</b>'; แปะสไลด์ Liver transplantation: orthotopic transplantation; living vs cadaveric; split vs reduced size vs whole graft; most common indication: pediatric — BA, adult — cirrhosis caused by HCV, HBV, alcohol; HCC (Milan's criteria); FHF",
  mnemonic:"Ortho = ตรงที่เดิม, Hetero = ต่างที่",
  guide:"EASL Clinical Practice Guidelines: Liver Transplantation 2016; Sabiston 21st ed. (2022)",
  opinion:"เห็นด้วยกับคีย์และสไลด์ที่รุ่นพี่แปะ. ช้อยต้นฉบับมี Allograft ซึ่งถูกเช่นกันถ้าถามชนิดตามผู้ให้ จึงเติม stem ให้ถามเรื่องตำแหน่ง",
  variants:["Kidney transplant วางที่ iliac fossa โดยไม่เอาไตเดิมออก → heterotopic","เด็ก biliary atresia หลัง Kasai ล้มเหลว ได้ตับส่วน left lateral segment จากพ่อ → living donor, reduced-size orthotopic allograft"]}),
A({page:5, page2:5, orig:"24", kimg:KI("24"),
  stem:"A patient with oliguric acute kidney injury after a crush injury develops an arrhythmia that progresses to ventricular fibrillation. Which electrolyte abnormality is the most likely cause?",
  gray:"24. Arrhythmia + VF — A. Hyperkalemia B. Hypokalemia C. HypoMg",
  opts:["Hyperkalemia","Hypokalemia","Hypomagnesemia","Hypercalcemia","Hypernatremia"],
  ans:0, key:"A Hyperkalemia"+KS, flag:"⚠ ต้นฉบับ 'Arrhythmia + VF' อย่างเดียวตอบได้ทั้ง hyperK, hypoK และ hypoMg — เติมบริบท oliguric AKI หลัง crush injury ให้เหลือ hyperkalemia",
  interp:"Crush injury → rhabdomyolysis + AKI แบบปัสสาวะน้อย → electrolyte ตัวไหนทำ VF",
  why:"Crush → กล้ามเนื้อตาย ปล่อย K ออกนอกเซลล์ + myoglobin ทำ AKI จนขับ K ไม่ได้ + metabolic acidosis ดัน K ออกจากเซลล์ → <b>hyperkalemia</b> (K &gt;5.5). ECG เรียงตามความรุนแรง: peaked T → PR ยาว, P แบนหรือหาย → QRS กว้าง → sine wave → <b>VF</b>/asystole. รักษา: calcium gluconate 10% IV (stabilize membrane) → insulin + glucose, salbutamol nebulizer, NaHCO3 ถ้า acidosis (shift) → K binder, dialysis (remove)",
  wrong:["Hypokalemia ทำ ST↓ T แบน U wave และ ventricular arrhythmia ได้ — จะเป็นคำตอบถ้าโจทย์ให้อาเจียนมาก, NG loss, diuretic หรือให้ insulin; ไม่เข้ากับ oliguric AKI จาก crush",
         "Hypomagnesemia ทำ long QT และ torsades de pointes → VF ได้ — จะเป็นคำตอบในผู้ป่วย alcoholism, diuretic, PPI, diarrhea (รักษาด้วย MgSO4 2 g IV)",
         "Hypercalcemia ทำ short QT และ bradyarrhythmia แต่ VF พบน้อย — ใน crush syndrome ช่วงแรกกลับเป็น <b>hypocalcemia</b> (Ca ไปจับกล้ามเนื้อที่ตาย) ส่วน hypercalcemia มักเกิดช่วง recovery",
         "Hypernatremia ทำอาการทางสมอง (ซึม ชัก) ไม่ใช่สาเหตุของ VF — พบในผู้ที่ขาดน้ำหรือ DI"],
  trap:"เห็น VF แล้วตอบ hypoK หรือ hypoMg ตามความเคยชิน — ต้องดูบริบท: ไตวาย + เนื้อเยื่อตาย = K สูง; crush ยังมี hypocalcemia ช่วงแรกซึ่งยิ่งเพิ่มพิษของ hyperK",
  summary:["Hyperkalemia: K &gt;5.5 mmol/L; อันตรายเมื่อ ≥6.5 หรือมี ECG change",
    "สาเหตุ: intake เกิน, ขับออกไม่ได้ (renal failure, RTA type 4, hypoaldosteronism, ACEI/ARB, spironolactone), shift ออกจากเซลล์ (acidosis, tissue damage จาก crush/burn/tumor lysis/hemolysis, succinylcholine, beta-blocker)",
    "ECG: peaked T → PR ยาว, P แบนหรือหาย → QRS กว้าง → sine wave → VF/asystole; ECG ปกติไม่ได้แปลว่าปลอดภัย",
    "รักษา 3 ขั้น: stabilize membrane (calcium gluconate 10% IV) → shift (insulin + glucose, salbutamol, NaHCO3 ถ้า acidosis) → remove (K binder, loop diuretic, dialysis)",
    "Crush syndrome: rhabdomyolysis → hyperK, metabolic acidosis, hypoCa ช่วงแรก, myoglobinuric AKI → ให้ isotonic fluid เร็ว (เริ่มก่อนนำผู้ป่วยออกจากที่ถูกทับถ้าทำได้) เป้าปัสสาวะสูง, dialysis ถ้า hyperK ดื้อการรักษา",
    "เปรียบเทียบ ECG: hypoK → ST↓ T แบน U wave; hypoMg → long QT, torsades; hypoCa → long QT; hyperCa → short QT",
    "ดูข้อ 16, 22, 32, 49 (fluids/electrolytes)"],
  notes:"วง A. Hyperkalemia และวงคำว่า VF ในโจทย์; ข้าง B hypokalemia เขียน '↓T, ↓ST, U wave'; แปะสไลด์ Hyperkalemia (K⁺ &gt; 5.5 mEq/L): excessive intake → oral, IV; inadequate excretion (renal failure, RTA, hypoaldosteronism); K⁺ shift out of cells (acidosis, tissue damage, drugs); S&amp;S — GI (N/V, cramping), muscle weakness, heart (EKG change: ↑T, QRS↑, ↓P, ↑PR, sine wave → VF, cardiac arrest)",
  mnemonic:"ECG hyperK: 'T แหลม → P หาย → QRS กว้าง → sine → VF'",
  guide:"UK Renal Association: Treatment of Acute Hyperkalaemia in Adults 2020; AHA Guidelines for CPR and ECC 2020; KDIGO AKI 2012",
  opinion:"เห็นด้วยกับ hyperkalemia ตามคีย์และสไลด์ที่รุ่นพี่แปะ. ต้นฉบับกำกวม (hypoK และ hypoMg ก็ทำ VF ได้) จึงเติมบริบทที่ทำให้ K สูงโดยไม่บอก ECG ตรง ๆ; ถ้าโจทย์ให้อาเจียนมากหรือได้ diuretic + U wave → hypokalemia; ถ้าให้คนติดสุรา long QT + torsades → hypomagnesemia",
  variants:["ผู้ป่วย CKD K 7.2 มี QRS กว้าง → ให้ calcium gluconate IV เป็นอย่างแรก","ผู้ป่วยอาเจียนมาก มี U wave → hypokalemia","ผู้ป่วยติดสุรา QT ยาว เกิด torsades → MgSO4 IV"]}),
A({page:5, page2:5, orig:"25", kimg:KI("25"),
  stem:"Mammography shows diffuse suspicious microcalcifications in one breast. Core needle biopsy shows invasive ductal carcinoma. The axillary lymph nodes are not palpable. What is the most appropriate surgical management?",
  gray:"25. นมมีmicrocal axilla LNคลำไม่ได้ — A. Masectomy ALND B. Masectomy sentinel C. BCS sentinel",
  opts:["Mastectomy with axillary lymph node dissection","Mastectomy with sentinel lymph node biopsy","Breast-conserving surgery with sentinel lymph node biopsy","Breast-conserving surgery with axillary lymph node dissection","Breast-conserving surgery without axillary staging"],
  ans:1, key:"B Mastectomy with sentinel lymph node biopsy"+KS, flag:"⚠ ต้นฉบับบอกแค่ 'microcal' + LN คลำไม่ได้ — ถ้า microcalcification เป็นกลุ่มเดียวขนาดเล็ก BCS + SLNB ก็ถูก จึงเติม diffuse suspicious microcalcifications + core biopsy IDC",
  interp:"ต้องตัดสิน 2 เรื่อง: (1) เต้านม — BCS ได้ไหม (2) รักแร้ — cN0 ใช้ SLNB หรือ ALND",
  why:"<b>Diffuse suspicious (malignant-appearing) microcalcifications</b> เป็น absolute contraindication ของ breast-conserving therapy (NCCN) เพราะตัดให้ margin negative พร้อม cosmetic ที่ยอมรับได้ไม่ได้ → <b>mastectomy</b>. รักแร้คลำไม่ได้ (cN0) → axillary staging ด้วย <b>SLNB</b> (lymphedema ราว 5% เทียบ ALND ราว 20%); ALND สงวนไว้สำหรับ node บวกที่พิสูจน์แล้วหรือ SLN mapping ล้มเหลว",
  wrong:["ALND ทำเมื่อ cN+ ที่พิสูจน์ด้วย US-guided biopsy (และไม่ได้ neoadjuvant หรือยังเหลือโรคหลัง neoadjuvant), SLN mapping ล้มเหลว หรือ SLN บวก ≥3 ต่อม — cN0 ไม่ควรทำ ALND ตั้งแต่ต้น",
         "เป็นมาตรฐานถ้า microcalcification จำกัดเป็นบริเวณเดียวที่ตัดได้ margin negative และฉายรังสีได้ — แต่ diffuse suspicious microcalcifications เป็น absolute contraindication ของ BCT",
         "ผิดทั้งสองส่วน: BCT ห้ามใน diffuse microcalcification และ ALND เกินจำเป็นใน cN0 — BCS + ALND ใช้ใน cN+ ที่พิสูจน์แล้วโดยก้อนเหมาะกับ BCS",
         "ละ axillary staging ได้เฉพาะกลุ่มเลือกสรร (อายุ ≥70, HR+/HER2−, T1 cN0 ตาม Choosing Wisely; SOUND 2023 และ INSEMA 2024 ศึกษาใน BCS ที่ US รักแร้ปกติ) — ข้อนี้ยังติดที่ BCS ทำไม่ได้"],
  trap:"เห็น 'microcalcification' แล้วนึกว่าเป็นโรคเล็ก → BCS — ต้องดูการกระจาย: diffuse หรือหลาย quadrant = mastectomy; และ LN คลำไม่ได้ ไม่ได้แปลว่าไม่ต้อง staging",
  summary:["Contraindication ของ BCT (NCCN 2024): absolute — pregnancy ที่ต้องฉายรังสีระหว่างตั้งครรภ์, diffuse suspicious หรือ malignant-appearing microcalcifications, โรคกว้างตัดผ่านแผลเดียวให้ margin negative และ cosmetic ดีไม่ได้, diffusely positive margin, homozygous ATM mutation; relative — เคยฉายรังสีที่เต้าหรือผนังอก, active connective tissue disease ที่ผิวหนัง (scleroderma, lupus), TP53 (Li-Fraumeni), ก้อน &gt;5 cm",
    "BCT = BCS + whole breast RT ให้ overall survival เท่ากับ mastectomy (NSABP B-06, Milan I)",
    "Axilla: cN0 → SLNB; cN+ (พิสูจน์ด้วย US-guided biopsy) → ALND หรือ neoadjuvant แล้วประเมินใหม่ (SLNB หรือ targeted axillary dissection ถ้า ycN0)",
    "SLN บวก 1–2 ต่อมใน BCS + whole breast RT → ไม่ต้อง ALND (ACOSOG Z0011); ใน mastectomy อาศัยข้อมูล AMAROS (axillary RT แทน ALND) และ SENOMAC",
    "Lymphedema หลัง ALND ราว 20% เทียบ SLNB ราว 5%",
    "ละ SLNB ได้ในผู้สูงอายุ ≥70 HR+/HER2− T1 cN0 หรือตามเกณฑ์ SOUND/INSEMA",
    "ดูข้อ 19 (โจทย์ microcalcification หลาย quadrant แบบเดียวกัน)"],
  notes:"วง B. Masectomy sentinel + เขียน '<b>น่าจะเอาแค่นี้ก่อน</b>'; แปะสไลด์ NCCN Guidelines Version 3.2024 Invasive Breast Cancer — Special considerations to breast-conserving therapy requiring RT: contraindications (ชี้และไฮไลต์บรรทัด diffuse suspicious microcalcifications)",
  mnemonic:"",
  guide:"NCCN Breast Cancer v.3.2024; ASCO Guideline Sentinel Lymph Node Biopsy in Early-Stage Breast Cancer 2021",
  opinion:"เห็นด้วยกับคีย์เมื่อ microcalcification กระจาย (ความมั่นใจสูง). ต้นฉบับไม่บอกลักษณะการกระจาย — ถ้าเป็น cluster เดียวที่ตัดได้ → C (BCS + SLNB) ถูก; ถ้ามี axillary LN บวกพิสูจน์แล้ว → ต้องทำ ALND หรือ neoadjuvant ก่อน",
  variants:["Microcalcification cluster 1.5 cm ที่ upper outer quadrant core biopsy IDC LN คลำไม่ได้ → BCS + SLNB + whole breast RT","IDC 2 cm มี axillary LN โต FNA บวก → ALND หรือ neoadjuvant systemic therapy","BCS + SLNB พบ SLN บวก 2 ต่อม จะฉาย whole breast RT → ไม่ต้อง ALND (Z0011)"]}),
A({page:5, page2:5, orig:"26", kimg:KI("26"),
  stem:"Which pairing of an infectious agent with the cancer it causes is incorrect?",
  gray:"26. ทำให้เกิดcancer ข้อไหนผิด — A. Hep A-HCC B. EBV-burkitt C. HPV-penis D. O.viver-cholang E. H.pylori-gastric adeno",
  opts:["Hepatitis A virus and hepatocellular carcinoma","Epstein-Barr virus and Burkitt lymphoma","Human papillomavirus and penile cancer","Opisthorchis viverrini and cholangiocarcinoma","Helicobacter pylori and gastric adenocarcinoma"],
  ans:0, key:"A Hepatitis A virus and hepatocellular carcinoma"+KS,
  interp:"ถามคู่เชื้อก่อมะเร็ง (IARC Group 1) ที่ผิด",
  why:"HAV เป็น RNA picornavirus ติดทาง fecal-oral ก่อ acute hepatitis ที่หายเองเกือบทั้งหมด <b>ไม่มี chronic carrier state</b> → ไม่ทำ cirrhosis หรือ HCC. ไวรัสก่อ HCC คือ <b>HBV</b> (DNA virus integrate เข้าจีโนม ก่อ HCC ได้แม้ไม่มี cirrhosis) และ <b>HCV</b> (ผ่าน chronic inflammation → cirrhosis)",
  wrong:["ถูก — EBV เป็น IARC Group 1 ก่อ Burkitt lymphoma (โดยเฉพาะ endemic, t(8;14) MYC), Hodgkin lymphoma, nasopharyngeal carcinoma, extranodal NK/T-cell lymphoma และ PTLD; จะเป็นคู่ที่ผิดถ้าจับคู่ EBV กับ HCC",
         "ถูก — high-risk HPV (16, 18) ก่อ SCC ของ cervix, anus, vulva, vagina, penis และ oropharynx; จะผิดถ้าจับคู่ HPV กับมะเร็งที่ไม่ใช่ squamous ของบริเวณเหล่านี้",
         "ถูก — liver fluke ที่พบในภาคอีสาน (กินปลาน้ำจืดดิบหรือสุกไม่ทั่ว เช่นก้อยปลา) → chronic biliary inflammation → cholangiocarcinoma; Clonorchis sinensis ก็เป็น Group 1",
         "ถูก — H. pylori ก่อ non-cardia gastric adenocarcinoma และ gastric MALT lymphoma (eradication รักษา MALT lymphoma ระยะแรกได้)"],
  trap:"คิดว่า hepatitis ทุกตัวก่อ HCC — เฉพาะตัวที่เป็นเรื้อรังได้ (B, C และ D ร่วมกับ B); A และ E ติดทางปากและไม่เรื้อรังในคนภูมิปกติ",
  summary:["IARC Group 1 ไวรัส: HBV, HCV → HCC; EBV → Burkitt, Hodgkin, NPC, NK/T-cell lymphoma; HPV → cervix, anus, penis, vulva, vagina, oropharynx; HHV-8 → Kaposi sarcoma, primary effusion lymphoma; HTLV-1 → adult T-cell leukemia/lymphoma; HIV-1",
    "Parasites: Opisthorchis viverrini, Clonorchis sinensis → cholangiocarcinoma; Schistosoma haematobium → bladder SCC",
    "Bacteria: H. pylori → non-cardia gastric adenocarcinoma และ gastric MALT lymphoma",
    "HAV และ HEV ติดทาง fecal-oral → acute hepatitis ไม่เรื้อรังในคนภูมิปกติ → ไม่ก่อ HCC",
    "ปัจจัยเสี่ยง HCC อื่น: cirrhosis จากทุกสาเหตุ, alcohol, MASLD, aflatoxin B1 (เสริมฤทธิ์กับ HBV), hemochromatosis",
    "ภาคอีสานของไทยมีอุบัติการณ์ cholangiocarcinoma สูงมากจาก O. viverrini — ป้องกันด้วยการไม่กินปลาดิบ"],
  notes:"กากบาท A. Hep A-HCC ✗ เขียน 'Hepatitis B, C'; B ✓ 'Hodgkin, Burkitt (non-Hodgkin), Nasopharyngeal CA'; C ✓; D ✓; E ✓ + วงเล็บ 'gastric adenoCA, gastric MALT lymphoma'",
  mnemonic:"'A กับ E กินเข้าไปแล้วหาย — B กับ C เรื้อรังจนเป็นมะเร็ง'",
  guide:"IARC Monographs Volume 100B: Biological Agents (2012)",
  opinion:"",
  variants:["ข้อใดไม่ใช่สาเหตุของ cholangiocarcinoma → H. pylori (ส่วน O. viverrini, PSC, choledochal cyst ใช่)","HHV-8 สัมพันธ์กับมะเร็งใด → Kaposi sarcoma","เชื้อใดสัมพันธ์กับ MALT lymphoma ของกระเพาะ → H. pylori"]}),
A({page:6, page2:6, orig:"27", kimg:KI("27"),
  stem:"A patient presents with symptoms of obstructive jaundice. Imaging shows a mass at the hepatic hilum, dilated hepatic ducts, and peritoneal nodules. What is used to relieve his symptoms?",
  gray:"27. Patient w obstructive jaundice symptoms. Imaging มี mass at hepatic hilum, dilated hepatic duct มี peritoneal nodules. What is used to relieve his symptoms — A. PTBD B. ERCP + stent",
  opts:["Percutaneous transhepatic biliary drainage","ERCP with biliary stent","Hepaticojejunostomy bypass","Pancreaticoduodenectomy","Systemic chemotherapy alone"],
  ans:1, key:"B ERCP with biliary stent"+KS, flag:"⚠ ใช้โจทย์ตามต้นฉบับ — คำตอบขึ้นกับ Bismuth type: ถ้าก้อนลามทั้ง right และ left hepatic duct (Bismuth III–IV) หรือ ERCP ไม่สำเร็จ หลายสถาบันเลือก PTBD",
  interp:"Hilar mass + obstructive jaundice + peritoneal nodules = perihilar cholangiocarcinoma ระยะแพร่กระจาย → ต้องการแค่ palliation ของ jaundice",
  why:"Peritoneal nodules = distant metastasis → unresectable → เป้าหมายคือ biliary drainage เพื่อลด jaundice, pruritus, cholangitis และให้ bilirubin ลดพอจะเริ่ม chemotherapy. <b>ERCP + stent</b> (SEMS ถ้าคาดว่ามีชีวิต &gt;3 เดือน) เป็น internal drainage ไม่มีสายออกนอกตัว ไม่เสียน้ำดี คุณภาพชีวิตดีกว่า และเป็นวิธีที่ใช้บ่อย (รุ่นพี่: 'more common &amp; recommended'); เป้าคือระบายเนื้อตับที่ทำงานอย่างน้อย 50%",
  wrong:["เลือกเมื่อ hilar ซับซ้อน (Bismuth III–IV) ที่ ERCP ระบายได้ไม่พอหรือเสี่ยง cholangitis ใน segment ที่ฉีด contrast แต่ระบายไม่ได้, ERCP ล้มเหลว, หรือกายวิภาคถูกผ่าตัดเปลี่ยน (Roux-en-Y) — ข้อเสียคือสายภายนอก เจ็บ หลุด เสียน้ำดี เลือดออก; ถ้าโจทย์บอก Bismuth IV หรือ ERCP ไม่สำเร็จ → ตอบข้อนี้",
         "Surgical bypass ใช้น้อยลงมากเพราะ morbidity สูงในผู้ป่วยระยะแพร่กระจาย — พิจารณาเมื่อเปิดผ่าตัดหวังตัดแล้วพบว่าตัดไม่ได้ในผู้ป่วยที่แข็งแรง",
         "Whipple เป็นการผ่าตัดหวังหายขาดของ distal cholangiocarcinoma หรือ periampullary tumor ที่ resectable — ไม่ใช่ hilar และห้ามเมื่อมี peritoneal metastasis",
         "Chemotherapy (gemcitabine + cisplatin + durvalumab หรือ pembrolizumab) เป็นการรักษาหลักของ advanced biliary tract cancer แต่ไม่ได้ลด jaundice เร็ว และ bilirubin สูงหรือ cholangitis เป็นข้อจำกัดในการให้ยา → ต้องระบายน้ำดีก่อน"],
  trap:"คิดว่ามะเร็งท่อน้ำดี = Whipple — Whipple สำหรับ distal CBD/periampullary; hilar ที่ตัดได้ต้อง hepatectomy + bile duct resection; มี peritoneal nodule = M1 ไม่ผ่าตัดหวังหายขาด",
  summary:["Perihilar cholangiocarcinoma (Klatskin tumor): painless jaundice, intrahepatic duct โต แต่ GB และ CBD ไม่โต",
    "Bismuth–Corlette: I ใต้ confluence, II ถึง confluence, IIIa ลาม right hepatic duct, IIIb ลาม left, IV ทั้งสองข้างหรือ multifocal",
    "Unresectable: ลาม second-order ducts สองข้างจนเหลือตับไม่พอ, vascular encasement สองข้าง, distant metastasis รวม peritoneal → palliation",
    "Palliative drainage: ERCP + stent (SEMS ถ้าคาดชีวิต &gt;3 เดือน, plastic ถ้าน้อยกว่าหรือยังไม่ชัดว่าผ่าได้) หรือ PTBD; ระบาย ≥50% ของเนื้อตับที่ทำงาน; Bismuth III–IV หรือ ERCP ล้มเหลว → PTBD",
    "Distal malignant biliary obstruction → ERCP + SEMS เป็น first-line; ล้มเหลว → EUS-guided biliary drainage หรือ PTBD",
    "ถ้ายังอาจผ่าตัดได้ ควรทำ CT/MRCP ก่อนใส่ stent เพื่อไม่ให้รบกวน staging",
    "Systemic therapy ของ advanced biliary tract cancer: gemcitabine + cisplatin + durvalumab (TOPAZ-1) หรือ + pembrolizumab (KEYNOTE-966)",
    "ดูข้อ 6, 41, 58 (biliary obstruction)"],
  notes:"เลขข้อไฮไลต์เหลือง (รุ่นพี่ไม่ชัวร์); เขียนเหนือ peritoneal nodules ว่า '<b>CA stage 4?</b>'; ข้าง A เขียน 'percutaneous transhepatic biliary drainage'; กากบาท B. ERCP + stent และเขียน '<b>more common &amp; recommended</b>'",
  mnemonic:"",
  guide:"ESGE Endoscopic Biliary Stenting Guideline (updated 2017, Endoscopy 2018); NCCN Biliary Tract Cancers 2024",
  opinion:"เห็นด้วยกับคีย์ในระดับปานกลาง: ต้นฉบับไม่บอก Bismuth type. ESGE ให้เลือก endoscopic หรือ percutaneous ตามความชำนาญของสถาบัน; หลายการศึกษาพบ PTBD ระบายสำเร็จสูงกว่าและ cholangitis น้อยกว่าใน Bismuth III–IV ขณะที่ ERCP สะดวกกว่าและไม่มีสายภายนอก — ถ้าโจทย์ระบุว่าก้อนลามทั้ง right และ left hepatic duct หรือ ERCP ล้มเหลว ควรตอบ PTBD",
  variants:["Distal CBD stricture จาก pancreatic head cancer มี liver metastasis → ERCP + SEMS","Hilar cholangiocarcinoma Bismuth IV ERCP ล้มเหลว เกิด cholangitis → PTBD","Hilar cholangiocarcinoma Bismuth II ไม่มี metastasis → extended hepatectomy + bile duct resection"]}),
A({page:6, page2:6, orig:"28", kimg:KI("28"),
  stem:"A patient with chronic hepatitis B virus infection needs an operation. Which of the following should NOT be done?",
  gray:"28. คนไข้ติดHBVไม่ควรทำอะไร — A. Observe ไม่เข้าผ่า B. ใส่ goggle C. ใส่apron",
  opts:["Observe and decline to operate","Wear protective eyewear","Wear an impermeable apron","Wear double gloves","Use standard precautions as for all patients"],
  ans:0, key:"A Observe and decline to operate"+KS,
  interp:"ถามสิ่งที่ไม่ควรทำเมื่อผ่าตัดผู้ป่วย HBV — แยกการป้องกันที่ถูกต้องออกจากการปฏิเสธการรักษา",
  why:"การไม่ผ่าตัดเพราะผู้ป่วยติด HBV <b>ผิดจริยธรรมและไม่มีเหตุผลทางการแพทย์</b> — บุคลากรป้องกันตัวเองได้ด้วย HBV vaccination (anti-HBs ≥10 mIU/mL = มีภูมิ), standard precautions กับผู้ป่วยทุกราย, PPE ตามความเสี่ยง และ post-exposure prophylaxis. ผู้ป่วยต้องได้รับการรักษาตามข้อบ่งชี้เหมือนคนอื่น",
  wrong:["ควรทำ — eye protection ป้องกันเลือดกระเด็นเข้าตาและ mucosa; เป็นส่วนหนึ่งของ standard precautions ในทุกการผ่าตัดที่มีโอกาส splash ไม่ใช่เฉพาะผู้ป่วยติดเชื้อ จึงไม่มีบริบทที่ข้อนี้เป็น 'สิ่งที่ไม่ควรทำ'",
         "ควรทำ — impermeable gown หรือ apron เมื่อคาดว่าจะสัมผัสเลือดหรือสารคัดหลั่งปริมาณมาก; ถูกต้องในทุกผู้ป่วย",
         "ควรทำ — double gloving ลดการทะลุของถุงมือชั้นในและการสัมผัสเลือดของศัลยแพทย์ แนะนำในการผ่าตัดทั่วไปโดยเฉพาะผู้ป่วยที่มี blood-borne infection",
         "ถูก — standard precautions คือถือว่าเลือดและสารคัดหลั่งของทุกคนอาจติดเชื้อ จึงปฏิบัติเหมือนกันทุกราย ไม่ต้องรู้สถานะการติดเชื้อก่อน"],
  trap:"ข้อนี้ถาม 'ไม่ควรทำ' — ช้อย PPE ทุกตัวเป็นสิ่งที่ควรทำ; อย่าเผลอเลือก double glove หรือ apron เพราะคิดว่า 'ไม่จำเป็นถ้าใช้ standard precautions'",
  summary:["Standard precautions ใช้กับผู้ป่วยทุกราย: hand hygiene, PPE ตามความเสี่ยง (gloves, gown หรือ apron, mask, eye protection), safe sharps (ไม่ recap เข็ม, ใช้ neutral zone ส่งของมีคม), ทิ้ง sharps ในภาชนะเฉพาะ",
    "ความเสี่ยงติดเชื้อจากเข็มตำในผู้ที่ไม่มีภูมิ: HBV clinical hepatitis 1–6% ถ้าผู้ป่วย HBeAg− และ 22–31% ถ้า HBeAg+ (serologic evidence 23–37% และ 37–62% ตามลำดับ), HCV ราว 1.8%, HIV ราว 0.3%",
    "บุคลากรต้องได้ HBV vaccine 3 เข็ม และตรวจ anti-HBs 1–2 เดือนหลังครบ (≥10 mIU/mL = responder)",
    "PEP หลังสัมผัสเลือด HBsAg+: responder → ไม่ต้องทำอะไร; non-responder หลังวัคซีน 1 ชุด → HBIG 1 ครั้ง + เริ่มวัคซีนชุดใหม่; non-responder หลัง 2 ชุด → HBIG 2 ครั้งห่าง 1 เดือน; ไม่เคยได้วัคซีน → HBIG + เริ่มวัคซีน (HBIG ให้เร็วที่สุด ภายใน 24 ชม.)",
    "Double gloving ลดการทะลุของถุงมือชั้นใน; indicator glove ช่วยให้เห็นรูรั่ว",
    "การปฏิเสธรักษาเพราะผู้ป่วยติด HBV, HCV หรือ HIV ผิดจริยธรรม",
    "ดูข้อ 76 (hand hygiene)"],
  notes:"กากบาท A. Observe ไม่เข้าผ่า (เลือกเป็นคำตอบ) — ไม่มีโน้ตเพิ่ม",
  mnemonic:"Rule of 3s เข็มตำ: HBV 30%, HCV 3%, HIV 0.3% (ตัวเลขจำง่าย; HCV จริงราว 1.8%)",
  guide:"CDC Updated US Public Health Service Guidelines for Management of Occupational Exposures to HBV, HCV, and HIV 2001; CDC Guidance for Evaluating Health-Care Personnel for HBV Protection 2013; SHEA Guideline for Management of HCWs Infected with HBV, HCV, and/or HIV 2010",
  opinion:"",
  variants:["ศัลยแพทย์ที่ anti-HBs ≥10 mIU/mL โดนเข็มตำจากผู้ป่วย HBsAg+ → ไม่ต้องให้ HBIG หรือวัคซีนเพิ่ม","บุคลากรไม่เคยได้วัคซีน โดนเข็มตำจากผู้ป่วย HBsAg+ → HBIG + เริ่ม HBV vaccine","เข็มตำจากผู้ป่วย HIV+ → เริ่ม PEP antiretroviral ให้เร็วที่สุด ภายใน 72 ชม. นาน 28 วัน"]}),
A({page:6, page2:6, orig:"29", kimg:KI("29"), imgNote:"รูปในข้อสอบ: plain film ช่องท้อง — เงาทึบรังสีที่ RLQ ร่วมกับลำไส้เล็กอุดตัน (ไม่มีรูปในไฟล์)",
  stem:"A patient presents with symptoms of small bowel obstruction. An abdominal X-ray is provided, showing a radiopaque density in the right lower quadrant. What is the most likely diagnosis?",
  gray:"29. Patient มี small bowel obstruction symptoms.มี X ray มาให้ (มีขาว ๆ ที่ RLQ) ผู้ป่วยเป็นอะไร — A. Midgut volvulus B. Gallstone ileus C. Acute cholangitis D. Acute cholecystitis",
  opts:["Midgut volvulus","Gallstone ileus","Acute cholangitis","Acute cholecystitis","Sigmoid volvulus"],
  ans:1, key:"B Gallstone ileus"+KS,
  interp:"Small bowel obstruction + เงาทึบที่ RLQ (ตำแหน่ง terminal ileum ใกล้ ileocecal valve) → นึกถึงก้อนอะไรมาอุดใน lumen",
  why:"<b>Gallstone ileus</b> = mechanical SBO จากนิ่วถุงน้ำดีขนาดใหญ่ (มัก &gt;2–2.5 cm) ที่ผ่าน <b>cholecystoenteric fistula</b> (cholecystoduodenal บ่อยที่สุด) แล้วไปติดที่ส่วนแคบที่สุดของลำไส้เล็ก คือ <b>terminal ileum ใกล้ ileocecal valve</b> → เงาทึบที่ RLQ. พบมากในผู้หญิงสูงอายุ. <b>Rigler triad</b>: SBO + pneumobilia + ectopic radiopaque gallstone (เห็นครบใน plain film ไม่บ่อยเพราะนิ่วส่วนใหญ่ไม่ทึบรังสี) → CT วินิจฉัยได้ดีที่สุด",
  wrong:["Midgut volvulus จาก malrotation พบในทารกและเด็กเล็ก มาด้วย bilious vomiting; plain film อาจเห็น double bubble กับ gas ส่วนปลายน้อย ไม่มีเงาทึบที่ RLQ — UGI study เห็น corkscrew → Ladd procedure ฉุกเฉิน",
         "Acute cholangitis = obstruction ของท่อน้ำดี + infection มาด้วย Charcot triad (ไข้ ปวด RUQ เหลือง) ไม่ใช่ SBO — นิ่วอยู่ใน CBD ไม่ใช่ใน lumen ลำไส้",
         "Acute cholecystitis มาด้วยปวด RUQ, Murphy sign, ไข้ วินิจฉัยด้วย US; อาจมี ileus ข้างเคียงแต่ไม่ใช่ mechanical SBO และไม่มีนิ่วที่ RLQ — ทั้งนี้ cholecystitis เรื้อรังเป็นจุดเริ่มต้นของ fistula ที่นำไปสู่ gallstone ileus",
         "Sigmoid volvulus เป็น large bowel obstruction ในผู้สูงอายุท้องผูกเรื้อรัง plain film เห็น coffee bean sign จาก LLQ ชี้ไป RUQ — ไม่ใช่ SBO"],
  trap:"ชื่อ 'ileus' ทำให้คิดว่าเป็น paralytic ileus — จริง ๆ เป็น <b>mechanical obstruction</b>; และอย่าเลือก cholecystitis หรือ cholangitis เพียงเพราะเห็นคำว่านิ่ว",
  summary:["Gallstone ileus: ผู้หญิงสูงอายุ, SBO แบบเป็น ๆ หาย ๆ (tumbling obstruction ขณะนิ่วเคลื่อน), ประวัติโรคถุงน้ำดี",
    "กลไก: cholecystitis เรื้อรัง → cholecystoenteric fistula (cholecystoduodenal บ่อยที่สุด) → นิ่วใหญ่ไปติด terminal ileum ใกล้ ileocecal valve",
    "Rigler triad: SBO + pneumobilia + ectopic gallstone; CT เป็น investigation of choice",
    "Bouveret syndrome = นิ่วไปติดที่ duodenum หรือ pylorus → gastric outlet obstruction",
    "รักษา: resuscitate (ผู้ป่วยมักขาดน้ำ electrolyte ผิดปกติ) → <b>enterolithotomy</b> (ผ่าลำไส้ส่วนต้นต่อจุดอุดเอานิ่วออก) ตรวจหานิ่วก้อนอื่นในลำไส้; cholecystectomy + fistula repair ทำพร้อมกันเฉพาะผู้ป่วยแข็งแรงที่เลือกไว้ หรือทำภายหลัง",
    "SBO ทั่วไป: สาเหตุอันดับ 1 คือ adhesion, อันดับ 2 hernia; gallstone ileus เป็นสาเหตุไม่บ่อย (ราว 1–4%) แต่พบบ่อยขึ้นในผู้สูงอายุ",
    "ดูข้อ 65 (SBO), 6 และ 43 (โรคทางเดินน้ำดี)"],
  notes:"กากบาท B. Gallstone ileus (เลือกเป็นคำตอบ) + เขียน '<b>น่าจะเป็น gall stone ที่ไปอุดแถว IC valve</b>'",
  mnemonic:"Rigler triad 'อุด–ลม–หิน': SBO, air in biliary tree, ectopic stone",
  guide:"Sabiston 21st ed. (2022); Schwartz's Principles of Surgery 11th ed. (2019)",
  opinion:"",
  variants:["ผู้หญิงอายุ 78 ปี SBO + CT เห็น pneumobilia และนิ่วใน terminal ileum → enterolithotomy","ผู้ป่วยอาเจียนมาก CT เห็นนิ่วใหญ่ติดที่ duodenal bulb + pneumobilia → Bouveret syndrome","ผู้สูงอายุท้องผูกเรื้อรัง ท้องอืดมาก film เห็น coffee bean sign → sigmoid volvulus → endoscopic detorsion"]}),
A({page:6, page2:6, orig:"30", kimg:KI("30"),
  stem:"Who is NOT contraindicated for solid organ donation?",
  gray:"30. Who is not contraindicated for solid organ donation. — A. HIV infection B. Malignant melanoma C. Persistent hypertension D. Creutzfeldt-Jakob disease",
  opts:["A donor with HIV infection","A donor with malignant melanoma","A donor with persistent hypertension","A donor with Creutzfeldt-Jakob disease","A donor with active disseminated tuberculosis"],
  ans:2, key:"C A donor with persistent hypertension"+KS,
  interp:"ถามว่าข้อใดไม่ใช่ข้อห้ามของการบริจาคอวัยวะ — แยก absolute contraindication (ถ่ายทอดโรคร้ายแรงไปผู้รับ) ออกจากภาวะที่เพียงทำให้คุณภาพอวัยวะลดลง",
  why:"<b>Hypertension ไม่ใช่ข้อห้าม</b> (อยู่ในกลุ่ม 'need to be risk assessed' ของสไลด์) — อาจทำให้ไตของผู้บริจาคมีคุณภาพลดลง (เป็นปัจจัยใน expanded criteria donor และ KDPI) แต่ยังใช้ได้หลังประเมินอวัยวะ. ข้อห้ามสัมบูรณ์คือภาวะที่ถ่ายทอดสู่ผู้รับแล้วรักษาไม่ได้หรืออันตรายถึงชีวิต: CJD (prion), active HIV ในบริบททั่วไป, malignancy ที่แพร่ทางอวัยวะได้สูง (melanoma, choriocarcinoma) หรือ metastatic cancer, การติดเชื้อที่ยังควบคุมไม่ได้",
  wrong:["HIV ถือเป็น absolute contraindication ในบริบททั่วไป (สไลด์ 'CHUMP' และโน้ตรุ่นพี่) — ยกเว้น HIV+ ไปยังผู้รับ HIV+ ซึ่งทำได้ภายใต้ HOPE Act ของสหรัฐฯ (2013) และในแอฟริกาใต้; ข้อนี้จะไม่ใช่ข้อห้ามถ้าโจทย์ระบุว่าผู้รับก็ติด HIV",
         "Melanoma ถ่ายทอดทางอวัยวะได้สูงมากและอาจกลับเป็นซ้ำหลังปลอดโรคนานหลายปี จึงเป็นข้อห้ามไม่ว่าห่างจากการรักษานานเท่าใด (เช่นเดียวกับ choriocarcinoma); ต่างจาก in situ skin cancer ที่ไม่ใช่ melanoma หรือมะเร็งที่รักษาหายนานแล้วซึ่งพิจารณาได้",
         "CJD เป็น prion disease ที่ถ่ายทอดผ่านเนื้อเยื่อได้ (มีรายงานจาก dura mater และ corneal graft) ไม่มีวิธีฆ่าเชื้อหรือรักษา → absolute contraindication เสมอ",
         "Active TB ที่ยังไม่ได้รักษาเป็นการติดเชื้อที่ควบคุมไม่ได้ จึงเป็นข้อห้าม — ต่างจาก TB ที่รักษาครบแล้ว หรือ latent TB ซึ่งบริจาคได้และให้ผู้รับได้ isoniazid prophylaxis ตามความเหมาะสม"],
  trap:"ใช้เกณฑ์ผู้บริจาคเลือดหรือเกณฑ์ 'สุขภาพดี' มาตัดสิน — ผู้บริจาคอวัยวะหลังเสียชีวิตเป็นผู้สูงอายุ เป็น HT, DM, AKI ได้ ซึ่งไม่ใช่ข้อห้าม",
  summary:["ABSOLUTE contraindications 'CHUMP': CJD, active HIV, uncontrolled infection หรือ donor sepsis ที่ไม่ทราบเชื้อ, metastatic หรือ non-curable malignancy, past malignancy ที่ถ่ายทอดได้สูงไม่ว่าปลอดโรคนานเท่าใด (melanoma, choriocarcinoma)",
    "NOT contraindications 'LIP-HEAD' (ต้องประเมินความเสี่ยง): Localised tumours (kidney, prostate), treated Infections (bacterial, hepatitis B หรือ C, risk factors for HIV), Past malignancy with long cancer-free interval, Hypertension, Elderly (เคยบริจาคจากผู้ป่วยอายุ 80 กว่า), Acute renal failure, Diabetes mellitus",
    "Primary CNS tumor ส่วนใหญ่ (ยกเว้น high grade หรือเคยผ่าตัดหรือ shunt) และ skin cancer ที่ไม่ใช่ melanoma บริจาคได้",
    "HBV+ หรือ HCV+ donor ใช้ได้กับผู้รับที่เหมาะสม (HCV ให้ DAA หลังปลูกถ่าย; HBV ให้ผู้รับที่มีภูมิหรือให้ prophylaxis)",
    "HIV+ donor → HIV+ recipient ทำได้ภายใต้ HOPE Act (สหรัฐฯ 2013)",
    "Hypertension, DM, อายุมาก, Cr สูงจาก AKI ลดคุณภาพไต (expanded criteria donor, KDPI สูง) แต่ไม่ใช่ข้อห้าม",
    "ดูข้อ 4, 23, 24, 73 (transplantation)"],
  notes:"กากบาท C. Persistent hypertension (เลือกเป็นคำตอบ); วงเล็บครอบ A, B, D เขียนว่า '<b>absolute contraindication!</b>'; ใต้ D เขียน 'neurocognitive disease due to prion'; แปะสไลด์ ABSOLUTE 'CHUMP': CJD, active HIV, uncontrolled infection (donor sepsis), metastatic or non-curable malignant disease, past history of malignancy that poses risk for transmission no matter how long the apparent disease-free period (e.g. melanoma, choriocarcinoma) และ NOT CONTRAINDICATIONS (need to be risk assessed) 'LIP-HEAD': localised tumours (kidney, prostate), treated infections (bacterial, hepatitis B or C, risk factors for HIV), past malignancy and a long cancer-free interval (childhood leukaemia, lymphoma), hypertension, elderly (donations have taken place from patients in early 80's), acute renal failure, diabetes mellitus",
  mnemonic:"ห้าม = '<b>CHUMP</b>' (CJD, HIV, Uncontrolled infection, Metastatic, Past melanoma or choriocarcinoma); ไม่ห้าม = '<b>LIP-HEAD</b>'",
  guide:"UK NHSBT/SaBTO Microbiological Safety Guidelines (2020); Council of Europe Guide to the Quality and Safety of Organs for Transplantation 8th ed. (2022); HIV Organ Policy Equity (HOPE) Act 2013",
  opinion:"เห็นด้วยกับคีย์ (ความมั่นใจสูง). ข้อสังเกต: HIV ไม่ใช่ absolute contraindication อีกต่อไปในบางประเทศ (HIV+ → HIV+) แต่ในบริบทข้อสอบทั่วไปยังถือเป็นข้อห้าม",
  variants:["ผู้บริจาคสมองตายอายุ 75 ปี เป็น DM และ HT → ไม่ใช่ข้อห้าม ประเมินอวัยวะรายตัว","ผู้บริจาคเคยตัด melanoma เมื่อ 15 ปีก่อน → ห้ามบริจาค","ผู้บริจาค HCV antibody+ → ให้ผู้รับได้ร่วมกับ DAA"]}),
A({page:6, page2:6, orig:"31", kimg:KI("31"),
  stem:"What is the expected urine output for a patient weighing 50 kg?",
  gray:"31. คาดหวังปัสสาวะ นน 50 กก — A. 20-25 cc/hr B. 30-50cc/hr C. 2-3cc/kg/hr D. 3-5cc/kg/hr",
  opts:["20–25 mL/hr","30–50 mL/hr","2–3 mL/kg/hr","3–5 mL/kg/hr","100–150 mL/hr"],
  ans:1, key:"B 30–50 mL/hr"+KS,
  interp:"ถามเป้า urine output ที่บ่งว่า end-organ perfusion และ volume status เพียงพอในผู้ใหญ่",
  why:"เป้าปัสสาวะผู้ใหญ่ = <b>0.5–1 mL/kg/hr</b> → 50 kg × 0.5–1 = <b>25–50 mL/hr</b> ซึ่งตรงกับช่วง 30–50 mL/hr ที่ใช้ทั่วไปในผู้ใหญ่ (เช่นเป้าใน burn resuscitation ตาม ABA). ต่ำกว่า 0.5 mL/kg/hr ต่อเนื่อง 6 ชม. = oliguria ตามเกณฑ์ KDIGO AKI",
  wrong:["20–25 mL/hr = ราว 0.4–0.5 mL/kg/hr ต่ำกว่าหรือแค่ขอบล่าง — ต่ำกว่า 0.5 mL/kg/hr นาน 6 ชม. เข้าเกณฑ์ oliguria (KDIGO stage 1) จึงไม่ใช่ค่าที่คาดหวัง",
         "2–3 mL/kg/hr = 100–150 mL/hr สูงเกินเป้าปกติ — สะท้อน over-resuscitation หรือ diuresis (osmotic diuresis จาก hyperglycemia, DI, post-obstructive diuresis); ค่าทำนองนี้คือ<b>ปริมาณ fluid</b> ไม่ใช่ urine output (Parkland 4 mL/kg/%TBSA, ABA 2–4 mL/kg/%TBSA)",
         "3–5 mL/kg/hr สูงมาก = polyuria (DI, osmotic diuresis) ไม่ใช่เป้า resuscitation",
         "100–150 mL/hr = 2–3 mL/kg/hr สูงเกินเป้าในผู้ใหญ่ทั่วไป — เป้าสูงขึ้นใช้ในบางภาวะ: myoglobinuria หรือ electrical injury ตั้งเป้า 75–100 mL/hr ในผู้ใหญ่ (ABLS) จนปัสสาวะใส, rhabdomyolysis หรือ crush syndrome ตั้งเป้าสูงกว่านี้"],
  trap:"สับสนระหว่าง <b>ปริมาณสารน้ำที่ให้</b> (mL/kg/%TBSA) กับ <b>urine output ที่ต้องการ</b> (mL/kg/hr); และเด็กใช้ 1 mL/kg/hr ไม่ใช่ 0.5",
  summary:["Urine output เป้า: ผู้ใหญ่ 0.5–1 mL/kg/hr (≈30–50 mL/hr); เด็ก ≥1 mL/kg/hr (ราว 1–1.5 ใน burn เด็ก); ทารก 1–2 mL/kg/hr",
    "Myoglobinuria หรือ high-voltage electrical injury: ผู้ใหญ่ตั้งเป้า 75–100 mL/hr จนปัสสาวะใส",
    "Oliguria ตาม KDIGO: &lt;0.5 mL/kg/hr ≥6 ชม. = stage 1, ≥12 ชม. = stage 2, &lt;0.3 mL/kg/hr ≥24 ชม. หรือ anuria ≥12 ชม. = stage 3",
    "Burn resuscitation: Parkland 4 mL/kg/%TBSA หรือ ABA 2–4 mL/kg/%TBSA ของ Ringer lactate ใน 24 ชม. (ครึ่งแรกใน 8 ชม. นับจากเวลาเกิดเหตุ) แล้วปรับอัตราตาม urine output",
    "Oliguria หลังผ่าตัด: แยก prerenal (hypovolemia — ดูชีพจร BP CVP, fluid challenge), renal, postrenal (เช็ก Foley อุดตันก่อน)",
    "การวัดต้องใส่ Foley catheter และบันทึกทุกชั่วโมงในผู้ป่วยที่ resuscitation",
    "ดูข้อ 16, 22, 25, 49 (fluids/electrolytes)"],
  notes:"กากบาท B. 30–50 cc/hr (เลือกเป็นคำตอบ) + เขียน '<b>0.5–1 ml/kg/hr</b>' และ '<b>25–50 ml/hr</b>'; ด้านบนเป็นส่วนต่อของสไลด์ CHUMP/LIP-HEAD จากข้อก่อนหน้า",
  mnemonic:"'ครึ่งถึงหนึ่ง' — 0.5–1 mL/kg/hr ในผู้ใหญ่, 1 ในเด็ก",
  guide:"KDIGO Clinical Practice Guideline for Acute Kidney Injury 2012; ABA Advanced Burn Life Support (ABLS) Provider Manual 2018; ATLS 10th ed. (2018)",
  opinion:"",
  variants:["ผู้ป่วย burn 60 kg TBSA 40% → Parkland 9,600 mL ใน 24 ชม. ครึ่งแรกใน 8 ชม. ปรับตามปัสสาวะ 30–60 mL/hr","เด็ก 20 kg หลังผ่าตัด ปัสสาวะที่ต้องการ → ≥20 mL/hr","ผู้ป่วย high-voltage electrical injury ปัสสาวะสีน้ำตาลเข้ม → เป้า 75–100 mL/hr"]}),
A({page:7, page2:7, orig:"32", kimg:KI("32"),
  stem:"A patient develops a fever on postoperative day 5. The urinary catheter was removed on day 2, oral diet was started on day 3, and the patient has been ambulating since day 4. Which is the most likely cause of the fever?",
  gray:"32. post op fever day 5. remove urinary catheter on day 2, start your oral diet day 3, ambulate ได้ day 4. Which is the most unlikely cause — A. Atelectasis B. UTI C. Wound infection D. DVT E. Thrombophlebitis",
  opts:["Atelectasis","UTI","Wound infection","DVT","Thrombophlebitis"],
  ans:2, key:"C Wound infection"+KS, flag:"⚠ ไฟล์โจทย์เขียน '<b>most unlikely</b> cause' แต่รุ่นพี่ขีดฆ่าคำว่า 'un' แล้ววง C — จึงใช้ stem 'most likely'; ถ้าข้อสอบจริงถาม 'unlikely' คำตอบคือ Atelectasis",
  interp:"ใช้ timing ของ postoperative fever: day 5 + ปัจจัยเสี่ยงแต่ละอย่างถูกตัดไปแล้ว (เอาสายสวนออกแล้ว, กินได้, เดินได้) → เหลือสาเหตุไหน",
  why:"ไข้หลังผ่าตัดตามเวลา: day 0–2 → inflammatory response จากการผ่าตัด (atelectasis เป็นสิ่งที่พบร่วมแต่ไม่ได้พิสูจน์ว่าเป็นสาเหตุของไข้); day 3–5 → UTI, pneumonia, thrombophlebitis; <b>day 5–7 → wound infection (SSI)</b> และ anastomotic leak/abscess; หลัง day 7 → DVT/PE, deep abscess. ในโจทย์นี้ถอด Foley ตั้งแต่ day 2 (ความเสี่ยง CAUTI ลดลง), ลุกเดินได้ day 4 (DVT ลดลง) → สาเหตุที่เข้ากับ day 5 ที่สุดคือ <b>wound infection</b> → ตรวจแผลก่อน",
  wrong:["Atelectasis พบบ่อย day 1–2 และหลักฐานปัจจุบันชี้ว่า<b>ไม่ได้เป็นสาเหตุของไข้</b>โดยตรง — ผู้ป่วยกินได้ เดินได้ day 5 ยิ่งไม่เข้า; ถ้าข้อสอบถาม 'most unlikely' ช้อยนี้คือคำตอบ",
         "UTI (CAUTI) พบ day 3–5 แต่ความเสี่ยงสัมพันธ์กับระยะเวลาคาสาย — ถอด Foley ตั้งแต่ day 2 จึงน้อยลง (รุ่นพี่: 'remove cath ไปแล้ว?'); จะเป็นคำตอบถ้ายังคาสายถึง day 4–5 และมี dysuria หรือ pyuria",
         "DVT มักทำไข้ต่ำ ๆ หลัง day 7 และพบน้อยเมื่อลุกเดินได้ — จะเป็นคำตอบถ้าโจทย์ให้ขาบวมข้างเดียวในผู้ป่วยนอนนาน ไม่ได้ป้องกัน หรือเป็นมะเร็ง",
         "Thrombophlebitis ที่ตำแหน่งเปิดเส้นพบ day 3–5 ได้ — จะเป็นคำตอบถ้าโจทย์บอกว่ามีเส้นเลือดแข็งเป็นลำ แดง กดเจ็บที่ตำแหน่ง IV cannula"],
  trap:"อ่าน 'unlikely' ไม่ทัน หรือไม่ใช้ข้อมูลตัดทิ้ง (ถอดสาย, เดินได้) ที่โจทย์ให้มา; และจำ 'atelectasis = ไข้ day 1' แบบเก่าซึ่งปัจจุบันถือว่าไม่ใช่สาเหตุพิสูจน์ได้",
  summary:["ไข้หลังผ่าตัด 'Wind–Water–Wound–Walking–Wonder drugs': day 1–2 Wind (pulmonary; ไข้ช่วงนี้ส่วนใหญ่เป็น inflammatory response), day 3–5 Water (UTI) และ IV line, day 5–7 Wound (SSI), day 5–7 ขึ้นไป anastomotic leak/intra-abdominal abscess, &gt;7 วัน Walking (DVT/PE), ทุกช่วง Wonder drugs (drug fever) และ transfusion",
    "ไข้ภายใน 48 ชม. ส่วนใหญ่ไม่ต้อง workup มาก ยกเว้นสงสัย necrotizing soft-tissue infection (Clostridium, group A strep) หรือ anastomotic leak เร็ว",
    "SSI: superficial incisional (ผิวหนัง/subcutaneous), deep incisional (fascia/กล้ามเนื้อ), organ/space — นับภายใน 30 วัน หรือ 90 วันถ้ามี implant (CDC NHSN)",
    "รักษา superficial SSI: เปิดแผลระบายหนอง ล้างทำแผล; ให้ antibiotic ถ้ามี cellulitis รอบแผลหรือ systemic sign",
    "CAUTI ลดได้โดยถอด Foley เร็วที่สุด (ภายใน 24–48 ชม. ในผ่าตัดส่วนใหญ่)",
    "Atelectasis ป้องกันด้วย incentive spirometry, ลุกนั่งเดินเร็ว, คุมปวด",
    "ดูข้อ 37 (mesh infection หลัง herniorrhaphy day 5), 35 (DVT prophylaxis)"],
  notes:"ไฟล์โจทย์เขียน 'most unlikely cause' — รุ่นพี่<b>ขีดฆ่าคำว่า 'un'</b> และ<b>กากบาท A. Atelectasis</b> แล้ว<b>วง C. Wound infection</b>; เลขข้อไฮไลต์เหลือง (ไม่ชัวร์); วงคำว่า 'day 5' และ 'on day 2'; ข้าง B UTI เขียน 'remove cath ไปแล้ว?'; ข้าง D DVT เขียน 'ambulate ได้ น่าจะดีแล้ว'",
  mnemonic:"5W: Wind (1–2), Water (3–5), Wound (5–7), Walking (&gt;7), Wonder drugs (ทุกเวลา)",
  guide:"Sabiston 21st ed. (2022); CDC NHSN Surgical Site Infection Event 2024",
  opinion:"⚠ ต้นฉบับถาม 'most unlikely cause' — ถ้าตีความตามตัวอักษร คำตอบคือ Atelectasis (ไข้ day 5 ในผู้ป่วยที่กินได้ เดินได้ และ atelectasis ไม่ได้เป็นสาเหตุของไข้ที่พิสูจน์ได้). รุ่นพี่ขีดคำว่า 'un' ออกแล้วตอบ Wound infection แสดงว่าเชื่อว่าคนจดโจทย์จดผิดหรือข้อสอบถาม 'most likely'. เราเลือกตามคีย์โดยใช้ stem 'most likely' → Wound infection (เข้ากับ day 5–7 และปัจจัยอื่นถูกตัดทิ้ง). ความมั่นใจปานกลาง: ถ้าในข้อสอบจริงเห็นคำว่า 'unlikely' ให้ตอบ Atelectasis",
  variants:["ไข้ day 1 หลัง laparotomy ปอดฟังมี crepitation เล็กน้อย → สังเกตอาการ, incentive spirometry, ส่วนใหญ่เป็น inflammatory response","ไข้ day 6 หลัง colectomy ปวดท้องมาก หัวใจเต้นเร็ว → anastomotic leak → CT","ไข้ day 10 ขาซ้ายบวม → DVT → compression duplex US"]}),
A({page:7, page2:7, orig:"33", kimg:KI("33"),
  stem:"A patient presents with hematemesis from esophageal varices. Resuscitation and sclerotherapy were performed. He now bleeds again. What should be done?",
  gray:"33. Patient hematemesis จาก esophageal varice. Resus กับ sclerotherapy ไปแล้ว. ตอนนี้ bleed อีกรอบ. ให้ทำอะไร. — A. Band ligation B. TIPS C. portocaval shunt D. Distal splenorenal shunt",
  opts:["Band ligation","TIPS","Portocaval shunt","Distal splenorenal shunt","Balloon tamponade as definitive therapy"],
  ans:0, key:"A Band ligation"+KS,
  interp:"Variceal rebleeding หลัง endoscopic therapy ครั้งแรก → ขั้นต่อไปตาม algorithm คืออะไร",
  why:"ตาม algorithm ที่รุ่นพี่แปะ: rebleeding หลัง endoscopic therapy ครั้งแรก → <b>repeat endoscopic therapy</b> โดย <b>EVL</b> เป็นวิธีเลือก (ดีกว่า sclerotherapy: rebleeding, stricture, ulcer และ complication น้อยกว่า) ร่วมกับ vasoactive drug (terlipressin, octreotide หรือ somatostatin 2–5 วัน) + ceftriaxone prophylaxis. Baveno VI/VII: rebleeding ช่วง 5 วันแรกให้ลอง endoscopic therapy ครั้งที่สองได้ ถ้าเลือดออกรุนแรงหรือยังคุมไม่ได้หลัง vasoactive + endoscopic → <b>rescue TIPS</b>",
  wrong:["TIPS เป็นขั้นถัดไปเมื่อ endoscopic therapy ครั้งที่สองล้มเหลว (uncontrolled หรือ further bleeding) หรือเลือดออกรุนแรง = rescue TIPS; และ <b>pre-emptive TIPS ภายใน 72 ชม.</b> (ดีที่สุดภายใน 24 ชม.) ในผู้ป่วยเสี่ยงสูง (Child C 10–13 หรือ Child B &gt;7 ที่มี active bleeding ขณะส่องกล้อง) — ถ้าโจทย์บอกว่าทำ EVL ซ้ำแล้วยังออก → ตอบ TIPS",
         "Total portosystemic shunt ลด portal pressure ได้ดีแต่ encephalopathy และ liver failure สูง (เลือดไม่ผ่านตับเลย) — ปัจจุบันถูก TIPS แทนเกือบทั้งหมด ใช้เมื่อ TIPS ทำไม่ได้หรือล้มเหลวในศูนย์ที่มีความชำนาญ",
         "Selective shunt (Warren) ลด pressure เฉพาะ gastrosplenic bed ยังรักษา portal flow ไปตับ — encephalopathy น้อยกว่า ใช้ในผู้ป่วย Child A ที่ rebleeding ซ้ำแบบ elective หรือ non-cirrhotic portal hypertension; ไม่ใช่ขั้นแรกของ acute rebleeding",
         "Balloon tamponade (Sengstaken-Blakemore, Minnesota) เป็น<b>bridge</b>ไม่เกิน 24 ชม. เมื่อเลือดออกควบคุมไม่ได้ระหว่างรอ TIPS หรือ endoscopy — rebleeding สูงเมื่อปล่อยลม เสี่ยง esophageal perforation และ aspiration; esophageal stent (SX-Ella Danis) ใช้แทนได้"],
  trap:"กระโดดไป TIPS หรือ shunt surgery ทันทีที่ rebleed — ต้องลอง endoscopic therapy ซ้ำก่อน (ยกเว้นเลือดออกรุนแรงคุมไม่ได้); และอย่าลืมว่า EVL ดีกว่า sclerotherapy",
  summary:["Acute variceal bleeding: airway protection, restrictive transfusion (Hb เป้า 7–8 g/dL), vasoactive drug ทันทีที่สงสัย (terlipressin, octreotide, somatostatin 2–5 วัน), ceftriaxone 1 g/วัน (สูงสุด 7 วัน), ICU",
    "EGD ภายใน 12 ชม. → esophageal varices: EVL; gastric varices (GOV2, IGV1): cyanoacrylate glue injection หรือ TIPS/BRTO",
    "Pre-emptive TIPS ภายใน 72 ชม. (ดีที่สุด &lt;24 ชม.) ใน Child C 10–13 หรือ Child B &gt;7 ที่มี active bleeding ขณะส่องกล้อง (Baveno VII)",
    "Rebleeding ช่วงแรก → repeat EVL; uncontrolled หรือ further bleeding → balloon tamponade หรือ esophageal stent เป็น bridge → rescue TIPS → shunt surgery ถ้า TIPS ทำไม่ได้",
    "Secondary prophylaxis: non-selective beta-blocker (propranolol หรือ carvedilol) + EVL ทุก 1–4 สัปดาห์จน varices หมด; ล้มเหลว → TIPS",
    "Shunt surgery: total (portocaval) → encephalopathy สูง; selective (distal splenorenal, Warren) → รักษา hepatic portal flow ใช้ใน Child A; transplant เป็น definitive therapy ใน decompensated cirrhosis",
    "ดูข้อ 59 (anatomy ของ esophageal varices: left gastric vein), 71 (UGIB จาก varices)"],
  notes:"กากบาท A. Band ligation (เลือกเป็นคำตอบ); ด้านบนเขียน 'sclerotherapy = ฉีด sclerosing agent เข้า varix'; ข้าง B เขียน 'Transjugular intrahepatic portosystemic shunt'; แปะ flowchart suspected variceal bleeding: airway protection, PRBC transfusion, vasoactive agents, antibiotics, medical ICU admission → EGD within 12 h → esophageal variceal bleeding: endoscopic variceal ligation → no further bleeding: secondary prophylaxis NSBBs or EVL; rebleeding: repeat EVL → further bleeding → TIPS; uncontrolled: balloon tamponade or metal stent → TIPS → (uncontrolled bleeding or TIPS contraindicated) porto-caval shunt surgery; failure or intolerant of NSBBs/EVL → TIPS; gastric variceal bleeding → endoscopic or EUS glue injection → eradication by glue injection; glue injection unavailable/unsuccessful → TIPS",
  mnemonic:"'Band → Band → TIPS → Shunt' (ระหว่างรอใช้ balloon เป็นสะพาน)",
  guide:"Baveno VII Renewing Consensus in Portal Hypertension 2022; AASLD Guidance on Risk Stratification and Management of Portal Hypertension and Varices in Cirrhosis 2024",
  opinion:"เห็นด้วยกับคีย์: ต้นฉบับบอกว่าเพิ่งทำ sclerotherapy ครั้งแรก จึงขั้นต่อไปคือ endoscopic therapy ซ้ำด้วย EVL. ถ้าโจทย์บอกว่าเลือดออกมากคุมไม่ได้หรือ rebleed หลัง EVL ครั้งที่สอง → TIPS; ถ้า Child C 10–13 ตั้งแต่แรก → pre-emptive TIPS",
  variants:["Rebleed หลัง EVL ครั้งที่สองแม้ได้ octreotide → rescue TIPS","Child C 11 มี active bleeding ขณะ EGD ทำ EVL หยุดได้ → pre-emptive TIPS ภายใน 72 ชม.","เลือดออกจาก varices มากคุมไม่ได้ระหว่างรอ TIPS → balloon tamponade เป็น bridge"]}),
A({page:7, page2:7, orig:"34", kimg:KI("34"),
  stem:"A patient with breast cancer undergoes breast surgery with a skin flap. Which of the following helps prevent DVT?",
  gray:"34.ผ่านมมาป็นมะเร็ง ละมีจำทำ skin flap ข้อไหนช่วยป้องกันDVT — A. Early ambulation+IV hydration B. sequential compression device C. ไม่ต้องให้อะไรเพราะผู้ป่วยไม่มี risk of DVT",
  opts:["Early ambulation plus IV hydration","Sequential compression device","No prophylaxis needed","Preoperative warfarin","IVC filter"],
  ans:1, key:"A Early ambulation plus IV hydration"+KS, flag:"⚠ คีย์รุ่นพี่ตอบ A (early ambulation + IV hydration, เลขข้อไฮไลต์เหลือง = ไม่ชัวร์) — เราตอบ B Sequential compression device ตามหลักฐาน: ผู้ป่วยมะเร็งที่ผ่าตัดใหญ่มี VTE risk สูง ต้องได้ prophylaxis ที่มีหลักฐาน (mechanical ± pharmacologic) ไม่ใช่แค่ลุกเดินและให้น้ำ",
  interp:"ผู้ป่วยมะเร็ง + ผ่าตัดใหญ่ (reconstruction ด้วย flap ใช้เวลานาน) = VTE risk สูง → วิธีใดเป็น prophylaxis ที่มีหลักฐาน",
  why:"Caprini: malignancy 2 คะแนน + major surgery &gt;45 นาที 2 คะแนน (+ อายุ, BMI, ระยะเวลาผ่าตัดยาวใน flap) → มัก ≥5 = <b>high risk</b>. ACCP 2012: high risk ที่ไม่เสี่ยงเลือดออกสูง → LMWH หรือ LDUH + mechanical (IPC); ถ้าเสี่ยงเลือดออกสูง (hematoma ใต้ flap) → <b>mechanical prophylaxis ด้วย IPC/SCD</b> จนกว่าจะให้ยาได้. SCD บีบน่องเป็นจังหวะ → เพิ่มความเร็วการไหลของเลือดดำ ลด stasis และกระตุ้น fibrinolysis — เป็นวิธีเดียวในช้อยที่มีหลักฐานป้องกัน DVT. (ASCO 2023 แนะนำ pharmacologic prophylaxis ในผู้ป่วยมะเร็งที่ผ่าตัดใหญ่ โดยใช้ mechanical เสริม หรือใช้เดี่ยวเมื่อยามีข้อห้าม — ช้อยไม่มี LMWH จึงเลือก SCD)",
  wrong:["Early ambulation และไม่ให้ขาดน้ำเป็นมาตรการพื้นฐานที่ควรทำทุกคน แต่<b>ไม่เพียงพอ</b>เป็น prophylaxis ในผู้ป่วยมะเร็งผ่าตัดใหญ่ — ACCP 2012 ใช้ early ambulation อย่างเดียวเฉพาะกลุ่ม very low risk (Caprini 0) เช่นผ่าตัดเล็กในคนอายุน้อยไม่มีปัจจัยเสี่ยง",
         "ผิด — มะเร็งเป็นปัจจัยเสี่ยง VTE สำคัญ (hypercoagulable state จาก tissue factor และ procoagulant ของเซลล์มะเร็ง) รวมกับการผ่าตัดใหญ่; 'ไม่ต้องป้องกัน' ใช้ได้เฉพาะ very low risk",
         "Warfarin ออกฤทธิ์ช้าหลายวัน ปรับขนาดยาก และเพิ่มเลือดออกใต้ flap — ไม่ใช้เป็น perioperative prophylaxis ในศัลยกรรมทั่วไป (ใช้เป็น extended prophylaxis หลัง arthroplasty ในบางแนวทาง)",
         "ACCP ไม่แนะนำ IVC filter เพื่อ primary prevention — filter ใช้เมื่อมี acute proximal DVT หรือ PE และให้ anticoagulant ไม่ได้"],
  trap:"เลือก 'ลุกเดินเร็ว + ให้น้ำ' เพราะฟังดูปลอดภัยและไม่เพิ่มเลือดออก — ในผู้ป่วยมะเร็งผ่าตัดใหญ่ต้องประเมิน Caprini แล้วให้ prophylaxis ที่มีหลักฐาน; และอย่าสับสน DVT ของผู้ป่วยกับ venous thrombosis ของ flap pedicle",
  summary:["Caprini score: 0 very low → early ambulation; 1–2 low → mechanical (IPC); 3–4 moderate → LMWH หรือ LDUH หรือ IPC; ≥5 high → LMWH หรือ LDUH + IPC (ACCP 2012)",
    "เสี่ยงเลือดออกสูง → mechanical (IPC) ก่อน แล้วเริ่มยาเมื่อเลือดหยุดและปลอดภัย",
    "ผู้ป่วยมะเร็งผ่าตัดใหญ่ (ASCO 2023): LMWH หรือ UFH เริ่มก่อนผ่าตัดและให้อย่างน้อย 7–10 วัน; ผ่าตัดใหญ่ในช่องท้องหรือ pelvis ที่เสี่ยงสูง → extended prophylaxis ถึง 4 สัปดาห์; mechanical เสริมยา หรือใช้เดี่ยวเมื่อยามีข้อห้าม",
    "IPC/SCD ทำงานโดยลด venous stasis และเพิ่ม fibrinolysis; ใส่ก่อนหรือระหว่างดมยาและใช้ต่อจนเดินได้ดี; ข้อห้าม: PAD รุนแรง, DVT ที่มีอยู่แล้ว, แผลหรือ graft ที่ขา",
    "IVC filter ไม่ใช้เพื่อป้องกัน primary; warfarin ไม่ใช้ใน perioperative prophylaxis ทั่วไป",
    "Flap failure ส่วนใหญ่เกิดจาก venous thrombosis ของ pedicle (microvascular) — เป็นคนละเรื่องกับ DVT ที่ขา",
    "ดูข้อ 14 (วินิจฉัย DVT ด้วย compression duplex US), 33 (ไข้หลังผ่าตัด)"],
  notes:"เลขข้อ<b>ไฮไลต์เหลือง</b> (ไม่ชัวร์); <b>กากบาท A. Early ambulation+IV hydration</b> (คีย์รุ่นพี่); วงคำว่า 'มะเร็ง' + เขียน '<b>paraneoplastic DVT ได้</b>'; ใต้ skin flap เขียน '<b>most cause of flap failure is venous thrombosis</b>' และ '<b>ที่เป็น plastic Sx หรอ :/</b>'; ใต้ B sequential compression device เขียนประมาณว่า '↳ … bleeding แต่ไม่ช่วยเรื่อง venous thrombosis' (ลายมืออ่านยาก — ตีความว่า SCD ลดปัญหา bleeding เทียบกับยา แต่ไม่ช่วย venous thrombosis ของ flap); ใต้ C เขียน '<b>is risk</b>' (ผู้ป่วยมี risk)",
  mnemonic:"",
  guide:"ACCP Antithrombotic Therapy 9th ed.: Prevention of VTE in Nonorthopedic Surgical Patients 2012; ASCO Guideline Update: VTE Prophylaxis and Treatment in Patients With Cancer 2023; NICE NG89 VTE in over 16s 2018 (updated 2019)",
  opinion:"⚠ ไม่เห็นด้วยกับคีย์ A. รุ่นพี่น่าจะเลือก early ambulation + hydration เพราะกังวลว่า SCD ไม่ช่วย venous thrombosis ของ flap (ซึ่งเป็นปัญหา microvascular ของ pedicle ไม่ใช่ DVT) — แต่โจทย์ถามการป้องกัน <b>DVT</b>. ผู้ป่วยมะเร็งที่ผ่าตัดใหญ่มี Caprini สูง ACCP 2012, NICE NG89 และ ASCO 2023 ต่างแนะนำ prophylaxis ที่มีหลักฐาน (pharmacologic และ/หรือ mechanical); การลุกเดินและให้น้ำเป็นแค่มาตรการพื้นฐาน. ในช้อยไม่มี LMWH จึงตอบ SCD. ความมั่นใจสูง",
  variants:["ผู้ป่วยผ่าตัด colectomy จาก colon cancer → LMWH + IPC และ extended LMWH 4 สัปดาห์","ผู้ป่วย Caprini ≥5 ที่เลือดออกมากระหว่างผ่าตัด → IPC ก่อน แล้วเริ่ม LMWH เมื่อเลือดหยุด","ผู้ป่วยอายุ 25 ปี ผ่าตัด hernia เล็ก ไม่มีปัจจัยเสี่ยง → early ambulation อย่างเดียว"]}),
A({page:7, page2:7, orig:"35", kimg:KI("35"),
  stem:"A patient has dysphagia to both solids and liquids. A barium swallow shows a dilated proximal esophagus with distal tapering. What is the next step?",
  gray:"35. กลืนอาหารไม่ลงทั้งsolid liquid ทำbariumเจอproximal dilate+taperingทำไรต่อ — A. EUS B. Biopsy C. Eso manometry D. ไม่มีEGD",
  opts:["Endoscopic ultrasound","Biopsy","Esophageal manometry","CT chest","24-hour pH monitoring"],
  ans:2, key:"C Esophageal manometry"+KS,
  interp:"Dysphagia ทั้ง solid และ liquid (ชี้ motility disorder) + barium เห็นหลอดอาหารโป่งด้านบนและเรียวแหลมที่ปลาย → ต้องยืนยันการวินิจฉัยด้วยอะไร",
  why:"Dysphagia ต่อทั้ง solid และ liquid ตั้งแต่แรก + barium เห็น dilated esophagus ที่เรียวแหลมที่ GEJ (bird's beak) → นึกถึง <b>achalasia</b>. <b>High-resolution esophageal manometry = gold standard</b> ในการวินิจฉัย: incomplete LES relaxation (IRP สูงกว่าเกณฑ์) + aperistalsis ของ esophageal body; แบ่ง type I, II, III ตาม Chicago Classification v4.0 ซึ่งช่วยเลือกการรักษา. ทั้งนี้ตาม ACG 2020 ต้องทำ <b>EGD ก่อน</b>เพื่อแยก pseudoachalasia (มะเร็งที่ GEJ) — ซึ่งไม่มีในช้อย (ต้นฉบับเขียนกำกับว่า 'ไม่มี EGD')",
  wrong:["EUS ใช้ประเมิน submucosal tumor (GIST, leiomyoma), staging มะเร็ง (T, N) และ EUS-guided intervention — ใช้ในกรณีสงสัย pseudoachalasia ที่ EGD ไม่ชัด (ผนัง GEJ หนา) แต่ไม่ใช่การยืนยัน achalasia",
         "Biopsy ทำผ่าน EGD เมื่อเห็นก้อนหรือ mucosa ผิดปกติที่ GEJ เพื่อวินิจฉัยมะเร็ง (pseudoachalasia) — ใน achalasia mucosa ปกติ การตัดชิ้นเนื้อแบบไม่มีเป้าหมายไม่ช่วยวินิจฉัย; จะเป็นคำตอบถ้าโจทย์บอกว่า EGD เห็นก้อนที่ cardia",
         "CT chest ใช้เมื่อสงสัย pseudoachalasia หรือมะเร็ง (ผู้สูงอายุ น้ำหนักลดมาก อาการเป็นไม่ถึงปี) เพื่อดูผนังหนาหรือก้อนรอบ GEJ — ไม่ใช่การตรวจยืนยัน motility disorder",
         "24-hour pH monitoring ใช้วินิจฉัย GERD (โดยเฉพาะก่อน antireflux surgery หรือ GERD ที่ EGD ปกติ) และติดตาม reflux หลัง myotomy หรือ POEM — ไม่ใช่การวินิจฉัย achalasia"],
  trap:"ตอบ EGD หรือ biopsy เพราะกลัวมะเร็ง — EGD จำเป็นจริงแต่เป็นขั้นแยก pseudoachalasia; การ<b>วินิจฉัย</b> achalasia ต้องใช้ manometry. ส่วน dysphagia ที่เริ่มจาก solid แล้วค่อยลามไป liquid ชี้ mechanical obstruction (มะเร็ง, stricture)",
  summary:["Achalasia: สูญเสีย inhibitory neurons ใน myenteric plexus → LES ไม่คลาย + aperistalsis; dysphagia ทั้ง solid และ liquid, regurgitation อาหารไม่ย่อย, น้ำหนักลด, chest pain",
    "Workup: EGD ก่อน (แยก pseudoachalasia และ structural lesion) → barium esophagram (bird's beak, timed barium ใช้ติดตามผล) → <b>high-resolution manometry</b> = gold standard",
    "Chicago Classification v4.0: type I (classic, ไม่มี pressurization), type II (panesophageal pressurization — ตอบสนองการรักษาดีที่สุด), type III (spastic — POEM ได้ผลดีกว่าเพราะ myotomy ยาวได้)",
    "Pseudoachalasia: มะเร็งที่ GEJ หรือ cardia (ส่วนใหญ่ adenocarcinoma); สงสัยเมื่ออายุ &gt;55–60 ปี, อาการเป็นไม่ถึง 1 ปี, น้ำหนักลดมาก → EGD + biopsy, EUS หรือ CT",
    "รักษา: Heller myotomy แบบ laparoscopic + partial fundoplication (Dor หรือ Toupet), POEM (reflux มากกว่า), pneumatic dilation (เสี่ยง perforation ราว 1–2%); botulinum toxin ในผู้ที่เสี่ยงผ่าตัดสูง (ผลอยู่ไม่กี่เดือน)",
    "Achalasia เพิ่มความเสี่ยง squamous cell carcinoma ของหลอดอาหาร; Chagas disease (Trypanosoma cruzi) ทำภาพเหมือน achalasia",
    "ดูข้อ 62 (esophageal cancer), 2 (esophageal perforation)"],
  notes:"วง C. Eso manometry (คีย์) และเลขข้อไฮไลต์เหลือง; ด้านขวาโจทย์เขียน '<b>→ สงสัย Achalasia vs Pseudoachalasia</b>'; ข้าง A EUS เขียน '→ GIST, staging tumor'; ข้าง C เขียน '→ <b>gold standard ของการ achalasia แต่แยก pseudo ไม่ได้</b>'; ช้อย D ในไฟล์โจทย์เขียนว่า 'ไม่มี EGD' — รุ่นพี่วงคำว่า EGD แล้วเขียน '→ ใช้แยก Achalasia &amp; Pseudo-achalasia'; ด้านล่างเขียน '<b>★ ตอบ 1st EGD 2nd manometry ★</b>'; แปะตาราง indications ของ EUS (submucosal/subepithelial tumors, staging of various cancers — esophageal, gastric, pancreatic, rectal, ampullary, EUS-guided therapeutic interventions: drainage procedures, injection treatment, other interventions)",
  mnemonic:"'Solid + Liquid พร้อมกัน = Motility; Solid ก่อนแล้วลาม = Mechanical'",
  guide:"ACG Clinical Guideline: Diagnosis and Management of Achalasia 2020; Chicago Classification v4.0 (2021); ISDE Guidelines for Achalasia 2018",
  opinion:"เห็นด้วยกับคีย์ภายใต้ช้อยที่มี (ความมั่นใจสูง). ในทางปฏิบัติและตามที่รุ่นพี่เน้น ★ — ลำดับจริงคือ EGD ก่อน (แยก pseudoachalasia) แล้วจึง manometry ยืนยัน; ถ้าช้อยมี EGD และโจทย์ถาม 'next step' ในผู้ป่วยที่ยังไม่ได้ส่องกล้อง ควรตอบ EGD",
  variants:["ช้อยมีทั้ง EGD และ manometry ผู้ป่วยอายุ 70 น้ำหนักลด 10 kg ใน 3 เดือน → EGD ก่อน (สงสัย pseudoachalasia)","Manometry พบ IRP สูง aperistalsis มี panesophageal pressurization → achalasia type II → ตอบสนองการรักษาดีที่สุด","Achalasia type III → POEM เพราะทำ myotomy ได้ยาว"]}),
A({page:7, page2:7, orig:"36", kimg:KI("36"),
  stem:"A patient recently underwent open herniorrhaphy. On postoperative day 5, he has a fever of 38°C, and the skin over the wound is swollen, red, and tender, with a burning pain. What is the most likely diagnosis?",
  gray:"36. พึ่ง open herniorraphy ไป. Post op day 5. ตอนนี้ไข้ 38C. ผิว บวม แดง tender. เจ็บแบบแสบ ๆ (?) เป็นอะไร — A. Mesh infection B. Cutaneous nerve injury C. Granuloma",
  opts:["Mesh infection","Cutaneous nerve injury","Suture granuloma","Seroma","Recurrent hernia"],
  ans:0, key:"A Mesh infection"+KS, flag:"⚠ ไข้ + แผลบวมแดงกดเจ็บใน day 5 = surgical site infection ของแผล; deep mesh infection แท้มักมาช้ากว่า (สัปดาห์ถึงเดือน) — ในช้อยไม่มี superficial SSI จึงตอบ mesh infection ตามคีย์",
  interp:"ไข้ + การอักเสบเฉพาะที่ (บวม แดง ร้อน กดเจ็บ) ที่แผล hernia repair ใน day 5 → แยกจากภาวะแทรกซ้อนอื่นของ herniorrhaphy ที่ไม่มีไข้",
  why:"ไข้ 38°C + แผลบวมแดงกดเจ็บใน POD 5 = ช่วงเวลาของ <b>surgical site infection</b> (day 5–7) — ในผู้ป่วยที่ใส่ mesh การติดเชื้อที่แผลลามถึง mesh ได้ จึงเรียกรวมว่า <b>mesh infection</b> ในช้อยนี้. เชื้อส่วนใหญ่เป็น <b>S. aureus</b> (รวม MRSA) และ coagulase-negative staphylococci. อาการปวดแสบร้อนเป็นตัวลวงไปทาง nerve injury แต่ nerve injury ไม่ทำให้มีไข้และแผลแดง",
  wrong:["Nerve injury (ilioinguinal, iliohypogastric, genital branch of genitofemoral) ทำให้ปวดแสบร้อน ชา หรือปวดร้าวลงขาหนีบ อัณฑะ ต้นขาด้านใน — แต่<b>ไม่มีไข้หรือแผลบวมแดง</b>; จะเป็นคำตอบถ้าโจทย์บอกปวดแสบหรือชาเรื้อรังหลังผ่าตัด &gt;3 เดือน (chronic postherniorrhaphy inguinal pain) โดยแผลปกติ",
         "Suture granuloma เป็นปฏิกิริยาต่อไหมที่ไม่ละลาย (โดยเฉพาะ multifilament) — มาช้าเป็นสัปดาห์ถึงเดือน เป็นตุ่มแข็งหรือ sinus มีหนองซึมเรื้อรัง ไม่ใช่การอักเสบเฉียบพลันพร้อมไข้ใน day 5",
         "Seroma = น้ำเหลืองคั่งใน dead space พบบ่อยหลัง hernia repair ในสัปดาห์แรก เป็นก้อนนุ่ม fluctuant ไม่แดง ไม่มีไข้ — ส่วนใหญ่หายเอง ไม่ควรเจาะ routine เพราะเพิ่มโอกาสติดเชื้อ",
         "Recurrence มาด้วยก้อนโผล่ตอนไอหรือเบ่ง มักเกิดหลังหลายเดือนถึงปี ไม่มีไข้หรือแผลแดง — early recurrence สัมพันธ์กับเทคนิค (mesh เล็กไป, ยึดไม่ดี)"],
  trap:"คำว่า 'ปวดแสบ' ดึงไปที่ nerve injury — ต้องให้น้ำหนักกับไข้ + แผลบวมแดงซึ่งบ่งการติดเชื้อ; และ 'granuloma' ต้องใช้เวลาเป็นสัปดาห์ขึ้นไป",
  summary:["ภาวะแทรกซ้อนของ inguinal herniorrhaphy ตามเวลา: hematoma และ seroma (วันแรก ๆ ถึงสัปดาห์แรก), SSI (day 5–7), urinary retention (หลังผ่าตัดทันที), chronic pain (&gt;3 เดือน), suture granuloma และ chronic mesh infection (สัปดาห์ถึงปี), recurrence (เดือนถึงปี)",
    "SSI หลัง open mesh repair พบไม่บ่อย; mesh infection แท้ราว 1% หรือน้อยกว่า; เชื้อหลัก S. aureus และ coagulase-negative staphylococci",
    "รักษา superficial SSI: เปิดแผลระบายหนอง ล้างทำแผล + antibiotic ถ้ามี cellulitis หรือ systemic sign; ส่ง culture",
    "Mesh infection: macroporous monofilament polypropylene มักรักษาได้โดยไม่ต้องเอา mesh ออก (drainage + antibiotic ± NPWT); multifilament หรือ ePTFE และ chronic sinus ที่ไม่หาย → ต้อง explant",
    "Chronic postherniorrhaphy inguinal pain: ปวดหรือชาเกิน 3 เดือน จาก nerve entrapment หรือ injury; ป้องกันด้วยการระบุและเก็บรักษาเส้นประสาทระหว่างผ่าตัด; ดื้อการรักษา → nerve block หรือ triple neurectomy",
    "HerniaSurge 2018: ไม่แนะนำ antibiotic prophylaxis routine ใน open mesh repair ในผู้ป่วยความเสี่ยงต่ำในสถานที่ที่ SSI ต่ำ แต่แนะนำในผู้ป่วยหรือสถานที่ที่เสี่ยงสูง",
    "ดูข้อ 33 (ไข้หลังผ่าตัดตามวัน), 64, 66 (การผ่าตัด inguinal hernia)"],
  notes:"วง A. Mesh infection (คีย์); ขีดเส้นใต้ 'Post op day 5'; ข้าง B Cutaneous nerve injury เขียน '<b>ไม่น่ามีไข้, แดง, น่าจะเป็นเจ็บ ๆ ชา ๆ</b>'; ข้าง C Granuloma เขียน '<b>ไม่น่าบวมแดง, น่าจะ &gt; 5 day</b>'",
  mnemonic:"",
  guide:"HerniaSurge Group: International Guidelines for Groin Hernia Management 2018; CDC NHSN Surgical Site Infection Event 2024",
  opinion:"⚠ เห็นด้วยกับคีย์ในบริบทของช้อย (ความมั่นใจสูง). ข้อสังเกต: ภาพ day 5 + ไข้ + แผลแดงคือ incisional SSI; deep mesh infection ที่ต้องเอา mesh ออกมักมาช้าเป็นสัปดาห์ถึงเดือน (sinus, หนองเรื้อรัง) — ถ้าช้อยมีทั้ง 'superficial SSI' และ 'mesh infection' ควรตอบ superficial SSI ก่อน",
  variants:["Herniorrhaphy 6 เดือนก่อน ปวดแสบร้าวลงอัณฑะ ชาต้นขาด้านใน แผลปกติ → chronic postherniorrhaphy pain จาก nerve entrapment","POD 7 มีก้อนนุ่ม fluctuant ที่ขาหนีบ ไม่มีไข้ ไม่แดง → seroma → สังเกตอาการ","มีหนองซึมจากแผลเรื้อรัง 4 เดือนหลังใส่ multifilament mesh → chronic mesh infection → explant"]}),
A({page:8, page2:8, orig:"37", kimg:KI("37"),
  stem:"A patient with liver metastases is planned for hepatic resection, but the future liver remnant is insufficient. What should be done before resection?",
  gray:"37. มีmetasไปตับจะตัดแต่remnantไม่พอ จะทำอะไรก่อนตัด — A. TACE B. PVE C. Hep v embolize /occlusion?",
  opts:["Transarterial chemoembolization","Portal vein embolization","Hepatic vein embolization","Radiofrequency ablation","Systemic chemotherapy alone"],
  ans:1, key:"A Transarterial chemoembolization"+KS, flag:"⚠ คีย์รุ่นพี่ตอบ A TACE (เขียน '1st TACE → PVE') — เราตอบ B Portal vein embolization: เป็นวิธีมาตรฐานเพิ่ม future liver remnant ก่อน major hepatectomy; การทำ TACE ก่อน PVE (sequential) ใช้ใน HCC บนตับแข็ง ไม่ใช่ liver metastasis",
  interp:"ก้อนในตับตัดได้ทางเทคนิค แต่ส่วนที่จะเหลือ (FLR) น้อยเกินไป เสี่ยง post-hepatectomy liver failure → ต้องทำอะไรเพื่อให้ FLR โตก่อนผ่า",
  why:"<b>PVE</b>: อุด portal vein ข้างที่จะตัด (มักเป็น right ± segment 4) → portal flow และ hepatotrophic factors ไปที่ FLR → <b>FLR hypertrophy</b> ภายในราว 3–6 สัปดาห์; ข้างที่ถูกอุดฝ่อ. เกณฑ์ FLR ที่ปลอดภัย: ตับปกติ ≥20%, ได้ chemotherapy นาน (chemotherapy-associated liver injury) ≥30%, ตับแข็ง ≥40% ของ total liver volume. ผลการโตหลัง PVE ยังเป็น stress test — ถ้า degree of hypertrophy หรือ kinetic growth rate (≥2% ต่อสัปดาห์) ดี ความเสี่ยง liver failure หลังผ่าตัดต่ำ",
  wrong:["TACE เป็นการรักษาหลักของ HCC ระยะ intermediate (BCLC B) และใช้ก่อน PVE (sequential TACE → PVE) ใน <b>HCC บนตับแข็ง</b> เพื่อคุมก้อนระหว่างรอและอุด arterioportal shunt ให้ PVE ได้ผลดีขึ้น — แต่ TACE เองไม่ได้ทำให้ FLR โต; ใน liver metastasis ไม่ใช่ขั้นมาตรฐานก่อน PVE",
         "Hepatic vein embolization เดี่ยว ๆ ไม่ใช่มาตรฐาน — ใช้<b>ร่วมกับ</b> PVE (liver venous deprivation, PVE + HVE พร้อมหรือตามกัน) เพื่อให้ FLR โตเร็วและมากกว่า PVE อย่างเดียว ในศูนย์ที่ชำนาญหรือเมื่อ PVE เดี่ยวไม่พอ",
         "RFA ใช้กับก้อนเล็ก (มัก ≤3 cm) ที่ไม่ต้องการตัดเนื้อตับมาก หรือใช้ร่วมกับ resection ใน bilobar disease (ablate ก้อนเล็กในข้างที่เหลือ) — ไม่ได้เพิ่มปริมาตร FLR",
         "Systemic chemotherapy (FOLFOX หรือ FOLFIRI ± biologic ใน CRLM) ใช้เป็น conversion therapy ลดขนาดก้อนให้ตัดได้ และควบคุมโรคระหว่างรอ แต่ไม่ได้แก้ปัญหา FLR ไม่พอ และให้นานเกินไปทำให้ตับบาดเจ็บ (oxaliplatin → sinusoidal obstruction, irinotecan → steatohepatitis)"],
  trap:"เห็น 'TACE' แล้วนึกถึงการรักษาก้อนในตับทั่วไป — โจทย์ถามเรื่อง<b>เพิ่ม remnant</b> ซึ่งต้องอุด portal flow; TACE เกี่ยวกับ PVE เฉพาะใน HCC ที่ทำ sequential",
  summary:["Resectability ของ malignant liver tumor: adequate FLR และ liver function, ผู้ป่วยแข็งแรงพอ, ตัดก้อนออกได้หมด (ยกเว้น neuroendocrine ที่ debulking ได้), ไม่มี extrahepatic spread ที่คุมไม่ได้",
    "FLR ขั้นต่ำ: ตับปกติ ≥20%, หลัง chemotherapy นาน ≥30%, cirrhosis (Child A) ≥40% — วัดด้วย CT volumetry",
    "PVE: อุด portal branch ข้างที่จะตัด → FLR โตใน 3–6 สัปดาห์; kinetic growth rate ≥2% ต่อสัปดาห์ทำนาย liver failure ต่ำ; โรคลุกลามระหว่างรอ = ไม่ควรผ่า",
    "HCC บนตับแข็ง: sequential TACE → PVE เพิ่มการโตของ FLR และคุมก้อน",
    "ทางเลือกอื่นเมื่อ PVE ไม่พอ: liver venous deprivation (PVE + HVE), two-stage hepatectomy (bilobar CRLM), ALPPS (โตเร็วใน 1–2 สัปดาห์แต่ morbidity สูงกว่า)",
    "Unresectable liver tumor: systemic therapy, TACE/TARE, ablation, radiotherapy (SBRT), ระบายน้ำดีถ้าเหลือง",
    "ดูข้อ 41, 56, 57 (liver mass)"],
  notes:"<b>กากบาท A. TACE</b> (คีย์รุ่นพี่); ขีดเส้นใต้ 'จะตัดแต่ remnant ไม่พอ' และ 'Hep v embolize'; เขียน '<b>เหลือ liver ไม่พอ</b>' และ '<b>1st TACE → PVE</b>'; แปะสไลด์ malignant liver tumor — resectable: adequate liver remnant/liver function, patient fitness, complete tumor removal (except neuroendocrine tumor), no extrahepatic spread; unresectable: XRT, TOCE, chemotherapy, relieve jaundice — รุ่นพี่วงคำว่า TOCE แล้วลากลูกศรเขียนว่า '<b>remnant ไม่พอ</b>'",
  mnemonic:"'Portal ปิด → ฝั่งเหลือโต' (PVE = Pre-hepatectomy Volume Enlargement)",
  guide:"ESMO Metastatic Colorectal Cancer Clinical Practice Guideline 2023; EASL Clinical Practice Guidelines: Management of Hepatocellular Carcinoma 2018; Sabiston 21st ed. (2022)",
  opinion:"⚠ ไม่เห็นด้วยกับคีย์ A. สิ่งที่ทำให้ FLR โตคือ PVE; รุ่นพี่เขียนลำดับ '1st TACE → PVE' ซึ่งเป็นวิธี sequential ที่ใช้ใน HCC บนตับแข็ง (TACE ป้องกันก้อนโตและอุด arterioportal shunt ก่อน PVE) แต่โจทย์เป็น <b>liver metastasis</b> ซึ่งแนวทางมาตรฐานคือ PVE (± HVE หรือ two-stage hepatectomy) — และแม้ใน HCC ขั้นที่ทำให้ remnant เพิ่มก็ยังเป็น PVE. สไลด์ที่รุ่นพี่แปะจัด TOCE ไว้ในกลุ่ม unresectable ไม่ใช่ขั้นเตรียมก่อนตัด. ความมั่นใจสูง",
  variants:["CRLM ต้องทำ extended right hepatectomy FLR 18% หลังได้ FOLFOX 6 รอบ → PVE แล้ว CT volumetry ซ้ำใน 4 สัปดาห์","HCC บนตับแข็ง Child A ต้องทำ right hepatectomy FLR 30% → sequential TACE แล้ว PVE","Bilobar CRLM หลายก้อน → two-stage hepatectomy ร่วมกับ PVE"]}),
